### DISCUSSION TITLE
Show Kw to W at individual entity level

### DISCUSSION THREAD

**Discussion by KonsultDigital** [kalkih/mini-graph-card#1015] [Q&A]
Hi

Whats the best way to show a sensor entity that's in Kwh when all others are in watts

I know this doesn't work, but what I am needing.

`entity: (sensor.car_energy_added * 1000)
    name: Car`

**Comment by jdelamater99** [comment]
Old thread, but figured I'd post the answer incase anyone else was looking for it.

value_factor: -3

example:
```
type: custom:mini-graph-card
    entities:
      - entity: sensor.2022_ioniq_5_daily_driving_stats
        attribute: 2025-02-13.total_consumed
        name: Total Consumption
        color: green
      - entity: sensor.2022_ioniq_5_daily_driving_stats
        attribute: 2025-02-13.climate_consumption
        name: Climate Consumption
      - entity: sensor.2022_ioniq_5_daily_driving_stats
        attribute: 2025-02-13.regenerated_energy
        name: Regen
        color: purple
    value_factor: -3
    group: false
    show:
      icon: false
      name: false
      state: true
      labels: true
      labels_secondary: true
    hours_to_show: 72
    cache: true
    unit: kWh
    line_width: 2
```
