### DISCUSSION TITLE
Tracking Daily Online Hours via Ping

### DISCUSSION THREAD

**Discussion by baspax1** [kalkih/mini-graph-card#1089] [Q&A]
Good evening, what I want to achieve is to record the total hours a computer is online via Ping. I see it's not recording accurately, I want it to separate the data by day and produce a total of hours per day, in hours and minutes if possible.

Sensor
```
  - platform: history_stats
    name: Chris PC Daily Uptime
    entity_id: binary_sensor.chris_pc
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'
```

 Card:
 ```
 type: custom:mini-graph-card
name: Chris PC Daily Uptime
entities:
  - sensor.chris_pc_daily_uptime
hours_to_show: 168
aggregate_func: sum
group_by: date
show:
  labels: true
  fill: true
  graph: bar
  points: false
  smoothing: true
  hour24: true
color_thresholds:
  - value: 0
    color: '#FF0000'
  - value: 1
    color: '#FFFF00'
  - value: 12
    color: '#00FF00'
  - value: 24
    color: '#008000'

```
![Overview – Home Assistant](https://github.com/kalkih/mini-graph-card/assets/37578694/e28389a5-dc4c-46fa-bb44-1b1b586e1785)
