### DISCUSSION TITLE
On tap/click of graph show all entities in a bigger style

### DISCUSSION THREAD

**Discussion by DeFlanko** [kalkih/mini-graph-card#1127] [Q&A]
This might be a limitation of HA, but I'm going to start here. 

I have a ```custom:mini-graph-card``` and it has multiple entities, for example the many sensors in my house that record humidity:

![image](https://github.com/user-attachments/assets/81c09df5-d9fe-470c-8398-d335efe24abc)

Is it possible when i click on it to then show a bigger version of the ```custom:mini-graph-card``` to show more details of each entity?

Currently, when i click on the graph only the top entity shows up:

![image](https://github.com/user-attachments/assets/9d2abcd2-0039-4bd9-b928-823e2732571b)

```yaml
type: custom:mini-graph-card
show:
  labels: true
  legend: false
  name_adaptive_color: true
  icon_adaptive_color: true
  average: true
color_thresholds:
  - value: 100
    color: '#008fce'
  - value: 60
    color: '#fff2cc'
  - value: 20
    color: '#FF1A27'
height: 150
hours_to_show: 12
points_per_hour: 6
line_width: 2
animate: true
entities:
  - entity: sensor.my_ecobee_humidity
    name: Ecobee
  - entity: sensor.smart_air_housekeeper_6_in_1_humidity
    name: Tuya 6-in-1
  - entity: sensor.jd_bedroom_6aac_humidity
    name: Bedroom Puck
  - entity: sensor.office_2299_humidity
    name: Office Puck
  - entity: sensor.1930pwslocal_humidity_in
    name: Kitchen
name: Inside Humidity
```

**Comment by ildar170975** [comment]
1. The `mini-graph-card` has a common card-wide `tap_action`. Means - you cannot select a graph for `sensor.xxx` & see a card for `sensor.xxx`, then select a graph for `sensor.yyy` & see a card for `sensor.yyy`. But you may show a detailed graph for same ALL entities (see pt. 2 below).
2. Use a standard `navigation` action to navigate to a subview:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.system_monitor_processor_use
tap_action:
  action: navigate
  navigation_path: /lovelace-/my_sub_view
```
where the "my_sub_view" contains
```
type: custom:mini-graph-card
entities:
  - entity: sensor.system_monitor_processor_use
hours_to_show: 1
points_per_hour: 240
```
