### DISCUSSION TITLE
Line disappeared if the state is unchanged for a long time?

### DISCUSSION THREAD

**Discussion by johnmave126** [kalkih/mini-graph-card#1223] [Q&A]
![image](https://github.com/user-attachments/assets/df0b58ee-59f7-4699-b6ee-406771022ef5)

The humidity line on the right is not showing up. Last time the humidity value was not 20 was 3 weeks ago. I had another sensor also with humidity disappeared (2 weeks unchanged), and after I blow some humid air into it, the line suddenly appeared as if the whole day was with high humidity.

Any clue how I can fix this?

My config is as follows:
```yaml
type: custom:mini-graph-card
name: Server Room
icon: mdi:server
animate: true
hour24: true
min_bound_range_secondary: 5
points_per_hour: 1
show:
  labels: false
  labels_secondary: false
  fill: fade
entities:
  - entity: sensor.thermo_hygrometer_ed9027_xl0801_tempc
    name: Temperature
    color: "#FF5722"
  - entity: sensor.thermo_hygrometer_ed9027_xl0801_hum
    name: Humidity
    y_axis: secondary
    show_state: true
    show_fill: false

```
