### DISCUSSION TITLE
Show the time on X axis (or even on hover?)

### DISCUSSION THREAD

**Discussion by vaderag** [kalkih/mini-graph-card#1262] [Q&A]
I have a graph card with the code below and currently looks like this:
![image](https://github.com/user-attachments/assets/c961a0ae-e346-4338-acd4-c055b33a46fa)
When hovering I can see the current cat and the history, but I have no idea what time an change event actually occurred
![image](https://github.com/user-attachments/assets/14d6b674-6c4f-4af3-911b-dad3fd7036ce)

I may be missing something obvious but is there a way to show the time on the X axis? I see the hour24 setting allows you to adjust the time format, but I don't see the time anywhere?!
Thanks!

```
type: custom:mini-graph-card
icon: mdi:cat
align_icon: left
entities:
  - entity: binary_sensor.cocoa
    name: Cat1
    color: lightblue
    show_points: true
    show_legend_state: true
  - entity: binary_sensor.harley
    name: Cat2
    color: lightgreen
    show_points: true
    show_legend_state: true
  - entity: binary_sensor.blossom
    name: Cat3
    color: pink
    show_points: true
    show_legend_state: true
name: Cats Time Outside (12hrs)
hours_to_show: 12
points_per_hour: 60
line_width: 3
smoothing: false
height: 110
hour24: true
show:
  points: true
  state: false
  labels: true
state_map:
  - value: "on"
    label: Inside
  - value: "off"
    label: Outside

```
