### DISCUSSION TITLE
group_by half day

### DISCUSSION THREAD

**Discussion by cybermaus** [kalkih/mini-graph-card#695] [Q&A]
Hello

Is there any way to get the energy bar-graph to group in half day?
By which I mean, from 12h00 noon to 12h00 noon next day. Or alternative, group by AM and PM (so we can mentally add together)?

I have looked at the `interval` explanation [here](https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1843), but that seems to not work
So I am hoping someone has a more lateral solution to this.

Thanks
Maurits

BTW: The closest I get is this, which does show half days, but this is a sliding 12-hour window from current time, rather then on fixed noon borders:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.tuya_esp12f_energy_total
name: Energy consumption
hour24: true
hours_to_show: 168
points_per_hour: 0.083333333
aggregate_func: delta
lower_bound: 0
min_bound_range: 1
show:
  graph: bar
  labels: true
```
