### DISCUSSION TITLE
Problem when adding custom "color_thresholds"

### DISCUSSION THREAD

**Discussion by pimmen85** [kalkih/mini-graph-card#763] [General]
i have two sensors in the same card side by side in a horizontal stack, but the options for coloring the line depending on temperature is only working for one of them.

i also wonder if i can remove the points completely, i have tried all options i can find but nothing removes them.

**Comment by ildar170975** [comment]
No code is provided.

**Comment by pimmen85** [comment]
```
type: vertical-stack
title: Weather
cards:
  - show_current: true
    show_forecast: true
    type: weather-forecast
    entity: weather.gunnebogatan_54
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.netatmo_gunnebogatan_54_indoor_temperature
        line_width: 11
        font_size: 90
        hour24: true
        hours_to_show: 48
        color_thresholds:
          - value: 0
            color: aqua
          - value: 5
            color: aquamarine
          - value: 10
            color: mediumaquamarine
          - value: 15
            color: lawngreen
          - value: 20
            color: limegreen
          - value: 25
            color: green
          - value: 30
            color: orange
          - value: 35
            color: red
      - type: custom:mini-graph-card
        entities:
          - sensor.netatmo_gunnebogatan_54_outdoor_temperature
        line_width: 11
        font_size: 90
        hour24: true
        hours_to_show: 48
        color_thresholds:
          - value: 0
            color: aqua
          - value: 5
            color: aquamarine
          - value: 10
            color: mediumaquamarine
          - value: 15
            color: lawngreen
          - value: 20
            color: limegreen
          - value: 25
            color: green
          - value: 30
            color: orange
          - value: 35
            color: red

```

**Comment by ildar170975** [comment]
> options for coloring the line depending on temperature is only working for one of them.

Do not confirm.
Thresholds work for both cards.
```
type: vertical-stack
title: Weather
cards:
  - show_current: true
    show_forecast: true
    type: weather-forecast
    entity: weather.home_met
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.cleargrass_1_temperature
        <<: &ref_settings
          line_width: 1
          hour24: true
          hours_to_show: 48
          color_thresholds_transition: hard
          color_thresholds:
            - value: 22
              color: blue
            - value: 23
              color: green
            - value: 24
              color: orange
            - value: 25
              color: red
      - type: custom:mini-graph-card
        entities:
          - sensor.cleargrass_2_temperature
        <<: *ref_settings
```
![изображение](https://user-images.githubusercontent.com/71872483/158460200-9a22facc-c2bc-43d2-a6dd-f4e138e6f0bf.png)

**Comment by ildar170975** [comment]
> i also wonder if i can remove the points completely, i have tried all options i can find but nothing removes them.

Try `show_points: false` ([link](https://github.com/kalkih/mini-graph-card#entities-object)) or `points: false` ([link](https://github.com/kalkih/mini-graph-card#available-show-options))

**Comment by pimmen85** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/83097086/158490356-16f3e499-a4b8-42df-988f-8681c0aafc46.jpg)
something is funny, its something with the entity, because if i choose another entity, it works with the colors, there is no thing like limited length for entity name right?

**Comment by ildar170975** [comment]
~~Seems that the graph is not displayed at all. Check with history-graph~~
Checked the last picture on mobile, did not notice the graph of black color...

Now I created some temperature sensor "netatmo_gunnebogatan_54_outdoor_temperature" - will come back after 24 hours (need to collect some data).

**Update:**
Do not see any problems:
![изображение](https://user-images.githubusercontent.com/71872483/158687208-07552bb8-aa32-47b3-af84-ae6409c36ce4.png)
```
type: vertical-stack
title: Weather
cards:
  - show_current: true
    show_forecast: true
    type: weather-forecast
    entity: weather.home_met
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.netatmo_gunnebogatan_54_indoor_temperature
        <<: &ref_settings
          line_width: 1
          hour24: true
          hours_to_show: 24
          points_per_hour: 60
          smoothing: false
          aggregate_func: last
          color_thresholds_transition: hard
          color_thresholds:
            - value: 22
              color: blue
            - value: 23
              color: green
            - value: 24
              color: orange
            - value: 25
              color: red
      - type: custom:mini-graph-card
        entities:
          - sensor.cleargrass_2_temperature
        <<: *ref_settings
```
