### DISCUSSION TITLE
Longer the binary sensor is switched on, higher the peak in graph

### DISCUSSION THREAD

**Discussion by milindpatel63** [kalkih/mini-graph-card#798] [Q&A] [answered]
I want to generate a graph for refrigerator door binary sensor.
But I want the peak of the graph to be directly proportional to the amount of time the door is opened for.
Would be much cooler if color also changed based on the peak for that specific peak in bar graph.

I think this could be done maybe using this graph only, or via some other templates stuff in home assistant.

Maybe someone can give me some ideas.

**Comment by ildar170975** [comment]
> graph to be directly proportional to the amount of time the door is opened for.

Could be solved by History stats integration IMHO.
Output is "amount of time when the sensor is ON" (or OFF).



> if color also changed based on the peak for that specific peak in bar graph

May be implemented by a standard "color_thresholds" option then.

**Comment by milindpatel63** [comment, marked as answer]
Thanks @ildar170975 for pointing me in right direction...

Here's my implementation for anyone else searching for similar stuff..

Create a Number Variable in Helper's section named "fridgeopen"

An automation

```
alias: Refrigerator Door Graph
description: ''
trigger:
  - type: opened
    platform: device
    device_id: xxx
    entity_id: binary_sensor.lg_refrigerator_door_open
    domain: binary_sensor
condition: []
action:
  - repeat:
      while:
        - type: is_open
          condition: device
          device_id: xxx
          entity_id: binary_sensor.lg_refrigerator_door_open
          domain: binary_sensor
      sequence:
        - service: input_number.increment
          data: {}
          target:
            entity_id: input_number.fridgeopen
        - delay:
            hours: 0
            minutes: 0
            seconds: 1
            milliseconds: 0
  - service: input_number.set_value
    data:
      value: 0
    target:
      entity_id: input_number.fridgeopen
mode: single
```

For Dashboard Card
Install custom mini graph

```
type: custom:mini-graph-card
name: Refrigerator Door
animate: true
hour24: true
group: false
hours_to_show: 24
points_per_hour: 4
aggregate_func: max
group_by: interval
smoothing: false
lower_bound: 0
show:
  graph: bar
  name_adaptive_color: true
  icon_adaptive_color: true
entities:
  - entity: sensor.refrigerator_door
    name: Door Status
    show_state: true
    show_indicator: false
    show_graph: false
    show_line: false
    show_points: false
    show_legend: false
  - entity: input_number.fridgeopen
    name: Refrigerator Door Opened for
    show_state: false
state_map:
  - value: Closed
    label: Closed
  - value: Open
    label: Open
color_thresholds:
  - value: 0
    color: green
  - value: 30
    color: blue
  - value: 60
    color: orange
  - value: 90
    color: red
```

**Reply by milindpatel63** [reply]
Update:

Added one more automation.
With the above, the number entity didn't had any value after refrigerator door was closed, until it was opened again...
This caused the graph to always stuck at last value...

This automation will reset the value to 0 every second when the door is closed..

```
alias: Refrigerator Door Graph Zero
description: ''
trigger:
  - type: not_opened
    platform: device
    device_id: xxx
    entity_id: binary_sensor.lg_refrigerator_door_open
    domain: binary_sensor
condition: []
action:
  - repeat:
      while:
        - type: is_not_open
          condition: device
          device_id: xxx
          entity_id: binary_sensor.lg_refrigerator_door_open
          domain: binary_sensor
      sequence:
        - service: input_number.set_value
          data:
            value: 0
          target:
            entity_id: input_number.fridgeopen
        - delay:
            hours: 0
            minutes: 0
            seconds: 1
            milliseconds: 0
mode: single
```
