### DISCUSSION TITLE
No color line change with color_thresholds

### DISCUSSION THREAD

**Discussion by miggi92** [kalkih/mini-graph-card#806] [Q&A] [answered]
Hello together, 

I'm not sure, if I'm doing something wrong or it is a bug. 
I'm expecting the line color to change, when reaching the color threshold values. 
0 - 500 should be a green line
500 - 700 a yellow line 
above 700 a red line.

But the only thing changed are the value points. (see screenshot)

![image](https://user-images.githubusercontent.com/9019692/177510152-5bd21ae2-cf48-47d3-a064-5ffcd198fb56.png)

```yaml
type: custom:mini-graph-card
hours_to_show: 48
points_per_hour: 0.25
hour24: true
entities:
  - sensor.sky_q_used_storage
color_thresholds:
  - value: 0
    color: '#00ff00'
  - value: 500
    color: '#ffff00'
  - value: 700
    color: '#ff0000'
```

**Comment by ildar170975** [comment, marked as answer]
No requests should be investigated with wrongly formatted code.

**Reply by miggi92** [reply]
updated coding...

**Reply by ildar170975** [reply]
Try to test with these similar settings for:
```
        lower_bound: 0
        line_width: 1
        color_thresholds_transition: hard
        aggregate_func: last
        show:
          points: true
          labels: true
```

In my case it works OK:
```
      - type: custom:mini-graph-card
        hours_to_show: 1
        points_per_hour: 240
        hour24: true
        lower_bound: 0
        line_width: 1
        color_thresholds_transition: hard
        aggregate_func: last
        height: 400
        entities:
          - sensor.processor_use
        show:
          points: true
          labels: true
        color_thresholds:
          - value: 0
            color: '#008000'
          - value: 40
            color: '#ffff00'
          - value: 60
            color: '#ff0000'
          - value: 80
            color: '#00ffff'
```
![image](https://user-images.githubusercontent.com/71872483/177542420-3ba6fb4a-8954-4a49-8c0a-a22a750b04e5.png)
