### DISCUSSION TITLE
Unit before value

### DISCUSSION THREAD

**Discussion by hancooo** [kalkih/mini-graph-card#845] [General]
Hello. 

Is there a way for the unit to be placed before the value. 
In my case it is the cost of something. I want it to read £7.09 instead of 7.09£.

![image](https://user-images.githubusercontent.com/20757683/193674645-f2e63aca-dac9-42e1-acf7-fb1d2563b439.png)

Thanks

```
type: custom:mini-graph-card
entities:
  - sensor.daily_usage_cost
name: Daily Cost
icon: mdi:transmission-tower
unit: £
color_thresholds:
  - value: 17
    color: '#2ecc71'
  - value: 19
    color: '#f1c40f'
  - value: 24
    color: '#e74c3c'
font_size: 75
hours_to_show: 168
aggregate_func: max
group_by: date
show:
  graph: bar
```
