### DISCUSSION TITLE
How to show value for today or this year only ?

### DISCUSSION THREAD

**Discussion by KrzesloSzatan** [kalkih/mini-graph-card#849] [Q&A]
Ive got a socket that aggregates power usage but unfortunately to be able to see it in hass i have to use Riemann's sum for its Current consumption since its the only parameter i cag get out of it. With that i get an energy usage sensor but it shows whole usage from the beginning to this moment. I would like to somehow see only today's or/and this year's usage or from date to date. I have tried this way

```
entities:
  - entity: sensor.energy_spent
    name: Current usage
    aggregate_func: diff
    update_interval: 60
group_by: date
hour24: true
hours_to_show: 168
show:
  graph: bar
  labels: false
type: custom:mini-graph-card
icon: mdi:lightning-bolt
```

But it still shows current value in the main screen and i would like to see today's value there :/ When i setup hours_to_show: 24 so in theory i should get only 1 bar with today it doesnt show any value on hoover. 

Is there any option to show not the current sensor value in the main screen but an aggregated value ONLY or/and display only today's or this year values ?
