### DISCUSSION TITLE
WAN Traffic Graph with Inverse In/Out

### DISCUSSION THREAD

**Discussion by DeFlanko** [kalkih/mini-graph-card#861] [Q&A] [answered]
The best way to describe it is to show you what pfSense is doing:
![image](https://user-images.githubusercontent.com/5233969/198895124-0eb5f73a-0bf6-4fc6-9823-742336d13068.png)

looking to find a way to replicate this in mini-graph where the WAN traffic In and Out or inversed to each other. 

Is this possible now or is this a feature?

**Comment by DeFlanko** [comment]
Currently what i have:
```YAML
type: custom:mini-graph-card
show:
  labels: true
  name_adaptive_color: true
  icon_adaptive_color: true
  average: true
  extrema: true
height: 150
hours_to_show: 0.25
points_per_hour: 360
line_width: 2
animate: true
value_factor: -2.108
lower_bound: ~0
color_thresholds:
  - value: 10000
    color: '#8FCE00'
  - value: 4000
    color: '#008fce'
  - value: 500
    color: '#ce008f'
entities:
  - entity: >-
      sensor.protectli_pfsense_1930networks_com_interface_wan_inbytes_kilobytes_per_second
    unit: Mbit/s
    name: Download
  - entity: >-
      sensor.protectli_pfsense_1930networks_com_interface_wan_outbytes_kilobytes_per_second
    unit: Mbit/s
    name: Upload
name: Active Internet (Last 15 Mins)
```
(The value factor took a bit of trial and error, that too should use a "if this then convert to that" feature... in this case i needed to convert kilobytes/s to MegaBits/s)

![image](https://user-images.githubusercontent.com/5233969/198897563-5ce6bfc4-7625-47e9-bc02-9235323827f7.png)

**Reply by ildar170975** [reply]
Not related to the main issue - but I personally do not suggest to show "extrema" & "average" values when more than 1 entity displayed with graphs since these "extrema" & "average" values are shown for the 1st entity only.
One of exclusions: card contains 2 or more entities, the 2nd & 3rd entities are with "show_state=true" & "show_graph=false"; then a user is less confused - for the "main" entity a graph, a state and  "extrema" & "average" values are displayed, for other entities only states are displayed.

**Reply by DeFlanko** [reply]
I was using value_factor: -2.108 becasue the data on the pfsense is not in mBit/s -- this logic is no longer in the graph per the latest update i did. i made a calculated sensor to fix that. 

Im reviewing your second update to see if works for me too .

**Reply by ildar170975** [reply]
> this logic is no longer in the graph per the latest update i did

What update are you talking about?

**Reply by DeFlanko** [reply]
https://github.com/kalkih/mini-graph-card/discussions/861#discussioncomment-5388745

**Comment by DeFlanko** [comment, marked as answer]
Update.

```yaml
type: custom:mini-graph-card
show:
  labels: true
  name_adaptive_color: true
  icon_adaptive_color: true
  average: true
  extrema: true
height: 150
hours_to_show: 0.25
points_per_hour: 360
line_width: 2
animate: true
lower_bound: ~0
color_thresholds:
  - value: 100
    color: '#8FCE00'
  - value: 40
    color: '#008fce'
  - value: 10
    color: '#ce008f'
  - value: 0
    color: '#000000'
  - value: -10
    color: '#008fce'
  - value: -40
    color: '#8FCE00'
entities:
  - entity: sensor.pfsense_download_mbps_speed
    unit: Mbit/s
    name: Download
  - entity: sensor.pfsense_upload_mbps_speed
    unit: Mbit/s
    name: Upload
name: Active Internet (Last 15 mins)
```

Where i had to add the following in `configuration.yaml`
```yaml
      - name: "pfSense_Upload_Mbps_speed"
        state_class: measurement
        #Replace by MB/s if you want to use bytes/sec instead of bits/sec
        unit_of_measurement: Mb/s
        icon: mdi:upload
        state: >
          {% set WAN = states('sensor.protectli_pfsense_1930networks_com_interface_wan_outbytes_kilobytes_per_second') | float(0) %}
          {{ (0-(WAN)*8/1024) }}

      - name: "pfSense_Download_Mbps_speed"
        state_class: measurement
        #Replace by MB/s if you want to use bytes/sec instead of bits/sec
        unit_of_measurement: Mb/s
        icon: mdi:download
        state: >
          {% set WAN = states('sensor.protectli_pfsense_1930networks_com_interface_wan_inbytes_kilobytes_per_second') | float(0) %}
          {{ (WAN)*8/1024 }}
```

![image](https://user-images.githubusercontent.com/5233969/226808895-dc8c7eb9-5843-4931-9c74-b1f052b8c1dc.png)
