### DISCUSSION TITLE
update_interval does not work

### DISCUSSION THREAD

**Discussion by tzwientjuh** [kalkih/mini-graph-card#908] [Q&A]
Copy of code down below. Title explains itself. Update_interval does not seem to work. It stays at 5 seconds (timed with stop watch) changing to 1 or 10 or any other number does nothing

```
type: custom:mini-graph-card
name: Huidig Energie Verbruik
font_size_header: 14
hours_to_show: 2
align_state: right
show:
  fill: fade
  icon_adaptive_color: true
entities:
  - sensor.elek_huidig_verbruik
font_size: 75
line_color: '#ab3ce7'
decimals: 0
smoothing: true
animate: true
update_interval: 10 
points_per_hour: 60
line_width: 4
fixed_value: false
hour24: true
```
