### DISCUSSION TITLE
How: power consumption per month?

### DISCUSSION THREAD

**Discussion by kuttikutt** [kalkih/mini-graph-card#927] [Q&A]
Hello!

I added a Helper which accumulates the used power of my grids power meter. This gets reset monthly. (so e.g. my power meter goes from 7000 kWh to 7100 kWh = 100kWh, next month: it goes from 7100 to 7222 = 122kWh etc.)

Tried a lot of things but now I'm kinda lost. 

Here is my code:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.verbrauchpromonat
    unit: kWh
name: Monatsverbrauch
hours_to_show: 8760
hour24: true
aggregate_func: last
group_by: interval
show:
  graph: bar
  state: true
lower_bound: 0
```
The sensos "sensor.verbrauchpromonat" increases and gehts reset to 0 every month. 
hours_to_show: 8760 = one year
I think the issue is "group_by" - I'm missing something like "monthly" there... 

Now it looks like this: 
![grafik](https://user-images.githubusercontent.com/17554764/220043626-f37635e5-181d-4063-a1a7-2855bacd38a8.png)

Why are there so many bars? Interval of the sensor = month (so 30 days). 30 days = 720h, 8760 / 720h = 12 (around 12). 
Also: Why is the inverval so odd? 
`So., 12., 18:14 - Do.,16., 13.28?`
That's 3 days, 19 hours, 14 minutes ... 

But I want to display the past 12 months in 12 bars showing the monthly power consumption. 

Any ideas?
