### DISCUSSION TITLE
Options:  hours_to_show: and  points_per_hour: seems not working?

### DISCUSSION THREAD

**Discussion by lucode** [kalkih/mini-graph-card#946] [Q&A] [answered]
Hi there, 
I try to fiddle out how I can display my Solar yield and forecast in an nice way, but I don't get any big changes in what the graph shows. The time range is not set to 48 hours and instead of displaying 60 datapoints per hour I get only 1 per 2 hours.
 
![image](https://user-images.githubusercontent.com/2928740/227886381-13dd3def-2c02-4a53-b089-7389a0a3bb4a.png)
    
Furthermore I would like to show some number on the Y axis (time). I would really appreciate some help for this.

 ```
  - entity: sensor.energy_production_today
        name: Production today
        show_line: true
        show_points: false
        show_legend: true
        smoothing: false
        hours_to_show: 48
        points_per_hour: 60
        lower_bound: 2
    show:
      labels: true
```

At the end I would like to have a similar graph then from the normal graph card, but with the options from mini-graph-card.

![image](https://user-images.githubusercontent.com/2928740/227888313-dfd771e3-1c1f-4245-bf83-0720323bb482.png)

**Comment by ildar170975** [comment, marked as answer]
Wrong indentation - some options are ignored.

**Reply by lucode** [reply]
Got it, but it is a bit confusing. This way it works.

```
entities:
  - entity: sensor.energy_production_tomorrow
    name: Production tomorrow
  - entity: sensor.energy_production_today
    name: Production today
smoothing: false
hours_to_show: 48
points_per_hour: 6
```
