### ISSUE TITLE
Error when stacking graphs in horizontal-stack panel

### ISSUE THREAD

**Issue by dominikheinz** [kalkih/mini-graph-card#100]
Hello,

When I am trying to add a graph for my humidity sensor like so it works just fine:
![image](https://user-images.githubusercontent.com/32770080/58386717-f11d5780-8003-11e9-8e66-f3710930993f.png)

However when trying to do the exact same thing in a stack panel so that I can add more sensors I am prompted with the following error:
![image](https://user-images.githubusercontent.com/32770080/58386729-1c07ab80-8004-11e9-88dd-f934972a3801.png)

Whats wrong?

**Comment by kalkih** [comment]
Hey, you forgot the dash before the card type

```yaml
- type: horizontal-stack
  cards:
    - type: custom:mini-graph-card #here
      entities:
        - sensor.example
       
```

**Comment by dominikheinz** [comment]
Thanks for your reply. But this doesn't fix the issue. The problem is the same.

**Comment by kalkih** [comment]
Sorry, I've never really used the card configuration GUI, but I think you might have to remove the dash before type on the horizontal stack
```yaml
type: horizontal-stack
cards:
  - type: custom:mini-graph-card #here
    entities:
      - sensor.example
```
