### ISSUE TITLE
hiding main entity state / show_icon_adaptive_color: true doens't seem ok

### ISSUE THREAD

**Issue by lecocqe** [kalkih/mini-graph-card#1018]
hello, 

in the following snippet, 
1) i would like to hide "50%" (state of main entity) from the graph
![image](https://github.com/kalkih/mini-graph-card/assets/18657222/da81a75d-fba6-4c78-85ff-45876fb1d670)
```
type: custom:mini-graph-card
entities:
  - entity: sensor.wc_batt
    show_graph: false
    show_state: false

  - entity: sensor.wc_temp
    show_graph: true
    show_state: true
name: WC
show_state: false
show_icon_adaptive_color: true
show_legend: false

```

2) i would like to make the color of the battery icon follow the value as indicated in documentation
![image](https://github.com/kalkih/mini-graph-card/assets/18657222/65c59c20-6b35-44f8-b4ad-75c5d8578519)

![image](https://github.com/kalkih/mini-graph-card/assets/18657222/62fc8c68-e7e7-4ed0-b1ed-3426a5382431)

as mentioned in entity card:
![image](https://github.com/kalkih/mini-graph-card/assets/18657222/57e6cd5e-d156-4400-8330-726018b7afc2)

thank you for the great job you do
Regards
