### ISSUE TITLE
Values wrong with grouping by hour to show max value

### ISSUE THREAD

**Issue by wizbowes** [kalkih/mini-graph-card#1020]
I have a graph showing hourly rainfall.  However sometimes the bars don't match the underlying data.

Here's the yaml:

```
type: custom:mini-graph-card
icon: mdi:weather-rainy
name: Hourly Rainfall
hours_to_show: 24
points_per_hour: 1
group_by: hour
aggregate_func: max
show:
  graph: bar
  fill: true
  icon: false
color_thresholds:
  - value: 12
    color: '#030ffc'
  - value: 7
    color: '#353ffc'
  - value: 5
    color: '#656dfc'
  - value: 3
    color: '#979dfc'
  - value: 1
    color: '#afb3fa'
  - value: 0
    color: '#ffffff'
entities:
  - entity: sensor.rainfall_hour
    state_adaptive_color: false
```

Here's the current output - as you can see the last hour with data is showing 1.5mm rain

![image](https://github.com/kalkih/mini-graph-card/assets/25068983/23933da6-5382-44a9-a279-4aa68356677a)

However in the raw data you can see that it should be 0.5mm

![image](https://github.com/kalkih/mini-graph-card/assets/25068983/23a39b12-f315-4ddc-8d53-7edb51da0356)

Home Assistant 2023.10.3
Frontend 20231005.0 - latest
Mini-Graph:  v0.11.0
