### ISSUE TITLE
Showing all data points

### ISSUE THREAD

**Issue by dopeytree** [kalkih/mini-graph-card#1031]
Hi having some issues with all data points showing even when turned off.

Here we have our 4 sensors overlaid onto one card. They are all temperature sensors essentially in different parts of the house.
<img width="517" alt="Screenshot 2023-11-19 at 01 32 02" src="https://github.com/kalkih/mini-graph-card/assets/103341262/468e60b6-2cbc-470c-af7e-27ec6b11d2ac">

If you hover over a line this you get the detail of one sensors history. This is working correctly.
<img width="522" alt="Screenshot 2023-11-19 at 01 32 15" src="https://github.com/kalkih/mini-graph-card/assets/103341262/1761fd4f-d219-49ca-baed-30cb7e7d8f61">

However when you then stop the 'hover' over the line and it should refresh the graph, it is instead showing all points ever recorded - which looks super messy..
<img width="520" alt="Screenshot 2023-11-19 at 01 32 07" src="https://github.com/kalkih/mini-graph-card/assets/103341262/e8fa70ad-bfe7-4f01-b63f-91d699e112c6">

This is the code I am using
<img width="979" alt="Screenshot 2023-11-19 at 01 32 22" src="https://github.com/kalkih/mini-graph-card/assets/103341262/edb9cdcd-1993-473d-834c-9d03938f72b5">

```
type: custom:mini-graph-card
name: Temperature
show:
  state: true
  average: false
  extrema: true
  labels: false
  legend: true
  fill: false
  show_points: true
  icon_adaptive_color: true
  name_adaptive_color: true
hours_to_show: 24
points_per_hour: 3
line_width: 1
entities:
  - entity: sensor.1_garden_temperature
    color: '#02a8f4'
  - entity: sensor.2_phonebox_temperature
    color: '#ff9800'
  - entity: sensor.3_greenhouse_temperature
    color: '#f44336'
  - entity: sensor.4_shed_temperature
    color: '#e91e63'
  - entity: sensor.7_barn_temperature
    color: '#9c27b0'
```
