### ISSUE TITLE
Ignore "Entity not available"

### ISSUE THREAD

**Issue by monsieurhannes** [kalkih/mini-graph-card#1032]
Hi,

I have an ESPHome-device that is from time to time offline. It shows the temperature, but it's either out of range or just picky. 
However, I display it with all the other sensors in the house on the main page, but when this (or any other) sensor goes offline for more than 24h, the whole graph disappears with the following error:
![image](https://github.com/kalkih/mini-graph-card/assets/20651440/f6ddd7f6-a73d-49a1-a8c7-e0221e9a2c43)

Is there anything I can do to ignore missing entities? 

```yaml
type: custom:mini-graph-card
decimals: 1
entities:
  - entity: sensor.lumi_lumi_weather_temperature
    name: Living Room
    color: violet
  - entity: sensor.lumi_lumi_airmonitor_acn01_temperature
    name: Bedroom
    color: '#FBB829'
  - entity: sensor.lumi_lumi_weather_temperature_2
    name: Emma's Room
    color: lightgreen
  - entity: sensor.temp_sensor_01_temp_sensor_01_temp
    name: Attic
    color: '#B7121F'
  - entity: sensor.lumi_lumi_weather_temperature_4
    name: Bathroom
  - entity: sensor.altherma_outside_temperature
    name: Heat pump outdoor
    color: '#1B3D81'
  - entity: sensor.bt_bridge_01_temp_sensor_03_temp
    name: Kitchen
    color: orange
  - entity: sensor.temp_sensor_02_temp_sensor_02_temp
    name: Garden
    color: green
name: Temperature 24h
hour24: true
hours_to_show: 24
line_width: 0.5
points: false
points_per_hour: 1
show:
  fill: fade
  icon_adaptive_color: false
animate: true
```
