### ISSUE TITLE
Fill based on another entity?

### ISSUE THREAD

**Issue by fodi666** [kalkih/mini-graph-card#1036]
Hi,
is it possible to specify that a line should be filled on parts when another entity has a certain value? I have my heating system's data hooked up with this card and I wold like to show when the heating is active. Currently I have a temperature entity which I display and I have a heating active binary entity that I'd like to use to control the fill (fill only when true, similar to the default display of a climate entity).
Thanks

**Comment by ildar170975** [comment]
Not possible currently.
You may prepare a DETAILED description of a desired functionality and propose a "Feature request".

Or find another ways.

**Comment by fodi666** [comment]
how much detail do you need?

**Comment by ildar170975** [comment]
How much do YOU need to write a working code?
Principles of making a good technical assignment is an off-topic here.
It should be a complete description  for a person who will be able to implement this.

**Comment by Glideh** [comment]
That'd be great to have the same conditional fill under the temperature line as HA's default graph behavior with the thermostat
![image](https://github.com/kalkih/mini-graph-card/assets/1119270/c972f7b5-f251-4d81-9615-8fb5ec97f1e8)
_even if this one is quite ugly :)_

Maybe we could give the ability to configure a conditional fill property into the entity line like this:

```yml
type: custom:mini-graph-card
entities:
  - entity: climate.heater
    attribute: current_temperature
  - entity: climate.heater
    attribute: temperature
    fill:
      type: entity
      entity: climate.heater
      color_mapping:
        heat: red
        cool: blue
```
