### ISSUE TITLE
❔ How to calculate sec to hour for additional info

### ISSUE THREAD

**Issue by n3de** [kalkih/mini-graph-card#1043]
Hey,

first thank you very much for this great card! It is awesome. I'm unsing it so show the energy from my devices:
![image](https://github.com/kalkih/mini-graph-card/assets/81101039/51326995-2b9d-4075-8ef0-ce083b49f141)

```
type: custom:mini-graph-card
hours_to_show: 8
points_per_hour: 60
graph: line
animate: true
line_width: 2
line_color: green
hour24: true
show:
  average: true
  extrema: true
entities:
  - entity: sensor.gefrierschrank_leistungswert
  - entity: sensor.gefrierschrank_stromzahler
    show_state: true
    show_graph: false
  - entity: sensor.gefrierschrank_betriebsstunden
    show_state: true
    show_graph: false
```
As you can see, the "betriebsstunden" (working hours) are in seconds. Is there any option to display this in hour directly in the card?
