### ISSUE TITLE
`tap_action` does not do anyting in HA 2024

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [kalkih/mini-graph-card#1052]
Hi there,

I am trying to set `action` to `none` for `tap_action`. But the card still shows the more-info dialog.

Example code:

```yaml
type: custom:mini-graph-card
tap_action:
  action: none
```

System

Home Assistant
Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.4
Frontend 20240104.0

Any idea what is broken?
