### ISSUE TITLE
The display of numerical values does not support the format set in HA

### ISSUE THREAD

**Issue by trandus** [kalkih/mini-graph-card#1061]
Numerical values on chart sheets are always displayed in the format xxx,xxx.yy, irrespective of the format set in HA.
Chart example:
![image](https://github.com/kalkih/mini-graph-card/assets/25478709/7608fb05-5e5f-4c38-9bb1-5b5bc2917f89)
Settings in HA:
![image](https://github.com/kalkih/mini-graph-card/assets/25478709/c86dd52c-4964-4e60-9f44-4163d93af477)
Graph YAML:
```
type: custom:mini-graph-card
name: Weather
entities:
  - entity: sensor.weather_forecast_home_temperature
    name: Temperature Outside
  - entity: sensor.lumi_gerald_pressure_calibrated_average
    name: Pressure
    show_state: true
    y_axis: secondary
    color: '#7516e0'
hours_to_show: 96
points_per_hour: 1
show:
  fill: false
color_thresholds:
  - value: -50
    color: '#036bfc'
  - value: 0
    color: '#00c427'
  - value: 25
    color: '#fc3838'

```
