### ISSUE TITLE
Bug: color_thresholds gray

### ISSUE THREAD

**Issue by WhistleMaster** [kalkih/mini-graph-card#107]
Hi, 

I've the following configuration:

```
color_thresholds:
  - color: blue
    value: 0
  - color: lightblue
    value: 10
  - color: orange
    value: 20
  - color: red
    value: 30
entities:
  - sensor.netatmo_indoor_temperature
name: Indoor
show:
  extrema: true
type: 'custom:mini-graph-card'

```

resulting to the following:

<img width="472" alt="Screenshot 2019-06-16 at 10 01 04" src="https://user-images.githubusercontent.com/1544568/59561213-e01da000-901d-11e9-85e8-5edd408a1b83.png">

I've just upgraded to 0.4.3 from 0.3.3 and it was working fine with 0.3.3.
