### ISSUE TITLE
show_points: false

### ISSUE THREAD

**Issue by dusan-ivanco** [kalkih/mini-graph-card#1083]
show_points: false make exception

```
          - type: custom:mini-graph-card
            name: Teplota
            icon: mdi:thermometer
            aggregate_func: median
            points_per_hour: 1
            hours_to_show: 12
            line_width: 5
            decimals: 1
            smoothing: true
            hour24: true
            show:
              state: last
              points: false
            tap_action:
              action: none
            entities:
              - entity: sensor.temperature
                name: Priemer
              - entity: sensor.thermo_room_1_temperature
              - entity: sensor.thermo_room_2_temperature
              - entity: sensor.thermo_room_3_temperature
```

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Kd.getEntityState (graph-card.js?v=0.12.0:1:100443)
    at Kd.renderState (graph-card.js?v=0.12.0:1:100638)
    at Kd.renderStates (graph-card.js?v=0.12.0:1:100127)
    at Kd.render (graph-card.js?v=0.12.0:1:99132)
    at Kd.update (graph-card.js?v=0.12.0:1:49160)
    at Kd.performUpdate (graph-card.js?v=0.12.0:1:46377)
    at graph-card.js?v=0.12.0:1:46037
    at Generator.throw (<anonymous>)
    at R (graph-card.js?v=0.12.0:1:17743)
    at g (graph-card.js?v=0.12.0:1:17962)
```
