### ISSUE TITLE
Having problems getting this to work again, "No card type configured"

### ISSUE THREAD

**Issue by YamiFrankc** [kalkih/mini-graph-card#109]
Hello, I have a new installation of Hassio and im having trouble getting this card to work:
This is what I have in my ui-lovelace.yaml
```
resources:
  - type: module
    url: /local/mini-graph-card-bundle.js?v=0.4.3
title: casa
views:
...
```
And this is that Im trying to add to love lace(grabbed from one of the examples from here):
```
- type: custom:mini-graph-card
  entities:
   - sensor.speedtest_download
  align_icon: left
  align_state: center
  show:
    fill: false
```

And im getting a "No card type configured" error, I have the .js file in the www/ folder. Im not completely sure what is wrong here
