### ISSUE TITLE
Unable to set range correctly

### ISSUE THREAD

**Issue by wolf99** [kalkih/mini-graph-card#1090]
Hi there,

Firstly thank you for such a great card!

Probably this is more of a question than any issue or bug report. I cannot figure out how to correctly set the height that the y- axiz should show.

My graph shows humidity, so the Y-axis should show from 0 to 100% at all times, this would mean that changes from (for example) 99% to 98% would look very small. But instead my configuration is only showing the Y-axis with the min and max so far, whereby the change from 94% to 99% looks like the entire verticle height of the graph.

Please could someone indicate what I am doing wrong?

Apologies but I could not figure it out myself after reading the README.md

My configuration:

```yaml
type: custom:mini-graph-card
name: Owlet O2 Saturation
entities:
  - entity: sensor.owlet_baby_care_sock_o2_saturation
    name: O2 Saturation
    show_state: true
    y_axis: secondary
hours_to_show: 36
lower_bound: 0
upper_bound: 100
min_bound_range: 100
color_thresholds_transition: hard
show:
  extrema: true
  average: true
  icon_adaptive_color: true
  labels: true
color_thresholds:
  - value: 0
    color: '#ed4c3e'
  - value: 90
    color: '#7ef97d'
  - value: 100
    color: '#7ef97d'

```

Screenshot:

![image](https://github.com/kalkih/mini-graph-card/assets/281700/b4d5c62c-f5bd-4b0f-ae65-f75883362fce)
