### ISSUE TITLE
Enhancement - Show state for numerical range values

### ISSUE THREAD

**Issue by DeFlanko** [kalkih/mini-graph-card#1097]
Looking to utilize the State_map function for heart rates:

```yaml
type: custom:mini-graph-card
labels: true
name_adaptive_color: true
lower_bound: 50
color_thresholds:
  - value: 180
    color: '#9A56A3'
    name: High Performance Zone
  - value: 155
    color: '#3B9555'
    name: Performance Zone
  - value: 135
    color: '#EA9423'
    name: Fitness Zone
  - value: 110
    color: '#FEEB3F'
    name: Health Improvement Zone
  - value: 90
    color: '#8CABD7'
    name: Inactive
state_map:
  - value: 180
    color: '#9A56A3'
    label: High Performance Zone
  - value: 155
    color: '#3B9555'
    label: Performance Zone
  - value: 135
    color: '#EA9423'
    label: Fitness Zone
  - value: 110
    color: '#FEEB3F'
    label: Health Improvement Zone
  - value: 90
    color: '#8CABD7'
    label: Inactive
height: 50
hours_to_show: 4
points_per_hour: 12
line_width: 3
animate: true
show:
  name_adaptive_color: true
  icon_adaptive_color: true
  labels: true
entities:
  - entity: sensor.google_pixel_watch_jd_heart_rate_2
name: Heart Rate
`

currently it wont show what heart zone the sensor is in. Would be nice to see that next to the bpm
![image](https://github.com/kalkih/mini-graph-card/assets/5233969/2578e8d8-a0bc-4e9b-a1e5-52a582bb4603)

**Comment by ildar170975** [comment]
Suggest to re read Docs & check your code.
Just a 1st glance:

```
type: custom:mini-graph-card
labels: true
```
Here the `labels` is misplaced.

```
color_thresholds:
  - value: 180
    color: '#9A56A3'
    name: High Performance Zone
```
The `color_thresholds` does not have `name` option.

```
state_map:
  - value: 180
    color: '#9A56A3'
    label: High Performance Zone
```
The `state_map` does not have `color` option.

Also, `state_map` does not work for ranges, it works for exact values.

**Comment by DeFlanko** [comment]
which is why i asked it to be an **_enhancement_** request, i completely understand how the state_map is only for single digit non ranged values, but i'm looking to have it look to ranged values so that anything in between the two heart ranges can named that state_mapped value. 

Corrected all the code logic btw, still works - but again asking for the state_mapped value to be a range. 

```yaml
type: custom:mini-graph-card
name_adaptive_color: true
lower_bound: 50
color_thresholds:
  - value: 180
    color: '#9A56A3'
  - value: 155
    color: '#3B9555'
  - value: 135
    color: '#EA9423'
  - value: 110
    color: '#FEEB3F'
  - value: 90
    color: '#8CABD7'
state_map:
  - value: 180
    label: High Performance Zone
  - value: 155
    label: Performance Zone
  - value: 135
    label: Fitness Zone
  - value: 110
    label: Health Improvement Zone
  - value: 90
    label: Inactive
height: 50
hours_to_show: 4
points_per_hour: 12
line_width: 3
animate: true
show:
  name_adaptive_color: true
  icon_adaptive_color: true
  labels: true
entities:
  - entity: sensor.google_pixel_watch_jd_heart_rate_2
name: Heart Rate

```
