### ISSUE TITLE
[Question] Is it possible to link the color threshold value to a sensor so it changes dynamically?

### ISSUE THREAD

**Issue by Boerny41** [kalkih/mini-graph-card#1099]
```
type: custom:mini-graph-card
entities:
  - sensor.bme280_temp
icon_adaptive_color: true
icon: mdi:home-thermometer-outline
font_size: 140
name: null
hour24: true
hours_to_show: 24
points_per_hour: 6
show:
  labels: false
color_thresholds_transition: smooth
color_thresholds:
  - value: 20
    color: blue
  - value: 21
    color: turquoise
  - value: 22
    color: lightgreen
  - value: 23
    color: yellow
  - value: 24
    color: orange
  - value: '{{ states("sensor.max_temperature") }}'
    color: red
```

I tried it like this but it didn't work. The sensor has a valid number (26.7) and is online. All I could finde was one guide but he used "value_template" which doesn't seem to be supported anymore.
