### ISSUE TITLE
Date Format on Extrema

### ISSUE THREAD

**Issue by zillion42** [kalkih/mini-graph-card#1102]
I have the following card:
![2024-05-11 15_59_48-Overview – Home Assistant](https://github.com/kalkih/mini-graph-card/assets/36650866/2037b0f8-86f9-4bc5-b11f-2fb365b3d39f)

with this code:
```
      - entities:
          - entity: sensor.samsung_c3060_series_cyan_toner_s_n_crum_21071530203
            name: Cyan Toner_S/N_:CRUM-21071530203
            show_points: false
          - color: gray
            entity: sun.sun
            name: Sun
            show_line: false
            show_points: false
            show_legend: false
            y_axis: secondary
        type: custom:mini-graph-card
        upper_bound: 100
        lower_bound: 2
        points_per_hour: 1
        height: 100
        line_width: 2
        hour24: true
        hours_to_show: 2000
        show:
          fill: true
          labels: true
          labels_secondary: false
          extrema: true
        state_map:
          - value: above_horizon
          - value: below_horizon
        color_thresholds:
          - value: 0
            color: '#ffffff'
          - value: 100
            color: '#00deff'
```
It looks like the date format is `d dddd, HH:MM` <- thats really not helpful.
