### ISSUE TITLE
Dynamic line color breaks at highest value

### ISSUE THREAD

**Issue by FilmForge3D** [kalkih/mini-graph-card#1108]
When using the dynamic line color on my installation (fully up to date as of 2.6.2024) the coloring of the line stops working when the sensor value is over the color threshold. Instead of the highest value color the line color is one from a lower point on the graf.

Adding another value high above the ones that can ever be reached does not resolve the issue.

![image](https://github.com/kalkih/mini-graph-card/assets/65822131/0b6a3e62-ccf8-449c-a02c-a606b3d7d01e)

```
type: custom:mini-graph-card
name: Gartenklima
icon: mdi:thermometer-water
entities:
  - entity: sensor.thermometer_garten_temperature
    show_legend: false
    show_state: true
  - entity: sensor.thermometer_garten_humidity
    color: blue
    show_legend: false
    show_state: true
    y_axis: secondary
color_thresholds:
  - value: -5
    color: '#8000ff'
  - value: 0
    color: '#0045ff'
  - value: 10
    color: '#00c8ff'
  - color: '#c8ff80'
  - color: '#ffc800'
  - color: '#ff8000'
  - value: 25
    color: '#ff0000'
line_width: 2
points_per_hour: 2
hour24: true
smoothing: true
animate: true

```
