### ISSUE TITLE
A weird padding when "fill: false"

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#1109]
Compare these cards:

1. `fill: true`:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_temperature
show:
  fill: true
```
![изображение](https://github.com/kalkih/mini-graph-card/assets/71872483/251d3d2a-9d57-4d8a-a628-cad03a08d16e)

2. `fill: false`:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_temperature
show:
  fill: false
```
![изображение](https://github.com/kalkih/mini-graph-card/assets/71872483/368d8a58-e5b0-4830-8954-203a79bee58b)

3. `show_fill: true`:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_temperature
    show_fill: true
```
![изображение](https://github.com/kalkih/mini-graph-card/assets/71872483/6521781b-0619-4258-a762-ce45a54ad29e)

4. `show_fill: false`:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_temperature
    show_fill: false
```
![изображение](https://github.com/kalkih/mini-graph-card/assets/71872483/c22a006c-7cdc-4b85-a6d7-5b7d670651d5)

There is a weird padding when `fill: false`.
