### ISSUE TITLE
Layoutoption with HA 2024.7.0bx

### ISSUE THREAD

**Issue by ChristophCaina** [kalkih/mini-graph-card#1111]
With HomeAssistant 2024.7.x a new Layout-Option for cards will be implemented.
This option does allow to define, what size a card should have.

This can be implemented in UI or via YAML:

UI Option for different cards:
![image](https://github.com/kalkih/mini-graph-card/assets/26391061/e25f4a8a-4510-46d9-be0e-0b26535098ef)

same card, yaml-code:
```
type: gauge
entity: sensor.heizkorperthermostat_kuche_level
name: Ventilstellung
layout_options:
  grid_columns: 2
  grid_rows: 2
```

I've used the yaml option for the mini-graph-card as well - and it is working
```
type: custom:mini-graph-card
entities:
  - entity: sensor.heizkorperthermostat_kuche_actual_temperature
hours_to_show: 24
points_per_hour: 4
name: Temperatur
layout_options:
  grid_columns: 2
  grid_rows: 2
```
![image](https://github.com/kalkih/mini-graph-card/assets/26391061/46ab0ab4-1b56-46b5-b5ad-4a2b7cd2ccef)

But having the gauge and the mini-graph-card placed by each other, it is visible, that the graph card is slightly bigger than the gauge:

This screenshot is showing the same configuration - in the first row, both cards are placed inside a horizontal-stack card,
In the row below, they are using the new layout option inside a section.
![image](https://github.com/kalkih/mini-graph-card/assets/26391061/41e0e3f2-a16a-479e-ae48-ff68fb853674)
