### ISSUE TITLE
Graph not displaying correct values

### ISSUE THREAD

**Issue by bkr1969** [kalkih/mini-graph-card#1114]
I believe this just started yesterday, but not 100 percent sure.  However, I have two sets of data that I display related to solar power for the past 24 hours, current production and total.  This previously gave me a chart where both bars would grow throughout the day then taper down as the sun set, with the current production going to near 0 while the total would remain at the peak for the day until the next morning.  Now, both bars are the same throughout and do not display the values at all.  I'm not eve sure where they are getting the numbers that are displayed.

```
type: custom:mini-graph-card
entities:
  - entity: sensor.envoy_121847041313_current_power_production
    name: Current Production
  - entity: sensor.envoy_121847041313_energy_production_today
    color: green
    name: Total Production
name: Solar Energy Prodution
icon: mdi:sun-wireless
hours_to_show: 24
points_per_hour: 1
show:
  graph: bar
state: true
show_state: true
```
