### ISSUE TITLE
Color threshold for secondary axis entities

### ISSUE THREAD

**Issue by MaJerle** [kalkih/mini-graph-card#1119]
How can we set secondary axis color threshold?

I would like to have different ones for temperature and humidity.

```yaml
type: custom:mini-graph-card
entities:
  - entity: sensor.temp_hum_sensor_5_terrace_temperature
    name: Temperature
  - entity: sensor.temp_hum_sensor_5_terrace_humidity
    name: Humidity
    y_axis: secondary
name: Temperature
points_per_hour: 4
color_thresholds:
  - value: 0
    color: '#FF0000'
  - value: 18
    color: '#FFFF00'
  - value: 20
    color: '#00FF00'
  - value: 24
    color: '#FFFF00'
  - value: 28
    color: '#FF0000'

```

**Comment by akloeckner** [comment]
I don't think, it is possible. But maybe you could just extend the list of thresholds to the humidity values' range?

Something like:

```yaml
color_thresholds:
  - value: 0
    color: '#FF0000'
  - value: 18
    color: '#FFFF00'
  - value: 20
    color: '#00FF00'
  - value: 24
    color: '#FFFF00'
  - value: 28
    color: '#FF0000'
  - value: 35
    color: '#FF0000'
  - value: 35.1
    color: '#00FF00'
  - value: 60
    color: '#FFFF00'
  - value: 70
    color: '#FF0000'
```
