### ISSUE TITLE
icon_adaptive_color always show first color threshold if entity attribute selected

### ISSUE THREAD

**Issue by klonwar** [kalkih/mini-graph-card#1129]
I have a graph for openmeteo weather:

```
type: horizontal-stack
cards:
  - type: custom:mini-graph-card
    unit: °C
    icon: mdi:thermometer
    align_icon: state
    align_state: center
    color_thresholds:
      - value: -30
        color: '#7851a9'
      - value: -20
        color: '#7366bd'
      - value: -10
        color: '#6495ed'
      - value: 0
        color: '#00bfff'
      - value: 10
        color: '#00BCD4'
      - value: 15
        color: '#45cea2'
      - value: 18
        color: '#FF9800'
      - value: 20
        color: '#FF9800'
      - value: 30
        color: '#e64a19'
      - value: 35
        color: '#C62828'
    decimals: 1
    entities:
      - entity: weather.openmeteo
        attribute: temperature
        state_adaptive_color: true
        show_fill: false
      - entity: input_number.nighttime
        color: gray
        name: Night
        show_line: false
        show_fill: true
        show_points: false
        show_legend: false
        y_axis: secondary
    font_size: 88
    hour24: true
    hours_to_show: 48
    line_width: 3
    points_per_hour: 4
    show:
      icon_adaptive_color: true
      labels: hover
      labels_secondary: false
      name: false
      points: false
    card_mod:
      style: |
        ha-card > div:nth-child(-n+2) {
          padding: 0 14px 0 14px !important
        }
        ha-card > .info {
          padding: 0 14px 0px 14px !important
        }
```

And it's colors are correct except for the icon.
![image](https://github.com/user-attachments/assets/bec3698a-1111-4658-95e9-e0924d2c4a85)

**Comment by ildar170975** [comment]
Retest with this config:
```
    type: custom:mini-graph-card
    entities:
      - entity: ...
        show_state: true
        show_fill: true
        state_adaptive_color: true
    color_thresholds: ....
    color_thresholds_transition: hard
    hours_to_show: 24
    points_per_hour: 60
    line_width: 1
    show:
      labels: true
      icon_adaptive_color: true
    height: 300
```

**Comment by klonwar** [comment]
That is the point! It works fine when setting entity like you did! All other graphs working fine.
![image](https://github.com/user-attachments/assets/e34f2c66-b500-444a-86bf-3939a98a5f0b)
 
But if I try to use `attribute` like:
```
...
entities:
  - entity: weather.openmeteo
    attribute: temperature
show:
  icon_adaptive_color: true
```
It just stops showing color on the icon

**Comment by ildar170975** [comment]
I see, there is a problem with attribute.
Thanks for reporting.
Will take a look.

For you - a suggestion: when you will post a code next time for issues:
-- always post a short minimal code: no card-mod, no possibly unrelated options -start from a simple case, increase a complexity step by step;
-- for testing thresholds - use SIMPLE clear colors like "red", "#ff0000" (nobody will decode smth like "ae54f3"); and "hard" transition.

**Comment by ildar170975** [comment]
@akloeckner 
Can you have a look if it is related somehow to the recent changes? 
```
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.xiaomi_cg_1_co2
    <<: &ref_settings
      color_thresholds:
        - value: 450
          color: red
        - value: 500
          color: orange
        - value: 510
          color: yellow
        - value: 520
          color: green
        - value: 530
          color: cyan
        - value: 540
          color: blue
        - value: 550
          color: lightgreen
        - value: 560
          color: magenta
      color_thresholds_transition: hard
      hours_to_show: 0.25
      points_per_hour: 240
      aggregate_func: last
      show:
        labels: true
        points: true	
        icon_adaptive_color: true
      height: 300
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.xiaomi_cg_1
        attribute: co2
    <<: *ref_settings
```
![изображение](https://github.com/user-attachments/assets/f6247ad9-923d-439a-8ed1-a569d621cf21)

In case of using `attribute` - color is taken for the 1st threshold.

**Comment by klonwar** [comment]
Thank you for your suggestions!

> In case of using attribute - color is taken for the 1st threshold.

yep, same for me

And if I add in your config another threshold with value is less or equal 0, the issue I've described reproduces!

```
color_thresholds:
  - value: 0
    color: purple
  - value: 10
    color: red
```
Result:
![image](https://github.com/user-attachments/assets/e9f002e5-3934-409c-a1f3-c2485c4032d2)
(And in icon's html: `style="color: #;"`)

And if we set value to 1

```
color_thresholds:
  - value: 1
    color: purple
  - value: 10
    color: red
```
Result:
![image](https://github.com/user-attachments/assets/a9a06e82-fee9-4034-9868-c02c71aa6b52)

**Comment by ildar170975** [comment]
> And if I add in your config another threshold with value is less or equal 0, the issue I've described reproduces!

I am not following, which particular my config do you mean?
Post a full (but still minimized) code.

**Comment by klonwar** [comment]
Ok, here

```
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.xiaomi_cg_1_co2
    <<: &ref_settings
      color_thresholds:
        - value: 0
          color: purple
        - value: 450
          color: red
        - value: 500
          color: orange
        - value: 510
          color: yellow
        - value: 520
          color: green
        - value: 530
          color: cyan
        - value: 540
          color: blue
        - value: 550
          color: lightgreen
        - value: 560
          color: magenta
      color_thresholds_transition: hard
      hours_to_show: 0.25
      points_per_hour: 240
      aggregate_func: last
      show:
        labels: true
        points: true	
        icon_adaptive_color: true
      height: 300
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.xiaomi_cg_1
        attribute: co2
    <<: *ref_settings
```

With this config It'll set `style="color: #;"` for the icon

**Comment by ildar170975** [comment]
With added "purple":
- the 1st card with "state": icon=cyan (as expected)
- the 2nd card with "attribute": icon=purple (as observed earlier) - i.e. again a color from the 1st threshold is used

And in Code Inspector it is "rgb(128,0,128)" (which I believe could be a "purple").

**Comment by klonwar** [comment]
Interesting! I'm using last version I believe (v0.12.1) and with value <= 0 it sets this
![image](https://github.com/user-attachments/assets/e77d6f13-b6d0-45b7-91c5-d798c3a41535)

And if you set -1 as a value?

**Comment by ildar170975** [comment]
> But maybe we should concentrate on that attribute-first-threshold problem

Agreed.
But anyway show me YOUR code which causes "color: #"

**Comment by ildar170975** [comment]
And I am using 
![изображение](https://github.com/user-attachments/assets/cd8bdf4d-0de8-4c40-bb77-6df7a413bf2c)

**Comment by ildar170975** [comment]
Recheck with 0.12.2-dev.2

**Comment by klonwar** [comment]
Yep, in dev.2 it sets color in `rgb` format instead of hex, and it's purple, so the first threshold is used

**Comment by akloeckner** [comment]
I think, the icon (and also the name) do not use attribute for calculating their colours, see here:

https://github.com/kalkih/mini-graph-card/blob/49ca1cd8627381e2981f57906014f615f08301c9/src/main.js#L241

And here

https://github.com/kalkih/mini-graph-card/blob/49ca1cd8627381e2981f57906014f615f08301c9/src/main.js#L152-L156

Does the colour become correct, when you hover over a point?

**Comment by klonwar** [comment]
> Does the colour become correct, when you hover over a point?
yep, it does

**Comment by akloeckner** [comment]
:+1: I cannot promise anything right now. But that should be solvable...

**Comment by akloeckner** [comment]
Could you check out #1131, please? It seems to work on my end, but I did not thoroughly test it.

**Comment by ildar170975** [comment]
@akloeckner 
> Could you check out #1131

Tested with [that js](https://github.com/kalkih/mini-graph-card/actions/runs/10586001387) and still an icon uses the 1st color:
![image](https://github.com/user-attachments/assets/c7bbea0a-2158-4475-a228-2a9abbcdd658)
```
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.xiaomi_cg_1_co2
    <<: &ref_settings
      color_thresholds:
        - value: 500
          color: red
        - value: 570
          color: cyan
        - value: 610
          color: yellow
        - value: 700
          color: green
      color_thresholds_transition: hard
      hours_to_show: 6
      points_per_hour: 240
      aggregate_func: last
      show:
        labels: true
        points: true
        icon_adaptive_color: true
      height: 300
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.xiaomi_cg_1
        attribute: co2
    <<: *ref_settings
```
