### ISSUE TITLE
Wrong icon being displayed for entity in graph

### ISSUE THREAD

**Issue by kaizersoje** [kalkih/mini-graph-card#1132]
This entity has the icon shown below
![image](https://github.com/user-attachments/assets/d8372bcb-436d-446a-b759-7ccad8e44df5)

However, the graph below shows a different icon from the entity icon.
![image](https://github.com/user-attachments/assets/ae8bd296-e1a1-4dfe-9f8c-7c7109b48f4d)

Below is the code for the card
```yaml
type: custom:mini-graph-card
entities:
  - entity: sensor.rumpus_pressure
hour24: true
font_size_header: 11
font_size: 60
group_by: interval
line_width: 4
hours_to_show: 24
```
