### ISSUE TITLE
Chart color is incorrectly set with value range

### ISSUE THREAD

**Issue by MaJerle** [kalkih/mini-graph-card#1137]
I've had rainy few days and humidity was at `99.99%`. I'm using this extension, with these color ranges:

```yaml
color_thresholds:
  - value: 0 
    color: '#FF0000'
  - value: 20
    color: '#FFFF00'
  - value: 35
    color: '#00FF00'
  - value: 70
    color: '#FFFF00'
  - value: 80
    color: '#FF0000'
```

Strange thing is that when humidity was at 99%, it showed green value:
![IMG_2390](https://github.com/user-attachments/assets/e5e4de55-7245-45a3-8446-de34b6e2bc88)

But if I touched it by mouse on PC or finger on the phone, it switched to red, which is the color I originally want:
![IMG_2391](https://github.com/user-attachments/assets/d9d2de38-8acf-4999-85df-b1a1f5481d22)

And when we got less humid day today, value returned back to correct colors, even without touching or hovering the widget.
![IMG_2392](https://github.com/user-attachments/assets/a1bbd25c-790f-4671-b3ef-4ae392d11590)

Is this a bug?
