### ISSUE TITLE
Feature Request: a "soft" upper bound

### ISSUE THREAD

**Issue by worgarside** [kalkih/mini-graph-card#114]
I've got a couple of graphs where I'd like to set an upper bound, but the value being plotted does sometimes go over that value and then it doesn't look as nice. An example being a step count: the upper bound is 10,000 (so I can see how close I am to that goal), but sometimes I'll do more than 10K steps a day and then it'll go off the graph.

I was thinking that a nice solution to this would be the ability to make the upper bound "soft". i.e. It stays at the set value Y, until the value on the graph (Y1) is greater than Y, at which point the upper bound becomes Y1 so all values are plotted.

**Comment by kalkih** [comment]
Hmm, that's actually a neat idea, I like it!
Should be fairly easy to implement as well.

**Comment by michaelblight** [comment]
One option that doesn't involve a new feature would be to also store your step goal in Home Assistant and plot that too. With a step goal of 10,000 it will plot a horizontal line at this point, which will also be the maximum if the steps achieved is lower. However, if the steps achieved exceeds 10,000, they will be the new maximum for the graph. i.e. no need to set an upper bound.
You also get the benefit that you can change your step goal over time easily, and could even have different values for the weekends (for example).

**Comment by worgarside** [comment]
Ah that's actually a good shout! Cheers for the idea, I'll definitely implement that until I have time to look at adding a new feature

**Comment by worgarside** [comment]
For reference, this is my LoveLace config:

```yaml
- type: custom:mini-graph-card
  points_per_hour: 6
  icon: mdi:shoe-print
  entities:
    - entity: sensor.daily_step_count
    - entity: sensor.daily_step_count_goal
      color: '#00000000'
  lower_bound: 0
  line_width: 3
  show:
    points: false
    legend: false
  color_thresholds:
    - value: 0
      color: '#ff0000'
    - value: 10000
      color: '#00ff00'
```

and this is my goal template sensor:
```yaml
daily_step_count_goal:
  friendly_name: 'Daily Step Count Goal'
  unit_of_measurement: 'Steps'
  value_template: "{{ 10000 }}"
```

By setting the color of the goal sensor to transparent (`#00000000`) and hiding the legend on the graph, the graph doesn't actually look any different! 🎉
