### ISSUE TITLE
show_legend is not entity specific

### ISSUE THREAD

**Issue by Nickduino** [kalkih/mini-graph-card#1146]
```
type: custom:mini-graph-card
name: CO₂ et bruit
entities:
  - entity: sensor.interieur_carbon_dioxide
    show_state: true
    show_graph: true
    show_legend: false
    state_adaptive_color: true
  - entity: sensor.interieur_noise
    show_state: true
    state_adaptive_color: true
    show_graph: true
    show_legend: true
    line_color: blue
    color: lightblue
    y_axis: secondary
show:
  labels: false
  extrema: false
color_thresholds:
  - value: 600
    color: '#0c6114'
  - value: 800
    color: '#d35400'
  - value: 1000
    color: '#c0392b'
  - value: 1500
    color: '#9309b5'
font_size: 50
height: 78
layout_options:
  grid_columns: 2
  grid_rows: 2

```

Gives this result:

![image](https://github.com/user-attachments/assets/7bbad664-170a-4ba7-85ce-7fb14906983a)

When I was expecting this:

![image](https://github.com/user-attachments/assets/64c223d9-75d9-4b99-b0cf-9f6c1f11856c)
(Because it doesn't make much sense to color-code a legend when the line has a dynamic color)
