### ISSUE TITLE
[FR] Show all entities values and names in one line

### ISSUE THREAD

**Issue by pskowronek** [kalkih/mini-graph-card#1166]
Great card! However, I've tried to use it to accommodate 3 entities in one graph along with their current values: PM 2.5, PM10 and HCHO (air quality readings).

So far I was only able to achieve this:
![image](https://github.com/user-attachments/assets/1e3acf46-9e9e-4dde-b03d-c4b5ddc5adf3)

What I would like is something like this:

![image](https://github.com/user-attachments/assets/439adb30-78e4-44a5-b9a2-5db8b1fb349a)

i.e.:
- entity names for the values
- all values & names on the same line (if space allows, otherwise go to the next line)
- the same size of the values and the same indicator/bullet (now the first is square, the other 2 round)
- option or a way to turn off showing units (empty string for `unit` doesn't work, only space could do it (' ') but it consumes UI real estate)

My config so far:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.pm10
    name: PM10
    show_state: true
    show_indicator: true    
  - entity: sensor.pm2_5
    name: PM2.5
    show_state: true
    show_indicator: true
  - entity: sensor.hcho
    name: HCHO
    show_state: true
    show_indicator: true
hours_to_show: 24
points_per_hour: 5
animate: false
line_width: 2
group: false
smoothing: false
show:
  legend: false
  labels_secondary: false
  name: false
  icon: false
  extrema: false
  fill: false
hour24: true
```
