### ISSUE TITLE
Graph not displaying correct values. 

### ISSUE THREAD

**Issue by tomlut** [kalkih/mini-graph-card#117]
I'm seeing strange behaviour of the graph. It is reporting a high value when it shouldn't. See screen caps below:

![Annotation 2019-07-10 104738](https://user-images.githubusercontent.com/10679300/60932540-c5c7a100-a301-11e9-80f4-b88d0d3287a8.png)
![Annotation 2019-07-10 104822](https://user-images.githubusercontent.com/10679300/60932542-c5c7a100-a301-11e9-994e-f6c54b0d1256.png)

No amount of changing the points per hour seems to fix it.

```
      - color_thresholds:
          - color: '#0da035'
            value: -1
          - color: '#e0b400'
            value: 1800
          - color: '#e45e65'
            value: 2100
        color_thresholds_transition: hard
        entities:
          - sensor.lounge_dehumidifier_power
        group: false
        hour24: true
        line_width: 6
        name: Lounge Dehumidifier Power
        points_per_hour: 2
        show:
          fill: fade
          icon: true
          labels: false
          name: true
          state: true
        style: |
          ha-card {
            border: solid 2px var(--primary-color);
          }
        type: 'custom:mini-graph-card'
```

<s>EDIT: this appears to be a firefox issue. The graphs display correctly on Chrome and Safari. Clearing the cache on firefox (CTRL + F5) did not make any improvement.</s>

EDIT2: or maybe it is a caching issue. Opening the page in a private window in firefox does not have the problem.
