### ISSUE TITLE
Can I set a different unit for 2nd entity state I am displaying

### ISSUE THREAD

**Issue by warksit** [kalkih/mini-graph-card#1171]
Maybe have unit as a parameter of the entity rather than the card itself?

![image](https://github.com/user-attachments/assets/3aef36fc-acb8-45fa-91d4-c911c9a9d010)

````
type: custom:mini-graph-card
name: Office Climate
entities:
  - entity: climate.office_sensibo
    attribute: current_temperature
    name: Temperature (°C)
    show_state: true
  - entity: climate.office_sensibo
    attribute: current_humidity
    name: Humidity (%)
    y_axis: secondary
    show_state: true
show:
  graph: line
  legend: true
hours_to_show: 2
points_per_hour: 60
lower_bound: 0
upper_bound: 35
lower_bound_secondary: 50
upper_bound_secondary: 100
height: 300
unit: °C
````
