### ISSUE TITLE
hours_to_show + state_map error with labels

### ISSUE THREAD

**Issue by javierpose** [kalkih/mini-graph-card#1185]
If hours_to_show is used with state_map, instead of showing the 2 labels of the binary_sensor it repeats the last label. Example:
```yaml

type: custom:mini-graph-card
entities:
  - entity: binary_sensor.entrada_contact
  - entity: binary_sensor.nuki_casa_kato_kale_locked
name: Entrada
show:
  state: false
  labels: true
hours_to_show: 8
points_per_hour: 1
update_interval: 30
line_width: 2
state_map:
  - value: "on"
    label: Abierto
  - value: "off"
    label: Cerrado
grid_options:
  columns: full
visibility:
  - condition: state
    entity: device_tracker.tapo
    state_not: home

```

<img width="752" alt="Anotación 2024-12-17 115924" src="https://github.com/user-attachments/assets/cbaa8492-87d9-4936-a004-d86fa66c8a5a" />
