### ISSUE TITLE
lower_bound not calculated correctly when a hidden entity exists

### ISSUE THREAD

**Issue by cicero200272** [kalkih/mini-graph-card#119]
When I use two entities and suppress the graph of the second one, the lower_bound for the y-axis is set to 0. If delete the second entity, the lower_bound is calculated correctly.

```
- type: custom:mini-graph-card
  entities: 
    - entity: sensor.temp1
    - entity: sensor.temp2
      show_state: false
      show_graph: false
```

![graph2](https://user-images.githubusercontent.com/15817602/61133003-db34fa80-a4bc-11e9-98a5-5af8b9803a46.png)

```
- type: custom:mini-graph-card
  entities: 
    - entity: sensor.temp1
```

![graph3](https://user-images.githubusercontent.com/15817602/61133100-0ae40280-a4bd-11e9-8ff3-73bbe62e9a1a.png)
