### ISSUE TITLE
Max / Avg is not calculated correctly - on multiple entities 

### ISSUE THREAD

**Issue by spec8320** [kalkih/mini-graph-card#1192]
Hello, 

Sample example: 

![image](https://github.com/user-attachments/assets/2f6e1839-9956-44bd-bba6-20c3d39af079)

Already on chart you see that max should be higher than 19 

Config is ultra simple: 

```
type: custom:mini-graph-card
hours_to_show: 24
points_per_hour: 30
name: Korytarz rekuperacja - Temperatura
entities:
  - entity: sensor.sensor_piwnica_rekuperacja_temperature
    name: Rekuperacja
  - entity: sensor.sensor_piwnica_kotlownia_temperature
    name: Kotłownia
  - entity: sensor.sensor_piwnica_pralnia_temperature
    name: Pralnia
show:
  labels: true
  extrema: true
  average: true
```
