### ISSUE TITLE
Cannot hide a graph for entity

### ISSUE THREAD

**Issue by Koky05** [kalkih/mini-graph-card#1195]
After last update of HA to 2025.01 functionality for hide graph for some entity stop working. It show only load icon:
![Screenshot_2025-01-06-01-19-58-23_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/user-attachments/assets/50565537-2365-405d-934d-d83fc47a5cb8)

I use it with next code, to have summary label with detail graphs:

```
  - type: custom:mini-graph-card
    name: Teplota vonku
    entities:
      - entity: sensor.teplota_vonku_2
        show_state: true
        show_graph: false
      - entity: sensor.broadcast_outsidetemp_temp2
        name: Vaillant
      - entity: sensor.thm_139335746
        name: Jablotron vonku
      - entity: sensor.thm_137742250
        name: Búda Hugo
    points_per_hour: 6
    show:
      labels: false
```

**Comment by ildar170975** [comment]
This is how the code was posted, please correct.
![image](https://github.com/user-attachments/assets/cdb8f172-4641-48c8-99a8-1720d58bead3)

**Comment by ildar170975** [comment]
OK, here is a short code to demonstrate the bug:
```
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.xiaomi_cg_1_co2
        show_state: true
        show_graph: false
      - entity: sensor.xiaomi_cg_2_co2
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.xiaomi_cg_1_co2
        show_state: true
      - entity: sensor.xiaomi_cg_2_co2
```
![image](https://github.com/user-attachments/assets/ebae81d9-d2aa-4823-af4f-e0fc82eb3637)

The bug was added by https://github.com/kalkih/mini-graph-card/pull/1180
