### ISSUE TITLE
Use value from climate?

### ISSUE THREAD

**Issue by danielpondruff** [kalkih/mini-graph-card#12]
Hi,

is it possible to use the value "current_temperature" from the climate entity?

![screenshot 2018-10-29 at 14 23 45](https://user-images.githubusercontent.com/4953452/47652485-5b613d00-db86-11e8-8da4-c001813287dc.png)

Greetings
Daniel

**Comment by kalkih** [comment]
Yes, this should be possible if you create a [template sensor](https://www.home-assistant.io/components/sensor.template/) for the `current_temperature` of the climate entity.

* Add this to your `configuration.yaml`

```yaml
sensor:
  - platform: template
    sensors:
      climate_wc_temp:
        friendly_name: "Gäste-WC Temp"
        unit_of_measurement: "°C"
        value_template: "{{ states.climate.oeq1713652.attributes.current_temperature }}"
```

* Add this as your card
```yaml
- type: "custom:mini-graph-card"
  entity: sensor.climate_wc_temp
```
