### ISSUE TITLE
tap_action does not show more-info

### ISSUE THREAD

**Issue by giovi321** [kalkih/mini-graph-card#1212]
I am trying to introduce a tap_action that shows more-info on a graph with two entities shown.
The issue is that when I click or tap on the graph line of either entity nothing happens.
Here is the code I am using

```
type: custom:mini-graph-card
name: Temperature
icon: mdi:thermometer
entities:
  - entity: sensor.gc01srvr_cpu_temperature
    name: GC01SRVR
    color: "#ff9800"
    show_legend: false
    tap_action:
      action: more-info
  - entity: sensor.gc03srvr_cpu_temperature
    name: GC03SRVR
    color: "#03a9f4"
    show_legend: false
    tap_action:
      action: more-info
points_per_hour: 10
decimals: 1
line_width: 2
hours_to_show: 12
height: 100
show:
  labels: true
  header: false
  state: false
hour24: true
align_state: right
grid_options:
  columns: full
tap_action:
  action: more-info
```

I have also tried the following
```
type: custom:mini-graph-card
name: Temperature
icon: mdi:thermometer
entities:
  - entity: sensor.gc01srvr_cpu_temperature
    name: GC01SRVR
    color: "#ff9800"
    show_legend: false
    tap_action:
      action: more-info
  - entity: sensor.gc03srvr_cpu_temperature
    name: GC03SRVR
    color: "#03a9f4"
    show_legend: false
    tap_action:
      action: more-info
    tap_action:
      action: more-info
points_per_hour: 10
decimals: 1
line_width: 2
hours_to_show: 12
height: 100
show:
  labels: true
  header: false
  state: false
hour24: true
align_state: right
grid_options:
  columns: full
```
