### ISSUE TITLE
tap_action: inconsistency

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#1213]
https://www.home-assistant.io/dashboards/actions/#tap-action
Consider the card:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_co2
  - entity: sensor.xiaomi_cg_2_co2
    show_state: true
tap_action:
  action: more-info
  entity: sun.sun
```
![Image](https://github.com/user-attachments/assets/ef54eb11-d374-4d04-8654-29713e391b96)

It properly shows more-info:
-- tapping on a legend label will show a more-info for a corresponding entity;
-- tapping on a state label - similar;
-- tapping on an empty area - more-info for sun.sun.

Now a bit more complex case:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_co2
  # - entity: sensor.xiaomi_cg_2_co2 # these lines may be uncommented
  #   show_state: true
tap_action:
  action: call-service
  service: switch.toggle
  service_data:
    entity_id: switch.test_switch
```
In this case any tap causes calling `switch.toggle` - no more-info for entities is shown.
This is WRONG.

Now check with a new 2024.8 syntax:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_co2
  - entity: sensor.xiaomi_cg_2_co2
tap_action:
  action: perform-action
  perform_action: switch.toggle
  target:    # or data
    entity_id: switch.test_switch
```
In this case no action is executed.
This is WRONG.
