### ISSUE TITLE
Wrong handling of long-term statistics

### ISSUE THREAD

**Issue by lxffm** [kalkih/mini-graph-card#1215]
Hi y'all,

seems like the mini-graph is no able to proper handle long-term.
Apparently once the graph exceeds the short-term statistics it takes the first value of the long term statistic and show it for every previous datapoint. 

<img width="426" alt="Image" src="https://github.com/user-attachments/assets/9a0bc908-5ce4-4fe5-9b3c-4d5d0bb9d241" />

```
type: custom:mini-graph-card
hours_to_show: 744
group_by: date
decimals: 2
font_size: 80
height: 100
update_interval: 60
animate: true
hour24: true
color_thresholds_transition: smooth
show:
  labels: false
  icon: false
  graph: bar
entities:
  - entity: sensor.tibber_pulse_kumulierter_verbrauch
    name: Stromverbrauch/Tag
    aggregate_func: max
color_thresholds:
  - value: 0
    color: "#00e900"
  - value: 10
    color: "#f0a33b"
  - value: 20
    color: "#f75053"
grid_options:
  columns: 12
  rows: auto
```
