### ISSUE TITLE
Hide state, but show datestamps on hover

### ISSUE THREAD

**Issue by garyjlo** [kalkih/mini-graph-card#1226]
Apologies if this is already possible, if so please point me to how I can do this.

But here is my issue:
I am graphing a binary sensor for which the values are very obvious and I have no need to display the state value as it is huge:
![Image](https://github.com/user-attachments/assets/f0dad56a-612b-49a1-bb2b-1e40698ce648)

I want a more compact card, which we can do with show: state: false:
![Image](https://github.com/user-attachments/assets/985658b4-a93a-48ef-b4ee-3010151539a3)

However if I have hidden the state, then the date-time also does not appear when I hover over the points, which is a very useful feature.

Is there any way of hiding the state while keeping the datestamp on hover?  Like this:
![Image](https://github.com/user-attachments/assets/563b174f-ed37-447a-911e-8ecf88cfcf99)

**Comment by ildar170975** [comment]
> Is there any way of hiding the state while keeping the datestamp on hover? Like this:

On your picture no state is shown, what is a purpose to show a timestamp then?

Short answer: showing a timestamp w/o a state is not supported. Although you may try to hide a state (& thus left a timestamp shown) with a help of card-mod. For this you will help to learn css.

**Comment by garyjlo** [comment]
For a binary sensor, I don't really need to see the state displayed to know that the graph point is showing on/off, open/closed.
But I may want to confirm the time the event happened at, if I am showing a few hours worth of data it may not be so easy to tell exactly when it occurred just from the relative x position in the graph.

If I show the state and hide it will card-mod, would that still reduce the size of the card, or would there just be a big empty space where the state would have been shown?

**Comment by ildar170975** [comment]
> For a binary sensor, I don't really need to see the state displayed

Agree. For any sensor with clearly recognisable fixed states.
But I wound NOT suggest to use mini-graph-card for these cases, a stock history-graph is more suitable for this.

> If I show the state and hide it with card-mod, would that still reduce the size of the card, or would there just be a big empty space where the state would have been shown?

Depends on YOU only, which css styles you use.

**Comment by garyjlo** [comment]
Yes, I did try the stock history graph first, but I was not that happy with the design.
![Image](https://github.com/user-attachments/assets/27072471-3013-4093-bdab-2b0f2a939e1b)

I find the mini-graph-card design to be much more beautiful, and I'm trying to get as close to my ideal middle ground as possible between aesthetics and functionality by customizing the mini-graph-card.

Thankfully your suggestion would seem to work for me, I did a little poc by editing the DOM in developer mode to do a display: none on the span with state__value class, it reduced the size of the card and hid the state while keeping the datetime on hover:
![Image](https://github.com/user-attachments/assets/a94fe36f-90a6-4d6d-99b6-8eeb7a8d1e78)

I think I should be able to use this with the card-mod combination approach, thanks @ildar170975

**Comment by ildar170975** [comment]
Good, that you sorted this out.

**Comment by garyjlo** [comment]
Just to tie up loose ends for future visitors with a similar use-case, here is my final working config:

```
    - type: custom:mini-graph-card
      entities:
        - entity: binary_sensor.lower_stairs_motion
          color: "#5ef6ff"
      line_width: 3
      hours_to_show: 1
      points_per_hour: 60
      lower_bound: 0.3 # hide the 'off' datapoints
      upper_bound: 1.0 # force full y axis height
      aggregate_func: max # no partial value datapoints, only on/off
      show:
        graph: bar
        state: true # required to show date-time on hover
        icon_adaptive_color: true
        labels: false
      state_map:
        - value: "off"
          label: Clear
        - value: "on"
          label: Detected
      animate: true
      height: 40
      card_mod:
        # hide the big state display, keeping date-time on hover
        style: |
          span.state__value {
            display: none;
          }
```

![Image](https://github.com/user-attachments/assets/f4d50291-eeea-49a7-b628-664eccd84e24)
