### ISSUE TITLE
Feature Request: Changing default colors via theme, not only with accent-color

### ISSUE THREAD

**Issue by TECHNOFAB11** [kalkih/mini-graph-card#123]
Would be awesome to be able to change the colors via a theme, not only the first, but all / more of the default colors. Because with a theme the colors arent fitting sometimes, so it would be great to be able to change them with a theme :)

**Comment by kalkih** [comment]
Hey, you should actually be able to do this already, you can come up with your own theme variables and then use them as the color in your graphs.

```yaml
# theme file
graph-line-color: #FF0000
```

```yaml
# card config
- type: custom:mini-graph-card
  entities:
    - entity: sensor.example
      color: var(--graph-line-color)
```
