### ISSUE TITLE
Color_thresholds not working as expected.

### ISSUE THREAD

**Issue by Srjosep** [kalkih/mini-graph-card#1243]
I created a mini graph card in home assistant that read the value from a temperature sensor, and should change the line color depending on sensor value. It should be:
0 to 22.1=red
more then 22.1 to 23.9 = yellow
more than 23.9 to 28 = green
more than 28 to 32 = yellow again
more than 32 = red again

![Image](https://github.com/user-attachments/assets/c572158e-7b13-45f5-a356-8dc3294a4a39)

But, as seen in the image, a value of 23.5 show green line...What am I doing wrong? This is my code:

```
type: custom:mini-graph-card
entities:
  - input_number.temperatura_marino
name: Temperatura
line_color: white
line_width: 8
font_size: 75
show: null
labels: true
color_thresholds:
  - value: 0
    color: "#ff0000"
  - value: 22.1
    color: "#ffff00"
  - value: 23.9
    color: "#00ff00"
  - value: 28
    color: "#ffff00"
  - value: 32
    color: "#ff0000"
```

**Comment by ildar170975** [comment]
Please always post a code properly formatted, use triple "`".

**Comment by ildar170975** [comment]
Check with latest version. 
And make y-axis labels displayed.

**Comment by valimaties** [comment]
I confirm that something is awkard with the colors thresholds:

```
type: custom:mini-graph-card
entities:
  - entity: sensor.inverter_internal_temperature
    name: Temperatură invertor
align_icon: left
align_state: center
hours_to_show: 2
points_per_hour: 10
color_thresholds:
  - value: 20
    color: green
  - value: 40
    color: orange
  - value: 55
    color: red
```

![Image](https://github.com/user-attachments/assets/be139e16-83c1-4f23-8403-55b3b768858c)

Why the line is getting darker and does not goes to orange?

I see if the "next" value is greater than the max value display the treshold does not take in care the upper value in the list. From my example I expected that the darker line to become a little bit orange, but it goes to black instead.
