### ISSUE TITLE
State last fails to render card

### ISSUE THREAD

**Issue by MrWaggel** [kalkih/mini-graph-card#1248]
Changing the state to `last` fails to render the card;

```
type: custom:mini-graph-card
group_by: date
hours_to_show: 168
aggregate_func: diff
icon: mdi:lightning-bolt
height: 80
entities:
  - entity: sensor.p1_meter_energy_import
name: Electricity Consumption
show:
  graph: bar
  state: last 
```

![Image](https://github.com/user-attachments/assets/86439c11-feab-4544-b520-b3022b717bc7)

```
Uncaught (in promise) TypeError: this.points[a] is undefined
    getEntityState mini-graph-card-bundle.js:1
    shouldUpdate mini-graph-card-bundle.js:1
    performUpdate mini-graph-card-bundle.js:1
    _enqueueUpdate mini-graph-card-bundle.js:1
    T mini-graph-card-bundle.js:1
    g mini-graph-card-bundle.js:1
    promise callback*T mini-graph-card-bundle.js:1
    f mini-graph-card-bundle.js:1
    U mini-graph-card-bundle.js:1
    U mini-graph-card-bundle.js:1
    _enqueueUpdate mini-graph-card-bundle.js:1
    requestUpdateInternal mini-graph-card-bundle.js:1
    set mini-graph-card-bundle.js:1
    set hass mini-graph-card-bundle.js:1
    value hui-card.ts:190
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    value hui-section.ts:132
    value hui-section.ts:131
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    value hui-view.ts:266
    value hui-view.ts:264
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    value hui-root.ts:556
    _$AE reactive-element.ts:1395
    performUpdate reactive-element.ts:1345
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    W lit-html.ts:2183
    update lit-element.ts:166
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    value partial-panel-resolver.ts:98
    value hass-router-page.ts:89
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    W lit-html.ts:2183
    update lit-element.ts:166
mini-graph-card-bundle.js:1:111468
```
Followed by 404 XHR fetches;

```
XHRGET https://home.lan/unknown/src/scoped-custom-element-registry.ts [HTTP/1.1 404 Not Found 0ms]
XHRGET https://home.lan/unknown/src/reactive-element.ts [HTTP/1.1 404 Not Found 0ms]
```

Any other value renders it correctly, but I wish to see the value of the last bar.

![Image](https://github.com/user-attachments/assets/04ced384-cb44-4a6b-9f7a-51e6fecec188)

Entity data comes from the [Homewizard Energy P1 meter](https://www.home-assistant.io/integrations/homewizard/)

**Comment by skynetforcats** [comment]
For me it actually renders sometimes if I have multiple graph on the same view. But not with the last diff, but the last actual state (I guess expected.)

Would be great if this could show the diff for each day, and also the diff for the current day as the state. E.g.:

```
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.consumption
            show_state: true
            aggregate_func: diff
        hours_to_show: 72
        group_by: date
        show:
          graph: bar
          state: diff
```


<img width="496" height="214" alt="Image" src="https://github.com/user-attachments/assets/96f02219-b9b1-44eb-b3f4-d13addc8623f" />

<img width="484" height="230" alt="Image" src="https://github.com/user-attachments/assets/073201e4-7982-4ab5-9d26-1248750cb40c" />

Would be great if it could show the last period as the state.

This doesn't render:

```
        - type: custom:mini-graph-card
          entities:
            - entity: sensor.kamstrup_energy
              aggregate_func: delta
          hours_to_show: 72
          group_by: date
          show:
            graph: bar
            state: last

```
