### ISSUE TITLE
Unexpected value

### ISSUE THREAD

**Issue by tomlut** [kalkih/mini-graph-card#125]
I'm getting a lot of these errors in the browser inspector:
```

Unexpected value -Infinity% parsing offset attribute. mini-graph-card.js:1:29437
Unexpected value NaN% parsing offset attribute. mini-graph-card.js:1:29437
```

Graphs seem to be displaying ok. 

Example config:
```
color_thresholds:
  - color: '#039BE5'
    value: 0
  - color: '#0da035'
    value: 235
  - color: '#e0b400'
    value: 250
  - color: '#e45e65'
    value: 253
color_thresholds_transition: hard
entities:
  - sensor.lounge_av_voltage
group: false
hour24: true
line_width: 4
lower_bound: 220
points_per_hour: 1
show:
  extrema: true
  fill: fade
  labels: false
style: |
  ha-card {
    border: solid 2px var(--primary-color);
  }
type: 'custom:mini-graph-card'
upper_bound: 260

```
