### ISSUE TITLE
Can’t edit any dashboards with a mini graph card.

### ISSUE THREAD

**Issue by joeynz2** [kalkih/mini-graph-card#1251]
For over a year now any of my dashboards running a mini graph card will cause the dashboard to significantly slow down and making the editing impossible. To edit the page I need to add “?edit=1” to the url. This how how often is is updating, hours_to_show: 4, points_per_hour: 7

`
    entities:
      - entity: sensor.clark_home_temperature
        name: Lounge
    show:
      labels: true
    color_thresholds:
      - value: 0
        color: "#4C4FF5"
      - value: 22
        color: "#4CB0F5"
      - value: 25
        color: "#FFC300"
      - value: 30
        color: "#FF5733"
      - value: 36
        color: "#C70039"
    name: Palmy `

**Comment by ildar170975** [comment]
Please correct your post, the code cannot be read.

**Comment by joshuaboniface** [comment]
I'm somewhat experiencing this myself, but it seems like a combination of the mini graph card and the advanced camera card that grinds it right to a halt. With either alone, things are fine, but with both, the page completely freezes within about 10s or if I try to interact at all. I am using a lot more data points in each of my 11 graphs than the OP though.

With both cards, the mini graph card specifically seem to spin loading for minutes, until they eventually load.

Full dashboard config:

```
views:
  - type: sections
    cards: []
    max_columns: 4
    sections:
      - type: grid
        cards:
          - type: heading
            icon: mdi:camera
            heading_style: title
            heading: Camera
          - type: custom:advanced-camera-card
            cameras:
              - camera_entity: camera.k1max_b9af_webcam
            grid_options:
              columns: full
            profiles: []
            view: {}
            status_bar:
              style: none
            live:
              preload: true
              zoomable: false
              draggable: false
            performance:
              features:
                media_chunk_size: 1000
          - type: heading
            icon: mdi:thermometer
            heading_style: title
            heading: Temperatures
          - type: custom:layout-card
            layout_type: grid
            cards:
              - type: grid
                columns: 3
                square: false
                cards:
                  - type: heading
                    icon: mdi:printer-3d-nozzle-heat
                    heading_style: subtitle
                    heading: Extruder
                  - type: heading
                    icon: mdi:radiator
                    heading_style: subtitle
                    heading: Bed
                  - type: heading
                    icon: mdi:approximately-equal-box
                    heading_style: subtitle
                    heading: Chamber
                  - type: custom:mini-graph-card
                    name: Extruder
                    hours_to_show: 12
                    points_per_hour: 60
                    decimals: 1
                    font_size: 80
                    entities:
                      - entity: sensor.k1max_b9af_extruder_temperature
                        name: Temperature
                        show_state: false
                        state_adaptive_color: true
                      - entity: number.k1max_b9af_extruder_target
                        name: Target
                        show_state: true
                        show_graph: false
                        state_adaptive_color: true
                    show:
                      name: false
                      labels: true
                      icon: false
                      state: true
                      graph: line
                      extrema: false
                      points: hover
                  - type: custom:mini-graph-card
                    name: Bed
                    hours_to_show: 12
                    points_per_hour: 60
                    decimals: 1
                    font_size: 80
                    entities:
                      - entity: sensor.k1max_b9af_bed_temperature
                        name: Temperature
                        show_state: false
                        state_adaptive_color: true
                      - entity: number.k1max_b9af_bed_target
                        name: Target
                        show_state: true
                        show_graph: false
                        state_adaptive_color: true
                    show:
                      name: false
                      labels: true
                      icon: false
                      state: true
                      graph: line
                      extrema: false
                      points: hover
                  - type: custom:mini-graph-card
                    name: Chamber
                    hours_to_show: 12
                    points_per_hour: 60
                    decimals: 1
                    font_size: 80
                    entities:
                      - entity: sensor.k1max_b9af_chamber_temp
                        name: Temperature
                        show_state: false
                        state_adaptive_color: true
                    show:
                      name: false
                      labels: true
                      icon: false
                      state: true
                      graph: line
                      extrema: false
                      points: hover
            layout:
              margin: '-0px 0px 0px 0px'
              padding: 0px
            grid_options:
              columns: full
        column_span: 2
      - type: grid
        cards:
          - type: heading
            icon: mdi:power-plug
            heading_style: title
            heading: Power
          - type: entities
            entities:
              - type: custom:athom-switch-details
                device_id: Power Monitor Plug 575034
                entity: ''
                monitor_only: true
                name: Creality K1 Max Printer
                icon: mdi:printer-3d-nozzle
                secondary_entities:
                  - sensor.athom_without_relay_plug_575034_voltage
                  - sensor.athom_without_relay_plug_575034_current
                  - sensor.athom_without_relay_plug_575034_power
                  - sensor.athom_without_relay_plug_575034_energy
              - type: custom:athom-switch-details
                device_id: Power Monitor Plug 575176
                entity: ''
                monitor_only: true
                name: Creality Space PI Dryer
                icon: mdi:hair-dryer
                secondary_entities:
                  - sensor.athom_without_relay_plug_575176_voltage
                  - sensor.athom_without_relay_plug_575176_current
                  - sensor.athom_without_relay_plug_575176_power
                  - sensor.athom_without_relay_plug_575176_energy
            show_header_toggle: false
          - type: heading
            icon: mdi:printer-3d
            heading_style: title
            heading: Status
          - type: custom:compact-entity-card
            name: State
            icon: ''
            precision: 1
            state_color: true
            state_font_size: 20
            unit_font_size: 14
            show_name: true
            entity: sensor.k1max_b9af_nice_print_state
            grid_options:
              columns: 12
              rows: 1
          - type: custom:compact-entity-card
            name: File
            icon: ''
            precision: 1
            state_color: true
            state_font_size: 14
            unit_font_size: 14
            show_name: true
            entity: sensor.k1max_b9af_filename
            grid_options:
              columns: 12
              rows: 1
            unit_override: ''
          - type: custom:compact-entity-card
            name: Progress
            icon: ''
            precision: 1
            state_color: true
            state_font_size: 20
            unit_font_size: 14
            show_name: true
            entity: sensor.k1max_b9af_progress
            grid_options:
              columns: 12
              rows: 1
          - type: custom:compact-entity-card
            name: Time Left
            icon: ''
            precision: 1
            state_color: true
            state_font_size: 20
            unit_font_size: 14
            show_name: true
            entity: sensor.k1max_b9af_print_time_left
            grid_options:
              columns: 12
              rows: 1
      - type: grid
        cards:
          - type: heading
            icon: mdi:approximately-equal-box
            heading_style: title
            heading: Chamber Exhaust
          - type: custom:compact-entity-card
            name: Chamber Fan
            icon: mdi:fan
            precision: 0
            state_color: true
            state_font_size: 20
            unit_font_size: 14
            show_name: true
            entity: number.k1max_b9af_output_pin_fan1
            unit_override: '%'
            grid_options:
              columns: 12
              rows: 1
          - type: heading
            icon: mdi:air-purifier-off
            heading_style: subtitle
            heading: Pre-Filter
          - type: vertical-stack
            cards:
              - type: custom:layout-card
                layout_type: grid
                cards:
                  - type: grid
                    columns: 2
                    square: false
                    cards:
                      - type: custom:compact-entity-card
                        name: ' '
                        icon: ''
                        precision: 1
                        state_color: false
                        state_font_size: 16
                        unit_font_size: 12
                        entity: sensor.microenv_8ff6e4_sht45_temperature
                      - type: custom:compact-entity-card
                        name: ' '
                        icon: ''
                        precision: 1
                        state_color: false
                        state_font_size: 16
                        unit_font_size: 12
                        entity: sensor.microenv_8ff6e4_sht45_relative_humidity
                      - type: custom:mini-graph-card
                        name: Outside Temperature
                        hours_to_show: 12
                        points_per_hour: 60
                        decimals: 1
                        font_size: 80
                        height: 150
                        group: true
                        entities:
                          - entity: sensor.microenv_8ff6e4_sht45_temperature
                            name: Temperature
                            show_state: false
                            state_adaptive_color: true
                            color: lightblue
                        show:
                          name: false
                          labels: true
                          icon: false
                          state: false
                          graph: line
                          extrema: false
                          points: hover
                      - type: custom:mini-graph-card
                        name: Outside Humidity
                        hours_to_show: 12
                        points_per_hour: 60
                        decimals: 1
                        font_size: 80
                        height: 150
                        group: true
                        entities:
                          - entity: sensor.microenv_8ff6e4_sht45_relative_humidity
                            name: Relative Humidity
                            show_state: false
                            state_adaptive_color: true
                            color: blue
                        show:
                          name: false
                          labels: true
                          icon: false
                          state: false
                          graph: line
                          extrema: false
                          points: hover
                      - type: custom:compact-entity-card
                        name: ' '
                        icon: ''
                        precision: 1
                        state_color: false
                        state_font_size: 16
                        unit_font_size: 12
                        entity: sensor.microenv_8ff6e4_sgp41_voc_index
                      - type: custom:compact-entity-card
                        name: ' '
                        icon: ''
                        precision: 1
                        state_color: false
                        state_font_size: 16
                        unit_font_size: 12
                        entity: sensor.microenv_8ff6e4_sgp41_nox_index
                      - type: custom:mini-graph-card
                        name: Outside VOC
                        hours_to_show: 12
                        points_per_hour: 60
                        decimals: 1
                        font_size: 80
                        height: 150
                        group: true
                        entities:
                          - entity: sensor.microenv_8ff6e4_sgp41_voc_index
                            name: VOC
                            show_state: false
                            state_adaptive_color: true
                            color: red
                        show:
                          name: false
                          labels: true
                          icon: false
                          state: false
                          graph: line
                          extrema: false
                          points: hover
                      - type: custom:mini-graph-card
                        name: Outside NOx
                        hours_to_show: 12
                        points_per_hour: 60
                        decimals: 1
                        font_size: 80
                        height: 150
                        group: true
                        entities:
                          - entity: sensor.microenv_8ff6e4_sgp41_nox_index
                            name: NOx
                            show_state: false
                            state_adaptive_color: true
                        show:
                          name: false
                          labels: true
                          icon: false
                          state: false
                          graph: line
                          extrema: false
                          points: hover
                layout:
                  margin: 0px 0px 0px 0px
                  padding: 0px
          - type: heading
            icon: mdi:air-purifier
            heading_style: subtitle
            heading: Post-Filter
          - type: vertical-stack
            cards:
              - type: custom:layout-card
                layout_type: grid
                cards:
                  - type: grid
                    columns: 2
                    square: false
                    cards:
                      - type: custom:compact-entity-card
                        name: ' '
                        icon: ''
                        precision: 1
                        state_color: false
                        state_font_size: 16
                        unit_font_size: 12
                        entity: sensor.microenv_8ff654_sht45_temperature
                      - type: custom:compact-entity-card
                        name: ' '
                        icon: ''
                        precision: 1
                        state_color: false
                        state_font_size: 16
                        unit_font_size: 12
                        entity: sensor.microenv_8ff654_sht45_relative_humidity
                      - type: custom:mini-graph-card
                        name: Inside Temperature
                        hours_to_show: 12
                        points_per_hour: 60
                        decimals: 1
                        font_size: 80
                        height: 150
                        group: true
                        entities:
                          - entity: sensor.microenv_8ff654_sht45_temperature
                            name: Temperature
                            show_state: false
                            state_adaptive_color: true
                            color: lightblue
                        show:
                          name: false
                          labels: true
                          icon: false
                          state: false
                          graph: line
                          extrema: false
                          points: hover
                      - type: custom:mini-graph-card
                        name: Inside Humidity
                        hours_to_show: 12
                        points_per_hour: 60
                        decimals: 1
                        font_size: 80
                        height: 150
                        group: true
                        entities:
                          - entity: sensor.microenv_8ff654_sht45_relative_humidity
                            name: Relative Humidity
                            show_state: false
                            state_adaptive_color: true
                            color: blue
                        show:
                          name: false
                          labels: true
                          icon: false
                          state: false
                          graph: line
                          extrema: false
                          points: hover
                      - type: custom:compact-entity-card
                        name: ' '
                        icon: ''
                        precision: 1
                        state_color: false
                        state_font_size: 16
                        unit_font_size: 12
                        entity: sensor.microenv_8ff654_sgp41_voc_index
                      - type: custom:compact-entity-card
                        name: ' '
                        icon: ''
                        precision: 1
                        state_color: false
                        state_font_size: 16
                        unit_font_size: 12
                        entity: sensor.microenv_8ff654_sgp41_nox_index
                      - type: custom:mini-graph-card
                        name: Inside VOC
                        hours_to_show: 12
                        points_per_hour: 60
                        decimals: 1
                        font_size: 80
                        height: 150
                        group: true
                        entities:
                          - entity: sensor.microenv_8ff654_sgp41_voc_index
                            name: VOC
                            show_state: false
                            state_adaptive_color: true
                            color: red
                        show:
                          name: false
                          labels: true
                          icon: false
                          state: false
                          graph: line
                          extrema: false
                          points: hover
                      - type: custom:mini-graph-card
                        name: Inside NOx
                        hours_to_show: 12
                        points_per_hour: 60
                        decimals: 1
                        font_size: 80
                        height: 150
                        group: true
                        entities:
                          - entity: sensor.microenv_8ff654_sgp41_nox_index
                            name: NOx
                            state_adaptive_color: true
                        show:
                          name: false
                          labels: true
                          icon: false
                          state: false
                          graph: line
                          extrema: false
                          points: hover
                layout:
                  margin: 0px 0px 0px 0px
                  padding: 0px
    title: Creality K1 Max
```
