### ISSUE TITLE
Graph not loading

### ISSUE THREAD

**Issue by Tovrin** [kalkih/mini-graph-card#1257]
I have a graph to show me my 3-day temperature history, and it's not loading, with the "loading circle" just spinning.  It's nevertdone this and has been working for years.  I've reloaded the cache, but nothing seems to work.

The YAML is:
```
entities:
  - entity: sensor.outdoor_temperature
    name: Back
    color: silver
  - entity: sensor.mailbox_sensor_temperature
    name: Front
    color: deepskyblue
  - entity: sensor.kitchen_button_1_temperature
    name: Kitchen
    color: lime
    show_fill: false
  - entity: sensor.bedroom_1_button_1_temperature
    name: Bedroom 1
    show_fill: false
    color: orange
  - entity: sensor.dining_room_sensibo_temperature
    name: Dining Room
    color: purple
    show_fill: false
  - entity: sensor.bedroom_2_sensor_temperature
    name: Bedroom 2
    show_fill: false
    color: red
  - entity: sensor.bathroom_temperature
    name: Bathroom
    show_fill: false
    color: Teal
  - entity: sensor.lounge_room_sensor_temperature
    name: Lounge Room
    color: navy
    show_fill: false
  - entity: sensor.study_sensibo_temperature
    name: Study
    show_fill: false
    color: salmon
  - entity: input_number.binary_nighttime
    name: Night
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary
    color: black
name: 3-day Temperature
font_size_header: 20
height: 150
hours_to_show: 72
points_per_hour: 1
line_width: 2.5
color_thresholds_transition: smooth
tap_action:
  action: none
show:
  fill: true
  labels: true
type: custom:mini-graph-card
```
All my other graphs are working just fine.  This one isn't.

How do I go back to the previous version?

**Comment by ildar170975** [comment]
The card cannot load a history for one of your entities and thus shows a spinner. 
Consider this as a warning “something wrong is with my setup”. 
You can disable the spinner in options though.

**Comment by Tovrin** [comment]
Quite correct.  The battery had run out on one of my sensors last week and I hadn't got around to replacing it.  Will disabling the spinner loow it to load regardless?

**Comment by Tovrin** [comment]
I've tried using `loading_indicator: false` and it still doesn't load.

**Comment by ildar170975** [comment]
1. If the entity is just unavailable - it’s graph will still be showing if you have some previous history in DB. But if no history at all - then the spinner is displayed.
2. Disabling the spinner will cause showing all available graphs.

**Comment by ildar170975** [comment]
Show the SIMPLIFIED SHORT code with a disabled spinner which does not work.

**Comment by Tovrin** [comment]
I've never disabled the spinner before.  This is the first time I've needed to.  How do I do this?

**Comment by ildar170975** [comment]
Disabling a spinner is described in docs. Cannot give you an exact screenshot. 
Yo need to set loading_indicator=false in “show”.

**Comment by Tovrin** [comment]
Yeah.  I've added that just before `type: custom:mini-graph-card` line.  It had no effect.  Odd.

Edit: I've removed the entity in the interum.  There isn't any rush right now.  I need to order a battery for that sensor anyway.

**Comment by ildar170975** [comment]
We are moving in circles. I suggested you to post a code with a disabled spinner already. And suggested you to check Docs about a option to disable the spinner. And yet you are telling that added option in the wrong place.

**Comment by Tovrin** [comment]
```
entities:
  - entity: sensor.outdoor_temperature
    name: Back
    color: silver
  - entity: sensor.mailbox_sensor_temperature
    name: Front
    color: deepskyblue
  - entity: sensor.kitchen_button_1_temperature
    name: Kitchen
    color: lime
    show_fill: false
  - entity: sensor.bedroom_1_button_1_temperature
    name: Bedroom 1
    show_fill: false
    color: orange
  - entity: sensor.dining_room_sensibo_temperature
    name: Dining Room
    color: purple
    show_fill: false
  - entity: sensor.bedroom_2_sensor_temperature
    name: Bedroom 2
    show_fill: false
    color: red
  - entity: sensor.bathroom_temperature
    name: Bathroom
    show_fill: false
    color: Teal
  - entity: sensor.lounge_room_sensor_temperature
    name: Lounge Room
    color: navy
    show_fill: false
  - entity: sensor.study_sensibo_temperature
    name: Study
    show_fill: false
    color: salmon
  - entity: input_number.binary_nighttime
    name: Night
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary
    color: black
name: 3-day Temperature
font_size_header: 20
height: 150
hours_to_show: 72
points_per_hour: 1
line_width: 2.5
color_thresholds_transition: smooth
tap_action:
  action: none
show:
  fill: true
  labels: true
loading_indicator: false
type: custom:mini-graph-card
```

The second entity is the one with the issue.
