### ISSUE TITLE
Since v0.13.0-dev2 Graph not rendering -- Spinning HA in v0.13.0

### ISSUE THREAD

**Issue by DeFlanko** [kalkih/mini-graph-card#1258]
A hand full of cards that are using the mini-graph-card are doing this.  Has anyone else seen this before?

this is on v0.13.0 , rolled back to v0.12.1 and its fine. **Something is broken in v0.13.0**

![Image](https://github.com/user-attachments/assets/34ecf923-aae2-4269-9cd0-73027dfedffc)

![Image](https://github.com/user-attachments/assets/4cbae399-b98b-472d-9c9f-ed88805080f8)

**Comment by DeFlanko** [comment]
well the spinner is new, ok #1234 

However starting from v0.13.0-dev2 the graph is gone entirely. v0.13.0-dev3 still gone. v0.13.0 spinning ha thingy.

**Comment by ildar170975** [comment]
The spinner is shown when the entity history is not available. Check with a standard history graph with same hours-to-show. And upgrade to HA 2025.5

**Comment by DeFlanko** [comment]
Yeah the info is there , and the graph is shown when im on v0.12.1 -- the graph doesn't show in v0.13.0

![Image](https://github.com/user-attachments/assets/178034b7-c5de-40a9-bd6c-ed202302bce0)

**Comment by wstoettinger** [comment]
I'm having this problem too. not for all graphs though. I'll downgrade until this is fixed.

**Comment by ildar170975** [comment]
@DeFlanko 
Please post only related info:
1. Minimal code for mini-graph-card for ONE entity and screenshot - when you do not see a graph.  Of course for the latest 0.13 version. 
2. History graph for the same entity and same hours-to-show. 
3. The current state of the entity - screenshot from “dev tools - state”. 
4. Your version of HA.

**Comment by ildar170975** [comment]
@wstoettinger 
> until this is fixed.

There is nothing to fix since the “bug” is not confirmed yet. If you consider this as a bug - please provide the info requested above.

**Comment by DeFlanko** [comment]
> [@DeFlanko](https://github.com/DeFlanko) Please post only related info:
> 
> 1. Minimal code for mini-graph-card for ONE entity and screenshot - when you do not see a graph.
> 2. History graph for the same entity and same hours-to-show.
> 3. The current state of the entity - screenshot from “dev tools - state”.
> 4. You version of HA and mini-graph-card.

1) 
```Yaml
type: custom:mini-graph-card
entities:
  - entity: sensor.flume_current_month_ccf
    name: Flume - Current Month
  - color: "#008fce"
    entity: switch.grass
    name: Watering
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary
  - color: "#008fce"
    entity: switch.flowers
    name: Watering
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary
  - color: "#008fce"
    entity: switch.backyard_garden
    name: Watering
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary
show:
  labels: true
  name_adaptive_color: true
  icon_adaptive_color: true
color_thresholds:
  - value: 22
    color: "#FF1A27"
    name: Tier 3
  - value: 16
    color: "#ffe599"
    name: Tier 2
  - value: 0
    color: "#008fce"
    name: Tier 1
height: 100
days_to_show: 30
points_per_hour: 12
line_width: 3
animate: true

```
2) ![Image](https://github.com/user-attachments/assets/68c1068d-50ed-4dff-b0ba-326ba16cc8a9)

3) ![Image](https://github.com/user-attachments/assets/47a1a0c6-f290-4ea5-9a49-79532515c996)

4) **HA**
Installation method: Home Assistant OS
Core: 2025.5.3
Supervisor: 2025.05.3
Operating System: 15.2
Frontend: 20250516.0

**mini-graph-card.**
v0.13.0 is where the issue is, Currently Rolled back to v0.12.1

v0.13.0: ![Image](https://github.com/user-attachments/assets/daf81c70-3720-4914-833c-bfdea52ec93c)

v0.12.1: ![Image](https://github.com/user-attachments/assets/598fdd2b-bd4b-462d-b286-667b6158c2ab)

**Comment by ildar170975** [comment]
But I asked a card with ONE entity. 
In your case any entity can have missing history.

**Comment by ildar170975** [comment]
See, the spinner is shown while a history is loading. If any entity has no history available - the spinner is still shown. Note that the “spinner” element was added in HA 2025.5, so in earlier HA version you will see no spinner, no graph (we decided no to maintain old versions of HA in part of the spinner ). 
So, if your card has many entities and you keep seeing the spinner - you need to find out which entity is broken.

**Comment by DeFlanko** [comment]
> But I asked a card with ONE entity. In your case any entity can have missing history.

That is one entry. 



> See, the spinner is shown while a history is loading. If any entity has no history available - the spinner is still shown. Note that the “spinner” element was added in HA 2025.5, so in earlier HA version you will see no spinner, no graph (we decided no to maintain old versions of HA in part of the spinner ). So, if your card has many entities and you keep seeing the spinner - you need to find out which entity is broken.

I understand the spinner was added. 

so are you saying [Secondary Entities](https://github.com/kalkih/mini-graph-card?tab=readme-ov-file#alternate-y-axis) are no longer a thing??

Because those are just On/Off (1/0) switches 

```Yaml

  - color: "#008fce"
    entity: switch.grass
    name: Watering
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary  #<---
  - color: "#008fce"
    entity: switch.flowers
    name: Watering
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary  #<---
  - color: "#008fce"
    entity: switch.backyard_garden
    name: Watering
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary    #<---
```

![Image](https://github.com/user-attachments/assets/35438cc3-58ab-4476-9226-f7badc35c176)

**Comment by ildar170975** [comment]
There is no such a thing - “secondary entity”. There are just “entities”, and some of them can be moved to a secondary y-axis. But for each entity its history must be loaded from DB.
Assume your card has 2 entities, and you are seeing a spinner for 1 sec, then graphs are shown. This is normal: the card is loading a history, a slow system (or overloaded) needs more time to get data from DB. 
But if the spinner is keep shown - there is something wrong with at least 1 of your entities. You need to find out which entity has issues. 
Of course you can disable the spinner (check docs) and thus it will behave like before , but then you will not be informed about issues with your entities.

**Comment by DeFlanko** [comment]
All those entities are fine, they all have history. So what should i be looking at?

**Comment by ildar170975** [comment]
As I said, you can disable the spinner. 
But if all entities have a history and the spinner is shown - this is a bug which I will analyze.

**Comment by DeFlanko** [comment]
> As I said, you can disable the spinner. But if all entities have a history and the spinner is shown - this is a bug which I will analyze.

I'm also going to test if its `1/0` or `on/off` that's causing this... I think those Switch entitles are `on/off` ...

**Comment by ildar170975** [comment]
Switches are definitely on/off. Try removing them from the card , what will you have?

Honestly, adding non-numerical values onto a card is a bad idea. Yes, they are processed somehow, but imho there are issues with them.  

My experience: all binary values are converted to 0/1 with template sensors, and then these template 0/1 sensors I add onto a card. No issues, no state-map confusions. Just works.

**Comment by DeFlanko** [comment]
Added to `configuration.yaml`:
```YAML
sensor:
  - platform: template
    sensors:
      grass_watering_numeric:
        friendly_name: "Grass Watering Numeric"
        value_template: >
          {% if is_state('switch.grass', 'on') %}
            1
          {% else %}
            0
          {% endif %}
      flowers_watering_numeric:
        friendly_name: "Flowers Watering Numeric"
        value_template: >
          {% if is_state('switch.flowers', 'on') %}
            1
          {% else %}
            0
          {% endif %}
      backyard_garden_watering_numeric:
        friendly_name: "Backyard Garden Watering Numeric"
        value_template: >
          {% if is_state('switch.backyard_garden', 'on') %}
            1
          {% else %}
            0
          {% endif %
```

Then updated the dashboard entity:
```YAML
type: custom:mini-graph-card
entities:
  - entity: sensor.flume_current_month_ccf
    name: Flume - Current Month
  - color: "#008fce"
    entity: sensor.grass_watering_numeric
    name: Watering
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary
  - color: "#008fce"
    entity: sensor.flowers_watering_numeric
    name: Watering
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary
  - color: "#008fce"
    entity: sensor.backyard_garden_watering_numeric
    name: Watering
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary
show:
  labels: true
  name_adaptive_color: true
  icon_adaptive_color: true
color_thresholds:
  - value: 22
    color: "#FF1A27"
    name: Tier 3
  - value: 16
    color: "#ffe599"
    name: Tier 2
  - value: 0
    color: "#008fce"
    name: Tier 1
height: 100
days_to_show: 30
points_per_hour: 12
line_width: 3
animate: true
```

Which then DID resolve the issue. @ildar170975 was right about the `on/off` needing to be `1/0` 

![Image](https://github.com/user-attachments/assets/3a51157e-b6be-479e-9e6b-84ff66fd6d96)
