### ISSUE TITLE
Colors defined by CSS vars in "color_thresholds" are wrongly processed

### ISSUE THREAD

**Issue by krasatos** [kalkih/mini-graph-card#1259]
Hey everyone.

On 0.13.0 color vars `color: var(---color-var)` renders black bars on the card.
If i change to `color: green` it works ok.

Just rolled back to check, and this example code works ok on 0.12.1:
```
          - type: custom:mini-graph-card
            name: Master CPU Temp
            icon: mdi:temperature-celsius
            entities:
              - entity: sensor.processor_temperature
            show:
              graph: bar
            hours_to_show: 24
            points_per_hour: 3
            color_thresholds:
              - value: 0
                color: var(--success-color)
              - value: 40
                color: var(--error-color)
              - value: 65
                color: var(--warning-color)
```

Hope my submission includes all needed info.
Let me know if you need any further information from me.

**Comment by ildar170975** [comment]
Are these variables defined in the system?
I have some suspicions why this could be broken.
But can do nothing now, away from PC.

**Comment by heidrifx** [comment]
For me, this only ever occurs on the first color.
All other color thresholds work when using `var(--color)`.

The following works *besides* the first threshold:

```yaml
color_thresholds:
  - value: 0
    color: var(--red-color)   # <- this does *NOT* work
  - var(--deep-orange-color)  # <- these work just fine for me
  - var(--orange-color)
  - var(--light-green-color)
  - value: 66
    color: var(--green-color)
```

When I change the first threshold to a hex color (i.e., `#f44336`) or color name (i.e., `red`), the first color threshold works as well:

```yaml
color_thresholds:
  - value: 0
    color: red                # <- this *works*
  - var(--deep-orange-color)
  - var(--orange-color)
  - var(--light-green-color)
  - value: 66
    color: var(--green-color)
```

**Comment by ildar170975** [comment]
There are issues with colors defined by CSS vars.
Colors may be not processed properly.
Better to see it with `lower_bound` defined to "widen up" a graph:
```
  - type: custom:mini-graph-card
    name: vars
    <<: &ref_settings
      entities:
        - entity: sensor.system_monitor_processor_use
      points_per_hour: 120
      hours_to_show: 0.5
      color_thresholds_transition: hard
      height: 200
      show:
        points: true
    color_thresholds: &ref_thresholds_vars
      - value: 0
        color: var(--red-color)
      - value: 10
        color: var(--cyan-color)
      - value: 15
        color: var(--yellow-color)
  - type: custom:mini-graph-card
    name: names
    <<: *ref_settings
    color_thresholds: &ref_thresholds_names
      - value: 0
        color: red
      - value: 10
        color: cyan
      - value: 15
        color: yellow
  - type: custom:mini-graph-card
    <<: *ref_settings
    name: vars + lower_bound
    lower_bound: ~0
    color_thresholds: *ref_thresholds_vars
  - type: custom:mini-graph-card
    <<: *ref_settings
    name: names + lower_bound
    lower_bound: ~0
    color_thresholds: *ref_thresholds_names
```
![Image](https://github.com/user-attachments/assets/535daa5c-3d76-4d3c-bf2b-ee9aa5ae4fba)

**Comment by ildar170975** [comment]
Hopefully will be fixed with https://github.com/kalkih/mini-graph-card/pull/1270

![Image](https://github.com/user-attachments/assets/c259d189-37ab-46e1-8ffa-8e31edea1a6d)

**Comment by Mariusthvdb** [comment]
these thresholds are really fuzzy, if not buggy....

the topic here might not be limited to vars in the thresholds. plain color names also seem not followed

<img width="528" height="252" alt="Image" src="https://github.com/user-attachments/assets/8f84fe53-61ef-4da8-b0e5-30e66776b9ba" />

using
```
  - type: custom:mini-graph-card
    icon: mdi:speedometer
    entities:
      - entity: sensor.speedtest_download
        name: Download
#         color: var(--info-color)
    color_thresholds_transition: smooth/hard

    color_thresholds:
      - value: 0
        color: red
      - value: 100
        color: orange
      - value: 200
        color: green
      - value: 500
        color: limegreen
      - value: 800
        color: blue
      - value: 1000
        color: purple
```

shows a red line + green dots, while commenting the transition makes those yellow line green dots at 530 state for the entity.

setting a color to the entity itself overrides all, so that might be expected.

since documentation is rather lacking on the thresholds:
must we have descending order from 0 to 1000
can we use color names, and if yes which, (I would at least expect the official html names?)
if not please instruct the user to only use hex colors

system vars are applicable in the direct entity color (as you can see I use var(--info-color0 and success, warning, error color also work)

some explanation between colored dots, and colored graph lines would be welcome.

( I returned to this config after having disabled it for a longtime, figuring I would understand the docs, but now see why I disabled that again..)

End rant. please make clear what we can or can not do.

a direct example of the speedtest download sensor would probably fit everyones setup, so would a good to set in docs.

**Comment by ildar170975** [comment]
> shows a red line + green dots

Another issue registered in repo, unrelated to the current one. This current issue is about using vars.

**Comment by Mariusthvdb** [comment]
understood.
let me just summarize what I tested on that matter
```
  - type: custom:mini-graph-card
    icon: mdi:speedometer
    entities:
      - entity: sensor.speedtest_download
        name: Download
      - entity: sensor.speedtest_upload
        name: Upload
        color: var(--success-color)
    color_thresholds_transition: smooth
    color_thresholds:
      - value: 0
        color: var(--error-color)
      - value: 100
        color: var(--warning-color)
      - value: 200
        color: var(--success-color)
      - value: 800
        color: var(--info-color)
```

doesnt work either, and shows black... indicating they are not processed at all, but also dont default to the cards own graph color

even though opening post shows those to be functional

<img width="539" height="273" alt="Image" src="https://github.com/user-attachments/assets/4c3523bb-1588-4002-b844-39ce339f1a7b" />
