### ISSUE TITLE
13.0: disable blue circle when no stats are defined

### ISSUE THREAD

**Issue by pergolafabio** [kalkih/mini-graph-card#1263]
Hi, for some sensors, i disabled stats, to minimize the database
I just use your card to show  the current value, but now with new version, i see blue circle, because there is no histrory logged

What can i do to dissable the blue circle? probably i need to hide somewhing, but what? there are so many options on your card :-)

![Image](https://github.com/user-attachments/assets/217fcbda-7719-425a-9a7a-bbaf7c88ce4b)

**Comment by pergolafabio** [comment]
ok, i see an loading indicator , i set to false, but i still see the blue circle?

`- loading_indicator: false`

**Comment by pergolafabio** [comment]
i have it now like below:

```
          - type: custom:decluttering-card
            template: mini-graph
            variables:
              - entities: 
                  - sensor.pergola_quintens_total_consumption_today
              - name: Verbruik
              - loading_indicator: false
```

bit still see: 

![Image](https://github.com/user-attachments/assets/b83aae08-8c22-4cc7-bed0-bf28a46ccc7b)
