### ISSUE TITLE
After HA Core 2025.6.0 upgrade mini-graph card causes my HA dashboard to crash

### ISSUE THREAD

**Issue by dkorbee** [kalkih/mini-graph-card#1265]
This morging I upgrade my HA to Core 2025.6.0
I'm using Lovelace Mini Graph Card v0.13.0
In almost all my Dashboard Views (with Masonry layout) I use Mini-Graph-Cards.
Since the HA core upgrade all Views with a Mini-Graph-Card on it, crash when I open them.

This is one of the cards yaml config:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.tasmotemp1_am2301_temperature
    name: temperature
name: temperature
hours_to_show: 24
points_per_hour: 1
hour24: true
animate: true
line_color: var(--accent-color)
line_width: 8
font_size: 75
```

It looks like migrating the cards to Section View Layout fixes the issue.

Because that's a lot of work, for now I rolled back to HA Core 2025.5.3 and everything is working fine again.
