### ISSUE TITLE
color_thresholds , why some part of line is black, not config with black color

### ISSUE THREAD

**Issue by zhumuht** [kalkih/mini-graph-card#133]
home assistant version: 0.97.1
mini-graph-card version: 0.5
```yaml
      - type: custom:mini-graph-card
        name: 客厅7天PM2.5
        entities:
          - sensor.aircat_pm25
        hours_to_show: 168
        points_per_hour: 0.25
        show:
          fill: false
          labels: true
        color_thresholds:
          - value: 0
            color: green
          - value: 10
            color: green
          - value: 50
            color: green
          - value: 70
            color: yellow
          - value: 90
            color: red
```

picture: 
![image](https://user-images.githubusercontent.com/40521367/63019946-52501b00-becf-11e9-9ca3-a6b83cfb4d67.png)
