### ISSUE TITLE
hiding the first entity breaks the graph entity options

### ISSUE THREAD

**Issue by Proxx** [kalkih/mini-graph-card#137]
i am trying to create a graph that uses 2 sensors of my electric installation.
one for the low tarif and the other for the high tarif.

the high tarif only shows current watts on monday-friday from 8:00-21:000
the low ony shows current watts in the other timerange.

that is why i would like to use a third sensor that displays current watts all the time.
but when i use it as first entity to only display state the legend color/name isnt displayed correctly anymore

see below code:

``` yaml
  - type: custom:mini-graph-card
    entities:
      # only show state of consumption (watts) no graph
      - entity: sensor.dsmrreader
        name: hidden
        show_line: false
        show_fill: false
        show_legend: false
        show_points: false
        show_indicator: false
     # High tarif sensor consumption (watts)
      - entity: sensor.dsmr_pwr_high
        name: High
     # Lowtarif sensor consumption (watts)
      - entity: sensor.dsmr_pwr_low
        name: Low
```

![alt text](https://proxx.github.io/img/hidden.png "Logo Title Text 1")
as you can see the entity options are kind of mixed. and the label names seemd to move one position 
hidden should not be visible and had color orange?! and the Low entity isnt visible in the labels.

**Comment by kalkih** [comment]
Hey,
This, should be fixed in the development branch, will do a new release shortly and let you know when it's available.

**Comment by Proxx** [comment]
thanks mate :) really appreciate the support and great module 👍

**Comment by kalkih** [comment]
[New release](https://github.com/kalkih/mini-graph-card/releases/tag/v0.6.0) is available, please let me know if it works as expected again!

**Comment by Proxx** [comment]
Yes its working great!
thanks again 😄

**Comment by kalkih** [comment]
Btw,
Instead of this
```yaml
show_line: false
show_fill: false
show_legend: false
show_points: false
show_indicator: false
```

you should be able to just do
```yaml
show_graph: false
show_legend: false
```

...should work better overall 😄
