### ISSUE TITLE
more_info 2nd click open tab

### ISSUE THREAD

**Issue by zibous** [kalkih/mini-graph-card#143]
When I first click on the label then the popup dialog will be displayed.  
If I click again on a legend text, the view tab opens.

```
arch | armv7l
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.7.3
timezone | Europe/Vaduz
version | 0.97.2
virtualenv | true

Mini Graph Card
Installed version: | v0.6.0
```

What am I doing wrong in the configuration?

```yaml
      - type: "custom:mini-graph-card"
        align_icon: left
        align_state: center
        entities:
          - entity: sensor.heizraum_allgemein
            name: Allge...
          - entity: sensor.heizung
            name: Heiz... 
          - entity: sensor.heizungspumpe
            name: H-Pump..        
        font_size: 80
        height: 290
        hours_to_show: 36
        hour24: true
        icon: "mdi:home-floor-0"
        line_color: "#e74c3c"
        line_width: 1
        points_per_hour: 0.25
        width: 290
        unit: Watt
        ## -------------
        more_info: true
        ## -------------
        style: |
          ha-card {
            border-radius: 4px;
            transform: scale(0.95);
            background-size: 100% 100%;
          }
        show:
          icon_adaptive_color: true
          name_adaptive_color: true
          name: true
          icon: true
          state: true
          fill: fade
          points: true
          legend: bottom
          extrema: false
          labels: hover
          graph: bar
```
