### ISSUE TITLE
Can't get it work :( Very strange it looks like pretty easy to install..

### ISSUE THREAD

**Issue by Toukassay** [kalkih/mini-graph-card#145]
1 - I've installed it with HACS
2 - I've check to see if files are in config/www/community/mini-graph-card  -They are
3 - I've add this in the UI config editor :
```yaml
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
```
4 - I got this red box of death :
```json
No card type found
[
  {
    "entities": [
      "sensor.xiaomi_illumination"
    ],
    "type": "custom:mini-graph-card"
  }
]
```

Thanks for your help. Seems like a great card.

**Comment by Toukassay** [comment]
Ok got it !
None of my new custom cards was working so I suspect other things than your card.

Solution was to remove the initial "-" before entities. Like this :
```yaml
type: 'custom:mini-graph-card'
entities:
  - sensor.xiaomi_illumination
```

and **not** like this ([see here](https://github.com/kalkih/mini-graph-card#single-entity-card)) :
```yaml
- type: custom:mini-graph-card
  entities:
   - sensor.illumination
```
