### ISSUE TITLE
Entity legend is not updating with proper color

### ISSUE THREAD

**Issue by SelcouthGuy** [kalkih/mini-graph-card#151]
Legend for first entity have wrong color. Should have the same as current state.
[Screenshot](https://drive.google.com/file/d/1lfNM9GPD5XFTJAjNbuaJEkrpFZ78eOSa/view?usp=sharing)

```
- align_header: default
        align_icon: right
        align_state: left
        color_thresholds:
          - color: '#C0392B'
            value: 30
          - color: '#D35400'
            value: 25
          - color: '#F39C12'
            value: 20
          - color: '#C3FDB8'
            value: 15
          - color: '#BDEDFF'
            value: 0
        entities:
          - entity: sensor.xiaomi_temp_sensor_temperature
            name: Temperatura
            show_fill: true
            show_legend: true
            show_line: true
            show_points: true
            show_state: true
            state_adaptive_color: true
          - color: '#BDEDFF'
            entity: sensor.xiaomi_temp_sensor_humidity
            name: Wilgotnosc powietrza
            show_fill: true
            show_legend: true
            show_line: true
            show_points: true
            show_state: true
            state_adaptive_color: true
            y_axis: secondary
        font_size: 100
        font_size_header: 14
        height: 150
        hour24: true
        hours_to_show: 24
        line_color:
          - '#FAAFBA'
          - '#BDEDFF'
          - '#72E4E8'
          - '#54C571'
          - '#E77471'
        line_width: 5
        name: Temperatura i wilgotnosc powietrza na balkonie
        points_per_hour: 0.7
        show:
          icon_adaptive_color: true
          labels: true
          labels_secondary: true
          name_adaptive_color: false
        type: 'custom:mini-graph-card'
```
