### ISSUE TITLE
Displays temperature icon for pressure sensor

### ISSUE THREAD

**Issue by sgofferj** [kalkih/mini-graph-card#155]
As the title says, the card uses the temperature icon for a pressure sensor. The sensor is defined with the correct device class and is displayed correctly on the more-info popup.

### Config
**Sensor**
```
- platform: mqtt                                                                                                                    
  name: "Outside pressure"                                                                                                          
  state_topic: "weather/pressuresl"                                                                                                 
  unit_of_measurement: "hPa"                                                                                                        
  device_class: pressure                                                                                                            
```
**Card**
```
cards:
  - entities:
      - sensor.outside_temperature
    show:
      labels: false
      extrema: true
    hour24: true
    font_size: 75
    line_color: '#e74c3c'
    line_width: 8
    name: Temperature
    type: 'custom:mini-graph-card'
  - entities:
      - sensor.outside_humidity
    show:
      labels: false
      extrema: true
    hour24: true
    font_size: 75
    line_color: blue
    line_width: 8
    name: Humidity
    type: 'custom:mini-graph-card'
  - entities:
      - sensor.outside_pressure
    show:
      labels: false
      extrema: true
    hour24: true
    font_size: 75
    line_color: var(--accent-color)
    line_width: 8
    name: Air pressure
    type: 'custom:mini-graph-card'
type: horizontal-stack
```
**Screenshot**
![Screenshot_20190914_130816](https://user-images.githubusercontent.com/3258466/64906558-d37a1800-d6f0-11e9-8401-9ccd5484b434.png)
