### ISSUE TITLE
Feature request: Arrange header and state on the same line

### ISSUE THREAD

**Issue by Kedryn** [kalkih/mini-graph-card#157]
I would like to hide name and show only icon and state. but on the same line to save space. Currently i can't do it, and if i hide the name, the icons stays alone in the row, with the state on a new line.

**Comment by piit79** [comment]
Second that. What I would like to use is align icon and name to the left, and the state to the right, but on the same line not to waste vertical space.

I'd love to contribute some code but I'm unfortunately short of time at the moment...

**Comment by kalkih** [comment]
This is actually already possible, I forgot I implemented support for just this.
```yaml
...
align_icon: state
show:
  name: false
```

![hyperion_8123_lovelace_example copy 3](https://user-images.githubusercontent.com/457678/68480489-3ee5ef00-0235-11ea-86e7-e646f224c57e.png)

You can also set `align_state: right` to have the icon / state swap places.

**Comment by kalkih** [comment]
And don't forget the option `font_size` if you want to save even more space.
```yaml
...
font_size: 75
```
![hyperion_8123_lovelace_example](https://user-images.githubusercontent.com/457678/68480684-adc34800-0235-11ea-97af-17163de009f0.png)

**Comment by piit79** [comment]
@kalkih That's great! Any chance adding support for one more combination - like this?

<ICON> <NAME> .... <STATE>

(Icon + name aligned left, state aligned right).

Also, what font are you using please? Looks very clean. Is that from a HA theme?

**Comment by kalkih** [comment]
Yes, could probably do that, might need to rename/change the options in order to achieve that.
I'm thinking, `align_header` or something, where the parameters would be `state` / `top` or something.

The font is Google Sans, loaded in as a CSS resource:
```yaml
resources:
  - url: /local/fonts/fonts.css
    type: css
```

Content of **fonts.css** with the font files located in the same folder.
```css
@font-face {
  font-family: "GoogleSans";
  src: url("GoogleSans-Regular.ttf") format("truetype");
  font-weight: 400;
  font-style: normal;
}
@font-face {
  font-family: "GoogleSans";
  src: url("GoogleSans-Medium.ttf") format("truetype");
  font-weight: 500;
  font-style: normal;
}
@font-face {
  font-family: "GoogleSans";
  src: url("GoogleSans-MediumItalic.ttf") format("truetype");
  font-weight: 500;
  font-style: italic;
}
@font-face {
  font-family: "GoogleSans";
  src: url("GoogleSans-Bold.ttf") format("truetype");
  font-weight: 700;
  font-style: normal;
}
@font-face {
  font-family: "GoogleSans";
  src: url("GoogleSans-BoldItalic.ttf") format("truetype");
  font-weight: 700;
  font-style: italic;
}

body {
  font-family: GoogleSans !important;
  --paper-font-headline_-_font-family: GoogleSans !important;
  --paper-font-common-base_-_font-family: GoogleSans !important;
}
```
