### ISSUE TITLE
bar and line together

### ISSUE THREAD

**Issue by jaburges** [kalkih/mini-graph-card#159]
Hi there,
I have tried many ways to achieve this, and I dont think its currently possible.

Would be great to have entity options 
```
- type: custom:mini-graph-card
            show_header_toggle: false
            hours_to_show: 168
            entities:
              - entity: sensor.daily_usage
                name: Daily Power Usage
                show:
                  graph: bar
              - entity: sensor.energy_usage
                name: Power Usage
                show:
                  graph: line
```

I think the bar would always need to be on the secondary y_axis and displayed in the background, with the lines on top?
