### ISSUE TITLE
tap_action - open url

### ISSUE THREAD

**Issue by alexmorbo** [kalkih/mini-graph-card#160]
Is there a way to make tap_action to open external url?
And which way to get url from sensor attribute?

Like
```
              - color_type: card
                icon: 'mdi:navigation'
                show_name: false
                tap_action:
                  action: url
                  url: sensor.ot_doma_do_petrovskogo_forta.mapurl
                type: 'custom:button-card'
```
