### ISSUE TITLE
Gradient fill thresholds dont work with bounds

### ISSUE THREAD

**Issue by tomlut** [kalkih/mini-graph-card#166]
Vertical fill thresholds do not display correctly if upper and/or lower bounds are defined.

Example graph config:
```
  - color_thresholds:
      - color: '#039BE5'
        value: 0
      - color: '#0da035'
        value: 235
      - color: '#e0b400'
        value: 250
      - color: '#e45e65'
        value: 253
    color_thresholds_transition: smooth
    entities:
      - sensor.mains_voltage
    group: false
    hour24: true
    hours_to_show: 24
    line_width: 4
    lower_bound: 220
    points_per_hour: 4
    show:
      extrema: true
      fill: fade
      labels: false
    style: |
      ha-card {
        border: solid 2px var(--primary-color);
      }
    type: 'custom:mini-graph-card'
    upper_bound: 260
```

With bounds, smooth transition (incorrect shading, red should be miles above this):
![66281027-26687900-e905-11e9-8e84-e05dafa6f10e](https://user-images.githubusercontent.com/10679300/66700150-4353e080-ed39-11e9-8604-66e584e548d6.png)

Without bounds smooth transition (correct shading. The line is the wrong colour in the dips but that is another open issue):
![66281230-1735fb00-e906-11e9-8cd2-874113258710](https://user-images.githubusercontent.com/10679300/66700159-62527280-ed39-11e9-97b7-b5dc8c4c47bf.png)

No bounds, hard transition (correct shading):
![66281538-7cd6b700-e907-11e9-9d4e-89174c87aba1](https://user-images.githubusercontent.com/10679300/66700166-79916000-ed39-11e9-8c11-3a3d9ca8074d.png)

With bounds, hard transition (incorrect shading):
![66281596-c2937f80-e907-11e9-8b0d-c5aad90bc474](https://user-images.githubusercontent.com/10679300/66700171-89a93f80-ed39-11e9-8786-7f5555bdef98.png)

**Comment by tomlut** [comment]
Updated to v0.8.0 cleared my browser cache but this is still an issue. 

With bounds:
![Screenshot_2019-10-21 Home Assistant](https://user-images.githubusercontent.com/10679300/67167883-0a2b0880-f3ea-11e9-8364-b9240c629507.png)


Without bounds:
![Screenshot_2019-10-21 Home Assistant(1)](https://user-images.githubusercontent.com/10679300/67167852-d4861f80-f3e9-11e9-825f-2232bc74249d.png)

Config:
```
      - color_thresholds:
          - color: '#e45e65'
            value: 0
          - color: '#e0b400'
            value: 60
          - color: '#0da035'
            value: 68
        color_thresholds_transition: hard
        entities:
          - sensor.xmas_lights_switch_wifi_signal
        group: false
        hour24: true
        line_width: 6
        name: Xmas Lights SW
        lower_bound: 0
        upper_bound: 150
        points_per_hour: 1
        show:
          fill: fade
          icon: true
          labels: false
          name: true
          state: true
        style: |
          ha-card {
            border: solid 2px var(--primary-color);
          }
        type: 'custom:mini-graph-card'
```

**Comment by kalkih** [comment]
Hey,
It looks like you're still on the old version, the fill gradient is even offset from the line gradient in your no custom bound config.

I'm at least not able to reproduce the issue anymore.

Quick dirty example:

```yaml
- type: custom:mini-graph-card
  name: Example
  entities:
    - sensor.temp
  hours_to_show: 168
  points_per_hour: .5
  height: 200
  show:
    labels: true
  upper_bound: 25 # only second example 
  lower_bound: 0 # only second example
  color_thresholds_transition: hard
  color_thresholds:
    - value: 0
      color: "#ffffff"
    - value: 5
      color: "#00f000"
    - value: 7.5
      color: "#ff0000"
    - value: 10
      color: "#ff00ff"
    - value: 12.5
      color: "#00ffff"
    - value: 15
      color: "#ffff00"
    - value: 17.5
      color: "#ffffff"
```

<img width="713" alt="Screenshot 2019-10-21 at 01 46 10" src="https://user-images.githubusercontent.com/457678/67168457-180a6a80-f3a5-11e9-8a23-6238bca49152.png">

If you've installed through HACS, please check this https://github.com/kalkih/mini-graph-card/issues/169
