### ISSUE TITLE
Data aggregation min/max/avg 

### ISSUE THREAD

**Issue by nin9s** [kalkih/mini-graph-card#167]
all agg func graphs are looking the same.

```
entities:
  - aggregate_func: max
    color: red
    entity: sensor.wohnzimmer_sensor_temperature
    name: Max
  - aggregate_func: min
    entity: sensor.wohnzimmer_sensor_temperature
    name: Min
  - aggregate_func: avg
    color: green
    entity: sensor.wohnzimmer_sensor_temperature
    name: Avg
group_by: date
hours_to_show: 168
name: Temp Wohnzimmer daily (last week)
type: 'custom:mini-graph-card'

```
If I mouse over min/max/avg all graphs are equal
why?

![card_1](https://user-images.githubusercontent.com/17455046/66721717-ab6ff880-ee05-11e9-8d82-c59fe2c933b4.PNG)
