### ISSUE TITLE
tap_action not working

### ISSUE THREAD

**Issue by ThePicklenat0r** [kalkih/mini-graph-card#168]
I'm not sure if this is a bug or if I'm doing something wrong, but `tap_actions` are not working for me, I'm just getting the more-info pop-up. Here's an example where it does not work:
``` 
 - entities:
      - sensor.home_energy_meter_power
    hour24: true
    name: Energy Consuption
    points_per_hour: 6
    show:
      fill: false
      points: false
    type: custom:mini-graph-card
    tap_action: 
      action: call-service
      service: notify.push_html5
      service_data:
        title: test
        message: test2
```

I installed through HACS and everything is up to date. So far I've tried clearing cache, hard refresh (shift+F5), reinstalling mini-graph-card through HACS, different browser, different computer, and incognito mode. From what I can tell the yaml is correct, but maybe I've missed something. The service call works if I run it elsewhere. Also tried the `navigate`  action with no success.
