### ISSUE TITLE
Non-numeric sensor states not working

### ISSUE THREAD

**Issue by automation4home** [kalkih/mini-graph-card#179]
Hey, I am trying to setup **Non-numeric sensor states**, but getting **NaN** no matter what sensor or state_map I use. Any idea why?
```
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.bedroom_motion
    name: bedroom
  - entity: sensor.hall_motion
    name: hall
  - entity: sensor.living_room_motion
    name: living room
    color: green
name: last hour
hours_to_show: 1
points_per_hour: 60
update_interval: 30
aggregate_func: max
line_width: 2
smoothing: false
state_map:
  - value: 'False'
    label: clear
  - value: 'True'
    label: motion
```
