### ISSUE TITLE
Feature request: relative color thresholds

### ISSUE THREAD

**Issue by bokub** [kalkih/mini-graph-card#182]
Hello,
I have an idea to improve the **Dynamic line color** feature.

Instead of setting absolute values in the `color_thresholds` option, it would be great to use relative values.

For example:

```yaml
  color_thresholds:
    - value: 0%
      color: "#1feaea" # Blue
    - value: 50%
      color: "#ffd200" # Yellow
    - value: 100%
      color: "#f72047" # Red
```

Or even easier, omitting values 
```yaml
  color_thresholds:
    - color: "#1feaea" # Blue
    - color: "#ffd200" # Yellow
    - color: "#f72047" # Red
```

![image](https://user-images.githubusercontent.com/17952318/67288877-f9f45580-f4dd-11e9-96f3-d42115ef7dc6.png)

The goal is that the bottom of the graph is always blue and the top is always red, no matter what the values are.

----

Technically, this is easy to do in SVG: 

```svg
<defs>
    <linearGradient id="my-gradient-id" x1="0" y1="1" x2="0" y2="0">
        <stop offset="0" stop-color="#1feaea"></stop>
        <stop offset="0.5" stop-color="#ffd200"></stop>
        <stop offset="1" stop-color="#f72047"></stop>
    </linearGradient>
</defs>
<path stroke="url(#my-gradient-id)" d="..."></path>

```
