### ISSUE TITLE
group_by: date not working as expected

### ISSUE THREAD

**Issue by stepanov1975** [kalkih/mini-graph-card#183]
I am using following definition
```
- type: custom:mini-graph-card
  entities:
    - entity: sensor.socket_dishwasher_energy_today
  name: Dishwasher
  aggregate_func: max
  group_by: date
  hours_to_show: 168
  show:
    graph: bar
```
So I expect that for each day maximum value calculated and single bar for this day will be present on the graph.
Instead, I see the following:
![Capture1](https://user-images.githubusercontent.com/9785479/67312514-202fea80-f50a-11e9-9924-93e40be4fb1b.PNG)
What am I doing wrong?

**Comment by kalkih** [comment]
Hey,
Looks like your browser isn't loading the latest version of the card.
If you've installed the card through HACS please check this: https://github.com/kalkih/mini-graph-card/issues/169
If you installed it manually, try clearing cache.

**Comment by stepanov1975** [comment]
Thanks. I fixed path and graph looks like expected, but values are wrong
Graph:
![Capture1](https://user-images.githubusercontent.com/9785479/67314524-75213000-f50d-11e9-83be-d885422f47cd.PNG)
Actual values:
![Capture](https://user-images.githubusercontent.com/9785479/67314608-a26dde00-f50d-11e9-855a-055917a4c786.PNG)

**Comment by kalkih** [comment]
Yeah that looks weird, does both graph use the same data source, the HA history database?

What does it look like if you do a line graph with the same data:

```yaml
- type: custom:mini-graph-card
  entities:
    - entity: sensor.socket_dishwasher_energy_today
  name: Dishwasher
  hours_to_show: 168
```

Any ideas @maxwroc ?
