### ISSUE TITLE
Barchart - auto-entities (Filter) ?

### ISSUE THREAD

**Issue by zibous** [kalkih/mini-graph-card#184]
I have 37 sensors that measure the power consumption and would like to represent the current consumption as a bar chart. Only the values> 0.00 should be displayed. I can not use "show_legend" because there are too many entries. So I'm looking for a way to:

![barchart](https://user-images.githubusercontent.com/30198737/67389928-e0b1de80-f59b-11e9-88dc-42abc9bae7e8.png)

1. Click on a bar to show the "more-info" dialog
2. Display a bar only if the value is greater than {value}.
3. Mouse move over a bar also shows the label

I tried to use custom: auto-entities (filter), but it looks like this can not be used.

```
#################################################################
#                                                               #
#               SMARTMETER ALL DEVICES .                        #
#                                                               #
#################################################################
type: "custom:vertical-stack-in-card"
title: Geräte Verbrauch 24h (max)
cards:
  - type: horizontal-stack
    cards:
      - type: "custom:mini-graph-card"
        align_state: center
        entities:
            - entity: sensor.s01
            - entity: sensor.s02
            - entity: sensor.s03
            - entity: sensor.s04
            - entity: sensor.s05
            - entity: sensor.s06
            - entity: sensor.s07
            - entity: sensor.s08
            - entity: sensor.s09
            - entity: sensor.s10
            - entity: sensor.s11
            - entity: sensor.s12
            - entity: sensor.s13
            - entity: sensor.s14
            - entity: sensor.s15
            - entity: sensor.s16
            - entity: sensor.s17
            - entity: sensor.s18
            - entity: sensor.s19
            - entity: sensor.s20
            - entity: sensor.s21
            - entity: sensor.s22
            - entity: sensor.s23
            - entity: sensor.s24
            - entity: sensor.s25
            - entity: sensor.s26
            - entity: sensor.s27
            - entity: sensor.s28
            - entity: sensor.s29
            - entity: sensor.s30
            - entity: sensor.s31
            - entity: sensor.s32
            - entity: sensor.s33
            - entity: sensor.s34
            - entity: sensor.s35
            - entity: sensor.s36
            - entity: sensor.s37
        font_size: 80
        hours_to_show: 24
        hour24: true
        line_width: 0.1
        width: 95%
        height: 160
        unit: kWh
        lower_bound: 0
        more_info: true
        aggregate_func: max
        group_by: date
        style: |
          ha-card {
            transform: scale(0.95);
            background-size: 100% 100%;
          }
        color_thresholds:
             - color: "#CFD8DC"
               value: 10
             - color: "#4CAF50"
               value: 50
             - color: "#FDD835"
               value: 100
             - color: "#64DD17"
               value: 200
             - color: "#FFF176"
               value: 300
             - color: "#FFEB3B"
               value: 400
             - color: "#FF5722"
               value: 600
             - color: "#f44336"
               value: 800
             - color: "#f44336"
               value: 5000  
        show:
          icon_adaptive_color: true
          name_adaptive_color: true
          name: false
          icon: false
          state: true
          fill: fade
          legend: false
          extrema: true
          average: true
          labels: hover
          graph: bar
```

Is there a solution for this ?

**Comment by zibous** [comment]
@kalkih 

> 1. Click on a bar to show the "more-info" dialog

If I hide the legend, then I can not call a dialog "more info (except for the first entry / bar)". When hovering over the bar, the name and the values are displayed, but at the "mouse-out" the first entry is selected again. Therefore, I can not call the "more info" for each entry.

> 2. Display a bar only if the value is greater than {value}.

Yes, completely hide.

**Example**
```
filter_min:0  ## The minimum entity state value to be displayed
```
To take up horizontal space i can reach if I put the line_width: 0


> 3. Mouse move over a bar also shows the label

Sorry, my mistake, the label (name) is displayed when I set **name: true.**

**Test for custom:auto-entities (do not work)**
Shows only one empty card without barchart.
```
type: "custom:vertical-stack-in-card"
title: "Aktueller Verbrauch"
cards:
  - type: custom:auto-entities
    card:
      type: "custom:mini-graph-card"
      align_state: center
      font_size: 80
      hours_to_show: 24
      hour24: true
      line_width: 0.1
      width: 95%
      height: 160
      unit: kWh
      lower_bound: 0
      more_info: true
      aggregate_func: max
      group_by: date
      show:
        name: true
        icon: true
        state: true
        fill: fade
        legend: false
        extrema: true
        average: true
        labels: hover
        graph: bar
    filter:
      include:
        - entity_id: "sensor.s*"
          state: "> 0.00"
          attributes:
            name: "Pokey*"
```

This is working:
```
type: "custom:vertical-stack-in-card"
title: "Aktueller Verbrauch"
cards:
  - type: custom:auto-entities
    card:
      type: entities
      title: Verbrauch Top Geräte
      show_header_toggle: false
    filter:
      include:
        - entity_id: "sensor.s*"
          state: "> 0"
          attributes:
            name: "Pokey*"
```
