### ISSUE TITLE
group_by: date - not working?

### ISSUE THREAD

**Issue by simonwood0609** [kalkih/mini-graph-card#191]
Thanks so much for sharing this card @kalkih !

I can't for the life of me figure out why the group_by flag isn't working - I copied your exact template from the guide and changed the sensor only.

Each day has multiple bar-points (the last two "trends" are two days).

```
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.fronius_day_energy
name: Energy Generation
hours_to_show: 168
aggregate_func: max
group_by: date
show:
  graph: bar
```

![image](https://user-images.githubusercontent.com/18339962/67619724-aae65180-f84a-11e9-84bb-e675dd7ac3fa.png)

**Comment by kalkih** [comment]
Hey,
You're most likely not loading the latest version of the card.
If you've installed through HACS, please see this https://github.com/kalkih/mini-graph-card/issues/191.
If you've installed the card manually, try clearing the browser cache.

**Comment by simonwood0609** [comment]
Sorry for the late reply - thanks, that fixed it!  Just deleted the plugin & re-installed via HACS since I'd previously added it manually.

By the way, any way to easily remove the timestamp from the data when mouse-over?

![image](https://user-images.githubusercontent.com/18339962/67766558-cba8e400-faa2-11e9-957d-504bafcaba47.png)

**Comment by kalkih** [comment]
Not without changing the source code, but yes, we should probably skip the timestamp if grouped by date.

**Comment by simonwood0609** [comment]
I'm pretty new to GitHub, where can I leave feature requests?

I'm also wondering if the bar graph can/does support negative values, as some days I produce more power than I consume so the net/total is negative.  Would be nice to have that coloured differently too.

**Comment by kalkih** [comment]
You can just open another issue and state that it's a feature request.

The bar graph does support negative value, the y-axis will change dynamically based on min/max data points.

Sure, you could use color thresholds to render negative bars red and positive bars green for example:
```yaml
- type: custom:mini-graph-card
  entities:
    - sensor.energy
  show:
    graph: bar
    icon_adaptive_color: true
  color_thresholds:
    - value: -50
      color: '#e74c3c' # red
    - value: 0 # above 0 render as this color
      color: '#27ae60' *# green
```

An example of a server load bar graph with color thresholds
![hyperion_8123_lovelace_example (17)](https://user-images.githubusercontent.com/457678/67778123-0854eb00-fa63-11e9-9b0c-f72d90126752.png)

**Comment by simonwood0609** [comment]
Thanks again for your time @kalkih .

I now understand how your graph visualises negative data - at first I thought the y-axis responsive scale must have been wrong (why is 1.17 so close to 6.84?)
![image](https://user-images.githubusercontent.com/18339962/67820674-5c68d980-fb0e-11e9-9584-17860281a1b5.png)

Then I realised that is because the zero-line is somewhere here:
![image](https://user-images.githubusercontent.com/18339962/67820799-cd0ff600-fb0e-11e9-8d77-36d7b84998ec.png)

This is what I was hoping to acheive:
![image](https://user-images.githubusercontent.com/18339962/67820953-67703980-fb0f-11e9-93da-14599f88daca.png)

Is that possible currently?

Also how would I add data-labels to the bar graph to show each bar's value?

Here's my current code:

```
entities:
  - entity: sensor.energyeasy_yesterday_usage
group_by: date
hours_to_show: 336
name: Energy Usage
show:
  graph: bar
type: 'custom:mini-graph-card'
icon_adaptive_color: true
color_thresholds:
  - color: green
    value: -50
  - color: yellow
    value: 0
  - color: orange
    value: 5
  - color: red
    value: 10
```
