### ISSUE TITLE
Feature request: aggregate_func: diff

### ISSUE THREAD

**Issue by orderofcodeadmin** [kalkih/mini-graph-card#197]
Hi,
This feature request is not that big of a deal but it would be very useful for counters presentation.
Graph should display difference between last values of groups.
Useful can be aggregation like "first" and "last" too.

```  
  - type: custom:mini-graph-card
    aggregate_func: diff
    group_by: date
    entities:
       - entity: sensor.gas_counter
```
