### ISSUE TITLE
Bar graph not showing correct values

### ISSUE THREAD

**Issue by tomlut** [kalkih/mini-graph-card#205]
Incorrect data shown in bar graph:

```
aggregate_func: max
color_thresholds:
  - color: '#039BE5'
    value: 0
  - color: '#0da035'
    value: 5
  - color: '#e0b400'
    value: 7.5
  - color: '#e45e65'
    value: 10
entities:
  - entity: sensor.total_cost_today
group_by: date
hours_to_show: 168
name: Energy Cost Per Day
show:
  graph: bar
  labels: true
type: 'custom:mini-graph-card'
```
![Screenshot_2019-11-12 Home Assistant(1)](https://user-images.githubusercontent.com/10679300/68654372-e2ab0400-0581-11ea-96b7-45eea05b9e6f.png)

Seems to be some sort of caching issue as a when opened in private browsing mode the graph displays correctly:
![Screenshot_2019-11-12 Home Assistant](https://user-images.githubusercontent.com/10679300/68654420-ff473c00-0581-11ea-95fa-b086c6339857.png)

Actual last seven days data (newest to oldest):
```
4.64
5.29
6.08
5.81
6.49
5.95
5.17
```
Interestingly a line graph shows the same incorrect values:
```
color_thresholds:
  - color: '#039BE5'
    value: 0
  - color: '#0da035'
    value: 5
  - color: '#e0b400'
    value: 7.5
  - color: '#e45e65'
    value: 10
color_thresholds_transition: hard
entities:
  - sensor.total_cost_today
group: false
hour24: true
hours_to_show: 168
line_width: 4
name: Daily energy cost
points_per_hour: 1
show:
  extrema: true
  fill: fade
  icon: true
  labels: false
  name: true
  state: true
type: 'custom:mini-graph-card'
```
![Screenshot_2019-11-12 Home Assistant(3)](https://user-images.githubusercontent.com/10679300/68655968-14719a00-0585-11ea-8505-0f171ef24ce1.png)

Compare to built in graph:
![Screenshot_2019-11-12 Home Assistant(2)](https://user-images.githubusercontent.com/10679300/68655268-d9bb3200-0583-11ea-8150-bf38b893b68c.png)

Or the mini graph opened in a private browsing window (values are slightly off due to number of points per hour, but not as bad as above):
![Screenshot_2019-11-12 Home Assistant(4)](https://user-images.githubusercontent.com/10679300/68656227-8649e380-0585-11ea-9e4f-cde97e3c7072.png)
