### ISSUE TITLE
Option to control title change to entity name

### ISSUE THREAD

**Issue by kmlucy** [kalkih/mini-graph-card#206]
In #39, you set the graph to show the entity name. Could this be moved to an option? I have several graphs with a single entity, and it makes it more confusing when the name changes when hovering. 

The example where this is most needed for me is that I have a graph for my weekly power consumption, but the entity it uses is 'Daily Power Consumption'. So on hover, the 'Weekly' label flashes to 'Daily Power Consumption'.

**Comment by kalkih** [comment]
I understand the issue but Idk if it's worth implementing as you could just set the name in the entity config.

```yaml
...
name: Weekly
entities:
  - entity: sensor.example
    name: Weekly
```
