### ISSUE TITLE
Crashing when using sensor from platform template

### ISSUE THREAD

**Issue by philipptrenz** [kalkih/mini-graph-card#207]
Hi there,

I'm using a sensor definition from the template platform to extract the current temperature from a climate device:
```yaml
sensor:
  # Weather prediction
  - platform: yr
  # Current temperature
  - platform: template
    sensors:
      spzb0001_current_temperature:
        friendly_name: "Inside_Temp"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.spzb0001', 'current_temperature') }}"
```

This sensor gets displayed correctly using the standard "Sensor" card from Lovelace. When using mini-graph-card, the card will not show up. 

Related Error in the JavaScript console:
```error
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this.entity[a.index].state')
	performUpdate (mini-graph-card-bundle.js:1:42218)
	(anonyme Funktion) (mini-graph-card-bundle.js:1:41825)
	asyncFunctionResume
	(anonyme Funktion)
	promiseReactionJob
```

I'm not sure if my way to extract the current temperature from the climate entity is the smartest way to go or if there is any better way to do so. I'm open for any suggestions ;)
