### ISSUE TITLE
Question: how to get night time shading

### ISSUE THREAD

**Issue by m90att** [kalkih/mini-graph-card#208]
Hi,

This is a great card.  I'm trying to get the night time shading that you have in one of your examples but I don't know how to set up/configure **input_number.nighttime**

Please can you explain.

Thanks.

**Comment by kalkih** [comment]
Hey, please see this issue https://github.com/kalkih/mini-graph-card/issues/127

With the new state_map option you can also achieve the same thing in an alternate way (simpler imo):

```yaml
- type: custom:mini-graph-card
  name: Temperature
  entities:
    - sensor.temp
    - entity: binary_sensor.night
      color: rgba(255,255,255,.25)
      y_axis: secondary
      aggregate_func: min
      show_state: true
      show_line: false
      show_points: false
  state_map:
    - value: "off"
      label: "Day"
    - value: "on"
      label: "Night"
```

![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/7/3/735ae2d57fa4eb066403c4a9817fbac715f760b6.png)


And the only sensor setup you need is:

```yaml
binary_sensor:
  - platform: tod
    name: Night
    after: sunset
    before: sunrise
```

**Comment by m90att** [comment]
Awesome. thanks for the swift response.  I got it working using issue 127 as I tried the state object but it didn't work.

**Comment by dede34fr** [comment]
> Hey, please see this issue #127
> 
> With the new state_map option you can also achieve the same thing in an alternate way (simpler imo):
> 
> ```yaml
> - type: custom:mini-graph-card
>   name: Temperature
>   entities:
>     - sensor.temp
>     - entity: binary_sensor.night
>       color: rgba(255,255,255,.25)
>       y_axis: secondary
>       aggregate_func: min
>       show_state: true
>       show_line: false
>       show_points: false
>   state_map:
>     - value: "off"
>       label: "Day"
>     - value: "on"
>       label: "Night"
> ```
> 
> ![](https://camo.githubusercontent.com/3acf3c7bb4e80b9c5c6a68f840cde22efc628829/68747470733a2f2f636f6d6d756e6974792d686f6d652d617373697374616e742d6173736574732e73332e6475616c737461636b2e75732d776573742d322e616d617a6f6e6177732e636f6d2f6f726967696e616c2f33582f372f332f373335616532643537666134656230363634303363346139383137666261633731356637363062362e706e67)
> 
> And the only sensor setup you need is:
> 
> ```yaml
> binary_sensor:
>   - platform: tod
>     name: Night
>     after: sunset
>     before: sunrise
> ```

Hi, what's that "tod" platform: any name?
I don't get the night zone to appear in my graph:
`        - type: custom:mini-graph-card
          name: Temp intérieur
          graph: line
          hour24: true
          show:
            labels: true
            labels_secondary: false
          entities:
            - entity: sensor.capteur_env_salon_temperature
              name: Salon
              color: blue
              show_fill: false
            - entity: sensor.capteur_env_sdb_rdc_temperature
              name: Sdb rdc
              color: green
              show_fill: false
            - entity: sensor.capteur_env_chambre_parents_temperature
              name: Chambre parents
              color: orange
              show_fill: false
            - entity: binary_sensor.nuit
              name: Nuit
              color: lightgrey
              aggregate_func: min
              show_state: true
              show_line: false
              show_points: false
              show_legend: false
              y_axis: secondary
          state_map:
            - value: "off"
              label: "Jour"
            - value: "on"
              label: "Nuit"`

**Comment by kalkih** [comment]
Here's the docs for the tod platform https://www.home-assistant.io/integrations/tod/

**Comment by attkri** [comment]
Hi, unfortunately the above instructions do not work for me. I do not see any shading:

![image](https://user-images.githubusercontent.com/59642616/112436087-dd4cf480-8d45-11eb-9d90-42d389747464.png)

```
type: 'custom:mini-graph-card'
name: Temperature
entities:
  - entity: sensor.haus_umweltsensor_temperature
  - entity: binary_sensor.night
    color: 'rgba(255,255,255,.25)'
    y_axis: secondary
    aggregate_func: min
    show_state: true
    show_line: false
    show_points: false
state_map:
  - value: 'off'
    label: Day
  - value: 'on'
    label: Night

-----------------------------------------
configuration.yaml:

binary_sensor:
  - platform: tod
    name: Night
    after: sunset
    before: sunrise
```

What have I missed?

**Comment by filikun** [comment]
> 
> 
> Hi, unfortunately the above instructions do not work for me. I do not see any shading:
> 
> ![image](https://user-images.githubusercontent.com/59642616/112436087-dd4cf480-8d45-11eb-9d90-42d389747464.png)
> 
> ```
> type: 'custom:mini-graph-card'
> name: Temperature
> entities:
>   - entity: sensor.haus_umweltsensor_temperature
>   - entity: binary_sensor.night
>     color: 'rgba(255,255,255,.25)'
>     y_axis: secondary
>     aggregate_func: min
>     show_state: true
>     show_line: false
>     show_points: false
> state_map:
>   - value: 'off'
>     label: Day
>   - value: 'on'
>     label: Night
> 
> -----------------------------------------
> configuration.yaml:
> 
> binary_sensor:
>   - platform: tod
>     name: Night
>     after: sunset
>     before: sunrise
> ```
> 
> What have I missed?

Did you ever get it to work? Mine looks exactly like yours

**Comment by RomRider** [comment]
On a white background you have to change the color to `rgba(0, 0, 0, .25)`

**Comment by kpurintun** [comment]
does this day/night sensor require some 'history' to work correctly?

**Comment by mrkesu** [comment]
I needed to add "group_by: hour" for everything to work as intended.

```
type: custom:mini-graph-card
name: Temperature
entities:
  - entity: sensor.motion_livingroom_temperature
  - entity: binary_sensor.night
    color: rgba(0, 0, 0, .25)
    y_axis: secondary
    aggregate_func: min
    show_state: true
    show_line: false
    show_points: false
state_map:
  - value: 'off'
    label: Day
  - value: 'on'
    label: Night
group_by: hour
```
