### ISSUE TITLE
Daily aggregration bar failed to display correct number

### ISSUE THREAD

**Issue by lovejoey11** [kalkih/mini-graph-card#217]
Hello, I'm having an issue to display daily data as shown below. 
JS version: 0.8.2
HA Version: 0.100.2

As shown in the below picture, the daily usage can not be displayed correctly. Any suggestions on the config?
![image](https://user-images.githubusercontent.com/2052809/70354120-79db4280-1834-11ea-98eb-8e8d72c0d2b8.png)

While HA historical shows this. 
![image](https://user-images.githubusercontent.com/2052809/70356400-ea389280-1839-11ea-9f79-49e01e9b2ddf.png)

Appreciate your time looking into this.

**Comment by kalkih** [comment]
Hey,
There are some issues with local caching of history data which I believe is the root of this issue.
It should hopefully be resolved in the latest beta release found [here](https://github.com/kalkih/mini-graph-card/releases/tag/v0.9.0-beta).

After updating to the beta the cache should sort itself out with time, but you can also clear it manually by changing `hours_to_show` to something else, refresh the page with the card and then change `hours_to_show` back.

There's also a new option in the beta release to disable cache completely `cache: false`, which you could try if you're still having issues after trying the above.

**Comment by dzikus** [comment]
I'm using version from github with new "cache: false" option and the bug is still there. It show especially on last bar but also on others.
```yaml
aggregate_func: max
cache: false
entities:
  - color: '#0399ff'
    entity: sensor.daily_water
    name: Dzienne zużycie wody
group_by: date
hours_to_show: 720
icon: 'mdi:water-pump'
show:
  graph: bar
type: 'custom:mini-graph-card'
```
<img width="333" alt="Zrzut ekranu 2019-12-12 o 10 01 17" src="https://user-images.githubusercontent.com/3209066/70697846-8e9d5780-1cc6-11ea-863c-9a61b1e8439c.png">
<img width="401" alt="Zrzut ekranu 2019-12-12 o 10 00 11" src="https://user-images.githubusercontent.com/3209066/70697855-93faa200-1cc6-11ea-89db-5b7739564570.png">
