### ISSUE TITLE
Not able to get the mini graph card working

### ISSUE THREAD

**Issue by MPJK77** [kalkih/mini-graph-card#222]
Hi,

I have tried to get the mini graph card to work but it won't work for me.
I have installed the mini graph card v0.8.2 via HACS.

This is what I have on top of my lovelace configuration:
```
resources:
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
```
This is the card I want to create:

```
animate: true
entities:
  - entity: sensor.ledstrip_ip67_estimated_current_2.
    show_state: true
  - entity: sensor.ledstrip_ip65_estimated_current.
    show_state: true
hour24: true
hours_to_show: 1
labels: true
legend: true
name: Ledstrip energie gebruik - 1 uur
points_per_hour: 60
type: 'custom:mini-graph-card'
```
The card won't show up, is there someone who can help me?
