### ISSUE TITLE
More than one value on label

### ISSUE THREAD

**Issue by Kedryn** [kalkih/mini-graph-card#224]
In a graph with 3 values shown, only the first one get it's numerical label.
Can at least 3 values be shown on the same line (left, mid and right align)?

**Comment by kalkih** [comment]
If you want to display several states you can do so with the `show_state` entity option.

```yaml
- type: custom:mini-graph-card
  entities:
    - entity: sensor.sensor_1 #no need for the option here as it defaults to true.
    - entity: sensor.sensor_2
      show_state: true
    - entity: sensor.sensor_3
      show_state: true
```
