### ISSUE TITLE
How to show sum/stack in "state"

### ISSUE THREAD

**Issue by Erimus-Koo** [kalkih/mini-graph-card#226]
```
    - entities:
        - entity: sensor.theater_mode_time_daily
      name: Theater
      icon: 'mdi:movie-open'
      refresh_interval: 0
      hours_to_show: 168
      aggregate_func: max
      group_by: date
      show:
        graph: bar
      type: 'custom:mini-graph-card'
```
I have a card like this, display daily theater mode usage.     
Is there a way to display the total time in state?  
"total" means `sum(aggregate.max(group by date))`, or I can write another sensor to count it, but I don't know how to merge the data in one card.    
I am new here, please advise.

**Comment by kalkih** [comment]
Hello,
Yes you would need to create an additional sensor to display that data.
When you got the sensor, list it first in the entities array and use the `show_graph` option to hide it from the graph.

```yaml
- entities:
    - entity: sensor.theater_mode_time_weekly
      show_graph: false
    - entity: sensor.theater_mode_time_daily
  name: Theater
  icon: 'mdi:movie-open'
  refresh_interval: 0
  hours_to_show: 168
  aggregate_func: max
  group_by: date
  show:
    graph: bar
  type: 'custom:mini-graph-card'
```

If you want to show the state of both sensors you can add `show_state: true` to the second entity.

**Comment by Erimus-Koo** [comment]
Yes, it works, thanks a lot.
![image](https://user-images.githubusercontent.com/17139670/71743296-2db90780-2e9f-11ea-8dd6-d6622ffad321.png)

**Comment by Erimus-Koo** [comment]
I found some problem with this method.
![image](https://user-images.githubusercontent.com/17139670/71757095-41c82d80-2ece-11ea-9b53-d15225dbfb08.png)

While add a "count sensor" and `show_graph: false`, the grid offset.

```
# The offset card (Above)
  - entities:
      - entity: sensor.theater_mode_time
        show_graph: false
      - entity: sensor.theater_mode_time_daily
    name: Theater
    icon: 'mdi:movie-open'
    refresh_interval: 0
    font_size: 50
    hours_to_show: 168
    aggregate_func: max
    group_by: date
    show:
      graph: bar
    type: 'custom:mini-graph-card'
```

```
# Normal card (Below)
  - entities:
      - entity: sensor.theater_mode_time_daily
    name: Theater
    icon: 'mdi:movie-open'
    refresh_interval: 0
    font_size: 50
    hours_to_show: 168
    aggregate_func: max
    group_by: date
    show:
      graph: bar
    type: 'custom:mini-graph-card'
```

Do you know how it happens?
