### ISSUE TITLE
Add option to always show scale

### ISSUE THREAD

**Issue by i00** [kalkih/mini-graph-card#231]
It would be nice if there was an option to always show the scale on the left side.

**Comment by kalkih** [comment]
This is already possible, see the `labels` option in the [show options](https://github.com/kalkih/mini-graph-card#available-show-options).
```yaml
- type: custom:mini-graph-card
  show:
    labels: true
  ...
```
