### ISSUE TITLE
Ability to ignore empty entities (and maybe in the future also invalid ones)

### ISSUE THREAD

**Issue by SeLLeRoNe** [kalkih/mini-graph-card#234]
Hey there,
I was wondering if there is the possibility to ignore invalid/empty entities in the config

```
      entities:
        - entity: '[[entity]]'
          name: Temperature
          color: '#FF5000'
          show_fill: false
        - entity: '[[entity2]]'
          name: Outside
          color: '#0099CC'
          show_state: true
          show_fill: true
        - entity: input_number.night_time
          color: '#B3B3B3'
          name: Night Time
          show_fill: true
          show_line: false
          show_points: false
          show_legend: false
          y_axis: secondary
```

I am using this in combination with the decluttering card and I can send variables ([[entity]]) this way:
```
              - type: custom:decluttering-card
                template: temperature
                variables:
                  - entity: sensor.patio_temperature
```

In the even (or requirement) that [[entity2]] comes empty, would be possible to simply not showing the specific entity rather then having the card fail?

```
Uncaught (in promise) TypeError: Cannot destructure property 'state' of 'this.entity[b]' as it is undefined.
    at HTMLElement.renderState (mini-graph-card-bundle.js:1)
    at mini-graph-card-bundle.js:1
    at Array.map (<anonymous>)
    at HTMLElement.renderStates (mini-graph-card-bundle.js:1)
    at HTMLElement.render (mini-graph-card-bundle.js:1)
    at HTMLElement.update (mini-graph-card-bundle.js:1)
    at HTMLElement.performUpdate (mini-graph-card-bundle.js:1)
    at HTMLElement._enqueueUpdate (mini-graph-card-bundle.js:1)
```
```
Uncaught (in promise) TypeError: Cannot destructure property 'state' of 'this.entity[b]' as it is undefined.
    at HTMLElement.renderState (mini-graph-card-bundle.js:1)
    at mini-graph-card-bundle.js:1
    at Array.map (<anonymous>)
    at HTMLElement.renderStates (mini-graph-card-bundle.js:1)
    at HTMLElement.render (mini-graph-card-bundle.js:1)
    at HTMLElement.update (mini-graph-card-bundle.js:1)
    at HTMLElement.performUpdate (mini-graph-card-bundle.js:1)
    at HTMLElement._enqueueUpdate (mini-graph-card-bundle.js:1)
```

Thanks
