### ISSUE TITLE
card not found

### ISSUE THREAD

**Issue by poudenes** [kalkih/mini-graph-card#239]
Hi All,

HA: 0.103.6 (docker)
mini-graph-card: 0.8.2 (installed using hacs)

Here all my plugins I installed. But only the mini graph card is not found.
```
resources:
  - type: js
    url: /community_plugin/calendar-card/calendar-card.js
  - type: js
    url: /local/simple_clock/simple-clock-card.js
  - type: module
    url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  - type: module
    url: /community_plugin/custom-header/custom-header.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
```

Restarted HA but its not found the custom card...

```
- type: 'custom:mini-graph-card'
  entities:
    - sensor.memory_use_percent
```

Can someone assist me?
