### ISSUE TITLE
Feature Request: Native support for climate entities

### ISSUE THREAD

**Issue by mouth4war** [kalkih/mini-graph-card#245]
This component is great but lacks one important feature - taking a climate entity and displaying the three sensors from it - target temperature, current temperature and climate state (hvac action idle/heat/cool).

Its currently possible to define template sensors for target temperature and current temperature to use in mini-graph but not climate state. History-graph shows climate state active (heating or cooling) as shaded area under the line graph.

Native support would be perfect.

**Comment by maxwroc** [comment]
If I understand the problem correctly you can use `state_map` feature to render the climate state (as it is a string value right?)

**Comment by reefland** [comment]
A state map allows you to take current state and show it as "auto, heat, cool. off" for example.  However I think the ask, is to be able to get at the attributes associated with the climate entity.

For example, My climate entity `climate.living_room_thermostat` has the current state of `cool` and the following attributes:
```
hvac_modes: auto, heat, cool, off
min_temp: 45
max_temp: 95
fan_modes: on, auto
preset_modes: none, eco
temperature: 77
target_temp_high: null
target_temp_low: null
current_humidity: 57
fan_mode: auto
hvac_action: idle
preset_mode: none
friendly_name: Living Room Thermostat
supported_features: 27
icon: mdi:thermometer
```
I've been trying to use "mini-graph-card" to plot current_temperature, current_humidity, temperature (the target temperature) and show when heating and cooling have been on.  

This would effectively be a replacement of the ugly climate history graph card:
![climate_history_graph](https://user-images.githubusercontent.com/16230914/82736119-2c289880-9cf5-11ea-9e4b-6daa6f3900f5.png)

That could look really nice as a mini-graph-card if it could get at the attributes.

Granted you can get at some of that using other sensors, but I've not seen anything expose that green bar (or red for heat) which would allow me to overlay temperature based on if the times the AC (or heat) was actually on.

**Comment by maxwroc** [comment]
Ok I got it now, make sense

**Comment by kalkih** [comment]
@reefland 
> That could look really nice as a mini-graph-card if it could get at the attributes.
> 
> Granted you can get at some of that using other sensors, but I've not seen anything expose the target temperature or green bar (or red for heat) which would allow me to overlay temperature based on when the AC (or heat) was actually on.

You could already do that by creating template sensors based on the climate entity attributes and use those sensors in the mini-graph-card as OP described, and now you could even show the state with the `state_map` option as Max suggested. The request as I understand it is to streamline this process and let the card populate all data automatically without the need of template sensors.

**Comment by golles** [comment]
I also want to join the club for this request. I think making a template sensors for each climate entity attribute is too much.
Maybe it could be achieved easier. Instead of passing entities to the card, have an option to pass an attribute of an entity. Similar to the standard entity card: https://www.home-assistant.io/lovelace/entities/#attribute

**Comment by bensuffolk** [comment]
Ok, 

So in my attempt to get something working I have made 2 template sensors:
```
- platform: template
    front_bedroom_target_temperature:
      friendly_name: Front Bedroom Target Temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('climate.front_bedroom', 'temperature') }}"

    front_bedroom_heating_state:
      friendly_name: Front Bedroom Heating State
      value_template: >
        {% if is_state_attr ('climate.front_bedroom','hvac_action', 'heating') %}
        {{ state_attr('climate.front_bedroom', 'temperature') }}
        {% else %}
        0
        {% endif %}

```

Which along with an existing sensor..front_bedroom_temperature gives me the 3 separate sensors I'm going to need.

This is my graph configuration

```
    type: 'custom:mini-graph-card'
    entities:
      - entity: sensor.front_bedroom_temperature
      - entity: sensor.front_bedroom_target_temperature
        smoothing: false
      - entity: sensor.front_bedroom_heating_state
    group: true
    hours_to_show: 24
    points_per_hour: 60
    lower_bound: ~20
    refresh_interval: 0
    show:
      fill: false
      graph: line
      icon: false
      labels: true
      name: false
      state: false
      legend: false
      points: false
    upper_bound: ~22

```

My problems are, that if I want a nice looking smooth line for the actual temperature I need to have points_per_hour at the default 0.5, but then the target temperature does not have right angles as it changes, but diagonal lines. It really needs to have 60 points_per_hour, but then the current temperature is all steps.

I think the answer would be to be able to specify points_per_hour on a per entity basis as opposed to a per graph basis.

Secondly the lower bounds is nominally set to 20 but allowing it to go lower if needed, however it of course now goes all the way to 0, meaning there is a a big lot of nothing in the graph and the bit I really want to look at is all bunched up. So I think I need to be able to specify the lower bounds to  limited to 2 of the entities (the lower of temperature and target_temperature) but not count the heating_state.

**Comment by bensuffolk** [comment]
I have updated my template for the heating state to

```
    front_bedroom_heating_state:
      friendly_name: Front Bedroom Heating State
      unit_of_measurement: '°C'
      value_template: >
        {% if is_state_attr ('climate.front_bedroom','hvac_action', 'heating') %}
        {{ state_attr('climate.front_bedroom', 'temperature') }}
        {% else %}
        {% if state_attr('climate.front_bedroom', 'temperature') > state_attr('climate.front_bedroom', 'current_temperature') %}
        {{ state_attr('climate.front_bedroom', 'current_temperature') }}
        {% else %}
        {{ state_attr('climate.front_bedroom', 'temperature') }}
        {% endif %}
        {% endif %}

```

Which limits the lower bound to the lower of the current_temperature or the target temperature, so that should stop the second issue I describe above. But I will need to wait a little for some data to find out if it works...

There is probably a better way to do the min value rather than an if statement, but 'm not really up to speed with these templates!

**Comment by makuser** [comment]
+1

Is there anything we can do to help? I am also looking for such a feature, because a template sensor is no option in my case.

**Comment by mouth4war** [comment]
Not quite native support but okay.

**Comment by kingzize** [comment]
> It doesn't work for me, for some reason. Has anyone got this to work?

Not working for me either on version 0.11.0-dev3 or 0.11.0-dev4

**Comment by kzaoaai** [comment]
it worked for me. All lowercase and underscores instead of spaces (like mouth4war's example).

**Comment by thecem** [comment]
Following with the second line is not working and shows `NaN`. Even when you change `current_humidity` to `current_temperature` it show `NaN`. `current_humidity` in the first entity show the humidity.

So I think there is a problem with the second (after the first entry) graph, value.

Recorder is on....

```
entities:
  - entity: climate.bad
    attribute: current_temperature
    unit: °C
    state_adaptive_color: true
  - entity: climate.bad
    attribute: current_humidity
    unit: '%'
    show_state: true
    state_adaptive_color: true
    y_axis: secondary
hour24: true
points_per_hour: 1
name: Thermo
show:
  extrema: false
  fill: false
  legend: false
  name: false
  icon: false
font_size: 80
type: custom:mini-graph-card
```
![grafik](https://user-images.githubusercontent.com/46648579/130415295-498d73a1-1b9d-4046-99e2-54b3c1a59218.png)
