### ISSUE TITLE
Status only on first entity

### ISSUE THREAD

**Issue by poudenes** [kalkih/mini-graph-card#246]
Hi All,

I love this add-on !!! So many thing I use of this.
Is there a option that you can give some settings that the "for example" motion detection part always show "clear" or Detected" on all entities and not only on the first entity in line

```
aggregate_func: max
entities:
  - entity: binary_sensor.node_19
    name: Livingroom
    color: red
  - entity: binary_sensor.node_18
    name: Diningroom
    color: green
  - entity: binary_sensor.node_14
    name: Bedroom
    color: blue
  - entity: binary_sensor.node_17
    name: Hallway
    color: yellow
hours_to_show: 1
line_width: 2
name: Motion last hour
points_per_hour: 60
smoothing: true
state_map:
  - label: No motion
    value: 'off'
  - label: Motion detected
    value: 'on'
type: 'custom:mini-graph-card'
update_interval: 5
show_label: false
```

It now only show detection when the "binary_sensor.node_19" is activated. But when im in room with sensor "binary_sensor.node_14" it not snow Detected.

**Comment by kalkih** [comment]
Hello!
You could solve this by creating a template sensor or a group of all the binary sensors, you can then use that entity in the card configuration to display the state for that entity, you'd probably want to hide it from the graph (`show_graph: false`).

```yaml
# configuration.yaml
group:
  all_motion:
    name: All motion
    entities:
      - binary_sensor.1
      - binary_sensor.2
      - binary_sensor.3
      - binary_sensor.4
```

```yaml
# card config:
...
entities:
  - entity: group.all_motion
    show_graph: false
  - binary_sensor.1
  - binary_sensor.2
  - binary_sensor.3
  - binary_sensor.4
state_map:
  - label: No motion
    value: 'off'
  - label: Motion detected
    value: 'on'
```
