### ISSUE TITLE
Cant change type of graph

### ISSUE THREAD

**Issue by jimmyeao** [kalkih/mini-graph-card#252]
All of my graphs show as a curved line, trying to get a bar chart using the example:

- type: custom:mini-graph-card
  entities:
    - entity: sensor.energy_consumption
  name: ENERGY CONSUMPTION
  show:
    graph: bar

**Comment by kalkih** [comment]
Hello,
It's hard to tell if your configuration and indentation is correct when its not posted inside a code block.

Try this config:
```yaml
- type: custom:mini-graph-card
  entities:
    - entity: sensor.energy_consumption
  name: ENERGY CONSUMPTION
  show:
    graph: bar
```

If you still don't get a bar chart make sure you've updated the card, try clearing cache e.t.c.  to make sure you're not loading an older version of the card.

If you're using HACS, check [this issue](#169).

**Comment by jimmyeao** [comment]
![image](https://user-images.githubusercontent.com/5197831/73163052-13152f80-40e7-11ea-847b-e887326e7906.png)
```
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.0x00158d00044a661c_temperature
name: Temperature
show:
  graph: bar
```

**Comment by jimmyeao** [comment]
PS the link "check issue" just comes to this page

**Comment by kalkih** [comment]
Here's the right link https://github.com/kalkih/mini-graph-card/issues/169

**Comment by jimmyeao** [comment]
Thanks, I have V0.8.2 installed in HACS, and have 
```
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
```
in my ui-lovelace.yaml

However, after re-editing my card to :
```
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.0x00158d00044a661c_temperature
name: Temperature
show:
  graph: bar
```

it is now working. Not sure what was going on there, but thanks for the help!
