### ISSUE TITLE
show_line: false hides the graphic when animate is on

### ISSUE THREAD

**Issue by mamartins** [kalkih/mini-graph-card#254]
Y-axis graph with `show_line: false` is not visible if animation is turned on.

```
- type: custom:mini-graph-card
  animate: true
  entities:
    - entity: sensor.verandah
      name: Verandah
    - entity: sensor.lounge
      name: Lounge
    - entity: sensor.kitchen
      name: Kitchen
    - color: gray
      entity: input_number.nighttime
      name: Night
      show_line: false
      show_points: false
      show_legend: false
      y_axis: secondary
  show:
    labels: true
    labels_secondary: true
```

Unless we change `animate: true` to `animate: false`
