### ISSUE TITLE
Last aggregate does not work

### ISSUE THREAD

**Issue by i00** [kalkih/mini-graph-card#259]
I installed 0.9.1 and updated the js to use .js?0.9.1 (so not cached)...

I have the following:
```YAML
aggregate_func: last
entities:
  - entity: sensor.withings_weight_kg_kris
    name: Weight
font_size: 75
group_by: date
height: 200
hours_to_show: 672
line_color: var(--accent-color)
show:
  icon_adaptive_color: true
  labels: true
  points: hover
style: |
  ha-card {
    padding-top: 0 !important;
    padding-left: 2px !important;
  }
  .header {
    padding-bottom: 0 !important;
  }
  .label--max,
  .label--min {
    box-shadow: unset !important;
  }
type: 'custom:mini-graph-card'
```
Which produces: 

![image](https://user-images.githubusercontent.com/1435262/73710614-3deb2d80-4750-11ea-8a43-737eb5a6c5d9.png)

The weight entry is 86.44 is the last reading that was taken this morning, however when I move over the last item that covers the day of the last reading I get the average still.

Yesterdays reading was 87.21 ... (86.44 + 87.21) / 2 = 86.825:

![image](https://user-images.githubusercontent.com/1435262/73710896-f0bb8b80-4750-11ea-962e-7487b62bbbba.png)
