### ISSUE TITLE
No graphs!!

### ISSUE THREAD

**Issue by dcnilas11** [kalkih/mini-graph-card#262]
Hi,
Since last update I just lost graphs in my minicard's.
Do you have any idea what can be wrong?

```
cards:
  - entities:
      - sensor.shelly1_current_consumption
    font_size: 75
    line_color: blue
    line_width: 8
    type: 'custom:mini-graph-card'
  - entities:
      - sensor.shelly2_current_consumption
    font_size: 75
    line_color: red
    line_width: 8
    type: 'custom:mini-graph-card'
  - entities:
      - sensor.shelly3_current_consumption
    font_size: 75
    line_color: orange
    line_width: 8
    show:
      graph: line
    type: 'custom:mini-graph-card'
type: horizontal-stack
```

![imagem](https://user-images.githubusercontent.com/59876737/73859684-56337900-4832-11ea-88a5-790125b455be.png)

Continue the good work.
