### ISSUE TITLE
Is aggregate_func sum not working? 

### ISSUE THREAD

**Issue by jnavarrodev** [kalkih/mini-graph-card#265]
I am not sure if it is not working right or I am misunderstanding what it should do.

For getting total power consumption of my house, I am inserting a list of values directly into a variable in the database (mariaDB). So, I have, for each day, for each hour, a value, like:

....
date                              value
2020-02-08 22:00:00   120.00
2020-02-08 21:00:00   153.00
2020-02-08 20:00:00   142.00
...

And this is how I display it:

```
- type: custom:mini-graph-card
  entities:
    - entity: sensor.power
  hour24: true
  hours_to_show: 168
  aggregate_func: sum
  group_by: date
  show:
    graph: bar
```

So I can see 7 bars (each one for each day), but, If I put the mouse over one day, that total number is wrong (the date showing under the total number is right) 
If I add all the values from one day that are in the database, the total number is not the same.

With min or max it goes right (it shows the max/min value of that day).

Is it not working right or sum function does another different thing?
