### ISSUE TITLE
Graph lines should be drawn in reverse order

### ISSUE THREAD

**Issue by i00** [kalkih/mini-graph-card#269]
When drawing my graph three series on it the last series specified gets drawn on top of the others...

I think that this should be the other way around ... so the "primary" appears on top.

**Comment by Mikk36** [comment]
Even better would be a way to manually set the order, for example an "index" property

**Comment by arigit** [comment]
+1, until (or if) a graph "drawing order" is supported, can we please get the the first defined entity in the list be "on top" of all the others (i.e. graphed last)? The first entity is the one that gets the official "accent color" in it is counter-intuitive that it gets pushed to the background by the other entities.

In this past, to work this problem, I used to manually define colors, and I would use the theme's accent color manually set in the "last entity" graphed which I wanted to prioritize so that it overlaps all the others. A lot of manual work that has to be re-done with every theme change. This would be avoided if the graphing order is reversed as requested here.

**Comment by emufan** [comment]
Second this. lease reverse the display order or provide an index-option.

**Comment by eddyg** [comment]
I was just looking for this option. I have a graph that displays temperatures, and I'd like the "main" temperature to be displayed as the default "state" value for the graph, so I put it first in the list, but then it gets drawn _underneath_ all the temperatures...

**Comment by jlsjonas** [comment]
Recap from #658 : the PR provided by Ricardo introduced a `order` attribute along with the fix to reverse the drawing order.
While _more options are always better_, we have to take into account that the maintainers only have so much spare time to dedicate to this project.
If there is sufficient need for an `order:` key (instead of just making sure that the primary entity appears on top, as would indeed be expected.) we can still consider this, but it's a seemingly simple feature that adds significant complexity in maintainability & increased risk for bugs (as we only have limited capacity available, this is something we'd rather avoid)

> This would be avoided if the graphing order is reversed as requested here, then one would simply add as "first entity" the one that one needs to prioritize

To be very clear: Reversing the graphing order to have the primary (first listed) entity on top **will** happen as part of the next (0.12) update; expected in Q1 this year. (and probably still this month on a beta release).

**Comment by emufan** [comment]
> **will** happen

Great!.

**Comment by cryptk** [comment]
I have been able to replicate this effect using card-mod.  While this functionality is still something that should happen (basically either reversing the draw order for the entities, or having the state draw from the last entity rather than the first one), in the meantime here is an example of how to achieve the same result.  Posting that workaround here to help out the other people who want this feature.

Basically, just add the card_mod snippet to your mini-graph-card config and then set `show_state: true` on your last entity (or whatever other entity it is you wanted to have the state rendered from).  The `show_state: true` on the last entity will cause it to show it's state on the right side of the card, and the card_mod snippet will hide the primary state display (allowing the secondary state to move to the left side) and then clean up the left side padding on the secondary state to get it positioned exactly where the primary state used to be at.  Here is the example

```yaml
type: custom:mini-graph-card
name: Downstairs Temperature
icon: mdi:thermometer
card_mod:
  style: |
    .states > .state {
      display: none;
    }
    .states--secondary {
      margin-left: 0 !important;
    }
entities:
  - name: Cooling Target
    entity: climate.downstairs
    attribute: target_temp_high
    smoothing: false
    show_fill: false
    color: blue
  - name: Heating Target
    entity: climate.downstairs
    attribute: target_temp_low
    smoothing: false
    show_fill: false
    color: red
  - name: Current Temperature
    entity: sensor.downstairs_current_temperature
    show_fill: false
    show_state: true
    color: yellow
```
