### ISSUE TITLE
State map labels being used for both axes

### ISSUE THREAD

**Issue by phardy** [kalkih/mini-graph-card#271]
I'm not sure if this is happening because I'm doing something wrong or not understanding the intended behaviour. But, when I define a `state_map` in my graph, I'm seeing mini-graph-card attempt to map both primary and secondary y axes using this map. This leads to a visual bug in how the axes are labelled, and a bunch of warnings thrown in the console.

I'm attempting to graph two sensors. The first is a standard binary sensor, and the second a number between 0-4 inclusive (For context, this is for a smart bassinet. One sensor shows whether the bassinet is on, the second the level of "soothing" it is using). I've configured the card like this:

```yaml
type: 'custom:mini-graph-card'
name: Snoo state
entities:
  - entity: binary_sensor.snoo_asleep
    name: Asleep
    aggregate_func: min
    color: grey
    show_state: true
    show_line: false
    show_points: false
  - entity: sensor.snoo_soothe_level
    name: Soothe level
    show_legend: true
    y_axis: secondary
    aggregate_func: max
lower_bound_secondary: 0
upper_bound_secondary: 4
hours_to_show: 12
points_per_hour: 60
smoothing: false
color_thresholds:
  - color: '#0000ff'
    value: 0
  - color: '#6600cc'
    value: 1
  - color: '#00ff00'
    value: 2
  - color: '#ffff00'
    value: 3
  - color: '#ff0000'
    value: 4
state_map:
  - value: 'off'
    label: Awake
  - value: 'on'
    label: Asleep
```

What I'm seeing is that values on the secondary Y axis are also being mapped according to the `state_map`. This can be seen in the Y axis labels, as well as when a point on the graph is selected:
<img width="529" alt="Screen Shot 2020-02-18 at 9 49 13 pm" src="https://user-images.githubusercontent.com/372919/74729603-d200dd00-5298-11ea-8772-239866edb45c.png">

The labels on the secondary Y axes are marked "Asleep" and "4" when they should be "0" and "4". Additionally, mousing over a 1 point indicates that the Level at that time is "Awake" when it should be "1".

This can also be seen with the card logging warnings in the console. When points on the graph higher than 1 are moused over, the card logs this:

```
mini-graph-card:  value [3] not found in state_map mini-graph-card-bundle.js:1:66925
mini-graph-card:  value [4] not found in state_map 2 mini-graph-card-bundle.js:1:66925
mini-graph-card:  value [2] not found in state_map mini-graph-card-bundle.js:1:66925
```

I think what I'm expecting here is for the card to not look up numeric values in the state map. But, more broadly, would it also be worthwhile making state maps axis-specific?

**Comment by kalkih** [comment]
Hello,
Yes this is indeed an issue, I'm leaning towards making it axis specific, started working on just this a few weeks ago: https://github.com/kalkih/mini-graph-card/commit/822d3f529ab76ba58c72916dc3a0041dda8f2a14.

**Comment by MarcHagen** [comment]
Really not want to be pushing something, but whats holding this up?
The work done in the branch looks good to me?

**Comment by tzwickl** [comment]
I have the exact same issue here any updates when this is going to be merged?

**Comment by ildar170975** [comment]
The issue is more important, this is not just an improvement:
https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1720?u=ildar_gabdullin

**Comment by arigit** [comment]
I run into the same problem. I use a secondary axis to show day/night transitions with the main graph been a water consumption sensor, like so.

![image](https://user-images.githubusercontent.com/652673/132035837-79c34e5d-c510-473c-81fd-3289effe261a.png)

The day/night sensor is a binary sensor, while the water consumption sensor is a 'numeric' sensor, it outputs a float number.
I have a state map configured like so,

```
            state_map:
              - value: 'off'
                label: Day
              - value: 'on'
                label: Night
```
WIth the current issue, when the water sensor has value '1', that value gets converted to a 'Night' as shown in the graph above.

The solution as I see it would be to make the 'state maps' to be entity-specific.

@kalkih any chance to get the code merged?

**Comment by ildar170975** [comment]
I am using usual day/night sensor:
```
sensor:
  - platform: template
    sensors:
      night:
        icon_template: mdi:power-sleep
        value_template: "{% if is_state('sun.sun', 'above_horizon') -%}
                         {{ 0 | int }}
                         {%- else -%}
                         {{ 1 | int }}
                         {%- endif %}"
```
Then I added this sensor to the graph with no problem:
```
      entities:
      - ...
      - entity: sensor.night
        name: Night
        color: choose any color you like
        unit: ''
        show_state: false
        show_indicator: false
        show_graph: true
        show_line: false
        show_fill: true
        show_points: false
        show_legend: false
        state_adaptive_color: false
        fixed_value: false
        aggregate_func: last
        y_axis: secondary
      lower_bound_secondary: ~0
      ...
      show:
        labels_secondary: false
        ...
```

**Comment by titiviking** [comment]
I'm also facing lots of events 

`mini-graph-card:  value [17.4] not found in state_map
mini-graph-card:  value [18.1] not found in state_map
mini-graph-card:  value [17.4] not found in state_map
mini-graph-card:  value [15.0] not found in state_map
mini-graph-card:  value [19.3] not found in state_map
`

my graph is displaying temperature readings, so I don't feel like creating a state_map for any possible value...
Could the state map be a range of some sort ?

**Comment by ildar170975** [comment]
> The solution as I see it would be to make the 'state maps' to be entity-specific.

Correct!

**Comment by jlsjonas** [comment]
State maps is one of the global items that should be made entity specific so this should be resolved in the 0.12 release (the one after this month's release)

**Comment by teskanoo** [comment]
Jus curious if this will be fixed at any time

I have bitten the bullet and defined a state map for every temperature (in the range my graph can show) but am still getting these browser warnings

```
  state_map:
  - label: '0'
  - value: 20.0
    label: '20'
  - value: 20.5
    label: '20.5'
  - value: 21.0
    label: '21'
...
  - value: 51.0
    label: '51'
  - value: 51.5
    label: '51.5'
  - value: 99.0
    label: '99.0'
  - value: "off"
    label: Inactive
  - value: "on"
    label: Active
```

![image](https://github.com/kalkih/mini-graph-card/assets/65863752/09e69548-8dd6-4cd4-ab8c-5483cdf22965)

**Comment by ildar170975** [comment]
@teskanoo 

With my all respect - the whole issue about `state_map` is exaggerated. In most cases a workaround may be found.

1. There is no meaning to have this mapping for numerical values:
```
  - value: 20.0
    label: '20'
  - value: 20.5
    label: '20.5'
  - value: 21.0
    label: '21'
```
Guess you did it for a test only.
2. These non-numerical values are not supposed to be used along with numerical ones:
```
  - value: 99.0
    label: '99.0'
  - value: "off"
    label: Inactive
  - value: "on"
    label: Active
```
Guess you did it for a test only.
3. Assume you have that "on/off" values for the same sensor which has numerical values. Then is not correct - a sensor which is supposed to have numerical values - must not have other values. It may only become `unavailable`. Also, temperatures should be of `device_class: temperature` - and in case of non-numerical values there will be errors in HA Log and the sensor will become `unknown` (these changes were incorporated about a year ago).
4. Assume you have that "on/off" values for the 2nd sensor on the card. This sensor is supposed to be a `binary_sensor`. And you need a background graph for these "on/off" values - it should be displayed on a `secondary` y-axis. Create a simple "on/of -> 1/0" (or 0/1 as you wish) template sensor and use it instead.
5. Any additional labels on a card and a logic like "if device is OFF - do not show a temperature, show INACTIVE instead" may be easily done by card-mod.

Ofc people may keep telling smth like "why we are not using `state_map`, I do not want to create template sensor, I do not want to use card_mod", etc.
OK, contribute and add a clear & 100% working logic for `state_map`.
Or - use a card for its main goal "show graphs for numerical values" and use easy & clear workarounds.

**Comment by tomlut** [comment]
> In most cases a workaround may be found.

So how would you stop the countess warning filling up the debug console for this config?

```
color_thresholds:
  - color: '#039BE5'
    value: 0
  - color: '#e0b400'
    value: 1000
  - color: '#0da035'
    value: 2000
color_thresholds_transition: hard
entities:
  - entity: sensor.grid_power
    name: Inverter Power
  - color: rgba(0,0,255,1)
    entity: binary_sensor.dark_outside
    show_line: false
    y_axis: secondary
group: false
hour24: true
hours_to_show: 24
line_width: 2
points_per_hour: 12
show:
  extrema: true
  average: true
  fill: fade
  labels: false
state_map:
  - label: Day
    value: 'off'
  - label: Night
    value: 'on'
type: custom:mini-graph-card
```
