### ISSUE TITLE
"hours_to_show" not working

### ISSUE THREAD

**Issue by chemelli74** [kalkih/mini-graph-card#272]
Hi,

I have implemented 2 cards using v0.9.2 on HA 0.105.2.
First one with:

```
show:
  hours_to_show: 8
```

and second one with:

```
show:
  graph: bar
  hours_to_show: 168
```

but on both cases is not correctly filtering the time range, showing a lot of data more.
For example at 3pm,  the first graph shows data from 5am.

Am I missing something ?

Simone

**Comment by kalkih** [comment]
Never seen that, set `points_per_hour` to `1` as well and send me screenshots of the graphs.

**Comment by SouravBasu** [comment]
I see a problem with bar graph. My config: 

```
          - type: custom:mini-graph-card
            entities:
              - sensor.sprinkler_duration_template
            name: Sprinkler Duration
            icon: mdi:water-pump
            line_color: "#4285F4"
            animate: true
            hours_to_show: 168
            points_per_hour: 1
            aggregate_func: max
            group_by: date
            hour24: true
            show:
              graph: bar
            tap_action: 
              action: more-info
              entity: switch.backyard_irrigation
```

This always shows the first bar as zero. Even if I change the number days by setting the hours_to_show to 144 or 48, the first bar is always zero.

![image](https://user-images.githubusercontent.com/153128/74793066-1cbc2e00-5274-11ea-92da-026921cc5fcc.png)
