### ISSUE TITLE
hours_to_show with group_by: date doesn't work for bar graph

### ISSUE THREAD

**Issue by SouravBasu** [kalkih/mini-graph-card#277]
My config:

```
- type: custom:mini-graph-card
  entities:
    - sensor.sprinkler_duration_template
  name: Sprinkler Duration
  icon: mdi:water-pump
  line_color: "#4285F4"
  animate: true
  hours_to_show: 168
  points_per_hour: 1
  aggregate_func: max
  group_by: date
  hour24: true
  show:
    graph: bar
  tap_action: 
    action: more-info
    entity: switch.backyard_irrigation
```

This always shows the first bar as zero. Even if I change the number days by setting the hours_to_show to 144 or 48, the first bar is always zero.

Screenshots:

hours_to_show: 168
![image](https://user-images.githubusercontent.com/153128/74793066-1cbc2e00-5274-11ea-92da-026921cc5fcc.png)

hours_to_show: 144
![image](https://user-images.githubusercontent.com/153128/74793111-41180a80-5274-11ea-90f2-a083e8b3fd72.png)

hours_to_show: 48
![image](https://user-images.githubusercontent.com/153128/74793145-58ef8e80-5274-11ea-968e-1e5bc8f44767.png)

I cleared all browser cookies and caches, but still no avail. 

I tried it with `cache: false` and noticed that every time it was hitting the cache I see this problem, but whenever it is a cache miss, and the actual data is fetched then it works correctly.
