### ISSUE TITLE
Graph fetches some erroneous data when displaying entity

### ISSUE THREAD

**Issue by dkalinai** [kalkih/mini-graph-card#279]
So here we have two utility meters created at the same time as well as visuals in lovelace. The one on the left works fine as expected, the one on the right, displays some values before the sensor was even created.

![image](https://user-images.githubusercontent.com/12793954/75087848-149f0f80-554e-11ea-95d7-b0429a0a4695.png)

The code for achieving the right middle graph is this one:

```
  entities:
      - entity: sensor.dmi_living_room_power_load_daily_consumption
        index: 0
        state_adaptive_color: true
    group_by: date
    hour24: true
    hours_to_show: 730
    icon: 'mdi:sofa'
    line_color: '#B4824D'
    line_width: 2
    lower_bound: 0
    name: Living Room Daily Consumption
    points_per_hour: 60
    show:
      graph: bar
    type: 'custom:mini-graph-card'
```

I got no clue why it would draw this like that, and struggling to understand. Was displaying fine while device was switched off, but as soon as i turned it on the whole graph populated like this...
