### ISSUE TITLE
[Enhancement?] multiple entities on one card

### ISSUE THREAD

**Issue by ideasman69** [kalkih/mini-graph-card#28]
Firstly - awesome work on this! It's _so_ much neater than the builtin graphs in HA. So thanks for putting it out there for everyone 👍 

Just wondering if there's a possibility of allowing multiple entities on the one graph? I use the built in graph to show a visual representation of inside/outside temp:

![image](https://user-images.githubusercontent.com/19260137/51941852-b0ed0480-2469-11e9-99b3-aed1cb8a31e8.png)

but something like this would like much nicer:

![image](https://user-images.githubusercontent.com/19260137/51941667-42a84200-2469-11e9-93c2-1d606be08ec3.png)

Thanks again!

**Comment by kalkih** [comment]
Thank you!
I've actually already started working on just this, there's still some issues but I might release it as beta with the next release.

Here's a sneak peek of some new stuff coming soon...
![hyperion_8123_lovelace_4 3](https://user-images.githubusercontent.com/457678/51945732-c2a9ba00-241f-11e9-9454-85b1c326964e.png)

**Comment by ideasman69** [comment]
wowee! can't wait :heart_eyes:

**Comment by kalkih** [comment]
Now possible with the latest release [v0.2.0](https://github.com/kalkih/mini-graph-card/releases/tag/v0.2.0)

```yaml
# Example multiple entities
- type: custom:mini-graph-card
  name: EXAMPLE
  entities:
    - sensor.aqara_gateway_illumination
    - sensor.aqara_sensor2_pressure
```

**Comment by kalkih** [comment]
I see that you are still loading the previous version of the card.
Make sure to either bump the version number at the end of your resource reference to 0.2.0, alternatively clear the browser cache.
```
# Bump version
resources:
  - url: /local/mini-graph-card-bundle.js?v=0.2.0
    type: module
```
