### ISSUE TITLE
Extrema labels Max & Min are the same values

### ISSUE THREAD

**Issue by octaviz** [kalkih/mini-graph-card#282]
I had not noticed and the maximum value is no longer differentiated with the minimum, I do not know why since it worked before and the code has not been touched at all, this is the code of my card

![Screenshot_1](https://user-images.githubusercontent.com/856579/75264619-f7896b80-57ef-11ea-8309-a7b0f9edc8d1.png)
```
animate: true
color_thresholds:
  - color: '#008aff'
    value: 10
  - color: '#ffae00'
    value: 15
  - color: '#ff0000'
    value: 25
decimals: 1
entities:
  - sensor.terraza_temperatura
icon_adaptive_color: true
labels: true
line_width: 2
more_info: true
name: Temperatura Exterior
points: true
show:
  extrema: true
  labels: true
  legend: true
show_state: true
style: |
  ha-card {
    border: solid 1px #ffc500;
    
    border-radius: 10px;
  }
type: 'custom:mini-graph-card'
unit: ºC
update_interval: 30
```
