### ISSUE TITLE
Cannot assign to read only property '0' of object '[object Array]'

### ISSUE THREAD

**Issue by jjanderson** [kalkih/mini-graph-card#286]
Hello,

After the upgrade today, I am getting this error on some of my graph's...

Here is a sample of one of the graph's throwing errors:

```
color_thresholds:
  - color: '#00CD00'
    value: 65
  - color: '#98FB98'
    value: 60
  - color: '#FFFF00'
    value: 51
  - color: '#FF9912'
    value: 38
  - color: '#B20000'
    value: 25
entities:
  - entity: sensor.bedroom_iaq_index
    name: Air Quality
hours_to_show: 168
icon: 'mdi:biohazard'
name: Air Quality
type: 'custom:mini-graph-card'
```
