### ISSUE TITLE
Wrong last bar value - always zero.

### ISSUE THREAD

**Issue by dzikus** [kalkih/mini-graph-card#289]
Last bar on graph is wrong, also hours to show omitting last day (history-graph show one day more with 720 hours).

![image](https://user-images.githubusercontent.com/3209066/75612285-54539180-5b22-11ea-885b-a9dbc7c0b1a3.png)
![image](https://user-images.githubusercontent.com/3209066/75612286-57e71880-5b22-11ea-8ff8-0269a343a715.png)
￼
```yaml
aggregate_func: max
cache: false
color_thresholds:
  - color: '#f0f042'
    value: 15
  - color: '#f0e342'
    value: 7.5
  - color: '#d0c442'
    value: 5
  - color: '#c0c042'
    value: 0
entities:
  - entity: sensor.daily_pv4
    index: 0
    name: Dzienna produkcja PV
group_by: date
hours_to_show: 720
icon: 'mdi:solar-power'
show:
  graph: bar
type: 'custom:mini-graph-card'
```

```yaml
entities:
  - entity: sensor.daily_pv4
hours_to_show: 720
refresh_interval: 0
type: history-graph
```

**Comment by kalkih** [comment]
Group by date will often show one less day than the history graph since using "group_by: date" will only display whole days compared to history graph where the first entry will be current time of day 720h. With mini-graph-card you'll get end of current day (00:00) - 720h.

I need more information than "last bar in graph is wrong", I can't really do anything with that information.

**Comment by dzikus** [comment]
It is showing 0, but there is 2.3 value as I show on history-graph card. Bellow again there is 248 max value on history-graph but on mini-graph-card there is zero 0.


<img width="344" alt="Zrzut ekranu 2020-03-1 o 11 43 54" src="https://user-images.githubusercontent.com/3209066/75624136-f078a980-5bb1-11ea-93dd-e601bf648b5a.png">
<img width="342" alt="Zrzut ekranu 2020-03-1 o 11 47 38" src="https://user-images.githubusercontent.com/3209066/75624196-78f74a00-5bb2-11ea-93d7-3fbc439c8750.png">

```yaml
aggregate_func: max
cache: false
entities:
  - color: '#0399ff'
    entity: sensor.daily_water
    index: 0
    name: Example of last bar with 0 value
group_by: date
hours_to_show: 168
icon: 'mdi:water-pump'
show:
  graph: bar
type: 'custom:mini-graph-card'
```

On my every bar graph last bar is 0:
<img width="341" alt="Zrzut ekranu 2020-03-1 o 11 42 55" src="https://user-images.githubusercontent.com/3209066/75624145-01291f80-5bb2-11ea-98b1-c011f213b8ba.png">
<img width="343" alt="Zrzut ekranu 2020-03-1 o 11 42 39" src="https://user-images.githubusercontent.com/3209066/75624150-06866a00-5bb2-11ea-90f2-8855968f0054.png">
