### ISSUE TITLE
Error "Cannot assign to read only property '0' of object '[object Array]'"

### ISSUE THREAD

**Issue by balajeek** [kalkih/mini-graph-card#290]
I am using many mini-graph cards in my HASS (ver 0.106.2) and it stopped working 2 days ago with the error message mentioned.  I haven't touched anything for a while so I am not sure what happen.  I went to community and noticed mini-graph card had an update  (0.9.3) so i took the update hoping that will fix, but not.  

any idea?

**Comment by balajeek** [comment]
just a screenshot of one of them here..

![Screen Shot 2020-02-29 at 9 58 09 PM](https://user-images.githubusercontent.com/19213088/75618587-a0143400-5b3e-11ea-893f-b82374f4d956.png)

**Comment by carlos-sarmiento** [comment]
I'm having the same error.
Here is my card configuration
```
    - type: custom:mini-graph-card
        line_width: 2
        name: "Days Remaining"
        points_per_hour: "1"
        icon: "fal:calendar"
        hours_to_show: "1"
        unit: days
        line_color: "var(--p367c)"
        update_interval: 5
        aggregate_func: "max"
        entities:
          - sensor.dry_age_60d_days
        show:
          labels: no
          points: no
          graph: no
```
