### ISSUE TITLE
Name change when highlighting a point value

### ISSUE THREAD

**Issue by kersten-lohmeyer** [kalkih/mini-graph-card#291]
When a name is set, e.g. "CPU Temperature" but the entity name is different, e.g. "Processor Temperature" und you highlight a point in history then the name next to the icon is overwritten by the entity name, e.g. "Processor Temperature".

Expected behaviour would be for the configured name to stay.

**Comment by kalkih** [comment]
This is by design, if you want the same name when hovering just set the name again in the entity object.

**Comment by kersten-lohmeyer** [comment]
Ok, but in some cases the entity can't be renamed like in System Monitor for Hass.io

**Comment by kalkih** [comment]
Set it in the card config for the entity, see the [entity object options](https://github.com/kalkih/mini-graph-card#entities-object)

```yaml
- type: custom:mini-graph-card
  name: EXAMPLE NAME
  entities:
    - entity: sensor.example
      name: EXAMPLE NAME
```
