### ISSUE TITLE
Sensor values shows period instead of timestamp

### ISSUE THREAD

**Issue by SebSeifert** [kalkih/mini-graph-card#298]
Hi.
I'm using this card for my temp sensors. It looks awesome but one thing is no so good. When i hover over a point on the graph the label is showing an period instead of one "timestamp" when this temperature entry is from. On the picture is the red box the label im talking of.
<img width="384" alt="Bildschirmfoto 2020-03-08 um 03 09 07" src="https://user-images.githubusercontent.com/13780520/76155334-1985c680-60eb-11ea-8bf2-5536b0c8e631.png">. 
Here is my code:

```
entities:
  - color: '#e74c3c'
    entity: sensor.wohnzimmer_temperature
    name: Wohnzimmer
    show_state: true
  - entity: sensor.buro_temperature
    name: Büro
    show_state: true
hour24: true
name: Temperaturen
points_per_hour: 4
show:
  average: true
  extrema: true
type: 'custom:mini-graph-card'
```
