### ISSUE TITLE
Card not working with iOS

### ISSUE THREAD

**Issue by metbril** [kalkih/mini-graph-card#301]
Since upgrading from 0.105.5 to 0.106.5 the mini card does not render on the iPhone. In a regular brower on my PC, the view shows fine, but the same view only shows badges and no cards at all in the ios app.

Example config:

```
title: Host
path: host
icon: 'mdi:server'

badges:
  - binary_sensor.hassio_update_available
  - binary_sensor.db_large
  - binary_sensor.cpu_high
  - binary_sensor.cpu_hot

cards:
  - entities:
      - entity: sensor.memory_use_percent
        name: Geheugen
      - entity: sensor.processor_use
        name: Processor
      - entity: sensor.disk_use_percent
        name: Opslag
      - entity: sensor.cpu_temperature
    title: Systeemperformance
    type: glance

  - entities:
      - entity: binary_sensor.db_large
      - entity: sensor.disk_use_percent
      - entity: sensor.disk_free
      - entity: sensor.home_assistant_v2_db
      - entity: alert.db_large
      - entity: script.purge_database
    show_header_toggle: false
    title: Systeemopslag
    type: entities

  - type: entities
    title: Systeemsoftware
    entities:
      - entity: binary_sensor.hassio_update_available
      - entity: sensor.hassio_version_installed
      - entity: sensor.hassio_version_stable
      - entity: sensor.hacs
      - entity: automation.hassio_update_available_notification
    show_header_toggle: false

  - entities:
      - entity: sensor.last_boot
      - entity: sensor.ha_uptime
    type: entities

  - entities:
      - entity: sensor.pi_hole_ads_blocked_today
      - entity: sensor.pi_hole_dns_queries_today
      - entity: sensor.pi_hole_ads_percentage_blocked_today
    show_header_toggle: false
    title: pi Hole
    type: entities

  - type: custom:mini-graph-card
    entities: 
      - entity: sensor.pi_hole_ads_blocked_today
      - entity: sensor.pi_hole_dns_queries_today
        y_axis: secondary
    points_per_hour: 1

  - entities:
      - entity: sensor.ssl_certificate_expiry
      - entity: sensor.cert_pem_last_updated
        icon: 'mdi:calendar-clock'
      - entity: sensor.myip
    show_header_toggle: false
    title: WAN
    type: entities
```

Screenshot browser:

<img width="1364" alt="Schermafbeelding 2020-03-10 om 21 07 24" src="https://user-images.githubusercontent.com/559346/76354672-343a8400-6313-11ea-9ada-7d81ea988bae.png">

Screenshot iOS:

![20200310-210816-0852](https://user-images.githubusercontent.com/559346/76354742-56cc9d00-6313-11ea-8051-f852b85580a0.png)

I don't see any error messages.
