### ISSUE TITLE
Support for group by month and quarter

### ISSUE THREAD

**Issue by Moneybox76** [kalkih/mini-graph-card#302]
Hi,

it would be great if you could add support for month and quarter fr the group_by parameter.
I would use this getting a graph for power metering.

Best,
Michael

**Comment by Moneybox76** [comment]
I just recognized that year also would be great to have.

**Comment by dzikus** [comment]
I agree, right now I cannot do graph with utility meter other than daily.

**Comment by finix77** [comment]
It woul be great an aggregation function 'inc' that stays for last-first. I want use it to know consume in a day, in a week, in a month etc

**Comment by tungmeister** [comment]
I'd also love to see this. I'd like to graph by day, week and month with one point per unit in bar form.

**Comment by gw1gw1** [comment]
Great idea ! upvote

**Comment by ced1442** [comment]
Hi, I'm also looking for this feature. 
I need to monitor by water/electricty consuption by day/month/year.
If someone has already a solution in home assistant to do that please let me know.

**Comment by dzikus** [comment]
up!

**Comment by finix77** [comment]
Probably with 0.94 versione we will have a similar functionality, with new aggregation function "delta".
But it's long time a wait for it.

**Comment by tbrasser** [comment]
let's assume you have a sensor for realtime power usage (in W).
```yaml
sensors:
  - platform: template
    sensors:
      power_instantaneous:
        unit_of_measurement: W
        value_template: "{{ states('sensor.actual_consumption_sensor') | round() }}"
        entity_id: sensor.actual_consumption_sensor
        device_class: power
```
then with the `integration` component you can create an energy sensor (in kWh):
```yaml
  - platform: integration
    source: sensor.power_instantaneous
    name: energy_total
    unit_prefix: k
    unit_time: h
    method: left
    round: 2
```
Then with the utility_meter component you build the sensor that have the data for your mini-graph-cards:
```yaml
utility_meter:
  hourly_energy_kwh:
    source: sensor.energy_total
    cycle: hourly
  daily_energy_kwh:
    source: sensor.energy_total
    cycle: daily
  weekly_energy_kwh:
    source: sensor.energy_total
    cycle: weekly
  monthly_energy_kwh:
    source: sensor.energy_total
    cycle: monthly
  quarterly_energy_kwh:
    source: sensor.energy_total
    cycle: quarterly
  yearly_energy_kwh:
    source: sensor.energy_total
    cycle: yearly
```
So it would be great if `mini-graph-card` would support all of `utility_meter`'s cycles, so maybe instead of:
```yaml
group_by: date
```
we could have
```yaml
  group_by: hour    # or
  group_by: day     # or
  group_by: week    # or
  group_by: month   # or
  group_by: quarter # or
  group_by: year
```
as mentioned before here, right now only daily is doable:
```yaml
  - type: custom:mini-graph-card
    name: energy today
    icon: mdi:transmission-tower
    entities: [sensor.daily_energy_kwh]
    hours_to_show: 168
    aggregate_func: max
    group_by: date
    points_per_hour: 24
    hour24: true
    show: {graph: bar}
```
