### ISSUE TITLE
tap_action url

### ISSUE THREAD

**Issue by echojjj** [kalkih/mini-graph-card#304]
I have this issue on all of my mini-graph-card(s).  It seems like it will work when I see the hand cursor, but nothing happens when I click on the card.  Didn't work with current release, so I went back to 0.9.0 just to see if I had better luck with the release that implemented the url action.  Also not working.  Same thing.  Hand cursor, but nothing happens.  Is this something wrong with my card config?

```
cards:
  - type: 'custom:mini-graph-card'
    decimals: 0
    entities:
      - entity: sensor.front_door_open_day1
        show_points: false
        show_state: false
      - entity: sensor.front_door_open_day2
        show_points: false
        show_state: false
      - entity: sensor.front_door_open_day3
        show_points: false
        show_state: false
      - entity: sensor.front_door_open_day4
        show_points: false
        show_state: false
    hours_to_show: 1
    lower_bound: 0
    name: Front Door
    show:
      graph: bar
      icon: false
      labels: false
      legend: false
      state: hover
    tap_action:
      action: url
      url_path: 'http://10.0.0.20'
    unit: x
    upper_bound: 80
  - type: 'custom:mini-graph-card'
    decimals: 0
    entities:
      - color: gray
        entity: sensor.front_door_open_today
        fixed_value: true
        name: Today
        show_points: false
        show_state: true
    hours_to_show: 1
    lower_bound: 0
    show:
      graph: bar
      icon: false
      labels: false
    show_name: false
    unit: x
    upper_bound: 80
type: horizontal-stack

```

**Comment by kalkih** [comment]
Hello,
Your config is invalid.
```yaml
tap_action:
  action: url
  url: 'http://10.0.0.20'
```
