### ISSUE TITLE
Show average as header value

### ISSUE THREAD

**Issue by Maltavius** [kalkih/mini-graph-card#313]
This is shows the temperature of all my sensors in the house with different labels.

But I would really like to have the current average temperature from all these sensors as the value shown on top, instead of the first sensor (Vardagsrummet).
 
So instead of 22.46C it would show 22.18C .

![image](https://user-images.githubusercontent.com/10133945/77424380-4ca9a480-6dd1-11ea-9546-6dddcc52210a.png)

```
- cards:
          - entities:
              - entity: sensor.sensor_temperature
                icon: 'mdi:sofa'
                name: Vardagsrummet
              - entity: sensor.sensor_hallen_temperature
                icon: 'mdi:door'
                name: Hallen
              - entity: sensor.kitchen_temperature
                icon: 'mdi:table-chair'
                name: Köket
              - entity: sensor.bedroom2_temperature
                icon: 'mdi:bunk-bed'
                name: Barnens rum
            hour24: true
            name: Temperatur
            type: 'custom:mini-graph-card'
```
