### ISSUE TITLE
24 hours doesn't show good time 

### ISSUE THREAD

**Issue by r3mcos3** [kalkih/mini-graph-card#314]
I've had a issue with the 24 hours notation. 
look at picture.

24:31 has to be 00:31 right??

![minigraphcard](https://user-images.githubusercontent.com/45529818/77524434-a076c500-6e87-11ea-9116-1664de83c5cf.jpg)

```
`color_thresholds:
  - color: '#0061fc'
    value: 250
  - color: e3fc00
    value: 500
  - color: '#fc0000'
    value: 750
entities:
  - sensor.speedtest_download
hour24: true
hours_to_show: 168
icon: 'mdi:download-network'
show:
  extrema: true
type: 'custom:mini-graph-card'`
```
