### ISSUE TITLE
dynamic time range

### ISSUE THREAD

**Issue by s3ta** [kalkih/mini-graph-card#322]
Feature Request: I'd like to change the hours_to_show dynamically in the ui. 

I can imagine having a clock symbol popping up a slider or navigation symbols in the graph (to change  beginning and ending of the shown graph and/or to move forward and backward) or +/- lens symbols,
so one can zoom in or out and change the viewed time range of the graph.

Is this somehow possible?

**Comment by kalkih** [comment]
Hello,
This is out of scope for this project.
You could however achieve something like this by using [lovelace-card-templater](https://github.com/gadgetchnnel/lovelace-card-templater) or [config-template-card](https://github.com/iantrich/config-template-card) together with a [input_number slider](https://www.home-assistant.io/integrations/input_number/) which would act as the `hours_to_show` option parameter in the graph card.

**Comment by s3ta** [comment]
Wow ... thanks for pointing me into the right direction - as a reference I installed `Lovelace card templater` from HACS. 
added in configuration.yaml: 
```input_number:
  thermostatwztimeslider:
    name: Zeit(h)
    initial: 24
    min: 1
    max: 168
    step: 1
```
and in the lovelace editor:
```
cards:
  - entity: climate.thermostatwz
    type: thermostat
  - card:
      animate: true
      color_thresholds:
        - color: '#4040bf'
          value: 1
        - color: '#ffde00'
          value: 200
        - color: '#ff4040'
          value: 300
      decimals: 1
      entities:
        - entity: sensor.temperature_wz
          name: aktuelle Temperatur
        - color: '#55ff55'
          entity: sensor.targettemperature_wz
          name: Zieltemperatur
      hour24: true
      hours_to_show_template: '{{ states.input_number.thermostatwztimeslider.state }}'
      points_per_hour: 0.5
      type: 'custom:mini-graph-card'
    entities:
      - input_number.thermostatwztimeslider
    type: 'custom:card-templater'
  - entities:
      - entity: input_number.thermostatwztimeslider
    show_header_toggle: false
    type: entities
type: vertical-stack
```
and I get:
![Screenshot from 2020-04-04 14-22-41](https://user-images.githubusercontent.com/11409228/78450581-f1549d80-767f-11ea-9342-9ba9d321e92f.png)


(Values are times ten - this is another issue I hope will be solved soon...)
Thanks again!

maybe this helps anyone ...
