### ISSUE TITLE
color_thresholds not working

### ISSUE THREAD

**Issue by StijnVdd** [kalkih/mini-graph-card#323]
I copy pasted the sample as provided on this github page
![image](https://user-images.githubusercontent.com/18342617/78425018-eabf2980-7671-11ea-8f56-86e9754d09a2.png)

After a correction was able to successfully load the grap
![image](https://user-images.githubusercontent.com/18342617/78425039-1215f680-7672-11ea-967c-00874f29cf3c.png)

![image](https://user-images.githubusercontent.com/18342617/78425094-818be600-7672-11ea-9aa3-e83c43ecc0ca.png)
From the moment I uncomment the other thresholds I receive a error
![image](https://user-images.githubusercontent.com/18342617/78425132-dcbdd880-7672-11ea-8262-a2f45a4deb35.png)

Code snippet

```
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.3d_printer_temp
        show:
          labels: true
        color_thresholds:
          - value: 20
            color: '#f39c12'
          - value: 21
            color: "#d35400"
          - value: 21.5
            color: "#c0392b"
```
