### ISSUE TITLE
Incorrect Data

### ISSUE THREAD

**Issue by SteveEdson** [kalkih/mini-graph-card#324]
I'm not sure what the issue is, but the data in the graph just seems massively inaccurate, see the 2 screenshots below

![Custom Graph](https://user-images.githubusercontent.com/1201960/78456534-28d14300-769c-11ea-8c56-a1c1fb33ab94.png)

![HA Graph)](https://user-images.githubusercontent.com/1201960/78456529-1eaf4480-769c-11ea-9ec9-09211ac8d68e.png)

These screenshots were taken at the exact same time, using the config:

```yaml
- type: custom:mini-graph-card
  entities:
    - sensor.hot_tub_temperature
```

This is using v0.9.3 of the graph js, and Home Assistant v0.107.7
