### ISSUE TITLE
Timestamp issue?

### ISSUE THREAD

**Issue by Flight777** [kalkih/mini-graph-card#326]
Hi there, first of all, great work on this card, it makes HASS so much nicer! :)

Forgive me if I'm asking something stupid, but need some help in troubleshooting this (or it might be a small bug in the end):

I have a bar chart that shows my actual energy cost, based on DSMR Reader integration (via MQTT).

```
aggregate_func: last
animate: true
cache: false
entities:
  - entity: sensor.dsmr_day_consumption_total_cost
group_by: date
hours_to_show: 168
name: Energy Cost
show:
  graph: bar
type: 'custom:mini-graph-card'
```
The total cost is accumulating (or reducing based on my solar panel production) constantly, thus I only want it to display the last value (and historically the last value of the day) to be accurate.

Now here is where mini-graph behaves a bit erratic, 2/3 times it shows 0 for all the historic days, which is the first value that the DSMR Reader Posts for the new day at 0:00. 1/3 times it does show the correct, last value of that day, posted at 23:59:xx. It seems somehow mini-graph might have some issues with selecting the correct timestamp if they are very close together, and then takes the first value of the new day, as the "last" value of the old day (hope that makes sense).
