### ISSUE TITLE
Support to show several states

### ISSUE THREAD

**Issue by kalkih** [kalkih/mini-graph-card#33]
@ideasman69 
> How hard is it to have the option of adding in the current value to the right of the screen? Like over here:
> 
> ![image](https://user-images.githubusercontent.com/19260137/52098583-b55d1d00-2623-11e9-951a-c52a7ec825dd.png)
> 
> I suppose it can get tricky with more than 2 sensors

**Comment by kalkih** [comment]
Definitely want to add this functionality, possibly with a `show_state` function in the entity object.
Have to figure out how to handle a few things, like default state.

Could look something like this.

```yaml
# Example of future option
- type: custom:mini-graph-card
  entities:
    - entity: sensor.example
      show_state: true
    - entity: sensor.example2
      show_state: true
    - sensor.example2
```
