### ISSUE TITLE
Graph showing old values

### ISSUE THREAD

**Issue by rs443** [kalkih/mini-graph-card#335]
In a chart that prints the nordpool spotprice once an hour, I have noticed that the chart sometimes is showing the value from the hour before.

Below is an example of the chart that have minimum configuration:
```
entities:
  - entity: sensor.nordpool_kwh_se3_sek_1_10_0
type: 'custom:mini-graph-card'
group_by: hour
smoothing: false
```

This results in the following graph. Highlighted is the bar 8:00 that show the value 52 and is the equal height as the bar at 07:00.
![1](https://user-images.githubusercontent.com/46565725/79549484-53a59900-8097-11ea-8d5c-2e5439b3ea40.PNG)

Showing the real values let us know it is acutally 48.9. We can also see the same pattern in the middle of the graph.
![2](https://user-images.githubusercontent.com/46565725/79549637-894a8200-8097-11ea-9857-57d20abc35c7.PNG)
![3](https://user-images.githubusercontent.com/46565725/79549753-abdc9b00-8097-11ea-8641-e8c3d2e93171.PNG)

Adding configuration to the chart, such as hours_to_show, aggregate_func (first,last,avg) does not change the result.

```
decimals: 1
entities:
  - entity: sensor.nordpool_kwh_se3_sek_1_10_0
    name: Nordpool spotpris
font_size: 75
hour24: true
hours_to_show: 24
group_by: hour
aggregate_func: first
labels: true
line_color: '#d4a3ab'
show:
  graph: bar
  labels: true
type: 'custom:mini-graph-card'
```

![4](https://user-images.githubusercontent.com/46565725/79550005-0c6bd800-8098-11ea-8086-12727bed8073.PNG)

Removing group_by and adding points_per_hour=1 and hours_to_show=24 results in the follow chart. Something seems odd here. It shows 12 bars but should show 24 which might explain why the chart issue?
```
entities:
  - entity: sensor.nordpool_kwh_se3_sek_1_10_0
type: 'custom:mini-graph-card'
smoothing: false
point_per_hour: 1
hours_to_show: 24
show:
  graph: bar

```
![5](https://user-images.githubusercontent.com/46565725/79550687-fe6a8700-8098-11ea-976c-d527da087d8d.PNG)

The chart is updated once an hour, at about 1-20 seconds past the hour.

I have version 0.9.3.
