### ISSUE TITLE
No card type configured.

### ISSUE THREAD

**Issue by erikhave** [kalkih/mini-graph-card#347]
I have installed mini-graph-card and get the error: 'No card type configured.'

1. I have installed Mini Graph Card from HACS (Installed: v0.9.3) in Home Assistant 0.109.4.
2. I have added plugin to Lovelace resources with 'Add to lovelace' from HACS.
3. I have added code to Lovelace:

No card type configured.
- type: 'custom:mini-graph-card'
  entities:
    - sensor.stuen_temperature

**Comment by kalkih** [comment]
Hello,
Try without the initial dash, the `-` before `type` so,
The initial dash is automatically added by the GUI editor so it's only relevant for Lovelace in Storage mode.

```yaml
type: 'custom:mini-graph-card'
  entities:
    - sensor.stuen_temperature
```
