### ISSUE TITLE
no graph 

### ISSUE THREAD

**Issue by matteos1** [kalkih/mini-graph-card#348]
i have this code but **lovelace** not show graph
show only the value of the sensor

```
aggregate_func: max
cache: false
entities:
  - entity: sensor.picco_energia_kw
group_by: date
hours_to_show: 168
icon: 'mdi:counter'
labels: true
name: Energia
show:
  graph: bar
show_state: true
type: 'custom:mini-graph-card'
```
![image](https://user-images.githubusercontent.com/16237822/81196446-5709b180-8fbf-11ea-92a9-ea80221828eb.png)
