### ISSUE TITLE
Graphs not rendering when card is placed within vertical- or horizontal-stack cards.

### ISSUE THREAD

**Issue by fi-sch** [kalkih/mini-graph-card#352]
Hi!

I've come across the bug that's pretty annoying and I'm out of ideas how to fix it.
I have an issue with rendering the graphs when mini-graph-card is being placed in either vertical-stack or horizontal-stack. It's behaving exactly the same way on Safari and within the iOS app. I tried clearing the cache, restarting HA and others, but with no success... It's worth to mention that I do not experience the above issue when graphs are not stacked with other cards.
The strange part is that it renders correctly after switching to another tab (lovelace view) and going back to the one with graphs.

Here are the steps to reproduce it on my setup:

> 1. Reload the page.
> 2. See that there are no graphs.
> 3. Switch views back-and-forth
> 4. Graphs are visible.

My code: 
```
cards:
  - animate: false
    cache: true
    decimals: 1
    entities:
      - color: '#0a84ff'
        entity: sensor.garaz_front_temperature
        index: 0
        show_fill: false
        show_indicator: false
        show_state: true
      - color: '#30d158'
        entity: sensor.salon_temperature
        index: 1
        show_fill: false
        show_indicator: false
        show_state: true
    font_size: 75
    font_size_header: 14
    hour24: true
    hours_to_show: 6
    line_width: 9
    name: Temperatura
    points_per_hour: 2
    show:
      icon: true
      labels: false
      legend: false
    type: 'custom:mini-graph-card'
    update_interval: 300
  - animate: false
    decimals: 1
    entities:
      - color: '#0a84ff'
        entity: sensor.garaz_front_humidity
        index: 0
        show_fill: false
        show_indicator: false
        show_state: true
      - color: '#30d158'
        entity: sensor.salon_humidity
        index: 1
        show_fill: false
        show_indicator: false
        show_state: true
    font_size: 75
    font_size_header: 14
    hour24: true
    hours_to_show: 6
    line_width: 9
    name: Wilgotność
    points_per_hour: 2
    show:
      icon: true
      labels: false
      legend: false
    type: 'custom:mini-graph-card'
    update_interval: 300
type: horizontal-stack
```

Thanks!

PS I'm running the latest version of HA and mini-graph-card.
