### ISSUE TITLE
Binary sensor showing inverted data although y-scale is ok

### ISSUE THREAD

**Issue by u8915055** [kalkih/mini-graph-card#380]
Hello, I am using this really nice card but having a problem with a particular sensor.  I am mapping two temperatures sensors in the same graph as a binary sensor. The binary sensor is based on the sun.sun sensor but ive created a templated sensor from this to represent a '1' when the sun.sun sensors says 'above-horizon' and a '0' when the sun.sun sensor says 'below-horizon'.  So 1 represents day and 0 represents night.

The two temperature sensors are working great, but having a problem with the binary sensor.  The y-axis is showing correctly as a range of 0 to 1.  However the individual data points are inverted.  A 0 showing where a 1 should be etc.  I thought I defined my binary sensor wrong but when I look in history its showing a 1 for daytime and a 0 for night.  Plus, in the actual graph card, if I hover over the legend for the binary sensor it says current state is '1' which means day yet the graph is showing 0.  Very strange.

Here's my card config:

```
name: Greenhouse Temperature
align_header: center
align_state: center
animate: true
entities:
  - entity: sensor.temperature
    name: Outside
    show_fill: false
  - entity: sensor.greenhouse_inside_temp
    name: Inside
    show_fill: false
  - entity: sensor.sun_status
    name: Day/Night
    show_fill: true
    show_points: true
    show_line: false
    y_axis: secondary
font_size: 70
font_size_header: 10
group: true
hours_to_show: 18
line_width: 2
points_per_hour: 3
show:
  icon: false
  labels: true
  labels_secondary: true
smoothing: true
tap_action:
  action: none
type: 'custom:mini-graph-card'
```
 and here's a picture of the card currently:

![image](https://user-images.githubusercontent.com/35235070/85345651-ddaf1b00-b4a7-11ea-9ed7-8a15651e550d.png)

You can see the day-night is inverted.

I cant figure it out.  

Here's my binary sensor config:

```
      sun_status:
        friendly_name: Sun Status
        value_template: '{% if states.sun.sun.state == "above_horizon" %} 1 {% else %}0{% endif %}'
```

Any ideas?  Im using the latest version of the card, 0.9.3.

Thank you

**Comment by kalkih** [comment]
Binary sensors are not supported by default.
Please use the [state-map](https://github.com/kalkih/mini-graph-card#state-map-object) option when using binary sensors.

See [example](https://github.com/kalkih/mini-graph-card#non-numeric-sensor-states)

**Edit: Nvm, forget the above, I see that you're not actually using a binary sensor entity.**

Try settings the bounds for the secondary axis, `lower_bound_secondary` & `upper_bound_secondary` to 0 & 1 respectively.
You would probably also want to set the following options on the binary entity:
* `smoothing: false`
* `aggregate_func: max` or `min`, it's average by default which could cause issues.

**Comment by u8915055** [comment]
Hello @kalkih thanks for your response.  yes I guess I should have been clearer.. I converted a binary sensor to a sensor and then attempted to graph it like the example in the docs.

Here is my updated config:

```
align_header: center
align_state: center
animate: true
entities:
  - entity: sensor.temperature
    name: Outside
    show_fill: false
  - entity: sensor.greenhouse_inside_temp
    name: Inside
    show_fill: false
  - color: gray
    entity: sensor.sun_status
    name: Day/Night
    show_fill: true
    show_line: false
    show_points: true
    smoothing: false
    aggregate_func: min
    y_axis: secondary
lower_bound_secondary: 0
upper_bound_secondary: 1
font_size: 70
font_size_header: 10
group: true
hours_to_show: 18
line_width: 2
name: Greenhouse Temperature
points_per_hour: 3
show:
  icon: false
  labels: true
  labels_secondary: true
smoothing: true
tap_action:
  action: none
type: 'custom:mini-graph-card'
```
ive tried aggregate max and min but no difference.  Here's an update though.  I created a history graph right below it with the same sun_status sensor.  As you can see it is changing from one to zero when it should. but now the mini graph isnt even showing the latest transition from 0 to 1, whether inverted or not.

Could it possibly have something to do with units?  Because the current sensor likely has no units at all.

Here's the graphs

![image](https://user-images.githubusercontent.com/35235070/85436789-72645800-b53e-11ea-9f31-383b26bd1a67.png)

Im happy to try out anything else you might suggest.

Thank you again, its really a beautiful module.. I track these temperatures in a little hobby greenhouse I have and your module is SO much more attractive than using plain old history graphs.. great work.  Thank you.

**Comment by u8915055** [comment]
One other update.. I changed the group_by to hour, and then date, and then back to the default of interval and now its really not doing well.. check out the graph now:

![image](https://user-images.githubusercontent.com/35235070/85437250-2960d380-b53f-11ea-8290-51a9836229d1.png)


Its now just a solid area.  Hope this helps.

**Comment by u8915055** [comment]
Here's another piece of info that may help.  This is the raw data for that sensor out of my mysql database

![image](https://user-images.githubusercontent.com/35235070/85443947-ae032000-b546-11ea-8140-c794821c8966.png)

**Comment by u8915055** [comment]
I see another potential issue.  the sun.sun entity is updating in the database about every 8 minutes.. However my templated sensor sensor.sun_status is only entering a record in the database every time there is a state change.. so there are hundreds of sun.sun state entries but as you can see above only 12 sensor.sun_status entries in that same time period.  Still think it should work with the aggregate_func: last setting maybe but wonder if you might now know whats going on with that info. Thanks again.

**Comment by u8915055** [comment]
Im basically trying to do this from your example in the docs but cant figure out how you got this.
![image](https://user-images.githubusercontent.com/35235070/85453307-96309980-b550-11ea-80f8-5fe2dd81d4a9.png)

How is the entity input_number.nighttime yielding a 1 or 0 result and how is the module interpreting that different than what mine is doing with the sensor.sun_status entity?

**Comment by u8915055** [comment]
Just another update, and sorry for all the messages.. its working now.. I dont know what I did, but its working now.  I have not changed the sensor.. and this is my working config:

```
align_header: center
align_state: center
animate: true
entities:
  - entity: sensor.temperature
    name: Outside
    show_fill: false
    smoothing: true
  - entity: sensor.greenhouse_inside_temp
    name: Inside
    show_fill: false
    smoothing: true
  - aggregate_func: min
    color: gray
    entity: sensor.sun_status
    name: Day/Night
    show_fill: true
    show_line: false
    show_points: true
    smoothing: false
    y_axis: secondary
font_size: 70
font_size_header: 10
group: true
hours_to_show: 24
line_width: 2
lower_bound_secondary: 0
name: Greenhouse Temperature
points_per_hour: 3
show:
  icon: false
  labels: true
  labels_secondary: true
tap_action:
  action: none
type: 'custom:mini-graph-card'
upper_bound_secondary: 1
```

Ill keep an eye on it.

My hunch is this.  In the config I was only showing 18 hours. For the temperature sensors they are sampling every few mins so there is lots of data to grab.  But with the sensor.sun_status, its only registering a new data entry when the sun.sun state changes.. so if all goes as planned, its two data points per day.  However if you dont show enough range in the card, I think it doesnt graph it correctly because it wont have state to work with until there is one of two daily state changes.  this is certianly not a fault of your card but of the template sensor.  I found many out there that have issues with a template sensor because its only updated when there is a state change in the parent sensor.. So even though the sun.sun entity has a database entry every few mins, each entry is the same as the one before except for two times per day, so my sensor.sun_status only registers two datapoints.  I tried to tie my template sensor to something that changes state often like sensor.load_5m but I think that facility is broken in the template sensor.  even the service homeassistant update-entity doesnt work, or doesnt create a database entry.

Anyway, it works now and I thank you again for your work on this.
