### ISSUE TITLE
Color threshold not displaying second threshold

### ISSUE THREAD

**Issue by u8915055** [kalkih/mini-graph-card#383]
Hello,
 I wanted to have a line color for temperature transition from green to yellow to red based on value.  I wanted the line to be green all the time except when crossing 70 then yellow, then 80 red.

The line is displaying green and then transitioning to yellow but even though the value is above 80 its not transitioning to red.

My config is as follows:
```
align_header: center
align_state: center
animate: true
entities:
  - entity: sensor.greenhouse_inside_temp
    name: Inside
    show_fill: false
  - entity: sensor.temperature
    name: Outside
    color: '#4299BA'
    show_fill: false
  - aggregate_func: min
    color: '#9a9a9a'
    entity: sensor.sun_status
    name: Day/Night
    show_line: false
    show_points: false
    y_axis: secondary
color_thresholds:
  - value: 1
    color: '#42D173'
  - value: 70
    color: '#EFDE09'
  - value: 80
    color: '#E64231'
color_thresholds_transition: hard
font_size: 70
smoothing: true
font_size_header: 10
group: true
hours_to_show: 36
line_width: 2
lower_bound_secondary: 0
name: Greenhouse Temperature
points_per_hour: 3
show:
  icon: false
  labels: true
  labels_secondary: false
tap_action:
  action: none
type: 'custom:mini-graph-card'
upper_bound_secondary: 1
```
Here's what my graph looks like:

![image](https://user-images.githubusercontent.com/35235070/85639684-4e883b80-b63e-11ea-82b5-17f315309143.png)

Any thoughts here?

Thank you kindly.
