### ISSUE TITLE
Independent Y-Axis scale for multiple entities

### ISSUE THREAD

**Issue by webbson** [kalkih/mini-graph-card#384]
I like to have my Temperature and humidity on the same graph, however they are so far apart in values and size that it looks like one of them is stuck when the other one flactuates. I would like both of them to have their own scale on the y-axis.

For example here I try to combine the two graphs on the left in the right one, and as you can see because of the different scales they movement of values is close to none.

![image](https://user-images.githubusercontent.com/1351961/85732594-cbc5b600-b6fb-11ea-8f63-2554d6536ef4.png)

**Comment by kalkih** [comment]
Hello,
This is actually already possible 🎉 see the [entity option](https://github.com/kalkih/mini-graph-card#entities-object) **y_axis**.

e.g.
```yaml
...
entities:
  - entity: sensor.temp
  - entity: sensor.humidity
    y_axis: secondary
```
