### ISSUE TITLE
Graphs are sometimes cut off

### ISSUE THREAD

**Issue by ZephireNZ** [kalkih/mini-graph-card#385]
I am seeing the graphs cut off part-way through the timerange configured, but only some of the time. For example, these two screenshots were taken within minutes of eachother. First is on desktop Chrome, second is the official Android app.

![image](https://user-images.githubusercontent.com/1644496/85792996-7683b600-b788-11ea-8aa3-dd187f976527.png)
![image](https://user-images.githubusercontent.com/1644496/85793019-7f748780-b788-11ea-812b-f8cccaa139ec.png)

configuration:
```yaml
      - entities:
          - aggregate_func: min
            entity: sensor.mitemp_bt_temperature
            index: 0
          - aggregate_func: max
            entity: sensor.mitemp_bt_temperature
            index: 0
        group_by: date
        hours_to_show: 720
        show:
          extrema: true
          legend: false
        type: 'custom:mini-graph-card'
      - entities:
          - aggregate_func: min
            entity: sensor.mitemp_bt_humidity
            index: 0
          - aggregate_func: max
            entity: sensor.mitemp_bt_humidity
            index: 0
        group_by: date
        hours_to_show: 720
        show:
          extrema: true
          legend: false
        type: 'custom:mini-graph-card'
```

info | info
-- | --
arch | x86_64
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 5.7.2-arch1-1
python_version | 3.7.7
timezone | Pacific/Auckland
version | 0.112.0b0
virtualenv | false
