### ISSUE TITLE
Colour thresholds show wrong line colour if data has not changed.

### ISSUE THREAD

**Issue by nathangreen06** [kalkih/mini-graph-card#391]
If the value of the graph has not changed for the longer than `hours_to_show`, then the line changes to a colour that does not match the threshold it is in.
![mini-graph-card](https://user-images.githubusercontent.com/16503836/86465582-d7cbfc00-bd29-11ea-9bdc-44f2e1e9bb2a.png)
^ left: graph with wrong colour, right: graph with correct colour.

Version: 0.9.3
Config for cards in screenshot:
```
- animate: true
  color_thresholds:
    - color: '#3689e6'
      value: 17
    - color: '#f9c440'
      value: 19
    - color: '#f37329'
      value: 21
    - color: '#c6262e'
      value: 23
    - color: '#910806'
      value: 25
  entities:
    - entity: sensor.study_temp_sensor
      name: Study
  hours_to_show: 24
  line_width: 10
  points_per_hour: 1
  show:
    icon: false
  tap_action:
    action: more-info
    entity: climate.study_radiator
  type: 'custom:mini-graph-card'

- animate: true
  color_thresholds:
    - color: '#3689e6'
      value: 17
    - color: '#f9c440'
      value: 19
    - color: '#f37329'
      value: 21
    - color: '#c6262e'
      value: 23
    - color: '#910806'
      value: 25
  entities:
    - entity: sensor.family_room_temp_sensor
      name: Family Room
  hours_to_show: 24
  line_width: 10
  points_per_hour: 1
  show:
    icon: false
  tap_action:
    action: more-info
    entity: climate.family_room_radiator
  type: 'custom:mini-graph-card'
```
