### ISSUE TITLE
Error: " Cannot read property 'setConfig' of undefined " 

### ISSUE THREAD

**Issue by MaxiStarling56** [kalkih/mini-graph-card#399]
# I keep getting the error " Cannot read property 'setConfig' of undefined "

## I tried installing via:
(I tried multiple time for each installation to reload browser without cache)
- HACS (tried last 2 versions: v0.9.4 - v0.9.3)
- js file from the latest GitHub release (v0.9.4)

### HACS version:
- Integration version -> 1.1.2
- Frontend version -> 202006281222
### HomeAssistant version:
- Supervisor -> 228
- System -> HassOS 4.11
- core -> 0.112.4
### Hardware:
- Raspberry pi 4 (4gb)

**Comment by MaxiStarling56** [comment]
# Closed this issue because there was no issue!

## What i did wrong:
In the documentation it's written: 
``` yaml
- type: custom:mini-graph-card
  entities:
   - sensor.illumination
```
but this does not works if you try to add it via the user interface edit in the front-end, this has worked for me:
``` yaml
type: custom:mini-graph-card
entities:
 - sensor.illumination
```
