### ISSUE TITLE
Wrong color shown when no activity

### ISSUE THREAD

**Issue by agneevX** [kalkih/mini-graph-card#406]
The card shows a wrong color (unspecified) when there is no activity. 

<img width="245" alt="image" src="https://user-images.githubusercontent.com/19761269/88473480-90591a00-cf3b-11ea-842c-9eaea0348b57.png">

```yaml
align_state: center
animate: true
color_thresholds:
  - color: '#ff0000'
    value: 95
  - color: '#ff8600'
    value: 97
  - color: '#04e700'
    value: 99
entities:
  - entity: sensor.internet_health
    state_adaptive_color: true
font_size: 105
hours_to_show: 1
icon: 'mdi:ethernet-cable'
line_width: 4
name: Internet
points_per_hour: 8
show:
  fill: false
  icon_adaptive_color: true
  labels: false
  name_adaptive_color: false
  points: false
style: |
  ha-card > div:nth-child(-n+2) {
    padding: 0 16px 0 16px !important
  }
  ha-card > .info {
    padding: 0 16px 0px 16px !important
  }
type: 'custom:mini-graph-card'
```
