### ISSUE TITLE
Chrome Issue with Non-Numeric Sensor, works in other browsers

### ISSUE THREAD

**Issue by kendrome** [kalkih/mini-graph-card#410]
I have the following basic card
```
  - type: custom:mini-graph-card
    hours_to_show: 168
    state_map:
      - value: "above_horizon"
        label: Day
      - value: "below_horizon"
        label: Night
    entities:
      - entity: sun.sun 
```
This works in Firefox, Edge, Safari and the official Android Home Assistant App, but does not work in Chrome on desktop or mobile.
Chrome:
![image](https://user-images.githubusercontent.com/4109239/88859693-d7efd800-d1bf-11ea-9d28-6dc20552382f.png)
Other:
![image](https://user-images.githubusercontent.com/4109239/88859729-ee962f00-d1bf-11ea-8eae-34d158210174.png)
