### ISSUE TITLE
Request: attribute variable

### ISSUE THREAD

**Issue by Krojack** [kalkih/mini-graph-card#411]
Few months back the [Entity Card](https://www.home-assistant.io/lovelace/entity/#attribute) had a new variable added called "attribute".  I was wonder if this could be something added to the min-graph-card at some point. Something like the following:

```
  - entity: sensor.some_json_data
    attribute: anAttrValueFromEntity
```

**Comment by Twanislas** [comment]
Hi, I would love that as well.
For the time being i've been relying on creating manual sensors to be able to graph attributes : 
```yaml
sun_elevation:
  friendly_name: Sun elevation
  unit_of_measurement: °
  value_template: "{{ state_attr('sun.sun', 'elevation') }}"
```
I would love to be able to cleanup my settings...

**Comment by ktownsend-personal** [comment]
I would love this feature too. It is unfortunate that I have to create a bunch of template sensors to break out attribute values just so the charts can use them.

**Comment by firestrife23** [comment]
likewise

**Comment by Koma-Andrea** [comment]
Yep! must have! climate in general are complex sensors we need to template them in order to use those attributes

**Comment by akeslo** [comment]
+1 for this

**Comment by Koma-Andrea** [comment]
Looks like someone has written PR but it's there without comments...

**Comment by RomRider** [comment]
This would introduce quite some complexity into `mini-graph-card` as I've said in the PR.

I feel that creating a template sensor is the standard and easy way to achieve that. I don't think this should be handled in the card itself.

Do you have some thoughts @kalkih?

**Comment by kalkih** [comment]
Quoting myself from the PR

> Indeed, that has been my though as well, I've always pointed people towards template sensors when it comes to this particular feature request.
> I understand it would be a nice addition, less hassle setting it up, but it adds quite some additional logic and complexity to the card.
> Not sure if I feel like it's worth it when it already can be achieved in HA, will have to think about it.

Will have to think about it...

**Comment by ktownsend-personal** [comment]
I'm curious what the technical challenges are. I'm a developer by trade, so although I haven't (yet) had time to ramp up on what it takes to make cards for Lovelace, I'm interested in that kind of detail. On a related note, I've always found it strange that cards in Lovelace don't natively handle attributes. Is that a limitation of the Lovelace framework or the Home Assistant API that could be improved upon?

**Comment by DrSpaldo** [comment]
Hi, any tips on how to use the new release (I am using dev.3). Apologies if I have missed the instructions, this is what I am currently using and I am just getting the "NaN" message.

```
      - type: custom:mini-graph-card
        name: SERVER
        icon: mdi:server
        entities:
          - entity: binary_sensor.edgeos_interface_eth0
            attribute: "KBytes/ps (Received)"
```

**Comment by Krojack** [comment]
That attribute doesn't look like a valid one. Look up your entity in the Config > Entities and see what its attributes are.

Example from one of mine:
https://i.imgur.com/IWl6wTp.jpg

In this case, if I wanted to display the "Median" then I would use "median" as the attribute. Always convert to lower case and replace spaces with an underscore.

**Comment by DrSpaldo** [comment]
Thanks for the reply @Krojack. I’m pretty sure it’s one of them, see the attached screenshot and let me know what you think.. 
![BC025BD3-CC08-458C-A213-E529C135DB0E](https://user-images.githubusercontent.com/8526509/126884777-e2d6b8be-9df7-46d0-9619-fd1df2cb633b.jpeg)

**Comment by Krojack** [comment]
It just dawned on me, the best way to get the exact attribute name is to go to Developer Tools > States and filter by the entity ID you're dealing with. On the right column, you will see all the attribute names and their values. Just copy and paste the name of the one you want to use.

**Comment by DrSpaldo** [comment]
Isn't that what I have though?

**Comment by Krojack** [comment]
What you see in your screenshot isn't what the real attribute name it. You're seeing a clean easy to read and formatted version. The real attributes names can't have blank spaces. They can ONLY contain alphanumeric and underscore characters in them.

For example, "Last Changed" is would be used as "last_changed" in your yaml code.  "MAC" would be "mac".  Uppercase characters aren't even used.

**Comment by FeroX-Ron** [comment]
Hi,
i tried all to get attribute running, but still the same problem:
   bad indentation of a mapping entry at line 5, column 3:
      attribute: "
I need an attribute from the Homematic-CCU:
type: 'custom:mini-graph-card'
name: Aktueller Stromverbrauch
entities:
  - homematic.ccu3
    attribute: "

Hope someone had a solution, thanks.

**Comment by thecem** [comment]
try:

```
entities:
  - entity: climate.wohnzimmer
    attribute: current_temperature
    unit: °C
    state_adaptive_color: true
  - entity: climate.wohnzimmer
    attribute: current_humidity
    unit: '%'
    show_state: true
    state_adaptive_color: true
```

**Comment by spencerthayer** [comment]
I would love to get the value of the description, such as "good," from the AirNow integration.

```yaml
type: custom:mini-graph-card
name: AIR QUALITY
entities:
  - entity: sensor.airnow_aqi
    attribute: description
    show_state: true
    state_adaptive_color: true
animate: true
line_width: 2
hours_to_show: 24
points_per_hour: 2
show:
  graph: line
  labels: true
  labels_secondary: true
  name_adaptive_color: false
  icon_adaptive_color: true
  average: true
  extrema: true
color_thresholds:
  - value: 0
    color: '#d6fffb'
  - value: 15
    color: '#00c853'
  - value: 51
    color: '#ffeb3b'
  - value: 101
    color: '#ff6f00'
  - value: 151
    color: '#ff3d00'
  - value: 201
    color: '#d500f9'
  - value: 301
    color: '#ab025b'
  - value: 500
    color: '#770a3f'
```
