### ISSUE TITLE
Card not showing at all

### ISSUE THREAD

**Issue by bobvmierlo** [kalkih/mini-graph-card#413]
The card is not showing at all.

```
No card type configured.
- type: 'custom:mini-graph-card'
  entities:
    - sensor.processor_use
    - sensor.synology_cpu_load_total
```
Installed through HACS, running 0.113.3 on HassOS 4.11

Using the latest Chrome browser, also tried clearing cache. And the js file is referenced correctly in the home assistant config.

**Comment by kalkih** [comment]
Remove the initial dash before type.

**Comment by theFork** [comment]
I have the same issue, without the dash:

```
type: 'custom:mini-graph-card'
entities:
  - sensor.nuc_cpu_temperature
  - sensor.owm_temperature
```
* Card installed manually
* HassOS 4.11
* Issue reproduced in Firefox and Chromium

**Comment by bobvmierlo** [comment]
For me it worked. Your indentation is wrong for the other lines. Put 2 spaces in front of line 2 and the rest.

**Comment by theFork** [comment]
In the raw config editor, my playground-tab looks like that:

```
  - badges: []
    cards:
      - type: 'custom:mini-graph-card'
        entities:
          - sensor.nuc_cpu_temperature
          - sensor.owm_temperature
      - type: gauge
        entity: sensor.owm_temperature
        min: 0
        max: 100
    path: dev
    title: Dev
```
Looks good to me. When saving, there is no error due to indentation. Still I cannot see the card. It appears as if there is still an issue (?) I suggest to reopen.

**Comment by bobvmierlo** [comment]
Why not just add the card from the UI with the correct indentations? That worked fine for me.
Anyway, if this is still an issue for you it's not the same as mine. While mine has been solved, I would suggest you open a new issue.

FYI: This is my raw config.
```
  - badges: []
    cards:
      - entities:
          - sensor.processor_use
          - sensor.synology_cpu_load_total
          - sensor.nucplex_intel_core_i5_8259u_load_cpu_total
        hours_to_show: 168
        show:
          fill: false
        type: 'custom:mini-graph-card'
    icon: 'mdi:desktop-tower'
    path: hardware
    title: Hardware
```
