### ISSUE TITLE
NaN value with template sensor

### ISSUE THREAD

**Issue by Sjeff** [kalkih/mini-graph-card#42]
With one of my template sensors im getting a NaN message instead of the sensor value.

(left mini graph card and right the default sensor card)
![image](https://user-images.githubusercontent.com/11430228/52521725-a7d71100-2c7b-11e9-9344-deed8b29ebb4.png)

Code : 

```
          - type: custom:card-modder
            style: {border-radius: "20px", border: "solid 1px rgba(100,100,100,0.3)", overflow: hidden}
            card:
              type: custom:mini-graph-card
              icon: mdi:fire
              name: Gas
              height: 100
              align_header: default
              align_icon: right
              align_state: center
              show:
                graph: false
                fill: true
                points: false
                legend: false
              entities: sensor.gas

          - type: custom:card-modder
            style: {border-radius: "20px", border: "solid 1px rgba(100,100,100,0.3)", overflow: hidden}
            card:
              type: sensor
              entity: sensor.gas
              icon: mdi:fire
              name: Gas
              graph: none
```

Template sensor : 
```
- platform: mqtt
  name: "Gas"
  state_topic: "dsmr/json"
  unit_of_measurement: 'm3'
  force_update: true
  value_template: "{{ (value_json.extra_device_delivered | float) | replace('.',',') }}"
```
