### ISSUE TITLE
HA 0.113.3 - Custom element doesnt exist: mini-graph-card

### ISSUE THREAD

**Issue by T2evh** [kalkih/mini-graph-card#421]
I've just upgraded to version 0.113.3 of HA and the mini-graph-card has stopped working. I have not changed Lovelace YAML or location of any files. Other custom elements continue to work ok.

Anyone suggestions on a fix?  

Thanks

**Comment by egelmex** [comment]
I am having the same issue, this is what I see in the browser console.
![image](https://user-images.githubusercontent.com/474014/90117075-4e5b1100-dd4e-11ea-8b11-13eb5d7b9d9e.png)

**Comment by russellhq** [comment]
I'm having the same issue as well

**Comment by koehntopp** [comment]
same issue here, doesn't even appear in HACS search anymore, but says it's installed

**Comment by T2evh** [comment]
I tried a reinstall - didn't fix. Moved to a different directory and that didn't fix.
I have other custom cards which work fine, so odd why it doesn't even see this.

**Comment by russellhq** [comment]
I followed this comment and it fixed my issue:
[https://community.home-assistant.io/t/lovelace-mini-media-player/68459/1793](https://community.home-assistant.io/t/lovelace-mini-media-player/68459/1793)

Changed my code from:
```
- type: 'custom:mini-graph-card'
  entities:
    - sensor.hall_temperature
    - sensor.0x00158d000543baa7_temperature
    - sensor.0x00158d000543b22b_temperature
    - sensor.0x00158d0005441294_temperature
    - sensor.0x00158d00051e3a78_temperature
  show:
    icon: false
    name: false
    state: false
```

To

```
type: 'custom:mini-graph-card'
entities:
  - sensor.hall_temperature
  - sensor.0x00158d000543baa7_temperature
  - sensor.0x00158d000543b22b_temperature
  - sensor.0x00158d0005441294_temperature
  - sensor.0x00158d00051e3a78_temperature
show:
  icon: false
  name: false
  state: false
```

And that fixed the problem
