### ISSUE TITLE
Aggregate max combined with group by date always shows a 0 value for the first group

### ISSUE THREAD

**Issue by KevinD-87** [kalkih/mini-graph-card#429]
I have the following configuration to show the total kWh consumption per day based on the max value of a sensor for that day. The first day always shows as value 0, even when changing the hours to show to 144 (6 days), 120 (5 days), ...
```
aggregate_func: max
entities:
  - color: orange
    entity: sensor.todays_consumption
group_by: date
hours_to_show: 168
icon: 'mdi:flash'
show:
  graph: bar
  icon: false
  labels: true
  name: false
type: 'custom:mini-graph-card'
```
Todays consumption is a calculated sensor based on the difference between an input_number, which gets set through an automation to the value of the total consumption sensor at 23:59 each day (sensor source: Shelly 3EM), and the current total consumption sensor.

7 days (hours_to_show: 168)
![image](https://user-images.githubusercontent.com/9356821/91464168-8c971b00-e88c-11ea-8b16-31a0a20506fe.png)
![image](https://user-images.githubusercontent.com/9356821/91464884-5c9c4780-e88d-11ea-970d-082d46813c76.png)

6 days (hours_to_show: 144)
![image](https://user-images.githubusercontent.com/9356821/91465236-d46a7200-e88d-11ea-844f-a5afb152fd52.png)

See for 7 days, the value for last Saturday is set to 9 kWh, whereas for 6 days it shows up as 0 kWh.
