### ISSUE TITLE
How to change color of lines in new lovelace editor?

### ISSUE THREAD

**Issue by YamiFrankc** [kalkih/mini-graph-card#43]
```
cards:
  - entities:
      - entity: light.luz_bano
      - entity: binary_sensor.movimiento_bano
      - entity: binary_sensor.0x00158d0002d43d30_occupancy_3
      - entity: binary_sensor.presencia_bano
    type: entities
  - entities:
      - entity: sensor.0x00158d0002726443_temperature_2
      - entity: sensor.0x00158d0002726443_humidity_2
    type: 'custom:mini-graph-card'
    line_color: purple
    name: Temperatura / Humedad
    points: hover
    location_state: center
    hours_to_show: 72
type: vertical-stack
```

Hello, this is the code that I have for a part of my lovelace config.. 
As it is right now it will make the temperature graph in a purple color, but if I add more `line_color: ` lines under the one I already have it doesnt work. How can I change the colors of all of my sensors?
Thanks

**Comment by kalkih** [comment]
Hi, the `line_color` option takes either a string or a list of strings, similar to the entities option. You can't define several `line_color` as they will overwrite each other.

Also, the `points` option should be under the `show` option, and the parameter `hover` is default so you could skip it if you'd like.

`location_state` should actually be `align_state`, I had a typo in the readme for a short time.

Try this:
```
  - entities:
      - entity: sensor.0x00158d0002726443_temperature_2
      - entity: sensor.0x00158d0002726443_humidity_2
    type: 'custom:mini-graph-card'
    line_color:
      - purple
      - teal
      - pink
    name: Temperatura / Humedad
    show:
      points: hover
    align_state: center
    hours_to_show: 72
```

**Comment by kalkih** [comment]
@YamiFrankc Did you get it to work?

With the latest version you can also do:
```yaml
  ...
  entities:
    - entity: sensor.0x00158d0002726443_temperature_2
      color: purple
    - entity: sensor.0x00158d0002726443_humidity_2
      color: teal
  ...
```

**Comment by YamiFrankc** [comment]
Yes it worked.
Sorry I've been busy and forgot to answer.
I think I will be going with the second example you gave because it make it easier to know what color is what whwn looking at the config :)
Cool!

**Comment by kalkih** [comment]
Great, closing this issue then, thanks!

**Comment by scargill** [comment]
That second option - color under entity no longer works.

**Comment by ildar170975** [comment]
> That second option - color under entity no longer works.

It works:
![image](https://github.com/user-attachments/assets/c4280e5e-8c9c-4c44-9b90-719e495c09a3)
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_co2
    color: red
  - entity: sensor.xiaomi_cg_2_co2
    color: cyan
```
Using [https://github.com/kalkih/mini-graph-card/releases/tag/v0.12.2-dev.2](v0.12.2-dev.2) - and it works at least since the version when I started using this card (~October 2020).
