### ISSUE TITLE
Utility Meter Issue

### ISSUE THREAD

**Issue by totalitarian** [kalkih/mini-graph-card#430]
Just tried to chart the daily usage of my utility meter. Not sure if it looks correct. Admittedly I only have 2 days worth of data. Should I be pointing the graph at my utility meter `sensor.electricity_daily_khw1` or the source sensor `sensor.electricity_energy_kwh` ?

```
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.electricity_daily_khw1
name: Energy consumption
hours_to_show: 168
aggregate_func: max
group_by: date
show:
  graph: bar
```

```
utility_meter:
  electricity_hourly_khw1:
    source: sensor.electricity_energy_kwh
    cycle: hourly
  electricity_daily_khw1:
    source: sensor.electricity_energy_kwh
    cycle: daily
  electricity_weekly_khw1:
    source: sensor.electricity_energy_kwh
    cycle: weekly
  electricity_monthly_khw1:
    source: sensor.electricity_energy_kwh
    cycle: monthly
  electricity_yearly_khw1:
    source: sensor.electricity_energy_kwh
    cycle: yearly
```

![image](https://user-images.githubusercontent.com/2385696/91504444-0ba84580-e8c5-11ea-94f8-5a2bb449eb59.png)
