### ISSUE TITLE
Difference between Google Chrome and Edge.

### ISSUE THREAD

**Issue by tnagels** [kalkih/mini-graph-card#431]
When I display the same graph on Google Chrome and Microsoft Edge I get different results. Not only is there a difference in the historic data shown, but there is also a difference in the calculated average value. Screenshot is of the graphs in the two browsers (left is Edge) at the same time on the same computer. You see that in Edge the left peaks are missing, however somehow the average is higher...

![2020-08-28 17_47_23-Window](https://user-images.githubusercontent.com/22787213/91587390-ff6cc880-e956-11ea-8ab9-2c836e8d9e1e.png)

The card was installed using HACS, and the configuration is as shown below:

```
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.solaredge_ac_power
    aggregate_func: max
    name: Maximum
    color: green
  - entity: sensor.solaredge_ac_power
    aggregate_func: min
    name: Minimum
    color: red
  - entity: sensor.solaredge_ac_power
    aggregate_func: avg
    name: Gemiddeld
    color: orange
name: Opbrengs zonnepanelen
hours_to_show: 24
points_per_hour: 2
show:
  average: true
  extrema: true
  graph: line
  points: false
```
