### ISSUE TITLE
label for second value show 0

### ISSUE THREAD

**Issue by rchovan** [kalkih/mini-graph-card#432]
Hi, 
label for second value is not updated and show 0, even after restart. As you can see on this image, when I hover mouse on second value, you can see that it is not 0.

![image](https://user-images.githubusercontent.com/6713920/91605840-67300d00-e971-11ea-800f-e7fc06120c3b.png)

this is my code :
```
entities:
  - entity: sensor.covid19_sk_active
    index: 0
    name: Active cases
  - entity: sensor.covid19_sk_daily
    index: 1
    name: Daily cases
hour24: true
hours_to_show: 180
name: Covid19 Slovakia (Worldometer)
points_per_hour: 0.5
show:
  labels: true
type: 'custom:mini-graph-card'
```
