### ISSUE TITLE
Feature request : Show Current state with current color defined in color threshold

### ISSUE THREAD

**Issue by xvolte** [kalkih/mini-graph-card#434]
Hi there,

it would be great if there was an option to put the color on the current state value.

I tried show_indicator but nothing shows ... (maybe because i got only one sensor in the graph)

here is my example:
![featrequ](https://user-images.githubusercontent.com/21142611/91666910-0df6e380-eb01-11ea-9cc2-bdede1ada928.png)

so if the green square could either represent the current color value or if we could change background or font color to the current used color, when colors are defined in color threshold : 

```
color_thresholds:
  - color: '#0000FF'
    value: 0
  - color: '#66CDAA'
    value: 17
  - color: '#00FFFF'
    value: 19
  - color: '#00FF00'
    value: 22
  - color: '#FFFF00'
    value: 24
  - color: '#FF4500'
    value: 26
  - color: '#FF0000'
    value: 28
entities:
  - sensor.mi_temperature
hour24: true
show:
  extrema: true
  labels: true
  points: true
type: 'custom:mini-graph-card'
```

and
```
entities:
  - sensor.mi_humidity
hour24: true
color_thresholds:
  - color: '#FF0000'
    value: 0
  - color: '#FF4500'
    value: 35
  - color: '#00FFFF'
    value: 45
  - color: '#FFFF00'
    value: 55
  - color: '#FF4500'
    value: 62
  - color: '#FF0000'
    value: 70
show:
  extrema: true
  labels: true
  points: true
type: 'custom:mini-graph-card'
```
