### ISSUE TITLE
Javascript templating

### ISSUE THREAD

**Issue by agneevX** [kalkih/mini-graph-card#442]
Hello,

Can you add support for Javascript templating? I thought something like this would work...

```yaml
entities:
  - color: '#F5BB41'
    entity: sensor.radarr_upcoming
    name: Upcoming
    state_adaptive_color: true
font_size: 90
font_size_header: 13
icon: 'mdi:movie-search'
unit: >
  [[[ 
    if (states['radarr_upcoming'].state == '1')
      return "Movie";
    else
      return "Movies";
  ]]]
show:
  graph: false
  icon_adaptive_color: true
  name_adaptive_color: true
type: 'custom:mini-graph-card'
```
