### ISSUE TITLE
Aggregate delta combined with group by date always shows a 0 value for the first group

### ISSUE THREAD

**Issue by amfetamin-pn** [kalkih/mini-graph-card#445]
```
aggregate_func: delta
animate: true
color_thresholds:
  - color: '#d34a00'
    value: 50
  - color: '#d38900'
    value: 100
  - color: '#d3d300'
    value: 150
  - color: '#78d300'
    value: 200
entities:
  - entity: sensor.home_cold_water_counter_sensor1
group_by: date
hours_to_show: 192
icon: 'mdi:snowflake'
name: Потребление холодной воды
show:
  graph: bar
  icon_adaptive_color: true
  labels: true
type: 'custom:mini-graph-card'

```
![image](https://user-images.githubusercontent.com/59441964/93025638-24746300-f608-11ea-8603-b19b52eb2670.png)
