### ISSUE TITLE
Feature request: possibility to move icon to line with state or fit all in single line

### ISSUE THREAD

**Issue by cadavre** [kalkih/mini-graph-card#449]
There are plenty of moments when graph is having enough width to display all three elements in single line:
1. icon
2. name
3. current state

But right now there's now way to configure it:
<img width="488" alt="Zrzut ekranu 2020-09-23 o 16 09 43" src="https://user-images.githubusercontent.com/461796/94024581-e3bedb80-fdb7-11ea-9fc8-5a30b9255663.png">

It would be great if, for example, setting
```
show:
  name: false
```
Would move icon to row with state – there's plenty of space for that.

What I'm trying to achieve is actually squeezing charts vertically to fit more data in single context.

In old TIleboard I had this:

<img width="336" alt="Zrzut ekranu 2020-09-23 o 16 16 05" src="https://user-images.githubusercontent.com/461796/94024782-179a0100-fdb8-11ea-855d-fbeae2c317a0.png">

In this example chart is taking 2/3 space and the rest 1/3. Currently there's no way to fit it like this with mini-graph-card.

BTW Awesome work with this card!

**Comment by kalkih** [comment]
Yes, good idea, kinda related to https://github.com/kalkih/mini-graph-card/issues/355.

**Comment by sibbl** [comment]
If you're using [card-mod](https://github.com/thomasloven/lovelace-card-mod), the following code might be helpful. 

```yaml
card_mod:
  style: |
    ha-card .header {
      display: none;
    }
    ha-card .state {
      width: 100%;
    }
    ha-card .state::before {
      content: 'Temperatur';
      flex: 1 1 0%;
      font-weight: 500;
      font-size: 16px;
      color: var(--secondary-text-color)
    }
    ha-card .state__uom { 
      flex: 0 0 auto;
    }
```

Huge disadvantages over a built-in feature: you need to manually set the `content` value via CSS and it will possibly break in future versions. Using this with mini-graph-card version 0.10.0, I could achieve the following compact layout for my e-ink Kindle display:

![image](https://user-images.githubusercontent.com/866535/115966958-3c15b180-a530-11eb-9ada-e3a64f9ad998.png)
