### ISSUE TITLE
wrong timespan when group_by: hour

### ISSUE THREAD

**Issue by vistalba** [kalkih/mini-graph-card#451]
I use a bar graph to display rain by date and hour.
Graph does work fine if `group_by: date` is configured.

If I configure `group_by: hour` the graph shows a bar for example 22:15-23:59.

![image](https://user-images.githubusercontent.com/12324196/94163822-978f9c00-fe88-11ea-84bb-2c9d9db4a072.png)

The used sensor `sensor.hourly_rain` contains valus that are resetted by `utility_meter` every hour. (like a power meter).
So I select the `max` value for each hour and want to show a bar for every hour the last 7 days.

Card config looks like this:

```
type: 'custom:mini-graph-card'
name: Rain (7 days)
bar_spacing: 0
entities:
  - aggregate_func: max
    color: '#3498db'
    entity: sensor.hourly_rain
    index: 1
    name: Rain
    show_graph: true
group: false
height: 150
hour24: true
hours_to_show: 168
point_per_hour: 1
group_by: hour
lower_bound: 0
line_width: 0
show:
  average: true
  extrema: true
  graph: bar
  labels: true
```

If I select just to display last 72h (instead of 168h) the bars are correct. So I think the problem is that there is a limit of bars that can be shown next to each other? Is there a way to solve this? Otherwise we should at least place some hint in documentation that there is a limitation.
