### ISSUE TITLE
Horizontal background color by range

### ISSUE THREAD

**Issue by JasonSwindle** [kalkih/mini-graph-card#454]
Howdy,

I wish to have horizontal background colors by range like this:

![image](https://user-images.githubusercontent.com/1776251/94353032-16740880-0032-11eb-9372-3a00dc68ff8c.png)

I can currently do something like this:

![image](https://user-images.githubusercontent.com/1776251/94353054-4f13e200-0032-11eb-9565-faeeea01c164.png)

Is this possible now?

AQI Line code:

```yaml
type: 'custom:mini-graph-card'
name: Air Quality Index - Bedroom
entities:
  - sensor.m5stack_aq_001_pm_2_5_aqi
hours_to_show: 48
points_per_hour: 60
show:
  labels: true
color_thresholds:
  - value: 50
    color: green
  - value: 100
    color: yellow
  - value: 150
    color: orange
  - value: 200
    color: red
  - value: 300
    color: purple
  - value: 500
    color: maroon
```
