### ISSUE TITLE
Custom theme variables don't work with color thresholds

### ISSUE THREAD

**Issue by agneevX** [kalkih/mini-graph-card#456]
I have a few custom theme variables set in my theme:

```yaml
  green-color: "#39FF14"
  yellow-color: "#FFFF00"
  red-color: "#FF0000"
```

When added to color thresholds with/without single quotes, the correct color doesn't show...

```yaml
color_thresholds:
  - value: 94
    color: var(--red-color)
  - value: 96
    color: var(--yellow-color)
  - value: 98
    color: var(--green-color)
```

However, if I don't use color thresholds, and instead just add `color:` under the entity, it works without any issue.
