### ISSUE TITLE
Unable to display entity attributes

### ISSUE THREAD

**Issue by LorenzoVasi** [kalkih/mini-graph-card#463]
Hi,
I'm new into this platform and I would ask if it was possible to add the possibility of display the entity attributes

Thank u so much (it isn't a very issues but i don't know where I could write this message :( )

**Comment by kalkih** [comment]
Hello and welcome 😃 
Yes, you can setup a [template sensor](https://www.home-assistant.io/integrations/template/) for the attribute you want to graph, and then use that newly created template sensor entity in the mini-graph-card.

See examples [here](https://www.home-assistant.io/integrations/template/)
```yaml
sensor:
  - platform: template
    sensors:
      some_attribute_name:
        friendly_name: "Some name"
        value_template: "{{ state_attr('domain.entity_name', 'the_attribute') }}"
```
