### ISSUE TITLE
Graphs take extremely long time to show

### ISSUE THREAD

**Issue by AivarasAukselis** [kalkih/mini-graph-card#465]
I have an issue for quite some time. My graphs take an extremely long time to load. This issue appears on all of my devices with different browsers. See the gif below:

![gif5](https://user-images.githubusercontent.com/46624640/95076315-f0292980-0711-11eb-90a5-b6d9c6770138.gif)
 
Here is the configuration I use for one panel:

```
cards:
  - cards:
      - entities:
          - entity: sensor.bedroom_temperature_avg
            index: 0
            name: Bedroom
          - entity: sensor.0x00158d00033b0e50_temperature
            index: 1
            name: Hall
        hours_to_show: 24
        icon: 'mdi:thermometer'
        line_width: 4
        name: Temperature
        points_per_hour: 3
        show:
          fill: false
          legend: false
        smoothing: true
        type: 'custom:mini-graph-card'
        update_interval: 30
      - entities:
          - entity: sensor.bedroom_humidity_avg
            index: 2
            name: Bedroom
          - entity: sensor.0x00158d00033b0e50_humidity
            index: 1
            name: Hall
          - entity: sensor.bedroom_humidity_avg
            index: 2
            name: Bedroom
        hours_to_show: 24
        icon: 'mdi:water-percent'
        line_width: 4
        name: Humidity
        points_per_hour: 3
        show:
          fill: false
          legend: false
        smoothing: true
        type: 'custom:mini-graph-card'
        update_interval: 30
    type: horizontal-stack
title: Inside Conditions
type: vertical-stack
```

Does anyone know what can cause this?
