### ISSUE TITLE
Strange behavior of color_thresholds

### ISSUE THREAD

**Issue by jsiemek** [kalkih/mini-graph-card#478]
I have 4 nearly identical graphs. so of them behave as expected, sone not.

What I'd like to have:
![mini-graph-card-1](https://user-images.githubusercontent.com/36767404/96724379-0f7db300-13b0-11eb-98ea-31423c77e27c.png)

```
  - color_thresholds:
      - color: orange
        value: 25
      - color: green
        value: 20
      - color: blue
        value: 15
    entities:
      - sensor.ola_temperature
      - color: indigo
        entity: sensor.sy_heating_temperature
        show_fill: false
        show_legend: false
      - color: gray
        entity: sensor.nighttime
        name: Night
        show_legend: false
        show_line: false
        show_points: false
        y_axis: secondary
      - color: red
        entity: sensor.sy_current_heating_state
        name: Heating
        show_legend: false
        show_line: false
        show_points: false
        y_axis: secondary
      - color: blue
        entity: sensor.sypialnia_okno_otwarte
        name: Okno Otwarte
        show_legend: false
        show_line: false
        show_points: false
        y_axis: secondary
    hours_to_show: 24
    line_color: blue
    line_width: 2
    name: Temp Sypialnia
    points_per_hour: 1
    height: 200
    type: 'custom:mini-graph-card'
```

If I add another sensor to it, it still works:
![mini-graph-card-2](https://user-images.githubusercontent.com/36767404/96724511-32a86280-13b0-11eb-9c52-80a971227e68.png)

```
   - color_thresholds:
      - color: orange
        value: 25
      - color: green
        value: 20
      - color: blue
        value: 15
    entities:
      - sensor.ola_temperature
      - sensor.sypialnia_temperature
      - color: indigo
        entity: sensor.sy_heating_temperature
        show_fill: false
        show_legend: false
      - color: gray
        entity: sensor.nighttime
        name: Night
        show_legend: false
        show_line: false
        show_points: false
        y_axis: secondary
      - color: red
        entity: sensor.sy_current_heating_state
        name: Heating
        show_legend: false
        show_line: false
        show_points: false
        y_axis: secondary
      - color: blue
        entity: sensor.sypialnia_okno_otwarte
        name: Okno Otwarte
        show_legend: false
        show_line: false
        show_points: false
        y_axis: secondary
    hours_to_show: 24
    line_color: blue
    line_width: 2
    name: Temp Sypialnia
    points_per_hour: 1
    height: 200
    type: 'custom:mini-graph-card'
```

But if I remove unneeded sensor, it shows as this:
![mini-graph-card-3](https://user-images.githubusercontent.com/36767404/96725068-cb3ee280-13b0-11eb-9eac-3dc75b9e722a.png)

```
  - color_thresholds:
      - color: orange
        value: 25
      - color: green
        value: 20
      - color: blue
        value: 15
    entities:
      - sensor.sypialnia_temperature
      - color: indigo
        entity: sensor.sy_heating_temperature
        show_fill: false
        show_legend: false
      - color: gray
        entity: sensor.nighttime
        name: Night
        show_legend: false
        show_line: false
        show_points: false
        y_axis: secondary
      - color: red
        entity: sensor.sy_current_heating_state
        name: Heating
        show_legend: false
        show_line: false
        show_points: false
        y_axis: secondary
      - color: blue
        entity: sensor.sypialnia_okno_otwarte
        name: Okno Otwarte
        show_legend: false
        show_line: false
        show_points: false
        y_axis: secondary
    hours_to_show: 24
    line_color: blue
    line_width: 2
    name: Temp Sypialnia
    points_per_hour: 1
    height: 200
    type: 'custom:mini-graph-card'
```

Any idea what this might trigger?
