### ISSUE TITLE
Bar chart continues with previous value if currently no value is available

### ISSUE THREAD

**Issue by eloo** [kalkih/mini-graph-card#481]
Hi,

i'm currently creating a bar graph with daily metrics. 
So one bar per day with the last value. But some value are not available at the start of the day..
I would expect that the bar chart then does not show any bar for this day till the value is available. 
But sadly it just copies the previous value for the chart. In the legend i see NaN as expected.

Here is my graph card 
```
type: 'custom:mini-graph-card'
entities:
  - sensor.daily_sensor
name: Daily_sensor
hours_to_show: 240
aggregate_func: last
lower_bound: 0
upper_bound: 200
hour24: true
icon: none
show:
  labels: false
  graph: bar
group_by: date
color_thresholds:
  - value: 0
    color: '#32CD32'
  - value: 35
    color: '#FFD700'
  - value: 50
    color: '#FF0000'
  - value: 100
    color: '#660000'
```
![image](https://user-images.githubusercontent.com/2631895/97406855-236a6d00-18fa-11eb-8b82-e9e1a6961f90.png)

Also i hover over the current bar (where no value is available) it shows the value of the day before
![image](https://user-images.githubusercontent.com/2631895/97406947-439a2c00-18fa-11eb-94ff-a3ac1abd4613.png)

Do you have any ideas how i can make the graph not showing a bar if the value is not yet available?

Thanks
