### ISSUE TITLE
[Question] Can I show a graph with data from today (00:00 - now) only?

### ISSUE THREAD

**Issue by Olliek95** [kalkih/mini-graph-card#486]
Is it possible to show only data from today, starting at 00:00?
I've been looking all over for this feature, but I am unable to find anything related.

There are other questions regarding this, but they only mention 1 bar per day in a bar chart.
I'd like to show a regular graph, but only with data from today, starting at 00:00 (so not the last 24 hours).

Currently I'm seeing this (with the option; hours_to_show set to 24 hours):
![image](https://user-images.githubusercontent.com/5971963/98123534-45439100-1eb2-11eb-98b3-2db840c513b1.png)

I'd however like to only show the marked data:
![image](https://user-images.githubusercontent.com/5971963/98123619-62785f80-1eb2-11eb-8687-f7c5df743905.png)

**Comment by thejonesyboy** [comment]
Can we set `hours_to_show = 24` and then trick the renderer into thinking the time is always currently midnight tonight?

My graph currently looks like this at 9:45am:
![image](https://user-images.githubusercontent.com/885571/105434587-cda62680-5c96-11eb-8566-8b9fcdeb6959.png)

But hoping to acheive something like this (same data as above from inverter dashboard):
![image](https://user-images.githubusercontent.com/885571/105434743-1c53c080-5c97-11eb-8875-ddb8e66a0b73.png)

**Comment by thejonesyboy** [comment]
code FYI:
```
type: 'custom:mini-graph-card'
name: Solar Power (9 hours)
icon: 'mdi:weather-sunny'
points_per_hour: 10
line_width: 3
hours_to_show: 9
entities:
  - entity: sensor.power_pv_in
    name: Solar
    color: green
  - entity: sensor.power_consumption
    name: Usage
    color: red
  - entity: sensor.power_pv_in
    name: Solar
    color: green
    show_points: false
    show_legend: false
  - entity: binary_sensor.night
    color: gray
    name: Night
    show_line: false
    show_points: false
    show_legend: false
    y_axis: secondary
```
