### ISSUE TITLE
show_state: false wont work for the first entity

### ISSUE THREAD

**Issue by bachy** [kalkih/mini-graph-card#489]
like this one
- entity: sensor.temp_dixhuit will show the state, i would not

```yaml
type: 'custom:mini-graph-card'
hours_to_show: 168
points_per_hour: 0.25
name: Sdb rdc
icon: 'mdi:shower-head'
entities:
  - entity: sensor.temp_dixhuit
    name: 18°C
    color: dimgrey
    show_points: false
    fixed_value: true
    show_indicator: false
    show_fill: false
    show_legend: false
    show_state: false
  - entity: sensor.lumi_lumi_weather_a52d8704_temperature
    name: Temp
    show_state: true
    state_adaptive_color: true
    color: darkorange
  - entity: sensor.lumi_lumi_weather_a52d8704_humidity
    name: Humidity
    y_axis: secondary
    show_state: true
    state_adaptive_color: true
    color: lightseagreen
show:
  labels: true
  labels_secondary: true
  legend: false
  fill: false
line_width: 2
```

**Comment by bojanpotocnik** [comment]
I can confirm that. I moved entity on the first place to make its line appear as "Behind all", but that causes its state impossible to disable
```yaml
type: 'custom:mini-graph-card'
name: Box
hours_to_show: 24
points_per_hour: 12
line_width: 2
hour24: true
smoothing: true
decimals: 1
entities:
  - entity: sensor.aqara_temperature_humidity_and_pressure_sensor_wsdcgq11lm_humidity
    name: RH in
    show_state: false
    y_axis: secondary
    color: lightgray
  - entity: >-
      sensor.aqara_temperature_humidity_and_pressure_sensor_wsdcgq11lm_temperature
    name: T in
    show_state: true
    show_indicator: true
    color: red
  - entity: sensor.outside_temperature
    name: T out
    show_state: true
    show_indicator: true
    color: blue
show:
  icon: false
  fill: false
  labels: true
  labels_secondary: hover
```
![image](https://user-images.githubusercontent.com/4901762/101099791-b36c9800-35c5-11eb-92c2-b09f63feabee.png)
If I place it on any other place, `show_state: false` works as expected
![image](https://user-images.githubusercontent.com/4901762/101099874-dd25bf00-35c5-11eb-9a9e-8f1961480573.png)
however in this case `show_indicator: true` does not show for first 2 entities.
