### ISSUE TITLE
Entity State driven Icons

### ISSUE THREAD

**Issue by SeLLeRoNe** [kalkih/mini-graph-card#50]
As suggeste on the Cmmunity site, it would be very usefl to be able to define icons based on status and threshold.

This makes sense for single entity, but might be adapted when multiple entities are present with the condition that a "main" one is defined (the one that define the bigger number, so I guess this can be another FR for that to be configurable :) )

This might require to change the newrly introduced color_threshold to become only threshold (just for clarity).
This way, you can specify a specific icon on a per state.

The original idea came to my mind because it would have been nice to have the thermometer icon to change based on the temperature (I tested with customizations without success, probably due to some darksky sensor limitations, there is an open issue for that, apparently was working in the past).

Cheers
Andrea

**Comment by kalkih** [comment]
@SeLLeRoNe You should now be able to achieve this with the help of @iantrich new awesome config template card
https://github.com/custom-cards/config-template-card

**Comment by SeLLeRoNe** [comment]
Yep I am already working on it! 🔝 
I will test it and report in the community thread with my findings ;)

Thanks!
Andrea

**Comment by kalkih** [comment]
Cool! 👍 
You won't be able to change the color of the icon though, might add an option to have the icon color change with the color threshold, and the same for the state as requested here: #67

**Comment by kalkih** [comment]
@SeLLeRoNe Did you get it to work with the template card?

Adaptive icon color is now available in the [latest release](https://github.com/kalkih/mini-graph-card/releases/tag/v0.3.1) with the new `icon_adaptive_color` option in the `show` option object.

**Comment by SeLLeRoNe** [comment]
Hi @kalkih , unfortunately no.

Last time I tried the extensa data where blinking, the plugin creator said he expected something like that but  as far as I know there is no fix yet.

**Comment by iantrich** [comment]
@SeLLeRoNe 
Resolved in [config-template-card 1.0.3](https://github.com/custom-cards/config-template-card/releases/tag/1.0.3)

**Comment by SeLLeRoNe** [comment]
Thanks @iantrich !!!
@kalkih  what should I set to prevent the update?

**Comment by SeLLeRoNe** [comment]
@kalkih the icon/name adaptive color are based only on threshold or also on the current entity color?

**Comment by iantrich** [comment]
@SeLLeRoNe how often are you polling temperature data? Maybe look into polling it less often, e.g. 5 minutes, and using that still as the entity to watch.

**Comment by SeLLeRoNe** [comment]
I didn't set anything custom, so far is the dark_sky sensor.

I tried to put the darksky sensor and it is not blinking, so everything is cool on that point of view :)

Just posted on the community forum something related the borders when I add in your plugin 

Thanks a lot for your work :)

**Comment by kalkih** [comment]
> @kalkih the icon/name adaptive color are based only on threshold or also on the current entity color?

It's based on the color of the entity, so if using thresholds it's based on the threshold color, if not -> entity line/bar color.

**Comment by SeLLeRoNe** [comment]
Cool!! 👍 
Then it is not working for me ^^

**Comment by kalkih** [comment]
What does your config look like?

**Comment by SeLLeRoNe** [comment]
Sure thing as usual :)

Give 2 mins

**Comment by SeLLeRoNe** [comment]
Now that I think about it, can it be because the graph is hidden?

![image](https://user-images.githubusercontent.com/9599441/54625116-8f21fe00-4a66-11e9-8738-5be3c8d63646.png)


```
          - type: custom:vertical-stack-in-card
            cards:
              - type: horizontal-stack
                cards:
                  - type: custom:config-template-card
                    entities:
                      - sensor.dark_sky_temperature
                    config:
                      type: custom:mini-graph-card
                      name: Outside
                      icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                      name_adaptive_color: true
                      icon_adaptive_color: true
                      more_info: false
                      height: 150
                      line_width: 4
                      hours_to_show: 24
                      points_per_hour: 0.50
                      group: false
                      hour24: true
                      animate: true
                      decimals: 1
                      align_state: center
                      show:
                        name: true
                        icon: true
                        state: true
                        graph: false
                        fill: false
                        points: false
                        legend: false
                        extrema: true
                        labels: false
                      entities:
                        - entity: sensor.dark_sky_temperature
                          color: '#FF8000'
                          show_indicator: true
                  - type: custom:config-template-card
                    entities:
                      - sensor.dark_sky_temperature
                    config:
                      type: custom:mini-graph-card
                      name: Master Bedroom
                      icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                      name_adaptive_color: true
                      icon_adaptive_color: true
                      more_info: false
                      height: 150
                      line_width: 4
                      hours_to_show: 24
                      points_per_hour: 0.50
                      group: false
                      hour24: true
                      animate: true
                      decimals: 1
                      align_state: center
                      show:
                        name: true
                        icon: true
                        state: true
                        graph: false
                        fill: false
                        points: false
                        legend: false
                        extrema: true
                        labels: false
                      entities:
                        - entity: sensor.dark_sky_temperature
                          color: '#0080FF'
                          show_indicator: true
                  - type: custom:config-template-card
                    entities:
                      - sensor.dark_sky_temperature
                    config:
                      type: custom:mini-graph-card
                      name: Living Room
                      icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                      name_adaptive_color: true
                      icon_adaptive_color: true
                      more_info: false
                      height: 150
                      line_width: 4
                      hours_to_show: 24
                      points_per_hour: 0.50
                      group: false
                      hour24: true
                      animate: true
                      decimals: 1
                      align_state: center
                      show:
                        name: true
                        icon: true
                        state: true
                        graph: false
                        fill: false
                        points: false
                        legend: false
                        extrema: true
                        labels: false
                      entities:
                        - entity: sensor.dark_sky_temperature
                          color: '#FF3333'
                          show_indicator: true

```
