### ISSUE TITLE
Binary sensor not properly shown

### ISSUE THREAD

**Issue by 3v1n0** [kalkih/mini-graph-card#505]
I want to graph two different binary sensors, one for a door lock sensor, the other for my heating systeem

Now, using this code

```yaml
type: 'custom:mini-graph-card'
entities:
  - entity: binary_sensor.carajito_active
    name: State
    color: red
name: Heating
hours_to_show: 24
points_per_hour: 4
aggregate_func: max
line_width: 2
smoothing: false
state_map:
  - value: 'off'
    label: Waiting
  - value: 'on'
    label: Heating
```

I'm just getting a flat line, even though as you can see the sensor assumes on/off values properly

![immagine](https://user-images.githubusercontent.com/345675/100683534-d5bda600-3378-11eb-9a39-1c5cfcccdf58.png)

---

For the door sensor is even weirder, as I'm getting an inverse graph:

```yaml
type: 'custom:mini-graph-card'
entities:
  - entity: binary_sensor.tuya_door_sensor
name: Hold the door!
icon: 'mdi:door-closed'
hours_to_show: 24
points_per_hour: 4
update_interval: 30
aggregate_func: max
line_width: 2
smoothing: false
state_map:
  - value: 'on'
    label: Mooooar
  - value: 'off'
    label: Bravo Hodor!
```

![immagine](https://user-images.githubusercontent.com/345675/100683961-b1ae9480-3379-11eb-96bd-6cdd3c4bf4aa.png)
 
![immagine](https://user-images.githubusercontent.com/345675/100683974-b96e3900-3379-11eb-879c-579aaa7d2097.png)

So the values are exactly the opposite value.

Any hint?
