### ISSUE TITLE
Extrema View - improvments

### ISSUE THREAD

**Issue by SeLLeRoNe** [kalkih/mini-graph-card#51]
It would be nice on the Extrema View to be able to see one line per entity so to keep track of all min-max of each entity of the graph.

It would also be nice, when there are multiple entities but you want to see only one min/max, to be able to define which entity provides you the min and which the max.

Hope is clear enough, if not let me know :)

Cheers
Andrea

**Comment by kalkih** [comment]
I think we could add this as an optional option in the [entity object](https://github.com/kalkih/mini-graph-card#entities-object), similar to `show_state`.

Possibly something like this:
```yaml
entities:
  - sensor.temperature
  - entity: sensor.pressure
    name: Pressure
    show_state: true
    show_extrema: true #show this entity in the extrema
  - sensor.humidity
```

**Comment by SeLLeRoNe** [comment]
Yep I think that would make a lot of sense.

It might actually also work in another way:
```
extrema: true
entities:
  - sensor.temperature
  - entity: sensor.pressure
    name: Pressure
    show_state: true
    show_extrema: false #don't show this entity in the extrema but show all the rest
  - sensor.humidity
```

**Comment by ahd71** [comment]
When displaying data over more than 24h it shows only TIME of the extreme value, would be good to be able to format the value to show DATE+TIME (in 12/24h, and with different date formats, i.e yyyy-mm-dd, preferably from some system setting)

**Comment by kalkih** [comment]
> When displaying data over more than 24h it shows only TIME of the extreme value, would be good to be able to format the value to show DATE+TIME (in 12/24h, and with different date formats, i.e yyyy-mm-dd, preferably from some system setting)

The day / weekday will be displayed by default in the next release if the graph timeframe is longer than 24 hours d1bdfce64a285e9bf9ccb068a668ebef021cb954

The format will be (D ddd, HH:mm - HH:mm ) or corresponding am/pm format

**Comment by ahd71** [comment]
Excellent, thanks!

**Comment by hekm77** [comment]
Is it possible to display the weekdays in a local HA language?

**Comment by kalkih** [comment]
@hekm77 

Sure, coming next update https://github.com/kalkih/mini-graph-card/commit/6d542863695e62a3d44dc089cc8ab82f3472a085

**Comment by kalkih** [comment]
@hekm77 This is now available in the latest release [v0.3.2](https://github.com/kalkih/mini-graph-card/releases/tag/v0.3.2), no config needed, utalize the language set in HA.

**Comment by mihalski** [comment]
Did this every get implemented?
I was just trying to achieve this for a temp/humidity graph so I could see the min/max for both sensors.

**Comment by kalkih** [comment]
No, this issue is still open.

**Comment by mihalski** [comment]
Was thinking maybe something like:
```
Min: TempValue / Time           Min: HumidityValue / Time
Max: TempValue / Time           Max: HumidityValue / Time
```
Maybe it can be even simpler and more elegant.

**Comment by Extreme79** [comment]
How about to have an option to place extrema on the same line of current status? This to have a more compact view.

**Comment by peter-dolkens** [comment]
I'd also love a more compact view - and also one that only triggers on hover

So my graph might normally look like: 
![image](https://user-images.githubusercontent.com/469666/108144883-6d9e7680-70c2-11eb-8515-0f81db97a766.png)

But when I hover, it might look like:
![image](https://user-images.githubusercontent.com/469666/108145215-f9180780-70c2-11eb-89e7-896479708e23.png)


Additionally, the ability to control `show_min` and `show_max` separately would be great too.

**Comment by peter-dolkens** [comment]
I'd also love a more compact view - and also one that only triggers on hover

So my graph might normally look like: 
![image](https://user-images.githubusercontent.com/469666/108144883-6d9e7680-70c2-11eb-8515-0f81db97a766.png)

But when I hover, it might look like:
![image](https://user-images.githubusercontent.com/469666/108145215-f9180780-70c2-11eb-89e7-896479708e23.png)


Additionally, the ability to control `show_min` and `show_max` separately would be great too.

Let me know if these should be separate tickets - this issue appears to be a bit of a "catch all for extrema improvements" at the moment, which feels weird, but I'd rather not give you duplicate tickets too.

**Comment by Manlycookiebear** [comment]
I would find this an extremely useful feature right now, to have an option for which entity I can see the extrema.

**Comment by ildar170975** [comment]
Let me conclude:

1. For each entity we may define `show_extrema` & `show_average` options (false/true).
2. If some graph is selected:
- the extrema data for THIS entity are displayed (if `show_extrema=true` for THIS entity);
- the average data for THIS entity are displayed (if `show_average=true` for THIS entity).

3. If no graph is selected:
- if entity #1 has `show_extrema=true` or `show_average=true` - the extrema or average data are displayed for this entity;
- otherwise - a blank line is displayed.

Additionally - I propose a new 'extrema_average_adaptive_color` option (per-entity) - similarly to `state_adaptive_color`.

As for ["show extrema / average" data in a compact manner](https://github.com/kalkih/mini-graph-card/issues/51#issuecomment-733247893) - let it be a separate issue.

**Comment by BuurmanG** [comment]
Would be nice if this was implemented.... 🎅 🎁

**Comment by antonio1475** [comment]
This is a pity 🥲 I have one card per room, with a "comparison" one (outside temp) to manage the windows. I would want the extrema for only the room so that I know how that room is behaving, keeping the secondary (outside temp) just as a reference line without affecting the extrema. Right now, in practice the extrema ends up being the outside temp (much more variable) than the room.

![image](https://github.com/kalkih/mini-graph-card/assets/63130724/af88a03f-9d9d-4339-ab5a-0fa8a4b711e1)

**Comment by ildar170975** [comment]
Currently extrema & average are shown for the 1st entity only:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_temperature
  - entity: sensor.ac68u_cpu_temperature
    show_state: true
points_per_hour: 60
name: xxx
show:
  extrema: true
  labels: true
```
![image](https://github.com/kalkih/mini-graph-card/assets/71872483/3ea6ebff-f78e-4345-9957-f40c21a3a3cb)

Means - this is achieved:
> I would want the extrema for only the room so that I know how that room is behaving, keeping the secondary (outside temp) just as a reference line without affecting the extrema

**Comment by antonio1475** [comment]
> show:
>   extrema: true
>   labels: true

My apologies. I just learnt that extrema is not what I thought it was.
I was talking about what I now know are the labels, which grab the min and max values of all entities and I have yet to learn if this is configurable so that labels only grab the data of the 1st entity.

![image](https://github.com/kalkih/mini-graph-card/assets/63130724/6b23b740-61e9-4b80-ae97-852af242e847)

I'm sorry. I'm happy to delete both my messages to avoid confusion, please tell me so.

**Comment by ildar170975** [comment]
> that labels only grab the data of the 1st entity

It is only possible if the 2nd entity is assigned to the 2nd axis:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_temperature
  - entity: sensor.ac68u_cpu_temperature
    show_state: true
    y_axis: secondary
points_per_hour: 60
name: xxx
show:
  extrema: true
  labels: true
  labels_secondary: true
```
![image](https://github.com/kalkih/mini-graph-card/assets/71872483/39e93a32-b45f-4669-b1b9-5f60d17f8d6f)

Now just remove `labels_secondary: true`.
