### ISSUE TITLE
Current State NaN

### ISSUE THREAD

**Issue by rjhilgefort** [kalkih/mini-graph-card#515]
Hello! Love this card and appreciate the work on it. I have been using it well for some motion detectors I have around the house. I recently got an Aqara Door Sensor and got it all setup. I am trying to use this card to display the sate of the garage over time and having an issue. Just using the "Entity Card" I can see the current state. When I setup the device with the mini-graph card, the current state shows as `NaN`. That said, the graph appears to be working well.

![image](https://user-images.githubusercontent.com/2034823/102112222-a2592d80-3df4-11eb-861b-c9261818c5c6.png)

```yaml
type: 'custom:mini-graph-card'
name: Garage Door Sensor (12H)
icon: 'mdi:garage'
entities:
  - color: '#ffb347'
    entity: binary_sensor.garage_door_sensor
hours_to_show: 12
line_width: 2
update_interval: 30
points_per_hour: 12
smoothing: false
aggregate_func: max
state_map:
  - label: Closed
    value: Closed
  - label: Open
    value: Open

```

**Comment by Gio-dot** [comment]
Same here... https://github.com/kalkih/mini-graph-card/issues/505

**Comment by rjhilgefort** [comment]
@Gio-dot I read through your card just now, but thought I would check- have you found any work-arounds or anything to fix it?

**Comment by Gio-dot** [comment]
> @Gio-dot I read through your card just now, but thought I would check- have you found any work-arounds or anything to fix it?

Unfortunately no, i have no idea why it doesn't work...

**Comment by Gio-dot** [comment]
> @Gio-dot I read through your card just now, but thought I would check- have you found any work-arounds or anything to fix it?

Don't know exactly why, but with this setting it is working for me now:

```
hours_to_show: 24
points_per_hour: 10
line_width: 2
font_size_header: 14
font_size: 80
decimals: 1
show:
  labels: true
  name: true
  icon: false
hour24: true
;lower_bound: 12
;upper_bound: 30
state_map:
  - value: 'off'
    label: 0
  - value: 'on'
    label: 1
type: 'custom:mini-graph-card'
```
![image](https://user-images.githubusercontent.com/55327160/102693362-5fdf8880-421a-11eb-98b6-13d61b92f645.png)
