### ISSUE TITLE
Feature Request: Secondary Color Thresholds

### ISSUE THREAD

**Issue by drinfernoo** [kalkih/mini-graph-card#519]
I love that we recently got the ability to set a secondary range for the Y-axis, but it would be great if we could also set color thresholds against *that* axis, rather than having them match the primary axis.

**Comment by parautenbach** [comment]
I just ran into the same requirement. 

Here is my example:
```
    - type: custom:mini-graph-card
      entities:
        - entity: sensor.sun_illuminance
        - entity: sensor.solar_angle
          color: '#cccccc'
          y_axis: secondary
      hours_to_show: 24
      hour24: true
      smoothing: true
      points_per_hour: 12  # every 5 min
      line_width: 2
      show:
        extrema: true
      color_thresholds:
        - value: 15320
          color: '#cccccc'
        - value: 15321
          color: var(--accent-color)
      color_thresholds_transition: hard
```

I can at least override the thresholds by providing a fixed colour for the second entity but have a threshold definition per entity or per axis would be nice.
