### ISSUE TITLE
Wrong average value calculated

### ISSUE THREAD

**Issue by brunohaller** [kalkih/mini-graph-card#522]
Hi,

I use a mini-graph-card to display power consumption for a device:

![image](https://user-images.githubusercontent.com/73822257/103249608-61beef80-4970-11eb-9d1d-e7cb71a62bfc.png)

Almost the whole day I have around 20W and only a few hours with around 120, so the average of 107 seems to be wrong.

Config:

```
type: 'custom:mini-graph-card'
name: Messsteckdose
points_per_hour: 6
hours_to_show: 24
icon: 'mdi:compare'
line_width: 3
decimals: 0
hour24: true
lower_bound: 0
show:
  extrema: true
  average: true
  labels: true
entities:
  - entity: sensor.plugable_switch_measuring_power

```
