### ISSUE TITLE
Use of value template 

### ISSUE THREAD

**Issue by titiviking** [kalkih/mini-graph-card#523]
Can we use a value_template for some of the parameters ?

I would like to define an input_number for the hours_to_show, so that I can create a minimal configuration screen for some layout.
I would be able to change the amount of hours dynamically by changing the value of my input_number.

partial code:
```
  type: 'custom:mini-graph-card'
  entities:
    - sensor.living_room_temperature
  name: Temperature
  height: 150
  line_width: 2
  font_size: 85
  hours_to_show: '{{ states.input_number.graph_timeframe.state | int }}'
  points_per_hour: 2
  hour24: true
```
