### ISSUE TITLE
Wrong first bar delta-value

### ISSUE THREAD

**Issue by PrastoDj** [kalkih/mini-graph-card#526]
Hi,
using aggregate function _delta_, the first bar displays always the value 0.
It's like it uses the > instead of >= in lower bound _hours_to_show_ parameter.

![image](https://user-images.githubusercontent.com/75693328/103453591-d3ce6600-4cdb-11eb-9d7a-19c5de4e7fba.png)

Thanks for your support

Prasto

**Comment by RomRider** [comment]
Please share your config :)

**Comment by outrun0506** [comment]
Hi,
same form me.

Here is my config:

```
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.amis_zahlerstand_gesamt
name: Verbrauch pro Stunde
hours_to_show: 6
aggregate_func: delta
points_per_hour: 1
group_by: hour
hour24: true
icon: 'mdi:counter'
show:
  graph: bar
```
