### ISSUE TITLE
Most recent sensor state not reflected in card

### ISSUE THREAD

**Issue by titiviking** [kalkih/mini-graph-card#530]
Loading the Lovelace homepage, I display a few Mini-Card-Graph with temperature and humidity history.
The cards display the state of those sensor as well.

The value of those states however do not display the actual latest state. Other cards (like Entities) do display the latest state properly. Hence on the homescreen I see differents values for the same sensor, the value of the mini-graph-card is known to be incorrect because not updated.

![image](https://user-images.githubusercontent.com/73351833/104030263-6a62c180-51cb-11eb-9a10-5ddf49a271b4.png)
_blue = correct
red = wrong_

Even after a few minutes (without page refresh), the mini graph card displays the same value.
Graph is also not being updated.

Full page refresh is required to show temporarily the correct value...

**Comment by RomRider** [comment]
mini-graph-card smoothes out the graph based on your number of points per hour.
Increasing the `points_per_hour` might help getting the appropriate value. Also please share your config :)

**Comment by jeremycook61** [comment]
I have the same problem. A bar graph updates regularly as expected, but a line graph with the same update_interval and points_per_hour does not which means the alignment of energy use and load balancing gets out of whack. 

Here are my configs. The first updates without a reload, the second does not.

```
  type: 'custom:mini-graph-card'
  entities:
    - entity: sensor.home_total_consumption_active_power
  name: Energy Consumption last hour
  hours_to_show: 1
  aggregate_func: max
  group_by: interval
  update_interval: 30
  show:
    graph: bar
  points_per_hour: 60
```

```
type: 'custom:mini-graph-card'
entities:
  - entity: switch.xxxx_livingroom_heater
    name: Living room
  - entity: switch.xxxx_downstairs_hall_heater
    name: Downstairs hall
  - entity: switch.xxxx_hot_water
    name: Hot water tank
  - entity: input_boolean.kitchen_state
    name: Kitchen
name: Load balancing
hours_to_show: 1
points_per_hour: 60
update_interval: 60
aggregate_func: max
line_width: 2
smoothing: false
icon: 'mdi:transmission-tower'
show:
  state: false
  graph: line
state_map:
  - value: 'off'
    label: 'Off'
  - value: 'on'
    label: 'On'
```
![image](https://user-images.githubusercontent.com/8317651/106587117-80a13a80-6549-11eb-880f-d313103f4263.png)

**Comment by mp3guy** [comment]
Another repro here. I have to refresh the page. If I use the stock "Sensor" card that comes with Lovelace it has no problem updating instantaneously. Seems like a regression?

**Comment by RomRider** [comment]
A regression between which version and which other version?

**Comment by mp3guy** [comment]
I don't know which version. I haven't had the time to bisect it and see. I'm just assuming it's a regression as it is touted as a feature in the documentation under the "update_interval" option and is currently not working. So either it regressed or never worked.

**Comment by mp3guy** [comment]
Any chance this issue will be addressed? It totally ruins the HA experience, having to refresh the page or re-open the app to get up to date readings. I'll probably have to switch to using a different graph card otherwise.

**Comment by theetron** [comment]
Same here,

I have three binary sensors showing if a door is open or closed.
The graph shows an open door and the caption above the chart tells me all doors are closed, or the other way around.
Its not ok.

```
type: 'custom:mini-graph-card'
entities:
  - entity: binary_sensor.deursensor_01_contact
    name: Voordeur
  - entity: binary_sensor.deursensor_02_contact
    name: Achterdeur
  - entity: binary_sensor.deursensor_03_contact
    name: Schuuur
name: Deuren laatste 8 uur
hours_to_show: 1
points_per_hour: 60
update_interval: 30
line_width: 2
aggregate_func: max
smoothing: false
state_map:
  - value: 'off'
    label: All doors are closed
  - value: 'on'
    label: Open door

```
