### ISSUE TITLE
Secondary axis not displaying proper value

### ISSUE THREAD

**Issue by titiviking** [kalkih/mini-graph-card#534]

**Comment by RomRider** [comment]
I believe this happens because of smoothing. Would you mind increasing the `points_per_hour` to 30?

**Comment by titiviking** [comment]
Agreed pount_per_hour has an impact.
Although for binary sensors I would expect it can adjust to the binary states. 

Perhaps it would help to have a flag that doesn't use averages, but solely relies on the actual state changes. 

In my case the points per hours should only be for the temperature and not for the heating state.

**Comment by RomRider** [comment]
I'm not yet familiar with the codebase but @kalkih, do you think it would be possible to add a flag in the entities so that the graph only relies on the exact points of data pulled from HA (like `raw: true`)? And specifically for binary sensors having flat lines until the state changes?

**Comment by kalkih** [comment]
I think setting the option `smoothing: false` should fix this, please, give it a shot!

**Comment by titiviking** [comment]
I've set the `smoothing:false` for the secondary data set I'm showing (heating state).

This is my config:

```
            type: 'custom:mini-graph-card'
            entities:
              - entity: sensor.living_room_temperature
              - entity: binary_sensor.heat_on
                color: red
                name: heat
                show_fill: true
                show_line: false
                show_points: false
                show_legend: false
                y_axis: secondary
                smoothing: false
            name: Temperature
            height: 150
            line_width: 2
            font_size: 85
            hours_to_show: '${ HOURS }'
            points_per_hour: 10
            hour24: true
            show:
              icon: true
              extrema: true
              labels: true
              icon_adaptive_color: true
            color_thresholds:
              - value: 23
                color: '#e74c3c'
              - value: 19
                color: '#1db954'
              - value: 16
                color: '#3498db'
            state_map:
              - value: 'off'
              - value: 'on'
```

From a screenshot below, you see that the state however is not reflected properly... even with `smoothing:false` , the 'on' state for the last 10 min is not even shown. as there is no smoothing, I would expect to already see that state.
(Current value for the `hour_to_show` is 24)
