### ISSUE TITLE
Second Axis gets Interpolated

### ISSUE THREAD

**Issue by itsyoshio** [kalkih/mini-graph-card#541]
I'm at my Wits end with this.

![image](https://user-images.githubusercontent.com/12760988/105055298-37de8180-5a73-11eb-9bee-ef0432e8c8d1.png)

for some reason, the Secondary Axis gets Stretched (to a Triangle) instead of staying Rectangular. It feels like the Entity gets Averaged, yet i don't understand why it would.

It's meant to Display a Binary Sensor (Window, Door openness) so it can't be any Value between 0 or 1.
I'm trying to build something more like this :
![image](https://user-images.githubusercontent.com/12760988/105055601-8855df00-5a73-11eb-88c9-2a4066d6363c.png)

```yaml
type: 'custom:mini-graph-card'
name: Air Quality
icon: 'mdi:air-filter'
hours_to_show: 10
lower_bound: 0
upper_bound: ~100
lower_bound_secondary: 0
upper_bound_secondary: 1
animate: true
show:
  average: true
  extrema: true
  name: true
  icon: true
  labels: false
  labels_secondary: false
entities:
  - entity: sensor.bme680_iaq
    show_legend: true
    show_line: true
    show_points: true
  - entity: binary_sensor.bedroom_windows
    smoothing: false
    show_line: false
    show_points: false
    show_legend: false
    color: white
    y_axis: secondary
    group_by: interval
    aggregate_func: max
state_map:
  - value: 'off'
    label: closed
  - value: 'on'
    label: open
color_thresholds:
  - value: 0
    color: '#00E400'
  - value: 51
    color: '#FFFF00'
  - value: 101
    color: '#FF7E00'
  - value: 151
    color: '#FF0000'
  - value: 201
    color: '#99004C'
  - value: 301
    color: '#7E0023'
```

Any ideas?
Thanks <3
