### ISSUE TITLE
Color Thresholds only showing 1 color

### ISSUE THREAD

**Issue by czech12** [kalkih/mini-graph-card#548]
I'm having issues with the color thresholds.  I believe I have the config right and if I play with the threshold numbers I can get it to work sometimes.

I have a speedtest sensor for download, upload, and ping response that I'm graphing.  Here is my code and graph output:

Download Card:
```
type: 'custom:mini-graph-card'
name: Download
hours_to_show: 24
points_per_hour: 6
font_size: 60
entities:
  - entity: sensor.speedtest_download
show:
  name: true
  icon: true
  state: true
  line_width: 10
  font_size: 70
color_thresholds:
  - value: 0
    color: red
  - value: 100
    color: red
  - value: 200
    color: red
  - value: 300
    color: red
  - value: 400
    color: yellow
  - value: 500
    color: yellow
  - value: 600
    color: green
  - value: 700
    color: green
  - value: 800
    color: green
  - value: 900
    color: green
  - value: 1000
    color: green
```

![image](https://user-images.githubusercontent.com/74950455/105393738-b01b8300-5bea-11eb-8570-274645fab936.png)

Upload card: 
```
type: 'custom:mini-graph-card'
name: Upload
hours_to_show: 24
points_per_hour: 6
font_size: 60
entities:
  - entity: sensor.speedtest_upload
show:
  name: true
  icon: true
  state: true
  line_width: 10
  font_size: 75
color_thresholds:
  - value: 0
    color: red
  - value: 5
    color: red
  - value: 10
    color: red
  - value: 15
    color: red
  - value: 20
    color: yellow
  - value: 25
    color: yellow
  - value: 30
    color: yellow
  - value: 35
    color: yellow
  - value: 40
    color: green
  - value: 45
    color: green
  - value: 50
    color: green
```

![image](https://user-images.githubusercontent.com/74950455/105393886-e5c06c00-5bea-11eb-9cbc-2b81ce409abd.png)

Ping Response Card:

```
type: 'custom:mini-graph-card'
name: Latency
hours_to_show: 24
points_per_hour: 6
font_size: 60
entities:
  - entity: sensor.speedtest_ping
show:
  name: true
  icon: true
  state: true
color_thresholds:
  - value: 0
    color: green
  - value: 10
    color: green
  - value: 20
    color: green
  - value: 30
    color: yellow
  - value: 40
    color: yellow
  - value: 50
    color: red
  - value: 60
    color: red
```

![image](https://user-images.githubusercontent.com/74950455/105393985-05579480-5beb-11eb-9789-d720f3e52dbe.png)

My goal is to have green for "good" numbers, yellow for "average" numbers, and red for "bad" numbers.  At first I just tried to set 3 color thresholds for those 3 value ranges, but that didn't work well for me.  For example, download speed of 0-399 is red, 400-599 is yellow, and 600+ is green.

That is how I got to my current config of being more specific with the values, thinking that it just turns on that color for a set plus or minus range from the value I specify.  I had better luck doing it this way, but when I look at the graph again the next day with different values, it goes back to 1 primary color with black lines below (and sometimes above as you can see with my Upload card).

What am I doing wrong?

**Comment by RomRider** [comment]
The colors need to be defined in RGB hexadecimals.
Eg instead of `green`, you'd put `'#00FF00`

**Comment by czech12** [comment]
> The colors need to be defined in RGB hexadecimals.
> Eg instead of `green`, you'd put `'#00FF00'`

Thank you.  I am getting some better results using the hex numbers.  It fixed my Ping Response Graph:

![image](https://user-images.githubusercontent.com/74950455/105396931-6fbe0400-5bee-11eb-979e-c9c2e1592b31.png)

The Upload one is still giving me issues though.

![image](https://user-images.githubusercontent.com/74950455/105397079-9c721b80-5bee-11eb-8674-13bedc4c07b1.png)

```
type: 'custom:mini-graph-card'
name: Upload
hours_to_show: 24
points_per_hour: 6
font_size: 60
entities:
  - entity: sensor.speedtest_upload
show:
  name: true
  icon: true
  state: true
  line_width: 10
  font_size: 75
color_thresholds:
  - value: 0
    color: '#FF0000'
  - value: 5
    color: '#FF0000'
  - value: 10
    color: '#FF0000'
  - value: 15
    color: '#FF0000'
  - value: 20
    color: '#FFFF00'
  - value: 25
    color: '#FFFF00'
  - value: 30
    color: '#FFFF00'
  - value: 35
    color: '#FFFF00'
  - value: 40
    color: '#00FF00'
  - value: 45
    color: '#00FF00'
  - value: 50
    color: '#00FF00'
```

I'm gonna keep playing with the numbers, but can anyone explain how the color_threshold works?  Using this example again (download speed of 0-399 is red, 400-599 is yellow, and 600+ is green), should I only have to set 3 thresholds?  Like this?

```
type: 'custom:mini-graph-card'
name: Download
hours_to_show: 24
points_per_hour: 6
font_size: 60
entities:
  - entity: sensor.speedtest_download
show:
  name: true
  icon: true
  state: true
  line_width: 10
  font_size: 70
color_thresholds:
  - value: 0
    color: '#FF0000'
  - value: 400
    color: '#FFFF00'
  - value: 600
    color: '#00FF00'
```

**Comment by czech12** [comment]
I think I found a better way of doing this.  Once again, my example:  (download speed of 0-399 is red, 400-599 is yellow, and 600+ is green)

```
type: 'custom:mini-graph-card'
name: Download
hours_to_show: 24
points_per_hour: 6
font_size: 60
entities:
  - entity: sensor.speedtest_download
show:
  name: true
  icon: true
  state: true
color_thresholds:
  - value: 0
    color: '#DB2A0B'
  - value: 399
    color: '#DB2A0B'
  - value: 400
    color: '#D5DB0B'
  - value: 599
    color: '#D5DB0B'
  - value: 600
    color: '#0BDB1F'
```

This is giving me a HARD line switch between the 2 colors:

![image](https://user-images.githubusercontent.com/74950455/105399045-13101880-5bf1-11eb-829c-5f080e94dc70.png)


What's weird is that my other two graphs are working perfectly with a more gradient transition.

```
type: 'custom:mini-graph-card'
name: Upload
hours_to_show: 24
points_per_hour: 6
font_size: 60
entities:
  - entity: sensor.speedtest_upload
show:
  name: true
  icon: true
  state: true
color_thresholds:
  - value: 0
    color: '#DB2A0B'
  - value: 19
    color: '#DB2A0B'
  - value: 20
    color: '#D5DB0B'
  - value: 39
    color: '#D5DB0B'
  - value: 40
    color: '#0BDB1F'
```

![image](https://user-images.githubusercontent.com/74950455/105399237-5c606800-5bf1-11eb-820e-cda8ae3e0212.png)

I think this is due to the size of the download number vs. the size of the upload number.  Meaning the percentage drop of 600 to 599 is a lot less than 40 to 39.

I'm going to keep playing now that I understand a little better what is going on.

Thanks again @RomRider, that hex fix put me on the right track.
