### ISSUE TITLE
Certificate Expiry Display

### ISSUE THREAD

**Issue by broyuken** [kalkih/mini-graph-card#550]
Prior to HA release 2020.12 I had the certificate expiry entity displayed in an invisible graph card and it displayed the number of days until expiry. Since the upgrade it changed the way certificate expiry is displayed and the new entity lists it as the full date until expiry. However if I put this entity in an glance card it will display 5 weeks, etc. Can you please update the mini graph card to show the relative date for these types of entities instead of the full timestamp?

![image](https://user-images.githubusercontent.com/1593391/106159210-8ca88900-6152-11eb-85d9-c2a4571e9bd2.png)

My config:
```
type: grid
columns: 4
cards:
  - entities:
      - entity: sensor.processor_use
        index: 0
    font_size: 75
    line_color: blue
    line_width: 8
    name: CPU
    type: 'custom:mini-graph-card'
  - entities:
      - entity: sensor.memory_use_percent
        index: 0
    font_size: 75
    icon: 'mdi:chip'
    line_color: '#e74c3c'
    line_width: 8
    name: Mem
    type: 'custom:mini-graph-card'
  - entities:
      - entity: sensor.disk_use_percent
        index: 0
    font_size: 75
    line_color: var(--accent-color)
    line_width: 8
    name: Disk
    type: 'custom:mini-graph-card'
  - entities:
      - entity: sensor.cert_expiry_timestamp_secreturl_com
        index: 0
    font_size: 75
    line_color: var(--accent-color)
    line_width: 0
    name: Cert
    type: 'custom:mini-graph-card'
  - type: glance
    entities:
      - entity: sensor.cert_expiry_timestamp_secreturl_com
```
