### ISSUE TITLE
multiple show_state

### ISSUE THREAD

**Issue by LukasQ** [kalkih/mini-graph-card#56]
If I have multiple entities and want to show all states, it looks like this:
![image](https://user-images.githubusercontent.com/5947912/52943826-49421f00-336e-11e9-8f34-13fca20959b4.png)
IMHO there is room for improvement. I would suggest to add the value right next to the legend.

**Comment by LukasQ** [comment]
and now, after setting up a background image, the per entity line_color changes to default:
![image](https://user-images.githubusercontent.com/5947912/52949079-94166380-337b-11e9-9f80-5eaac7818f4f.png)
No idea why...

**Comment by kalkih** [comment]
Idk, I prefer the current design tbh.
I want to keep the "primary state" element, which the tooltip feature (hovering over points in the graph) relies on.

And just moving the secondary states to the legend would make the UI inconsistent.

The drawback of the current design is that it can be hard to tell which state correlates to which entity, however, legend items and states are always listed in the same order.

**Comment by LukasQ** [comment]
what about alignment plus font size?

**Comment by kalkih** [comment]
If only one additional state is shown, the font size will be the same as the main state (in the next update).
With the following config example you should be able to achieve what you want.
```yaml
- type: custom:mini-graph-card
  name: TEMPERATURE
  entities:
    - entity: sensor.aqara_multi_temperature_2
      name: Temperature 1
    - entity: sensor.aqara_multi_temperature_1
      name: Temperature 2
      show_state: true
  align_state: center
  align_header: center
  points_per_hour: .25
  show:
    icon: false
    fill: fade
```
![hyperion_8123_lovelace_4 22](https://user-images.githubusercontent.com/457678/52965310-c9837700-33a4-11e9-9207-c88c6f924dcf.png)
