### ISSUE TITLE
Error in determining the minimum value

### ISSUE THREAD

**Issue by ipmerlin** [kalkih/mini-graph-card#567]
![image](https://user-images.githubusercontent.com/35879628/108212566-15f22080-713f-11eb-9632-bbcddaefc558.png)
![image](https://user-images.githubusercontent.com/35879628/108212819-636e8d80-713f-11eb-8923-781d61e8f629.png)

**Comment by ildar170975** [comment]
The issue is stalled, no reaction from the topic starter.

Please try with:
smoothing: false
points_per_hour: 60
aggregate_func: last

Check again - does it still give an error?

Meanwhile - I do not confirm the bug.
The sensor is updated every 30 sec.
```
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.cleargrass_1_pm25
        color: green
        show_state: true
        show_points: true
    hours_to_show: 1
    points_per_hour: 120
    aggregate_func: last
    update_interval: 0
    show:
      state: true
      points: true
      extrema: true
      name: false
      icon: false
    line_width: 1
    hour24: true
    lower_bound: ~0
    smoothing: false
  - type: history-graph
    entities:
      - entity: sensor.cleargrass_1_pm25
    hours_to_show: 1
    refresh_interval: 0
```
![image](https://user-images.githubusercontent.com/71872483/153630122-003e4e8d-45d7-40e6-9014-05760aa773ae.png)
