### ISSUE TITLE
display input_boolean entities

### ISSUE THREAD

**Issue by TomaszKorwel** [kalkih/mini-graph-card#57]
I have a few graphs where I'd like to plot sensor value against input_boolean. Would that be possible to convert on/off of those entities to 0/1 and plot them on the chart?

**Comment by kalkih** [comment]
Yes, but you'd have to set up a [template sensor](https://www.home-assistant.io/components/sensor.template/), and then feed that template sensor to the card.

Also, since this graph is based on the moving average, I'm not sure the result will end up like you would maybe expect. Although setting the `points_per_hour` option to something like 30+ will basically make it behave like a normal graph.

**Comment by kalkih** [comment]
Something like this

```yaml
input_boolean:
  example:
    name: Hello World
```

```yaml
- platform: template
  sensors:
    input_boolean_sensor_example:
      value_template: "{% if is_state('input_boolean.example', 'on') %}1{% else %}0{% endif %}"
```
