### ISSUE TITLE
[Feature Request] Add a line with a preset value

### ISSUE THREAD

**Issue by hugosbnarciso** [kalkih/mini-graph-card#570]
Hey,

A cool feature would be to add in config a line in the graph.

Example, a graph that shows 0-100% humidity, i could have a dashed line at 50%, just for context.

![Screen Shot 2021-02-20 at 13 33 52](https://user-images.githubusercontent.com/44305822/108591110-62786e80-7380-11eb-89a8-331449324358.jpg)

great work!
Thanks,

**Comment by sbrisson1** [comment]
If I could add, I would give the possibility to add multiples lines.  Something like this:

```
   reference_lines:
    - value: 25
      style: "dashed"
      color: "#f39c12"
    - value: 50
      style: "solid"
      color: "#d35400"
    - value: 75
      color: "#c0392b"

```

**Comment by lanrat** [comment]
I could also use this feature.
For now I just made a helper in Home Assistant with the values that I want and graph them as well.

**Comment by RomRider** [comment]
This feature exists in apexcharts-card, probably won't make it to mini-graph-card as it's in maintenance mode.

**Comment by lanrat** [comment]
@RomRider how do I implement something like this in apexcharts-card?

Looking over the documentation it looks like it could be possible with `data_generator` but that is likely overkill.

**Comment by RomRider** [comment]
With annotations:
https://apexcharts.com/docs/options/annotations/

+ examples of what you can do:
https://apexcharts.com/javascript-chart-demos/line-charts/line-chart-annotations/

**Comment by lanrat** [comment]
Thanks for the pointer. I have a solution that is almost perfect, expect sometimes the annotations are outside of the viewpoint of the graph and are not shown. Is there a way to force an annotation to always be visible, or anchor one of the axis to always make it visible?

![image](https://user-images.githubusercontent.com/164192/121289990-b741e580-c89a-11eb-9bd7-55b52c9270c3.png)

```yaml
type: custom:apexcharts-card
all_series_config:
  curve: stepline
  stroke_width: 2
  group_by:
    func: avg
    duration: 5min
apex_config:
  annotations:
    yaxis:
      - 'y': 0
        strokeDashArray: 0
        borderColor: '#01579B'
        borderWidth: 2
        label:
          borderColor: '#01579B'
          text: Freezer Baseline
          style:
            color: '#fff'
            background: '#01579B'
      - 'y': 40
        strokeDashArray: 0
        borderColor: '#0277BD'
        borderWidth: 2
        label:
          borderColor: '#01579B'
          text: Fridge Baseline
          style:
            color: '#fff'
            background: '#0277BD'
series:
  - entity: sensor.fridge_temperature
    name: Fridge
    color: '#2196F3'
```
