### ISSUE TITLE
min_bound_range function?

### ISSUE THREAD

**Issue by tethyso** [kalkih/mini-graph-card#571]
EDIT
Sorry, just discovered I had to use

`lower_bound: 0`

to get what I want.

[original post]
Hi guys, i'm really enjoying mini-graph-card, it definetly changed my lovelace.
I do however have a problem with min_bound_range, it doesn't seem to have any effect on my graph

```
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.solare_production_power
    color: green
name: Produzione giornaliera (7 giorni)
icon: 'mdi:solar-panel-large'
hours_to_show: 168
aggregate_func: max
group_by: date
show:
  graph: bar
  labels: true
value_factor: -3
unit: kWh
min_bound_range: 0
align_state: center
```

![immagine](https://user-images.githubusercontent.com/21269650/109075877-06a04380-76fa-11eb-9ba0-ef2caeb6e942.png)

Is it a bug or my misconfiguration?
