### ISSUE TITLE
Attribute feature in v0.11.0-dev.3 only works for the first entity

### ISSUE THREAD

**Issue by MaxVRAM** [kalkih/mini-graph-card#580]
Does the attributes function in this branch work? I'm not having luck while using the following lovelace code:

```
type: 'custom:mini-graph-card'
entities:
  - entity: switch.hs110_server
    name: Watts
    attribute: current_power_w
```

Developer tools for the switch.hs110_server entity displays the following:

```
current_power_w: '87.49'
total_energy_kwh: '18.060'
voltage: '247.2'
current_a: '0.47'
today_energy_kwh: '1.844'
friendly_name: HS110 Server
```

My mini-graph-card display N/A for the switch.hs110_server entity and current_power_w attribute.

I have not excluded anything from recorder, and the attribute is confirmed to be listed in HA. Am I missing something here?
