### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replaceChild' of null

### ISSUE THREAD

**Issue by wiuwiu** [kalkih/mini-graph-card#59]
Hi @kalkih.

Weird thing. Please take a look at this config:
```
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                cards:     
                  # wykres wilgotności
                  - type: custom:mini-graph-card
                    entities: 
                      - sensor.mqtt_humidity_bedroom
                    font_size: 80
                    animate: true
                    hour24: true
                    points_per_hour: 1
                    hours_to_show: 12
                    show:
                      fill: false
                    line_color: '#ff0000'                                   # czerwony 
                    color_thresholds:
                      - value: 40.00
                        color: '#55ff00'                                    # zielony
                      - value: 60.00
                        color: '#00aaff'                                    # niebieski
                  # wykres ciśnienia
                  - type: custom:mini-graph-card
                    entities: 
                      - sensor.mqtt_pressure_bedroom
                    icon: mdi:gauge
                    font_size: 75
                    animate: true
                    hour24: true
                    points_per_hour: 1
                    hours_to_show: 12
                    show:
                      fill: false
                    line_color: '#55ff00'                                   # zielony
```

When I use `custom:mini-graph-card` nested in `vertical-stack` and then in  `horizontal-stack` I have this error on my log:
`https://XXX.org/frontend_latest/dcc7e8d8e861a5f2b17d.chunk.js:3203:365 Uncaught TypeError: Cannot read property 'replaceChild' of null`. This error occurs when I refresh the page.
