### ISSUE TITLE
entities vs. entity

### ISSUE THREAD

**Issue by FallenLeave91** [kalkih/mini-graph-card#60]
Hello there,

the card won´t work for me if i usw _entities:_ while using _entity:_ is working fine.

```
type: horizontal-stack
cards:
  - type: 'custom:mini-graph-card'
    entities:
      - sensor.0x00158d0002ca0ea2_temperature
    font_size: 75
    labels: true
    line_color: '#3498db'
    line_width: 8
    name: Temperatur
  - type: 'custom:mini-graph-card'
    entity: sensor.0x00158d0002ca0ea2_humidity
    font_size: 75
    line_color: '#e74c3c'
    line_width: 8
    name: Luftfeuchtigkeit
```
Top isn´t working while bottom is just fine.

Error: "Specify an entity from within the sensor domain."
