### ISSUE TITLE
Show current value of another entity beside label

### ISSUE THREAD

**Issue by bilogic** [kalkih/mini-graph-card#602]
![image](https://user-images.githubusercontent.com/946010/117527664-4b046580-b000-11eb-9b9d-bac1102c004f.png)

Is there a way to show the current charging status (which is another entity) in the red box?

Thank you!

**Comment by bilogic** [comment]
It is showing `NaN`, any idea? Thanks!

![image](https://user-images.githubusercontent.com/946010/117528143-40979b00-b003-11eb-8cf2-e52d74fae296.png)
```
name: Tablet
type: 'custom:mini-graph-card'
entities:
  - sensor.sm_t720_battery_level
  - entity: binary_sensor.sm_t720_is_charging
    name: Charging
    show_graph: false
    show_state: true    
line_color: var(--accent-color)
line_width: 8
font_size: 75
hours_to_show: 168
animate: true
```
