### ISSUE TITLE
color_thresholds_transition: hard doesn't seem to have an effect when using --accent-color

### ISSUE THREAD

**Issue by dekiesel** [kalkih/mini-graph-card#605]
Hi,

thank you for this custom component, it is great!

I seem to have run into a bug: `color_thresholds_transition: hard` doesn't seem to have an effect when using `--accent-color`
```
type: horizontal-stack
cards:
  - type: 'custom:mini-graph-card'
    entities:
      - entity: sensor.mysensors_wohnzimmer_main_3_1
        name: Temp
    show:
      name: false
    color_thresholds:
      - value: 0
        color: '#2274A5'
      - value: 21
        color: var(--accent-color)
      - value: 24
        color: '#A31621'
    color_thresholds_transition: hard
    points_per_hour: 1
    hour24: true
  - type: 'custom:mini-graph-card'
    entities:
      - entity: sensor.mysensors_wohnzimmer_main_3_0
        name: Temp
    show:
      name: false
    color_thresholds:
      - value: 0
        color: '#A31621'
      - value: 40
        color: '#00CC66'
      - value: 60
        color: '#A31621'
    color_thresholds_transition: hard
    points_per_hour: 1
    hour24: true
    decimals: 0

```

![image](https://user-images.githubusercontent.com/17333827/118498014-e1820680-b725-11eb-857e-94d8eaefa847.png)

As you can see the right graph shows no transition, but the left graph is smoothing the transition even though it shouldn't. Have I misconfigured this or did I run into a bug?

Thanks!
