### ISSUE TITLE
The graph line goes black if color_thresholds are set with value out of currently displayed range

### ISSUE THREAD

**Issue by Sindar-sudo** [kalkih/mini-graph-card#606]
Hi!
The custom card is great! However, I ran into a slight problem.
If I set color_thresholds with values that are not currently in the range of the visible graph with the default color_thresholds_transition: smooth, the graph does not transition to the specified color, but instead fades to black.
If I set it to color_thresholds_transition: hard or if I set lower/upper_bound, it works as expected, however, using these is not ideal.

Here's my config:
```
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.temperature
hours_to_show: 24
refresh_interval: 1
color_thresholds:
  - value: 18
    color: blue
  - value: 21
    color: green
  - value: 23
    color: red
color_thresholds_transition: smooth
```

This is what it looks like:
![image](https://user-images.githubusercontent.com/76867281/118655743-823df800-b7f2-11eb-9581-f9ad67929104.png)
