### ISSUE TITLE
Line don't change color based on color_thresholds

### ISSUE THREAD

**Issue by tethyso** [kalkih/mini-graph-card#619]
I'm not able to reproduce this issue, tried on Firefox, Chrome & Safari on macOS and Chrome on Android. (changed the yellow threshold to 35 for testing purposes)

![hyperion_8123_lovelace_4 (46)](https://user-images.githubusercontent.com/457678/54284656-a3ff1d00-45a0-11e9-9cee-fc6f6886552f.png)

Your issue sounds very similar to #52 & #54 but they were addressed with 7d65869b4fc93945c9e912f8bbb39a5c5c5ee43d

_Originally posted by @kalkih in https://github.com/kalkih/mini-graph-card/issues/70#issuecomment-472434568_

**Comment by tethyso** [comment]
Same problem here....

```
type: custom:mini-graph-card
name: HAL Utilizo RAM
font_size: 80
entities:
  - entity: sensor.glances_ram_used_percent
    show_state: true
    name: RAM
align_state: center
show:
  graph: line
  minimum: true
  average: true
  extrema: true
hours_to_show: 10
color_thresholds:
  - value: 0
    color: green
  - value: 60
    color: '#ff6007'
  - value: 90
    color: red
```

![immagine](https://user-images.githubusercontent.com/21269650/122625270-a405f580-d0a4-11eb-99ed-2f59ed271dc1.png)
