### ISSUE TITLE
Header, Icon & State: wrong adaptive color when "color_thresholds" defined

### ISSUE THREAD

**Issue by typxxi** [kalkih/mini-graph-card#621]
Yes, the colour does change, but the icon's and title's color does NOT REFLECT THE LASTEST state but the lowest state in my case. Look at this weight curve and you can see that the orange belongs to the past with the lowest weight and not to the latest weight which would mean a lot more red instead of orange. Here is the code. 
```
type: 'custom:mini-graph-card'
entities:
  - entity: sensor.ble_weight_mi_scale2
show:
  labels: 'true'
  state: 'false'
  name: 'false'
  icon: 'true'
  name_adaptive_color: 'true'
  icon_adaptive_color: 'true'
color_thresholds:
  - value: 102
    color: '#f39c12'
  - value: '104'
    color: '#d35400'
  - value: '105'
    color: '#c0392b'
```

![image](https://user-images.githubusercontent.com/20662430/122644144-15c95800-d114-11eb-85e2-942315a624c6.png)

If I change the thesholds I get this darke red and it looks like this, but again : icon and header represent a minimum and not the latest state which in this case would mean orange and not red.

![image](https://user-images.githubusercontent.com/20662430/122644390-41007700-d115-11eb-9d85-b9dc4d632583.png)

**Comment by ildar170975** [comment]
Surely there is some problems here.

These options work if `color_thresholds` NOT specified:
- name_adaptive_color (defined globally, set color dependingly on the 1st entity line color)
- icon_adaptive_color (defined globally, set color dependingly on the 1st entity line color)
- state_adaptive_color (defined per-entity, set color dependingly on THIS entity line color)
 
```
type: custom:mini-graph-card
entities:
  - entity: sensor.cleargrass_1_co2
    color: red
    state_adaptive_color: true
hours_to_show: 6
points_per_hour: 60
show:
  fill: true
  name_adaptive_color: true
  icon_adaptive_color: true
```
![image](https://user-images.githubusercontent.com/71872483/153621225-a8896add-42de-46c9-882e-3bd24de476fd.png)

When the `color_thresholds` are specified:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.cleargrass_1_co2
    state_adaptive_color: true
hours_to_show: 6
points_per_hour: 60
aggregate_func: last
smoothing: false
show:
  labels: false
  fill: true
  name_adaptive_color: true
  icon_adaptive_color: true
color_thresholds_transition: hard
line_width: 3
height: 500
color_thresholds:
  - value: 700
    color: cyan
  - value: 740
    color: orange
  - value: 800
    color: violet
  - value: 850
    color: blue
  - value: 900
    color: brown
```
The icon & name are colored only when the MAX points are selected - but it should be colored always dependingly on the selected point's color:
![image](https://user-images.githubusercontent.com/71872483/153623165-2623dbf1-98a8-4a06-8b58-f7a5e68843ba.png)

The state is colored always by the LATEST value's color - but it should be colored always dependingly on the selected point's color:
![image](https://user-images.githubusercontent.com/71872483/153623648-0d38478b-1b5b-4062-bbc1-1c7af84bbf46.png)
