### ISSUE TITLE
logarithmic scale appears to not be working

### ISSUE THREAD

**Issue by Mearman** [kalkih/mini-graph-card#623]
Don't think there's an error in my config, but the `logarithmic` option appears to not be working

![image](https://user-images.githubusercontent.com/1331872/122733655-47a60000-d275-11eb-98ac-445d8519be47.png)

![image](https://user-images.githubusercontent.com/1331872/122734745-41645380-d276-11eb-82d7-b4217f7b3d9f.png)

Here's my complete config:
```
type: custom:mini-graph-card
show:
  icon: false
  state: true
  name: true
logarithmic: false
animate: true
entities:
  - entity: sensor.heat_index_1
    name: Feels Like
    show_state: false
    show_legend: false
  - entity: sensor.shellyht_d4ce59_temperature
    name: Shelly
    show_state: false
    show_legend: false
  - entity: sensor.hue_motion_sensor_1_temperature
    name: Hue
    show_state: false
    show_legend: false
  - entity: sensor.outside_temperature
    name: Outside
    show_state: false
    show_legend: false
color_thresholds:
  - value: 25
    color: '#FF0000'
  - value: 21
    color: '#00FF00'
  - value: 15
    color: '#0000FF'

```
