### ISSUE TITLE
Can this be done?

### ISSUE THREAD

**Issue by Jaguaza** [kalkih/mini-graph-card#624]
Hello, I have this card that shows the price of two gas stations.

```
type: custom:mini-graph-card
entities:
  - entity: sensor.diesel_e_leclerc
    name: E.ELECLERC
    color: red
  - entity: sensor.diesel_ballenoil
    name: BALLENOIL
    color: blue
decimals: 3
hour24: true
hours_to_show: 192
icon: mdi:fuel
name: 'PRECIO MÁS BAJO:'
show:
  labels: true
animate: true
group_by: date
update_interval: 1800
```
![image](https://user-images.githubusercontent.com/46264854/122986752-1fff8680-d3a0-11eb-91d2-87436b3cb4b4.png)

Could it be made that instead of the value of the first entity coming out large, the lowest value of the two entities comes out?

Thanks
