### ISSUE TITLE
Group by month in bar style

### ISSUE THREAD

**Issue by octaviz** [kalkih/mini-graph-card#631]
hi! Is there an option to group by months? I want to have the total energy consumed for each month, now I have it for days and I see the kW consumed per day, I would like the same but for each month.

![image](https://user-images.githubusercontent.com/856579/125762112-aa2d8f73-8479-49cb-ab6c-b5abad1fbcc7.jpeg)

**Comment by swampylee** [comment]
I'd like to do exactly the same - group by month. Did you ever figure out a way to achieve that?

**Comment by Depulsor** [comment]
I'd like to do the same, but also for weeks and years.
Is there an option I miss?

**Comment by goliath888** [comment]
Would be this possible? I am also interested in be able to group by month

**Comment by octaviz** [comment]
The only way to do that is with ApxCharts-Card, an integration just like the Mini Graph Card, it's in HACS, I've been using it for a long time.

![CopyQ mOCpWY](https://user-images.githubusercontent.com/856579/198583202-a7db0ef2-932a-44de-a92b-745937254a8f.png)

It has many more options, maybe the learning curve is slower if you have never used one of these things, but if you come from Mini Graph Card, it is easier, I attach the code of one of the ones I have.

https://github.com/RomRider/apexcharts-card

I hope it helps!!

```
type: custom:apexcharts-card
apex_config:
  showForSingleSeries: true
  stroke:
    width: 4
    curve: smooth
  chart:
    zoom:
      enabled: true
    toolbar:
      show: true
      tools:
        zoom: false
        zoomin: true
        zoomout: true
        pan: true
        reset: true
graph_span: 30d
experimental:
  color_threshold: true
header:
  show: true
  show_states: false
  title: Temperatura Exterior MAX/MIN 30 días
show:
  last_updated: true
now:
  show: true
  label: Ahora
  color: ' #dc2c2c '
span:
  start: week
  offset: '-26d'
series:
  - entity: sensor.netatmo_casa_de_sh_interior_exterior_temperature
    type: line
    stroke_width: 6
    color: '     #fd6800     '
    show:
      in_brush: false
      in_chart: true
      extremas: true
    color_threshold:
      - value: 0
        color: '     #067fd0     '
      - value: 5
        color: '    #06d0c9    '
      - value: 10
        color: '   #06d0a5   '
      - value: 15
        color: '   #06d020   '
      - value: 20
        color: '   #95d006   '
      - value: 24
        color: '    #c2d006     '
      - value: 26
        color: '      #fcd843     '
      - value: 28
        color: '     #fc9f43    '
      - value: 30
        color: '     #e95538  '
      - value: 32
        color: '    #e93838    '
      - value: 34
        color: '     #d5495d     '
      - value: 36
        color: '     #9633d0    '
      - value: 38
        color: '     #d033af  '
      - value: 40
        color: '     #cb0059  '
    name: Temperatura MAX
    group_by:
      func: max
      duration: 24h
  - entity: sensor.netatmo_casa_de_sh_interior_exterior_temperature
    type: line
    color: '   #009bfd   '
    stroke_width: 4
    show:
      in_brush: false
      in_chart: true
      extremas: true
    color_threshold:
      - value: 0
        color: '     #067fd0     '
      - value: 5
        color: '    #06d0c9    '
      - value: 10
        color: '   #06d0a5   '
      - value: 15
        color: '   #06d020   '
      - value: 20
        color: '   #95d006   '
      - value: 24
        color: '    #c2d006     '
      - value: 26
        color: '      #fcd843     '
      - value: 28
        color: '     #fc9f43    '
      - value: 30
        color: '     #e95538  '
      - value: 32
        color: '    #e93838    '
      - value: 34
        color: '     #d5495d     '
      - value: 36
        color: '     #9633d0    '
      - value: 38
        color: '     #d033af  '
      - value: 40
        color: '     #cb0059  '
    name: Temperatura MIN
    group_by:
      func: min
      duration: 24h
```
