### ISSUE TITLE
Set-up of new card fails with "a is undefined"

### ISSUE THREAD

**Issue by michaelaye** [kalkih/mini-graph-card#633]
Hi!
Thanks for this work, i'm keen on seeing it finally but so far I can't even start to implement anything.

Installed 0.10.0 via HACS, all reset, I see the javascript entry in Configuration->Lovelace->Resources.

When I try to add a new mini-card though, it immediately is shown with the red error flag like this:

![image](https://user-images.githubusercontent.com/69774/126418403-a97ae864-abf6-46ec-9a7f-01739366b89b.png)

I don't know where even to start to debug this, as I'm not a JS coder and this is my first custom Lovelace object.

Here's my system info:

![image](https://user-images.githubusercontent.com/69774/126418491-4dd14e35-adeb-4767-b9b5-9d5343c68427.png)

**Comment by Mrten** [comment]
can confirm, quite annoying

**Comment by amadeo-alex** [comment]
Can also confirm.
HA running in docker container.

**Comment by jurgenweber** [comment]
yeah, I think I have this also. All I did is update a card with a different sensor before that it was working.

0.10.0 installed via HACS, on 2021.8.1 of HASS.

```
      - type: custom:mini-graph-card
        name: Sun vs Inverter kWh
        entities:
          - sensor.fronius_ac_power
          - entity: sensor.sun_elevation
            y_axis: secondary
        align_icon: left
        align_state: center
        show:
          fill: false
```

> TypeError: Cannot read property 'entity_id' of undefined

![image](https://user-images.githubusercontent.com/3013734/128426919-57b5c83f-e87e-456f-b4e4-4845abd8664a.png)
