### ISSUE TITLE
Sometimes all of sudden color lines appear black

### ISSUE THREAD

**Issue by DoCheckor** [kalkih/mini-graph-card#634]
Hey there!

Got mini-graph-card running for months now and am pretty happy about it!

Thanks for the efforts!

Several cards for a wide range of sensors usually work well for me - however - sometimes all of sudden a random card (got the same issue for several cards but usually only one at the time) appears with black lines instead of the color lines I'd expect.

So: It works for months and then suddenly it is black for a couple of days and usually will be fine again after that.

`type: custom:mini-graph-card
entities:
  - entity: sensor.ble_temperature_flowercare1
    name: FC 1
  - entity: sensor.ble_temperature_flowercare2
    name: FC 2
  - entity: sensor.ble_temperature_4
    name: Roof
name: Temperatur (48h)
show:
  labels: true
  legend: true
align_icon: state
align_header: center
align_state: right
color_thresholds:
  - value: 15
    color: darkblue
  - value: 19
    color: blue
  - value: 20
    color: green
  - value: 27
    color: yellow
  - value: 29
    color: orange
  - value: 30
    color: red
hours_to_show: 48
points_per_hour: 1`

![image](https://user-images.githubusercontent.com/46301119/126761377-b0fcb21e-6e76-452e-8b65-99c52f271722.png)

Also: I'd like to become the entitiy icon (the dots next to the entity name to be in the color of the color defined in the threshold - which appears to be working only for "red" values. Don't know why .

Any ideas on this?

Thanks in advance!

**Comment by wolfhond** [comment]
I have the same issue

**Comment by thetastate1** [comment]
Same

**Comment by Zahnweh** [comment]
Same here. that seems to happen when the values are too far apart. Tried to render whether it's cold or hot outside:

```
color_thresholds:
  - value: -15
    color: blue
  - value: 10
    color: green
  - value: 20
    color: yellow
  - value: 30
    color: red
  - value: 38
    color: crimson
```

But this turned the line black. The temperature during the last days was altering around 0 and 3 degrees, so I tried use some values that are not that far from each other:

```
color_thresholds:
  - value: -1
    color: blue
  - value: 0
    color: green
  - value: 1
    color: yellow
  - value: 2
    color: red
  - value: 3
    color: crimson
```

As the line was finally showing the colors as I wanted, I recon there's a problem when the dynamic range is too large.

**Comment by Zahnweh** [comment]
For everyone reading this: I just figured out that  6-digit hexcodes for colors are solving the problem. 

```
color_thresholds:
  - value: 0
    color: '#0000FF'
  - value: 50
    color: '#FFFF00'
  - value: 60
    color: '#FF0000'
  - value: 65
    color: '#DC143C'
```
