### ISSUE TITLE
Custom element doesn't exist: mini-graph-card.

### ISSUE THREAD

**Issue by ZhuDaHai** [kalkih/mini-graph-card#638]
Downloaded the latest release (0.10.0) and put it in /config/www folder
But is shows errors in the File Editor
![image](https://user-images.githubusercontent.com/14084743/127769104-f14da51b-6e32-4cec-9958-4655c9c2c4b6.png)
Added the resource in configuration.yaml:
```
resources:
  - url: /local/mini-graph-card-bundle.js?v=0.10.0
    type: module
```
Added the custom type in ui-lovelace.yaml:
```
          - type: custom:mini-graph-card
            name: Air quality inside
            icon: 'mdi:server'
            line_width: 2
            animate: true
            hours_to_show: 24
            points_per_hour: 1.5
            entities:
              - entity: sensor.pm1
                name: 1 µm >
              - entity: sensor.pm2_5
                name: 2.5 µm >
              - entity: sensor.pm10
                name: 10 µm >
```
Even after rebooting, I get this:
![image](https://user-images.githubusercontent.com/14084743/127769163-b47b3af5-1bf8-4f8d-89b5-87af354777ec.png)

And I get this is the Logs when I reboot:
![image](https://user-images.githubusercontent.com/14084743/127769187-57899d22-38d4-4f5c-a686-9d9663756f74.png)

What's wrong?
