### ISSUE TITLE
REQ: color_thresholds in entities object

### ISSUE THREAD

**Issue by ZhuDaHai** [kalkih/mini-graph-card#639]
I would like to be able to do this:
```
              - entity: sensor.pm10
                name: 10 µm >
                color_thresholds:
                  - value: 1
                    color: "#ff0000"
                  - value: 2
                    color: "#00ff00"
                  - value: 3
                    color: "#0000ff"                
```
So that each entity line could have its own set of threshold colors.

This is specifically for a PM1, PM2.5, PM10 sensor where I wish to have all the line graphs on the same card, but each has a different threshold for what is considered Good, Moderate, Bad and Deadly

Thanks
