### ISSUE TITLE
Doesn't seem to work with entity filter

### ISSUE THREAD

**Issue by marcschumacher** [kalkih/mini-graph-card#65]
There seem to be a bug when trying to use the entity filter with this component. Probably it uses the entity specified in the entity filter instead of the correct one defined inside the definition. I used the following snippet and it shall be possible to reproduce it with this:

```
        - type: 'entity-filter'
          entities:
          - 'input_boolean.bo_hot'
          show_empty: false
          state_filter:
          - 'off'
          card:
            type: custom:mini-graph-card
            name: "Temperatur Bad oben"
            hour24: true
            decimals: 2
            entities:
              - entity: sensor.bo_temperature
                color: '#3498db'
                show_state: true
            height: 50
            line_width: 2
            font_size: 60
            hours_to_show: 2
            detail: 2
            labels: true
            line_color: red
```

When you use this, the component seem to render `input_boolean.bo_hot` instead of `sensor.bo_temperature`. You can check that by clicking on the rendered component (which displays "NaN").
