### ISSUE TITLE
Color code wrong if flat line is shown

### ISSUE THREAD

**Issue by DocBru** [kalkih/mini-graph-card#652]
Hi,

when the displayed value did not show over the displayed period (e.g. one day), the color coding is incorrect.

![image](https://user-images.githubusercontent.com/83287560/134309876-95fda8ae-06da-4ced-8724-43a773ea2a86.png)

On the screenshot the value is close to the 70 threshold, but it also happens with values like 50 etc.

It should be yellow according to the config below. It works fine as soon as multiple different values  are present (a curve exists in the graph)

```
type: custom:mini-graph-card
entities:
  - sensor.netatmo_keller_humidity
name: Keller
decimals: 0
show:
  icon: false
line_width: 8
color_thresholds_transition: hard
color_thresholds:
  - value: 0
    color: '#FF0000'
  - value: 30
    color: '#FFA500'
  - value: 40
    color: '#149414'
  - value: 60
    color: '#FFA500'
  - value: 70
    color: '#FF0000'

```
