### ISSUE TITLE
Not show real data

### ISSUE THREAD

**Issue by gyenesadam** [kalkih/mini-graph-card#654]
Hello!

I am a full starter in HA.
When I try to setup the graph, after add the second data the graph show the AVG  lines only.

My code is: 
type: custom:mini-graph-card
```
entities:
  - entity: sensor.ble_temperature_haloszoba_xiaomi
    name: Hőmérséklet
    show_state: true
    color: chocolate

  - entity: sensor.ble_humidity_haloszoba_xiaomi
    name: Páratartalom
    show_state: true
    color: darkblue
```
I try everithing what I find on the Github page.

Can anybody help for me?
