### ISSUE TITLE
smoothing can give confusing data points depending on aggregation

### ISSUE THREAD

**Issue by duvalale** [kalkih/mini-graph-card#659]
Hello,

I have these sensors in a graph that display training distances per day over a week.
So I have the following configuration :
````
    type: custom:mini-graph-card
    name: Dernière semaine
    hours_to_show: 168
    group_by: date
    aggregate_func: last
    entities:
      - entity: input_number.today_cycling
        name: Vélo
      - entity: input_number.today_running
        name: Footing
      - entity: input_number.today_swimming
        name: Nage
````

As you can see in the below screenshots, the data computing seems wrong :
my yellow sensor's values are as follow : `[unknown, unknown, unknown, unknown, unknown, 35, 0]`, yet in the graph, the last value is 17.5.
Also, I'm not sure the yellow line should be set at 35 if/when its value is unknown, or maybe we should be able to configure this.

<img width="457" alt="Capture d’écran 2021-10-15 à 11 20 58" src="https://user-images.githubusercontent.com/16177191/137464563-5cc90eaa-0daa-4a92-8aec-05763f31bbc8.png">
<img width="454" alt="Capture d’écran 2021-10-15 à 11 23 22" src="https://user-images.githubusercontent.com/16177191/137464845-01829bae-6a67-4a81-beaa-faeed0ee79fc.png">

Thanks
