### ISSUE TITLE
Line color don't match color_thresholds

### ISSUE THREAD

**Issue by Quw1** [kalkih/mini-graph-card#663]
Line color never changes and always stays green when using color_thresholds. But this only happens with one sensor, another one works as expected.
Same issue as in [#70](https://github.com/kalkih/mini-graph-card/issues/70).

![image](https://user-images.githubusercontent.com/49838571/139585393-3990a562-7c4d-482b-8aeb-b09cdfdc5704.png)

```
type: horizontal-stack
cards:
  - type: custom:mini-graph-card
    color_thresholds:
      - value: 22
        color: '#3bcf77'
      - value: 27
        color: '#d7da40'
      - value: 32
        color: '#df6943'
    entities:
      - entity: sensor.weather_home_temp
        state_adaptive_color: true
    hours_to_show: 1
    points_per_hour: 14
    decimals: 1
    font_size: 92
    align_icon: state
    align_state: center
    line_width: 7
    show:
      fill: false
      name: false
      icon_adaptive_color: true
      labels: false
      points: false
    animate: true

  - type: custom:mini-graph-card
    color_thresholds:
      - value: 40
        color: '#3cbcc8'
      - value: 50
        color: '#29aaff'
      - value: 60
        color: '#005bff'
    entities:
      - entity: sensor.weather_home_hum
        state_adaptive_color: true
    align_state: center
    font_size: 92
    line_width: 8
    points_per_hour: 14
    hours_to_show: 1
    decimals: 1
    align_icon: state
    show:
      fill: false
      icon_adaptive_color: true
      labels: false
      points: false
      name: false
    animate: true
```
