### ISSUE TITLE
How can I only display the value when it's updated instead of a couple hours?

### ISSUE THREAD

**Issue by teijiIshida** [kalkih/mini-graph-card#665]
I'm currently using this code:

```
type: custom:mini-graph-card
name: SPEEDTEST
icon: mdi:speedometer
smoothing: false
entities:
  - entity: sensor.speedtest_download
    name: Download
  - entity: sensor.speedtest_upload
    name: Upload
show:
  graph: bar
```

I have an automation that runs the speedtest twice at day at 7:30am and 10:30pm. I only want to show those values in the graph (on a 7 day if possible), but currently it shows the values every 2 hours, even when speedtest isn't run (it used the previous values until speedtest is run again). How can I only display the value when it's updated instead of a couple hours?
