### ISSUE TITLE
Secondary axis state shows NaN

### ISSUE THREAD

**Issue by thecem** [kalkih/mini-graph-card#666]
Secondary axis shows NaN:

![grafik](https://user-images.githubusercontent.com/46648579/142738411-f801971e-77e0-4ad8-9263-c7541ecf173d.png)

config:

```
entities:
  - entity: climate.wohnzimmer
    attribute: current_temperature
    unit: °C
    state_adaptive_color: true
  - entity: climate.wohnzimmer
    attribute: current_humidity
    unit: '%'
    show_state: true
    state_adaptive_color: true
    y_axis: secondary
hour24: true
points_per_hour: 1
decimals: 1
name: Thermo
show:
  extrema: false
  fill: false
  legend: false
  name: false
  icon: false
font_size: 70
type: custom:mini-graph-card
```
If I change the attribute `current_humidity` to `current_temperature` it shows for the temp on the secondary axis the temperature but the state still remains `NaN`.

`developer-tools/state` of climate.wohnzimmer:

```
hvac_modes: heat, off
min_temp: 17
max_temp: 24
current_temperature: 22.2
current_humidity: 39
hvac_action: off
id: C1_T1
status: OK
pulse_width_modulation: 80
eco_setback: 2.5
friendly_name: Wohnzimmer
supported_features: 0
```

Many thanks for the help!

**Comment by ildar170975** [comment]
> - entity: climate.wohnzimmer
>     attribute: current_humidity

The latest release (I am not talking about the dev version) does not support attributes.
Probably, one of the latest dev versions does support attributes - check them.

**Comment by thecem** [comment]
![grafik](https://user-images.githubusercontent.com/46648579/145621420-3ee10c4f-1520-4535-ae27-ba5d5b9ff554.png)
Latest?

**Comment by ildar170975** [comment]
It is the latest one.

I reproduced your case. Yo are right - it is always NaN.
```
entities:
  - entity: device_tracker.life360_ildar_iphone_5s
    attribute: latitude
  - entity: device_tracker.life360_ildar_iphone_5s
    attribute: longitude
    y_axis: secondary
    show_state: true
decimals: 0
type: custom:mini-graph-card
```
![изображение](https://user-images.githubusercontent.com/71872483/145657162-641a00a0-2674-4d6b-9ef7-364e4e604ee6.png)

I suggest you not to deal with `dev` versions...
Create a template sensor for attributes or start using `apexcharts-card` - it is still evolving.
`mini-graph-card` seems to be stopped evolving.

**Comment by thecem** [comment]
Hey, thanks a lot! I will try apexcharts-card.

**Comment by ildar170975** [comment]
The latest v0.11.0-dev.5 seems to solve the issue:
```
entities:
  - entity: device_tracker.life360_ildar_iphone_5s
    attribute: latitude
  - entity: device_tracker.life360_ildar_iphone_5s
    attribute: longitude
    y_axis: secondary
    show_state: true
decimals: 0
type: custom:mini-graph-card
```
![image](https://user-images.githubusercontent.com/71872483/149815727-6246a791-41e9-4e2c-9762-8b7289ed4558.png)
