### ISSUE TITLE
Request : color_thresholds impacting the font color

### ISSUE THREAD

**Issue by septeven** [kalkih/mini-graph-card#67]
Hello,
Would it be possible to add an option where **color_thresholds** will impact the font color as well ? 
The best would be to be able to define whether you want only the value's font, the name's font or both to be impacted...

Hopefully you can add this in a future release.

Thanks

**Comment by kalkih** [comment]
Great suggestion,
I'll try to add this when I got some time over.

**Comment by kalkih** [comment]
Three new *color* options are now available in the latest release [v0.3.1](https://github.com/kalkih/mini-graph-card/releases/tag/v0.3.1)

Two global options in the `show` option object `icon_adaptive_color` & `name_adaptive_color`, and one entity specific option `state_adaptive_color`.

```yaml
# example
- type: custom:mini-graph-card
  show:
    icon_adaptive_color: true
    name_adaptive_color: true
  entities:
    - entity: sensor.example
      state_adaptive_color: true
```
