### ISSUE TITLE
Using time on y axis

### ISSUE THREAD

**Issue by catgiggle** [kalkih/mini-graph-card#673]
Is it possible to use time on "y" axis? I would like to make a graph that shows the sunrise and sunset times on a given day (like on picture below), but I don't see that possible.
![graph that shows the sunrise and sunset times](https://banana-soft.com/sites/default/files/371%20Daylight%20Chart.jpg)

And sensors configurations:
```
- platform: template
  sensors:
    sun_rising:
      icon_template: mdi:weather-sunny
      friendly_name: "Sun rising"
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_rising')) | timestamp_custom('%H:%M') }}
- platform: template
  sensors:
    sun_setting:
      icon_template: mdi:weather-sunset
      friendly_name: "Sun setting"
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_setting')) | timestamp_custom('%H:%M') }}
```
Current graph configuration:
```
type: custom:mini-graph-card
entities:
  - sensor.sun_rising
  - sensor.sun_setting
hours_to_show: 72
aggregate_func: first
group_by: date
```
