### ISSUE TITLE
Show state at legend's label (or name at state's label)

### ISSUE THREAD

**Issue by bobloadmire** [kalkih/mini-graph-card#679]
For instance, if I have a graph with inside and outside temperature, it's not immediately apparent which value is being displayed at the top of the card (It's whatever entity is listed first, but this isn't obvious at first glance)

I propose a way to list the current value next to the label on the graph, and get rid of the single value at the top of the card. Not only would this make things more clear, it would also eliminate all the white space to the right of the card, making it more space efficient.

Maybe there is a way to do this currently, but looking through the config, I didn't see any options to allow this.

**Comment by jlsjonas** [comment]
Great suggestion, this is definitely something we'd like to add in the future!
Feel free to suggest a more concrete UI example (pictures say more than a thousand words, after all ;) ) so we can also gauge interest

**Comment by ildar170975** [comment]
> to list the current value next to the label on the graph

Do you mean smth like this?
![image](https://user-images.githubusercontent.com/71872483/150044550-4e4ea76a-08d6-4aa9-a569-cdc9832fdf81.png)
https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1957?u=ildar_gabdullin

**Comment by bobloadmire** [comment]
> > to list the current value next to the label on the graph
> 
> Do you mean smth like this? ![image](https://user-images.githubusercontent.com/71872483/150044550-4e4ea76a-08d6-4aa9-a569-cdc9832fdf81.png) https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1957?u=ildar_gabdullin

That's exactly what I would like, thanks!

**Comment by ildar170975** [comment]
Displaying states near the legend breaks the card integrity:
1. You cannot show the "main" state's values on the top of the card because it'll duplicate already displaying states.
2. You cannot show points & states for selected points because of the point above.
So, the only suitable case for "displaying states near the legend" feature is "do not display main states, do not display points".
That is why I propose this feature to be achieved by card-mod only, not as a native mini-graph-card feature.
I suggest to close the issue.

**Comment by ildar170975** [comment]
> unlabeled values

To "label" values, you may use same colors for graphs & states by using already available "`state_adaptive_color: true`" options:
![image](https://user-images.githubusercontent.com/71872483/150054864-69ef970b-8c8b-4607-8472-39bdc00efc8c.png)
[This example ](https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1585)
Also, you may change a font size (by card-mod or available "`font_size_header`" & "`font_size`" options).

See, the changes you are proposing may be implemented in future by someone; I am trying to propose alternative ways for you.

**Comment by bobloadmire** [comment]
This assumes that you're using two sets of data that have different units though, if you want to compare inside and outside temperature on a chart or  inside and outside humidity, it makes it a mess.  I'm not entirely sure, for example, why you would compare temperature to CO2?

**Comment by ildar170975** [comment]
This was just an example of using available options & styling.
Surely you may display graphs for data of the same type on one Y-axis:
![image](https://user-images.githubusercontent.com/71872483/150057585-5bf87933-339c-489f-ba19-145a6b119b9f.png)

**Comment by bobloadmire** [comment]
> This was just an example of using available options & styling. Surely you may display graphs for data of the same type on one Y-axis: ![image](https://user-images.githubusercontent.com/71872483/150057585-5bf87933-339c-489f-ba19-145a6b119b9f.png)

yeah that is better, but it would still be much better to get everything all inline, there is still a ton of dead space on the card because of the layout, and you still have to read the card a bit to figure out which color corresponds with which dataset to know which temp corresponds with which label.

**Comment by ildar170975** [comment]
Similarly to https://github.com/kalkih/mini-graph-card/issues/507:
1) Either show state in the "legend line" (see example above).
2) Or show name in the "state line":
![image](https://user-images.githubusercontent.com/71872483/153666071-ef58cc57-b155-4649-821b-e3f3cd8ed994.png)

**Comment by bobloadmire** [comment]
Saw it was marked stale, I'm assuming there has been no movement on this?

**Comment by bobloadmire** [comment]
Just checking in to see if there has been anymore thought about implementing this?

**Comment by skvalex** [comment]
Hope to see this feature implemented too

**Comment by d3m3trius** [comment]
still active

**Comment by humplemann** [comment]
+1 - have the same exact issue.

**Comment by jlsjonas** [comment]
To be considered when implementing this:
- `show.state` (true & last)
- show the value in the respective legend label, hiding other states to avoid confusion
- documentation: indicate that this is intended for minimal compact layout scenarios only

**Comment by lecourtb** [comment]
Love to see that !

**Comment by sirmeili** [comment]
Would love to see this too. Currently showing 5 temps as an overview and showing all the states and the legend looks horrible

**Comment by sirmeili** [comment]
I hacked the code abit. it was all of 4 lines of code to do this with a new config called "show_legend_with_state". I know that it could be better and  I probably used the wrong CSS classes/etc, but this was more of a proof of concept.  I don't mind putting in a PR if it's acceptable to be included into a future release. 
![image](https://github.com/kalkih/mini-graph-card/assets/6846886/21bff824-02d4-4948-958f-5c8923929120)
![image](https://github.com/kalkih/mini-graph-card/assets/6846886/2bfc957d-488b-49bb-a7b9-41515500eab9)

**Comment by d3m3trius** [comment]
Also, consider how apexcharts card handles the state:
Somethings similar would be cool.

![immagine](https://github.com/kalkih/mini-graph-card/assets/53578119/e86da264-8834-404c-ae18-59ccc1e25c01)

**Comment by sirmeili** [comment]
I condensed it more to just 1 new line (moved the new lines into the same span). I also added a config for a separator. it's on the same line so that you can so something like household: and the : sits right next to the name.

Note my example below has some card-mod styling added to shrink the states on the side and increase the main state font size. just looks better on my phone, which is where I'm intending to show this specific card.

![image](https://github.com/kalkih/mini-graph-card/assets/6846886/24151937-cd4b-4844-b6df-bc1bbd0a25ff)
![image](https://github.com/kalkih/mini-graph-card/assets/6846886/4b75c171-f4ac-4da7-aa4d-f2a6a588462c)

the actual code. Again, I'm sure it could be cleaned up a bit (moved out to a separate function for instance)
`
${entityConfig.show_legend_with_state ? (entityConfig.name || entity.attributes.friendly_name) : ''}${entityConfig.show_legend_with_state ? (entityConfig.legend_state_separator || '') : ''}
`

**Comment by markfrancisonly** [comment]
bump

**Comment by jonprobst** [comment]
> I condensed it more to just 1 new line (moved the new lines into the same span). I also added a config for a separator. it's on the same line so that you can so something like household: and the : sits right next to the name.
> 
> Note my example below has some card-mod styling added to shrink the states on the side and increase the main state font size. just looks better on my phone, which is where I'm intending to show this specific card.
> 
> ![image](https://private-user-images.githubusercontent.com/6846886/276953248-24151937-cd4b-4844-b6df-bc1bbd0a25ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDEzOTIsIm5iZiI6MTcwNTAwMTA5MiwicGF0aCI6Ii82ODQ2ODg2LzI3Njk1MzI0OC0yNDE1MTkzNy1jZDRiLTQ4NDQtYjZkZi1iYzFiYmQwYTI1ZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMTkyNDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2IwYTZjNDQxNzhmN2QwYmU5NTg3YTBlMDcxMGY1ZTBlNDUwZGI0MWRjZjE4M2NjYWQ0NzZkNWQ1ZjlhNWMzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pWWiZ2zHsE6EfXUBp8U_emqczyBzgwk609TYDv0CMCM) ![image](https://private-user-images.githubusercontent.com/6846886/276953565-4b75c171-f4ac-4da7-aa4d-f2a6a588462c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDEzOTIsIm5iZiI6MTcwNTAwMTA5MiwicGF0aCI6Ii82ODQ2ODg2LzI3Njk1MzU2NS00Yjc1YzE3MS1mNGFjLTRkYTctYWE0ZC1mMmE2YTU4ODQ2MmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMTkyNDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDVkNzdlM2IyNTA1NDkwYjU1OWEwNDRhMGViMTU0MGEzY2E0OTk1MDEyODliMjZjZTBhN2U4OTlkMjA1M2RmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ir9guIrsAhxPt_-xcqaKfudxfado64ZoxRha-arbWz4)
> 
> the actual code. Again, I'm sure it could be cleaned up a bit (moved out to a separate function for instance) `${entityConfig.show_legend_with_state ? (entityConfig.name || entity.attributes.friendly_name) : ''}${entityConfig.show_legend_with_state ? (entityConfig.legend_state_separator || '') : ''}`

Where do you put this code in Home Assistant? Sorry if this is a dumb question. CSS noob here

**Comment by jonprobst** [comment]
Took way too long to figure things out, but hey, now I know more about CSS than I did yesterday. It's not dynamic like sirmeili's is but I couldn't figure out where to put his code to get it to work.

![Screenshot 2024-01-12 at 5 33 17 PM](https://github.com/kalkih/mini-graph-card/assets/40637256/12aef9b7-d033-4a7a-be5c-a6861810a761)

`type: custom:mini-graph-card
entities:
  - entity: sensor.avg_house_temperature
    name: House Avg
    show_state: false
    show_line: false
    state_adaptive_color: true
  - entity: sensor.living_room_temperature
    name: Living Room
    show_state: true
    state_adaptive_color: true
  - entity: sensor.office_temperature
    name: Office
    show_state: true
    state_adaptive_color: true
  - entity: sensor.spa_room_echo_dot_temperature
    name: Spa Room
    show_state: true
    state_adaptive_color: true
  - entity: sensor.garage_temperature
    name: Garage
    show_state: true
    state_adaptive_color: true
  - entity: sensor.forecast_temperature
    name: Outside
    show_state: true
    state_adaptive_color: true
name: Temperature
hours_to_show: 24
points_per_hour: 12
show:
  labels: true
  icon: false
  legend: false
align_state: center
align_header: center
decimals: 1
line_color:
  - '#e1e1e1'
  - crimson
  - '#F17F0C'
  - orange
  - '#FFCD00'
  - '#F0ED44'
card_mod:
  style: >
    .states.flex .state.false {
      font-size: 16px;
    } .states.flex .state.false .state__value.ellipsis:before {
      content: "Avg:";
      font-size: 12px;
    }.states.flex .states--secondary {
      font-size: 10px;
    } .states.flex .state.state--small:nth-of-type(1)
    .state__value.ellipsis:before {
      content: "Living Room:";
    } .states.flex .state.state--small:nth-of-type(2)
    .state__value.ellipsis:before {
      content: "Office:";
    } .states.flex .state.state--small:nth-of-type(3)
    .state__value.ellipsis:before {
      content: "Spa Room:";
    } .states.flex .state.state--small:nth-of-type(4)
    .state__value.ellipsis:before {
      content: "Garage:";
    } .states.flex .state.state--small:nth-of-type(5)
    .state__value.ellipsis:before {
      content: "Outside:";
    }
`

**Comment by jonprobst** [comment]
Took way too long to figure things out, but hey, now I know more about CSS than I did yesterday. It's not dynamic like sirmeili's is but I couldn't figure out where to put his code to get it to work.

![Screenshot 2024-01-12 at 5 33 17 PM](https://github.com/kalkih/mini-graph-card/assets/40637256/882e92e1-4dd3-44bf-85e3-fa225c033795)

`
type: custom:mini-graph-card
entities:
  - entity: sensor.avg_house_temperature
    name: House Avg
    show_state: false
    show_line: false
    state_adaptive_color: true
  - entity: sensor.living_room_temperature
    name: Living Room
    show_state: true
    state_adaptive_color: true
  - entity: sensor.office_temperature
    name: Office
    show_state: true
    state_adaptive_color: true
  - entity: sensor.spa_room_echo_dot_temperature
    name: Spa Room
    show_state: true
    state_adaptive_color: true
  - entity: sensor.garage_temperature
    name: Garage
    show_state: true
    state_adaptive_color: true
  - entity: sensor.forecast_temperature
    name: Outside
    show_state: true
    state_adaptive_color: true
name: Temperature
hours_to_show: 24
points_per_hour: 12
show:
  labels: true
  icon: false
  legend: false
align_state: center
align_header: center
decimals: 1
line_color:
  - '#e1e1e1'
  - crimson
  - '#F17F0C'
  - orange
  - '#FFCD00'
  - '#F0ED44'
card_mod:
  style: >
    .states.flex .state.false {
      font-size: 16px;
    } .states.flex .state.false .state__value.ellipsis:before {
      content: "Avg:";
      font-size: 12px;
    }.states.flex .states--secondary {
      font-size: 10px;
    } .states.flex .state.state--small:nth-of-type(1)
    .state__value.ellipsis:before {
      content: "Living Room:";
    } .states.flex .state.state--small:nth-of-type(2)
    .state__value.ellipsis:before {
      content: "Office:";
    } .states.flex .state.state--small:nth-of-type(3)
    .state__value.ellipsis:before {
      content: "Spa Room:";
    } .states.flex .state.state--small:nth-of-type(4)
    .state__value.ellipsis:before {
      content: "Garage:";
    } .states.flex .state.state--small:nth-of-type(5)
    .state__value.ellipsis:before {
      content: "Outside:";
    }

`

**Comment by jonprobst** [comment]
Took way too long to figure things out, but hey, now I know more about CSS than I did yesterday. It's not dynamic like sirmeili's is but I couldn't figure out where to put his code to get it to work.

![Screenshot 2024-01-12 at 5 33 17 PM](https://github.com/kalkih/mini-graph-card/assets/40637256/c9e4c6a4-8166-4ffb-8410-52f9fb284694)

```yaml
type: custom:mini-graph-card
entities:
  - entity: sensor.avg_house_temperature
    name: House Avg
    show_state: false
    show_line: false
    state_adaptive_color: true
  - entity: sensor.living_room_temperature
    name: Living Room
    show_state: true
    state_adaptive_color: true
  - entity: sensor.office_temperature
    name: Office
    show_state: true
    state_adaptive_color: true
  - entity: sensor.spa_room_echo_dot_temperature
    name: Spa Room
    show_state: true
    state_adaptive_color: true
  - entity: sensor.garage_temperature
    name: Garage
    show_state: true
    state_adaptive_color: true
  - entity: sensor.forecast_temperature
    name: Outside
    show_state: true
    state_adaptive_color: true
name: Temperature
hours_to_show: 24
points_per_hour: 12
show:
  labels: true
  icon: false
  legend: false
align_state: center
align_header: center
decimals: 1
line_color:
  - '#e1e1e1'
  - crimson
  - '#F17F0C'
  - orange
  - '#FFCD00'
  - '#F0ED44'
card_mod:
  style: >
    .states.flex .state.false {
      font-size: 16px;
    } .states.flex .state.false .state__value.ellipsis:before {
      content: "Avg:";
      font-size: 12px;
    }.states.flex .states--secondary {
      font-size: 10px;
    } .states.flex .state.state--small:nth-of-type(1)
    .state__value.ellipsis:before {
      content: "Living Room:";
    } .states.flex .state.state--small:nth-of-type(2)
    .state__value.ellipsis:before {
      content: "Office:";
    } .states.flex .state.state--small:nth-of-type(3)
    .state__value.ellipsis:before {
      content: "Spa Room:";
    } .states.flex .state.state--small:nth-of-type(4)
    .state__value.ellipsis:before {
      content: "Garage:";
    } .states.flex .state.state--small:nth-of-type(5)
    .state__value.ellipsis:before {
      content: "Outside:";
    }
```
