### ISSUE TITLE
adaptive color not working as expected

### ISSUE THREAD

**Issue by pachi81** [kalkih/mini-graph-card#688]
In version v0.10.0 the adaptive colors does not work as expected.

1. Color names like "blue" does not work, only if it is the last color in the color_thresholds. (picture 1 and 2)
2. color_thresholds_transition: smooth is not working for the second entity. (picture 2)
3. color_thresholds at the step to next color are shown incorrect for the second entity (picture 3)

Example configuration: 
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: input_number.test_nummer
  - type: custom:mini-graph-card
    name: Apaptive Color
    entities:
      - entity: input_number.test_nummer
        state_adaptive_color: true
      - entity: input_number.test_nummer
        state_adaptive_color: true
        show_state: true
    color_thresholds_transition: hard
    show:
      name_adaptive_color: true
      icon_adaptive_color: true
      graph: false
    color_thresholds:
      - value: 0
        color: green
      - value: 20
        color: yellow
      - value: 60
        color: orange
      - value: 80
        color: blue
      - value: 90
        color: purple
  - type: custom:mini-graph-card
    name: Apaptive Color
    entities:
      - entity: input_number.test_nummer
        state_adaptive_color: true
      - entity: input_number.test_nummer
        state_adaptive_color: true
        show_state: true
    color_thresholds_transition: smooth
    show:
      name_adaptive_color: true
      icon_adaptive_color: true
      graph: false
    color_thresholds:
      - value: 0
        color: '#02FF15'
      - value: 20
        color: '#ECFF02'
      - value: 60
        color: '#FFC902'
      - value: 80
        color: '#0215FF'
      - value: 90
        color: '#F002FF'
```
Different Results:
If the value is higher then the last value, all work like expected:
![image](https://user-images.githubusercontent.com/56817032/149496726-c10f02d6-84dc-4f74-8909-53569e48f6b6.png)
If the value is lower then the last value, color names are not working and smooth is not working for the second entity:
![image](https://user-images.githubusercontent.com/56817032/149496287-b61e2e52-f872-428e-8253-42ce50e0fabe.png)
For value 90, which is the border to use purple color, the second entity still shows the color from color threshold 80:
![image](https://user-images.githubusercontent.com/56817032/149496424-c098a909-eb34-47ec-bc3d-43450f31d33f.png)
