### ISSUE TITLE
Bar chart draws bars on last non zero input. 

### ISSUE THREAD

**Issue by Pocke01** [kalkih/mini-graph-card#69]
I notices that the bar chars I use on my rain sensor draws bars even if sensor reports zero. 

<img width="177" alt="skarmavbild 2019-03-04 kl 07 08 11" src="https://user-images.githubusercontent.com/29057367/53713770-58d06600-3e4c-11e9-935d-c263b419e8a1.png">

<img width="378" alt="skarmavbild 2019-03-04 kl 06 57 14" src="https://user-images.githubusercontent.com/29057367/53713605-b87a4180-3e4b-11e9-9f48-1c080ee8a9e1.png">

Still output bars even though it supposed to be zero får the last 7 hours.

**Comment by Pocke01** [comment]
Here is my card configuration. 
```
  - entities:
      - sensor.netatmo_ourrain_rain
    name: Regn
    show:
      graph: bar
      icon: false
    type: 'custom:mini-graph-card'
```
