### ISSUE TITLE
First entity shows zero

### ISSUE THREAD

**Issue by thetic** [kalkih/mini-graph-card#690]
on v1.15.0

```yaml
type: custom:mini-graph-card
lower_bound: 0
hour24: true
hours_to_show: 168
name: Upstairs Vacuum
icon: mdi:robot-vacuum
entities:
  - entity: sensor.valetudo_upstairs_vacuum_sensor_cleaning
    name: Sensors
  - entity: sensor.valetudo_upstairs_vacuum_main_brush
    name: Filter
  - entity: sensor.valetudo_upstairs_vacuum_main_filter
    name: Main Brush
  - entity: sensor.valetudo_upstairs_vacuum_right_brush
    name: Side Brush
```

![image](https://user-images.githubusercontent.com/1388052/149632038-f848721a-c094-4924-9b49-44dcf336d58f.png)

#580
