### ISSUE TITLE
Feature request: Use templates in all configuration values

### ISSUE THREAD

**Issue by tensiondriven** [kalkih/mini-graph-card#697]
Love `mini-graph-card`!

Forgive me if this has been requested.  I'd like to be able to use jinja templates in attribute values to, for example, change the `lower_bound` and `upper_bound` to be relative to the current value, for example:

```
type: custom:mini-graph-card
entities:
  - entity: sensor.temperature_2
    name: Outdoor Temp
lower_bound: "{{ states('sensor.temperature_2') }} - 5 | float }}"
upper_bound: "{{ states('sensor.temperature_2') }} + 5 | float }}"
```

**Comment by ildar170975** [comment]
Another case is to select `hours_to_show` dynamically.
Currently I have to use `config-template-card` for this.

**Comment by jlsjonas** [comment]
Definitely something to consider; depending on complexity-level, to be considered for 0.12.0

**Comment by jlsjonas** [comment]
Still considering this for a few elements (like state, icon, ...) for next release; but I'm foreseeing a lot of potential side-effects & complications when adding this to any element inside the graph.
Updated the issue for transparency.

**Comment by jchhenderson** [comment]
+1 for this.

Very useful for upper_bound / lower bound to show multiple graphs on the same scale.

**Comment by ildar170975** [comment]
Also for color_thresholds:
https://github.com/kalkih/mini-graph-card/issues/697
```
color_thresholds:
  - value: "{{ ((states.sensor.hallway_temperature.state) | float +0) }}"
    color: '#0066ff'
  - value: "{{ ((states.sensor.hallway_temperature.state) | float +3) }}"
    color: '#d35400'
```

**Comment by humanBeer** [comment]
From my post that got merged, I would like to do something like this:
```
                    show_graph: |
                      {{ states('input_boolean.test_graph_icon') }}
```

**Comment by DonCastor** [comment]
Hello team !

After opening this ticket : [https://github.com/kalkih/mini-graph-card/issues/943](url)

[ildar170975](https://github.com/ildar170975) told me to add my comments here :

I'm trying to do a simple thing, but it seems that i'm taking it on the wrong side!

I have created cards where I display temperature and humidity of the room (on that no issue). The temperature icon, is colored with different values as you can see below :

![image](https://user-images.githubusercontent.com/60355611/227463464-81ba35df-8956-4c21-be4f-1680d3389892.png)

It's working fine and I have the right color with the right temperature.
But when I want to apply this scheme to my mini-graph-card, it's not working : I just want to have my graph-line with the same color as my icon...

For that, here is the code :

![image](https://user-images.githubusercontent.com/60355611/227463516-2279e616-29f5-461c-a73a-a6bcdacf98b2.png)

This is driving me crazy, I'm sure it can work, but I don't understand why it is not.

**_Important :_** The color_treshold behaviour is not what I want.
I want the whole graph to be from the color I put in parameter, not the threshold.

For example, If my temperature is 19, I want the whole graph line in green.
If my temperature is 22, I want the whole line to be in red.

This is the difference between the treshold and my question.

Any idea ?

Kind regards.

**Comment by ildar170975** [comment]
> Any idea ?

Currently dynamic color is not supported by the card.
Your possible workaround - place the card inside `config-template-card`.
For details you may ask questions in a dedicated `mini-graph-card` or `config-template-card` threads in Community to avoid cluttering this issue.

**Comment by MRobi1** [comment]
Another +1 for this FR.
Would like the ability to dynamically change the graph color based on an entity's state.

My particular use-case is for climate devices. I'd like the graph to be orange if heating or blue if cooling.

```
      color: |
        {% if is_state('climate.thermostat_bar','heat') %}
          var(--orange-color)
        {% elif is_state('climate.thermostat_bar','cooling') %}
          var(--blue-color)
        {% endif %}
```

**Comment by ildar170975** [comment]
> dynamically change the graph color based on an entity's state.

Currently this may be done by card-mod:
![image](https://user-images.githubusercontent.com/71872483/233353149-0283a3f1-e7fd-491d-acc4-97aac12c94d3.png)
https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/2316?u=ildar_gabdullin

**Comment by MRobi1** [comment]
@ildar170975 Thanks!! I had managed to do it using config-template-card but I use card-mod everywhere else in my dashboard so it would be better for consistency.

Any idea how to handle when you have multiple lines on 1 graph and dynamically set the color of both??

**Comment by ildar170975** [comment]
> using config-template-card

Not a good solution - you need to define you graph's sensor as "monitored" in CTC (config-template-card).
Also, on every change of the sensor the whole card will flicker.

**Comment by Krzysztonek** [comment]
Here is a one-line excerpt of my card code:

``` show_hours: 720```

I would need to be able to change it from the hard-coded value (here: 720) to any numerical external value being kept in the numerical helper (e.g. `input_number.show_hours`) or any other numerical entity. 

This is basically what I want to achieve (don't look at the syntax, the semantic counts here):

 ```show_hours: Number(states['input_number.show_hours'].state)```

Is it possible to have it coded somehow?

**Comment by cryptk** [comment]
Another use-case for this would be converting a string state into a value that could then be graphed. For example, converting an hvac_action from a climate entity into values.  This would allow me to highlight the background of the chart in red or blue depending on if the heating or cooling was running during a time period which I am currently doing with the apexcharts card (but I like the look of this card much better and wish I could replicate this functionality)

**Comment by FauxPalindrome** [comment]
+1 for this.
Been waiting for this for a looong time.

I'd like to be able to dynamically change de number of hours showing.

**Comment by MaxLeb** [comment]
+1

I don't know if this is here but it would be usefull for `name` field of each entity. In my case all temperature sensors are numbered to avoid having there names/id linked to a room and I would like to use `area_name('sensor.xxx')` to avoid changing the graph if I move a sensor to an other room

Anyone with a `config-template-card` example as a workaround ?

**Comment by timbilalov** [comment]
Another +1 for this FR.

**Comment by SeBsZ** [comment]
Will this be added? +1 for this please.

**Comment by cinghialino** [comment]
one more let's do this please

**Comment by attyluccio** [comment]
+1 please!

**Comment by MankiniChykan** [comment]
+1 Allowing ```hours_to_show:``` to accept templates from an ```input_number ``` would be perfect. This will allow dynamically changing the chart from the dashboard.

**Comment by LukeCichon** [comment]
+1, that would be really helpful!

**Comment by nickmomrik** [comment]
Would be very useful for the `name` field. I have a temperature sensor that I make around and I set it's location with an Input Select. I'd love to be able to take the name from that.

**Comment by Dronedale** [comment]
I am currently using custom card 'card-templater' as a parent card. This way you can make templates for every config element, works perfectly 

Below I set hours_to_show parameter to only hours of the current day (default is last 24h)

![image](https://github.com/user-attachments/assets/c0d8c014-ee2b-4a56-974b-6a2613b73be7)

**Comment by ildar170975** [comment]
Both in card-templater and config-template cards you need to declare a “graph” entity as “monitored”, ie in the “entities” option. But due to some issues, a whole card is updated (fully redrawn) when the “graph” entity is updated. Contrary, when the “graph” entity is not “monitored” - the graph is not updated realtime.
So, wrapping the mini-graph-card into a template-supporting card has pro and contra.

**Comment by rosinscj** [comment]
+1

**Comment by demonizator** [comment]
+1, really need templates for color thresholds!

**Comment by demonizator** [comment]
I am trying to use card-templater to set the colors thresholds, but it's not working for me.. Any suggestions?

```
type: custom:card-templater
entities:
  - sensor.humidity_average
  - input_number.humidity_low_threshold
  - input_number.humidity_high_threshold
card:
  type: custom:mini-graph-card
  entities:
    - entity: sensor.sonoff_a4800eb8d9_humidity
      name: Влажност на въздуха
  hours_to_show: 6
  points_per_hour: 2
  line_color: cyan
  color_thresholds:
    - value: 25
      color: yellow
    - value: "{{ states('sensor.humidity_average') | float(0) + states('input_number.humidity_low_threshold') | float(10) }}"
      color: cyan
    - value: "{{ states('sensor.humidity_average') | float(0) + states('input_number.humidity_high_threshold') | float(10) }}"
      color: red
  decimals: 1
  hour24: true
  lower_bound: 30
  height: 100
  show:
    state: true
    icon_adaptive_color: true
```
