### ISSUE TITLE
"state_adaptive_color" option is confusing since the left "state" text is used for displaying states for all entities

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#698]
The `state_adaptive_color` may be used to visually associate a displayed state with a corresponding graph:
![image](https://user-images.githubusercontent.com/71872483/150060172-7f9159fd-4c88-4c52-b34a-4e64348a99a7.png)
```
type: custom:mini-graph-card
entities:
  - entity: sensor.cleargrass_1_temperature
    name: Temp
    show_state: true
    color: red
    state_adaptive_color: true
  - entity: sensor.cleargrass_2_co2
    name: CO2
    show_state: true
    color: green
    state_adaptive_color: true
    y_axis: secondary
show:
  name: false
  icon: false
```
If some point is selected on the 2nd graph then the left "state" text contains a value for this point:
![image](https://user-images.githubusercontent.com/71872483/150060372-54bee89f-d1b9-433a-92a1-80295f2ac595.png)
This confuses since the label has a value for the 2nd entity and a color for the 1st entity.

**Suggestion:**
If some point is selected for some entity and this entity has the `state_adaptive_color: true` option, then set the text color **accordingly to this entity**.

**Comment by akloeckner** [comment]
fixed in #1214

**Comment by ildar170975** [comment]
There is still a problem.
Assume we have `state_adaptive_color: true` for ONE entity defined only:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_co2
    color: red

  - entity: sensor.xiaomi_cg_2_co2
    show_state: true
    color: green
    state_adaptive_color: true
```
Then the 2nd entity's state is not colored when SELECTED:
![Image](https://github.com/user-attachments/assets/aa86abf7-3354-4ba0-ab40-5a0f8448e890)
