### ISSUE TITLE
Line Colors don't match color_thresholds

### ISSUE THREAD

**Issue by balsman225** [kalkih/mini-graph-card#70]
When using the color_thresholds the fills colors don't match the line color. 
The line color never changes - always stays green.

Attaching screenshot of CPU usage - 

<img width="512" alt="Screen Shot 2019-03-09 at 9 39 54 PM" src="https://user-images.githubusercontent.com/4239330/54080389-08c22b00-42b4-11e9-8752-733dff5c6d90.png">

```
type: horizontal-stack
cards:
  - type: 'custom:mini-graph-card'
    entities:
      - sensor.processor_use
    name: CPU
    color_thresholds:
      - value: 0
        color: green
      - value: 50
        color: yellow
      - value: 75
        color: red
    font_size: 75
    line_width: 8
  - type: 'custom:mini-graph-card'
    entities:
      - sensor.memory_use_percent
    name: Memory
    color_thresholds:
      - value: 0
        color: green
      - value: 50
        color: yellow
      - value: 75
        color: red
    font_size: 75
    line_width: 8
  - type: 'custom:mini-graph-card'
    entities:
      - sensor.disk_use_percent_home
    name: Disk
    color_thresholds:
      - value: 0
        color: green
      - value: 50
        color: yellow
      - value: 75
        color: red
    font_size: 75
    line_width: 8

```

Similar to #54

**Comment by kalkih** [comment]
Have you updated the card to the latest version? and cleared cache after doing so.

**Comment by balsman225** [comment]
I am currently running 0.3.0
I installed the custom card for the first time last week but I can try to remove and re-add to test.

**Comment by kalkih** [comment]
Please let me know browsers and browser version.

**Comment by balsman225** [comment]
iOS App (1.5.0) on iOS 12.1.4
Safari on iOS 12.1.4 
Safari (12.0.3) on MacOS 10.14.3
Chrome (72.0.3626.119) on MacOS 10.14.3
Firefox (65.0.1) in MacOS 10.14.3
Chrome (72.0.3626.121) on Windows Server 2016
Chrome (69.0.3497.100) on Android 6.0.1

**Comment by kalkih** [comment]
I'm not able to reproduce this issue, tried on Firefox, Chrome & Safari on macOS and Chrome on Android. (changed the yellow threshold to 25 for testing purposes)

![hyperion_8123_lovelace_4 (46)](https://user-images.githubusercontent.com/457678/54284656-a3ff1d00-45a0-11e9-9cee-fc6f6886552f.png)

Your issue sounds very similar to #52 & #54 but they were addressed with 7d65869b4fc93945c9e912f8bbb39a5c5c5ee43d

**Comment by balsman225** [comment]
Thank you for the reply. 
I will do some additional test when I can and spin up a separate HASS instance to try.

**Comment by Human** [comment]
I just started using this custom card today, version 0.3.2, and I'm having the same issue in Chrome and Firefox (desktop and mobile). HASS 0.90.2

**Comment by kalkih** [comment]
@Human, can you send me the card config and a screenshot of the issue.

**Comment by Human** [comment]
@kalkih  I checked it again, and I did see the colors change, but not when they should have according to the raw data. So I think this bug is actually user confusion (including myself) as to how the raw data maps to the graph card.

For example, I had a sensor value that spiked to 209 at 3:31, but the card shows green (below 160) until 3:55. My guess is that if people have data that fluctuates a lot, they might not see the colors change.

My config:
```
type: 'custom:mini-graph-card'
entities:
  - sensor.ch4
show:
  graph: true
  fill: true
  extrema: true
color_thresholds:
  - value: 155
    color: '#770000'
  - value: 140
    color: '#007700'
  - value: 0
    color: '#00ff00'
```

![ch4_card](https://user-images.githubusercontent.com/40866/55282187-b8b81080-5315-11e9-8eed-c30693720400.png)

![ch4_raw](https://user-images.githubusercontent.com/40866/55282188-b950a700-5315-11e9-8050-9ad5ef45c29e.png)
