### ISSUE TITLE
Bug: binary input in v0.11.0

### ISSUE THREAD

**Issue by Saentist** [kalkih/mini-graph-card#701]
After update to latest version v0.11.0 card refuse to use day/night binari sensor.

message 
```yaml
mini-graph-card
Entity not available: input_number.nighttime
```
In version v0.10.0 there was no problem.

**Comment by jlsjonas** [comment]
Hi, thanks for your report.
Could you please provide your full card configuration & can you please confirm that the entity does (still) exist?

**Comment by Saentist** [comment]
Entity exist im use it in other cards

```yaml
  - type: custom:mini-graph-card
    name: Temperature
    icon: mdi:thermometer-lines
    hour24: true
    line_width: 2
    animate: true
    entities:
      - entity: sensor.outdoor_temperature
      - entity: input_number.nighttime
        name: Night
        show_line: false
        show_points: false
        show_legend: false
        y_axis: secondary
    hours_to_show: 168
    show:
      fill: true
      extrema: true
      labels: true
      labels_secondary: true
    color_thresholds:
      - value: -5
        color: '#1286f3'
      - value: 0
        color: '#e317c4'
      - value: 15
        color: '#f5f1a9'

```
