### ISSUE TITLE
A new "state: last" option gives confusing result

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#707]
A new `show -> state: last` option gives different results.
[FR for the "last" option.](https://github.com/kalkih/mini-graph-card/pull/677l)
A believed that the `last` option should be used basically for `delta` & `diff` aggregations.
In my case values for "last state" & "current state" should be same.
```
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.cleargrass_1_co2
    hours_to_show: 1
    line_width: 2
    points_per_hour: 120
    aggregate_func: last
    show:
      state: true
      points: true
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.cleargrass_1_co2
    hours_to_show: 1
    line_width: 2
    points_per_hour: 120
    aggregate_func: last
    show:
      state: last
      points: true
```
![image](https://user-images.githubusercontent.com/71872483/150986481-dd8be1f5-a6e7-457a-bb00-8f0663216a0f.png)
The sensor is updated every 30 sec.
