### ISSUE TITLE
[FR] Add option to hide "0" values from bar graph

### ISSUE THREAD

**Issue by farberm** [kalkih/mini-graph-card#714]
How do I remove the "0" value bars from being displyed? I just want the bars that are positive

Current Code:
```
align_state: center
animate: true
entities:
  - entity: sensor.pool_filling
    aggregate_func: sum
    smoothing: false
hours_to_show: 24
name: Pentiar Pool Filing
type: custom:mini-graph-card
show:
  graph: bar
group_by: hour
```
<img width="421" alt="Screen Shot 2022-01-31 at 2 20 48 PM" src="https://user-images.githubusercontent.com/16128857/151858721-22092437-4e69-48db-9f83-4073fe789593.png">

**Comment by StormyKnight17** [comment]
Also the ability to hide -1 as I have a HDD temp sensor that once the HDD goes to sleep it returns -1 as the temp. I want to keep that in the history, but not necessarily graph it.

**Comment by ildar170975** [comment]
> Also the ability to hide -1

List of "bad values" may be endless.
These values are supposed to be filtered on a template sensor's level first.

**Comment by StormyKnight17** [comment]
Ok, sounds reasonable. 

Cheers
Richard

**Comment by ildar170975** [comment]
Reopened due to this request - https://github.com/kalkih/mini-graph-card/issues/800

**Comment by Alex-joomla** [comment]
Is there a way to hide those zero bars? In my opinion if the value is zero then the only thing one should see is the axis or nothing than an empty column.

**Comment by dddesign** [comment]
is there a solution?

**Comment by Alex-joomla** [comment]
Unfortunately not as far as I can see :-(

**Comment by ildar170975** [comment]
The issue is closed automatically as "stale".
No sense to comment here.
If you need this functionality - then you should have monitored it and prevent it closing.

**Comment by mendoncart** [comment]
Hi!

I had to follow @pachi81 suggestion on #722 

```
color_thresholds:
  - value: 0
    color: dark-grey
  - value: 0.1
    color: orange
```

![image](https://user-images.githubusercontent.com/62950083/236231691-c0104b4b-6a52-4420-9bf4-32f38d0c49f8.png)

Every issue I've seen about it, point it back to this one, that is closed without conclusion.
Nobody said that it would be implemented or not, so I still have hope.
I don't know if I have to open a new ticket, because all the new tickets were close due to this one...

I just want a way do deal with zero values. Ignore it and don't plot a line or bar for them.
If there's no data, should be no bar/line. A tiny bar implies that is tiny data there, witch does not.

**Comment by ildar170975** [comment]
> that is closed without conclusion.

What conclusion do you expect?
This is a FR.
Nobody who asked about it bothred to monitor the issue to prevent it to become "stale".
I will reopen it. But you need to un-stale it periodically.

**Comment by mendoncart** [comment]
> What conclusion do you expect?

I've said it on my message:
Conclusion: will be added, or, will not be added.

I'll try to monitor this post, I'm already subscribed to it.
But would it be nice if there was a "todo list" or a road map for this (if it's worthy to implement) to be added to.
We don't know if who originally requested this is still alive, same thing can happen to me.
So depending on who requested to follow up is not the most effective way to keep an feature request alive.

But then again, I'm asking for improvements in something that already was given for free, so, I don't want to be ungrateful.
I don't know how to implement this myself, but at least I can monitor this thread.

Thanks, and if there's anything more for me to do, please tell.

**Comment by ildar170975** [comment]
> So depending on who requested to follow up is not the most effective way to keep an feature request alive.

Everyone may un-stale an issue, not the author only.
Everyone who is interested in this functionality.

> Conclusion: will be added, or, will not be added.

OK, here is a conclusion: may be will be added in future in case of a presence of a clear algorithm & absence of conflicts with other functionality.
Currently we do not have lots a developers who may spend his time for even MAINTAINING the project (not to mention FRs).
Everyone is more than welcome to join & participate.
So, in these circumstances it is not easy to say "here is a roadmap, it will be ready by this date".

**Comment by mendoncart** [comment]
Keeping the FR "fresh".

![image](https://github.com/kalkih/mini-graph-card/assets/62950083/c877cd0b-538c-4ca2-b055-3021d4e47d12)

I've noticed, that this graph goes "below" the min value, so it gets hidden.
But this doesn't work to hide 0 values if I set the lower_bound to 1.

Code:
```type: custom:mini-graph-card
icon: mdi:server
name: SERVER
hour24: true
hours_to_show: 24
points_per_hour: 2
align_icon: name
align_state: left
state_adaptive_color: true
decimals: 1
lower_bound: 33
entities:
  - entity: sensor.sistema_temperatura_temperature
    name: Temperatura
    unit: ºC
show:
  labels: true
  icon_adaptive_color: false
color_thresholds:
  - value: 40
    color: '#cf2f1f'
  - color: '#ff6c00'
  - value: 35
    color: '#ecf00a'
  - value: 33
    color: '#00FF23'```

**Comment by mendoncart** [comment]
Keeping the FR "fresh".

**Comment by Alex-joomla** [comment]
@lidar unfortunately not

**Comment by danvy** [comment]
Here's a workaround:

<img width="546" height="257" alt="Image" src="https://github.com/user-attachments/assets/43aba95c-8480-4922-bad1-e84986cc9514" />

```
type: custom:mini-graph-card
name: Electricity instant
show:
  graph: bar
color_thresholds:
  - value: 0
    color: transparent
  - value: 0.1
    color: orange
entities:
  - entity: sensor.electricity_counter_low_instant
    name: Low
    color: green
    show_state: false
```
The key is to use color_thresholds and transparent color.
