### ISSUE TITLE
bar chart shows wrong values

### ISSUE THREAD

**Issue by miroslavpetrov** [kalkih/mini-graph-card#722]
I am using mini-graph-card with bars to show the energy usage in kwh for the last 31 days.
I am running the counter for around 24 hours now and the problem is that for the days before the 24h period the bar chart shows 0.02kwh as daily consumption instead of zero. Here is the config of the card and a screenshot:
```
type: custom:mini-graph-card
entities:
  - sensor.itd_meter_1_total_energy_daily
name: Дневна консумация
show:
  graph: bar
  extrema: false
  average: false
  labels: false
hour24: true
hours_to_show: 744
group_by: date
```
![Screenshot 2022-02-09 at 10 30 17](https://user-images.githubusercontent.com/25277610/153156481-378cd38d-e6d9-43a6-96ac-076096fc1f97.png)

**Comment by jlsjonas** [comment]
:thinking: Could you try with `smoothing: false`?

**Comment by ildar170975** [comment]
Btw, should the `smoothing` option be disabled in case of bars?

**Comment by patman15** [comment]
Hi!

I think, I have a similar issue with v0.11.0: Sometimes (not figured out when) the card shows instead of 0 the value of the last bar:
![screenshot](https://user-images.githubusercontent.com/14628713/163966488-66682db9-ca95-442c-9109-661e34d543dd.png)

The value (state) is only updated on bars that are non-zero. For bars that should be zero the value of the last bar is shown.

```
type: custom:mini-graph-card
entities:
  - entity: sensor.wasser_stundlich
    color: blue
group_by: hour
lower_bound: 0
points_per_hour: 1
hour24: true
hours_to_show: 48
aggregate_func: max
smoothing: false
show:
  graph: bar
```

**Comment by pachi81** [comment]
I have the same issue for my raining history. `smoothing: false` does not change anything. 
I have two workarounds for this problem:
1. Using `lower_bound: 0.2` (works for me, because the min rain detection is 0.2 in my case)
2. Make such values dark (depending on the theme):
```
color_thresholds:
  - value: 0
    color: dark-grey
  - value: 0.1
    color: blue
```
![image](https://user-images.githubusercontent.com/56817032/165243526-ef790a64-cbcc-4445-8ae3-140be3c4569a.png)
