### ISSUE TITLE
24 hours mode?

### ISSUE THREAD

**Issue by MrGlad8** [kalkih/mini-graph-card#724]
Hey! Its seems that the time stamps is in AM/PM but my settings and HA Logs are all in 24 hour mode. How come?

**Comment by pdwonline** [comment]
Seems to me that you could use the hour24 parameter like:

```
  - type: custom:mini-graph-card
     hour24: true
     entities:
          - entity: sensor.favourite

```
