### ISSUE TITLE
Only show today

### ISSUE THREAD

**Issue by pdwonline** [kalkih/mini-graph-card#726]
I want to show only todays values and hoped to manipulate the hours_to_show parameter with a template to only show up to the current hour like this:

```

  - type: custom:mini-graph-card
    min_bound_range: 50
    logarithmic: true
    hours_to_show: '{{ now().hour |int(0) }}'
    show:
      name: false
      icon: false
    entities:
      - entity: sensor.cv_burnrate
  
```
Unforunately it didn's work. How can I achieve this? Or is this a feature request?
