### ISSUE TITLE
Suddenly Mini Graph Doesn't Work.

### ISSUE THREAD

**Issue by spencerthayer** [kalkih/mini-graph-card#729]
This configuration was working perfectly for months and suddenly it's stopped working with the latest version of HA. Did something change with a recent update of this addon?

```yaml
type: entities
entities:
  - type: attribute
    entity: sensor.airnow_aqi
    attribute: description
    name: AIR QUALITY INDEX
    icon: mdi:blur
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.airnow_aqi
        type: attribute
        icon: mdi:blur
        attribute: description
        show_state: true
        state_adaptive_color: true
        animate: true
        line_width: 2
        hours_to_show: 24
        points_per_hour: 2
        show:
          name: false
          icon: false
          graph: line
          labels: false
          labels_secondary: false
          name_adaptive_color: true
          icon_adaptive_color: true
          average: true
          extrema: true
    color_thresholds:
      - value: 0
        color: '#f2fffb'
      - value: 12.5
        color: '#d6fffb'
      - value: 25
        color: '#00c853'
      - value: 51
        color: '#ffeb3b'
      - value: 101
        color: '#ff6f00'
      - value: 151
        color: '#ff3d00'
      - value: 201
        color: '#d500f9'
      - value: 301
        color: '#ab025b'
      - value: 500
        color: '#770a3f'
  - entity: sensor.allergy_index_today
  - entity: sensor.asthma_index_today
```
