### ISSUE TITLE
align_state not working correctly

### ISSUE THREAD

**Issue by Tek4Seth** [kalkih/mini-graph-card#731]
Hi,

When i add a graph in a horizontal-stack, align_state not working correctly.

br

**Comment by ildar170975** [comment]
![image](https://user-images.githubusercontent.com/71872483/153837566-f00d0e46-859b-4f21-8e0b-42919f61f34c.png)
```
type: horizontal-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.cleargrass_1_co2
    hours_to_show: 6
    points_per_hour: 60
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.cleargrass_1_co2
    hours_to_show: 6
    points_per_hour: 60
    align_state: center
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.cleargrass_1_co2
    hours_to_show: 6
    points_per_hour: 60
    align_state: right
```

what is wrong?
