### ISSUE TITLE
Graph not rendering when using 'last' as show state

### ISSUE THREAD

**Issue by tomkessler** [kalkih/mini-graph-card#736]
I have always increasing sensors for internet upload and download and I'm trying to make an hourly upload and download bar graph.  Everything works great except I'm trying to have the latest graph values show for the state rather than the actual sensor state values (as they are meaningless ... total upload and download since last router reboot).  If I change the show > state to true or false, everything is fine; it doesn't seem to like 'last' although that is the setting according to the docs which will render what I'm looking for.

I'm on the latest version of HA (2022.2.8), HACS, and the mini graph card.

```
type: custom:mini-graph-card
entities:
  - entity: sensor.asuswrt_download
    name: Download
    color: '#595BBD'
    show_state: true
  - entity: sensor.asuswrt_upload
    name: Upload
    color: '#CD90EA'
    show_state: true
show:
  state: last
  graph: bar
  labels: true
  legend: false
hours_to_show: 24
group_by: hour
aggregate_func: diff
name: Hourly Internet Bandwidth Used
icon: mdi:wan
```

This image is with the show > state set to true and everything looks good except the sensor states are showing.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/20233788/154811840-6a66b778-4bea-4591-9bac-cdc2d84d58d9.png">
