### ISSUE TITLE
Graph with aggregate_func: diff should show diff value instead of total value

### ISSUE THREAD

**Issue by EmJay276** [kalkih/mini-graph-card#738]
Hi, I have a sensor for my total energy consumption and I am trying to rebuild the "energy-usage-graph" from the energy dashbaord with the mini-graph-card. 

Using the "aggregate_func: diff" option works fine, but the value shown is still the total value instead of the diff value.

Plotting the energy consumption within the last 24h gives this graph (realy nice!), but the total power consumed (within the last 24h) is not "75,29 kWh" (this is the total value sind start of the sensor).
![grafik](https://user-images.githubusercontent.com/8619525/155034244-84cf5ace-a56b-45cf-9e2b-cc12e4680676.png)

```
type: custom:mini-graph-card
entities:
  - entity: sensor.energy_total
    aggregate_func: diff
color_thresholds:
  - value: 0
    color: '#2ecc71'
  - color: '#f1c40f'
  - value: 1
    color: '#e74c3c'
hour24: true
points_per_hour: 1
lower_bound: 0
hours_to_show: 24
```

I would expect to show the power consumed within the last 24h, which is roughtly 6 kWh.
Any suggestions hot to solve this?

**Comment by jlsjonas** [comment]
Hey, the graph shows the current state by default indeed
We do have a `last` option to show the value of the last graph point instead but you'd like a `current - starting` value, right?

```
show:
    state: last
```
Should already give you the last instead of current state, hope this helps for now.

Putting the extra feature on our radar!

**Comment by EmJay276** [comment]
> Hey, the graph shows the current state by default indeed We do have a `last` option to show the value of the last graph point instead but you'd like a `current - starting` value, right?
> 
> Putting the extra feature on our radar!

Hey, 

a `current - starting` value is exactly what I am looking for (and expecting as default when I'm using the `aggregate_func: diff`)
Thanks for adding!


Cause you mentionied:
Using the `state: last` results in a nice graph for a `group_by: date` graph for several days :+1:, 
but the value is not correct. It should be 7.47 kWh is 8.09 kWh. If I use `smoothing: false` the value 7.47 kWh is correct. Already mentioned in https://github.com/kalkih/mini-graph-card/issues/659, https://github.com/kalkih/mini-graph-card/issues/722 

# smoothing: true
```
type: custom:mini-graph-card
entities:
  - entity: sensor.energy_total
    aggregate_func: diff
color_thresholds:
  - value: 0
    color: '#2ecc71'
  - color: '#f1c40f'
  - value: 14
    color: '#e74c3c'
hour24: true
lower_bound: 0
hours_to_show: 240
show:
  state: last
group_by: date
```
![grafik](https://user-images.githubusercontent.com/8619525/155223368-13af6d7e-f4a0-4ed4-a761-faff4c394f69.png)

# smoothing: false
```
type: custom:mini-graph-card
entities:
  - entity: sensor.energy_total
    aggregate_func: diff
color_thresholds:
  - value: 0
    color: '#2ecc71'
  - color: '#f1c40f'
  - value: 14
    color: '#e74c3c'
hour24: true
lower_bound: 0
hours_to_show: 240
show:
  state: last
group_by: date
smoothing: false
```
![grafik](https://user-images.githubusercontent.com/8619525/155224715-407e6b3c-c4bb-4e60-b6a5-7fc1fdef91cf.png)
