### ISSUE TITLE
Request: add switch button

### ISSUE THREAD

**Issue by craigueh** [kalkih/mini-graph-card#74]
Love this custom gauge card, I use it for monitoring hot water temp in cylinder with a sonoff th10.
It would be really sweet if I could add a power toggle to the card to call a switch to turn on hot water as required. Currently I have to add it as a separate entity card and it takes up unnecessary space.

**Comment by kalkih** [comment]
Hey, I feel like this is a little out of scope for this card.
The card is built for sensor entities, and they usually don't have an on/off state to toggle.
This would require us to keep track of an additional entity and it's state plus add additional logic.

I would recommend wrapping a toggle-entity-row and a mini-graph-card inside an [vertical-stack-in-card](https://github.com/custom-cards/vertical-stack-in-card), and then hide the name and icon of the mini-graph-card.

```yaml
- type: custom:vertical-stack-in-card
  cards:
    - type: custom:hui-toggle-entity-row
      entity: switch.water_heater
    - type: custom:mini-graph-card
      entities:
        - sensor.water_temp
      show:
        name: false
        icon: false
````
![hyperion_8123_lovelace_4](https://user-images.githubusercontent.com/457678/54547921-085a1c00-49a7-11e9-89d6-fadddaf7ac9d.png)

You could potentionally also throw in [card-modder](https://github.com/thomasloven/lovelace-card-modder) to make the margins/paddings more unified.
