### ISSUE TITLE
Labels for secondary Y-axis: align right

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#741]
Currently labels for both primary & secondary Y-axis are left-aligned:
![изображение](https://user-images.githubusercontent.com/71872483/155400142-fba9a2bb-9bae-408b-b779-fefe15275c61.png)
```
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.cleargrass_1_temperature
        name: Temp
      - entity: sensor.cleargrass_2_co2
        name: CO2
        y_axis: secondary
    lower_bound: ~0
    lower_bound_secondary: ~0
    show:
      labels: true
      labels_secondary: true
```
It does not look fine if the max value is huge.

I think that for the secondary Y-axis the labels should be right-aligned:
![изображение](https://user-images.githubusercontent.com/71872483/155400189-741d95e9-f01b-4cdf-a261-3beb5052727f.png)

Currently I may achieve it by `card-mod` but it is better to have it permanently:
```
    card_mod:
      style: |
        .graph .graph__container .graph__labels.--secondary.flex {
          align-items: flex-end;
        }
```
