### ISSUE TITLE
lower_bound may cause wrong Y-axis labels

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#743]
There is a sensor `sensor.vmdebian_integration_availability_status_reversed` which may be `1` or `0`.
Here is a history for the last 72 hrs - the sensor was `1` a few times at the beginning of the timeline:
![изображение](https://user-images.githubusercontent.com/71872483/155550742-103fe9e4-0bb9-48e1-9b28-7baa55e14c34.png)
```
type: custom:mini-graph-card
entities:
  - entity: sensor.vmdebian_integration_availability_status_reversed
    color: red
    show_line: false
hours_to_show: 72
points_per_hour: 60
smoothing: false
aggregate_func: last
line_width: 1
lower_bound: 0
show:
  fill: true
  labels: true
```

Let's reduce the `hours_to_show` to 50 hrs.
Since the `1` values were earlier we cannot see them:
![изображение](https://user-images.githubusercontent.com/71872483/155551051-1f089a95-71d7-4642-8a81-0ebd0e1b538a.png)
So far it seems to be OK.

But let's change `lower_bound: 1`:
```
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.vmdebian_integration_availability_status_reversed
        color: red
        show_line: false
    hours_to_show: 50
    points_per_hour: 60
    smoothing: false
    aggregate_func: last
    line_width: 1
    lower_bound: 1
    show:
      fill: true
      labels: true
```
![изображение](https://user-images.githubusercontent.com/71872483/155551833-82e783d8-4c42-4aea-8b72-f895fb38385d.png)
Check that the Y-axis labels are in a reversed order, and the graph seems to be WRONG.

This is a synthetic example but it shows some wrong behaviour.
