### ISSUE TITLE
Feature request: Custom values for state

### ISSUE THREAD

**Issue by mbrammer** [kalkih/mini-graph-card#744]
It would be nice to have the possibility to show custom values as the state. Currently there is just a state mapping available.

![image](https://user-images.githubusercontent.com/2786547/155730505-0920985f-130c-48b4-9eb0-5296eb18afaa.png)

I have following cases, where I would like to show a spacial state value.
1. The screenshot above shows the last 12 hour yield of my photovoltaics. As the state value, I do not care about the current yield. I would like to see the summed yield value of the last 12 hours like this: **1.06 kWh**.
2. Below you see a screenshot of the card with temperature values of several rooms in my appartment. Here I would like to see the average temperature of the four rooms from **now**. In this case **20,9 °C**. By default the card is displaying the current value of the livingroom.

![image](https://user-images.githubusercontent.com/2786547/155731490-c44fbfc1-7a86-4bf4-afbb-26d47e3fabf4.png)

**Comment by ildar170975** [comment]
It is possible NOW by using this alternative method:
1) Create a template sensor to calculate a required parameter.
2) Add this sensor on the same "mini-graph-card"; probably it is better to set it for the secondary axis.
3) Define "show_state: true" & "color: transparent" for the sensor.
4) For other sensors - "show_state: false".

Untested; try it by yourself.

**Comment by kalkih** [comment]
Alternatively, put the sensor you want to have displayed in the state as the first entity in the card configuration, set `show_graph: false` for that entity configuration.

**Comment by ildar170975** [comment]
@kalkih
Great remark!
Same output but your solution causes less CPU load & more effective!
```
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.cleargrass_1_humidity
        show_state: true
        show_points: false
        show_legend: false
        color: transparent
        y_axis: secondary
      - &ref_entity_co2_1
        entity: sensor.cleargrass_1_co2
        color: green
        show_state: false
        show_points: false
        name: CO2-1
      - &ref_entity_co2_2
        entity: sensor.cleargrass_2_co2
        color: orange
        show_state: false
        show_points: false
        name: CO2-2
    <<: &ref_settings
      name: Humidity
      hours_to_show: 4
      points_per_hour: 60
      lower_bound: ~400
      aggregate_func: last
      smoothing: false
      line_width: 1
      height: 200
      show:
        name: true
        legend: true
        icon: false
        labels: true
        labels_secondary: false
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.cleargrass_1_humidity
        show_state: true
        show_points: false
        show_legend: false
        show_graph: false
      - *ref_entity_co2_1
      - *ref_entity_co2_2
    <<: *ref_settings
```
![изображение](https://user-images.githubusercontent.com/71872483/155765841-eff10c00-44e0-4474-a947-0f4ceffc6b93.png)
