### ISSUE TITLE
bug(color_thresholds): defaults to black instead of closest out-of-bounds color

### ISSUE THREAD

**Issue by alnavasa** [kalkih/mini-graph-card#764]
I have a graph meant to graph wind speed in different colors as you can see in the code. 
Though I find myself with an issue, if the color threshold value its not reached, the color it uses is black until (if it ever does) reaches the next value, In the image below you can see that in never reached purple color value, and therefore it started graphing towards black, if it ever reached the purple value, then the graph would be render towards that color. 

How can I fix this? 

Am I doing something wrong or is this an issue with the card

<img width="433" alt="Captura de pantalla 2022-03-17 a las 11 18 06" src="https://user-images.githubusercontent.com/458370/158788644-3f93d9fe-ec0e-45f7-b609-f2b42cbe2e90.png">

```

  - type: custom:mini-graph-card
    entities:
      - entity: sensor.aemet_wind_speed_kts
      - entity: sensor.aemet_wind_bearing
        show_state: true
        y_axis: secondary
        color: var(--accent-color)
    name: Viento 7d
    icon: mdi:weather-windy
    line_width: 1
    font_size: 70
    animate: true
    color_thresholds:
      - value: 5
        color: '#0095a6'
      - value: 10
        color: green
      - value: 16
        color: orange
      - value: 24
        color: red
      - value: 30
        color: purple
    hours_to_show: 168
    points_per_hour: 0.2
    lower_bound_secondary: 0
    upper_bound_secondary: 360
    show:
      average: true
      legend: false
      extrema: true
```

**Comment by StormyKnight17** [comment]
I noticed this too, it seems that color names don't always work. If I use '#######' it does render correctly for me.

**Comment by alnavasa** [comment]
> I noticed this too, it seems that color names don't always work. If I use '#######' it does render correctly for me.

That did the trick, but it needs to get solved.

**Comment by scyto** [comment]
ahh, i was wondering why all my color threshold names suddenly stopped working
+1 on issue here (i am using red / yellow / blue and only getting a black line)

**Comment by jlsjonas** [comment]
> it seems that color names don't always work

Could you please add information about which cases the "text colors" no longer work; _not always_ is sadly enough a bit too vague to fix ;)

**Comment by Fillius** [comment]
I have just encountered this issue. I have a temperature sensor which in the past 24 hours had recorded 10.1 as its lowest value. I tried setting a colour threshold of "blue" that started at 0 and ended at 15 but it showed as black. I tried changing the colour to "red", "green", "orange" etc. none of which worked. Changing the value to 11 (higher than the 10.1 minimum recorded value) fixed it. After seeing this issue, I changed it to use hex codes which has fixed it.

**Comment by kate-shine** [comment]
> > it seems that color names don't always work
> 
> Could you please add information about which cases the "text colors" no longer work; _not always_ is sadly enough a bit too vague to fix ;)

It doesn't work for me as well. Basically, until the threshold value is reached - threshold value becomes part of the graph, the graph color stays black.
Example: My setting for CO2:
```
type: custom:mini-graph-card
entities:
  - sensor.co2_air_quality
color_thresholds:
  - value: 600
    color: green
  - value: 1000
    color: orange
  - value: 1500
    color: red
```

Until my CO2 value reaches 1500, upper values fade to black.

It can be worked around by forcing graph to always contain those values
(setting upper ad lower bound), but it's really just a workaround.

**Comment by ildar170975** [comment]
My case:
```
type: custom:mini-graph-card
entities:
  - sensor.xiaomi_cg_1_co2
points_per_hour: 120
hours_to_show: 1
line_width: 1
show:
  points: false
  labels: true
color_thresholds_transition: hard
color_thresholds:
  - value: 575
    color: green
  - value: 582
    color: orange
  - value: 592
    color: red
```
First - when I lower bound (568) is LESS than the 1st threshold (575):
![image](https://user-images.githubusercontent.com/71872483/193939770-0576d0ed-a153-4ffa-a1e2-7a05e47b8b75.png)

Everything seems OK.

A bit later - a lower bound (577) is MORE than the 1st threshold (575):
![image](https://user-images.githubusercontent.com/71872483/193939931-9aaa9d82-e759-457c-a7be-b888d0ce186d.png)

The lower part of the graph is of BLACK color.

**Comment by StormyKnight17** [comment]
Yes, hex rgb is not as user friendly 😊

Cheers
Richard

**Comment by jlsjonas** [comment]
Sadly enough I'm having a hard time reproducing the issue...

Could someone try to reproduce it on a demo instance of HA?
Attempted with several iterations of the following config:
```yaml
      - type: custom:mini-graph-card
        hours_to_show: 1
        points_per_hour: 120
        lower_bound: 0
        upper_bound: 1000
        smoothing: false
        height: 600
        show:
          extrema: true
        entities:
          - entity: sensor.random_0_1000
            name: log(150 - 1000) Simple
            aggregate_func: last
        color_thresholds:
          - value: 0
            color: green
          - value: 200
            color: red
          - value: 1000
            color: blue
```
ended up with:
![image](https://user-images.githubusercontent.com/932193/201527793-d70ec74a-7534-4e3b-bd55-00449876d0d9.png)

**Comment by NickdeK** [comment]
Also ran into this issue. It seems it has to do with the threshold value somehow. If I set the 1500 value to anything below 1060 it seems to change a bit.

![image](https://user-images.githubusercontent.com/6631170/219318871-25bc60fc-44f8-4df1-b2ee-c4cc938ce897.png)
<details>
  <summary>Code</summary>
  ```yaml
type: custom:mini-graph-card
name: CO2
icon: mdi:molecule-co2
hour24: true
hours_to_show: 12
decimals: 0
show:
  legend: false
entities:
  - entity: sensor.awair_element_74851_carbon_dioxide
    show_state: true
    state_adaptive_color: true
color_thresholds:
  - value: 0
    color: var(--success-color)
  - value: 600
    color: var(--warning-color)
  - value: 1500
    color: var(--error-color)
  ```
</details>

![image](https://user-images.githubusercontent.com/6631170/219318913-a46300d4-27d5-40f8-81eb-676298db6174.png)
<details>
  <summary>Code</summary>
  ```yaml
type: custom:mini-graph-card
name: CO2
icon: mdi:molecule-co2
hour24: true
hours_to_show: 12
decimals: 0
show:
  legend: false
entities:
  - entity: sensor.awair_element_74851_carbon_dioxide
    show_state: true
    state_adaptive_color: true
color_thresholds:
  - value: 0
    color: var(--success-color)
  - value: 600
    color: var(--warning-color)
  - value: 1059
    color: var(--error-color)
  ```
</details>

Setting a hex code seems to work indeed.
