### ISSUE TITLE
Wrong history graph, if values missing

### ISSUE THREAD

**Issue by pachi81** [kalkih/mini-graph-card#778]
Hi,

maybe it is a configuration issue from my site or there is a workaround for this case, but I haven´t found one.
I collect the daily rain with a rain gauge using mqtt. This will reset every day at 0:00 to zero. 

The problem is, if there was no rain for the recording time (10 days), there are no data in the database. The graph shows zero over the time, which is correct, but after the first day it rains, the graph shows the same value for the days before (in the picture, the first day with rain, was 24.04.):
![image](https://user-images.githubusercontent.com/56817032/165245152-b44d8e57-88db-431b-a0b7-82307094c9bc.png)

The current detected values are visible in the HA graph:
![image](https://user-images.githubusercontent.com/56817032/165245605-49c68e7f-e5c9-49fd-9daf-b8e705c6a467.png)

The rain starts at April, 24th... and there is no value before (I think because of the 10 days purge configuration of the recorder, which will delete the oldest values and there was no rain for the last 10 days).
Is there any option to force setting zero to database for each day? Or is there any way for setting a default value (0 in my case) in the mini-graph-card configuration?

**Comment by hcrohland** [comment]
I have a similar problem: 
My temperature sensor lost connectivity for some hours:
![Bildschirmfoto 2022-06-05 um 11 56 58](https://user-images.githubusercontent.com/18126119/172045098-22f0b95d-9892-43cf-957d-d0f695abb55e.png)

And now the card shows a constant temperature since then:

![grafik](https://user-images.githubusercontent.com/18126119/172045254-70d78f60-b8f5-4930-9ac5-dabe173c4ae0.png)


Config is:

```
type: custom:mini-graph-card
entities:
  - entity: sensor.ausentemperatur_temperature
    show_fill: false
  - entity: sensor.ausentemperatur_humidity
    show_fill: false
    show_state: true
    y_axis: secondary
upper_bound_secondary: 100
name: Wetter
icon: mdi:home-thermometer-outline
```
