### ISSUE TITLE
`Color_tresholds` not works with paralelly used `state_map`

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [kalkih/mini-graph-card#780]
Hi!

First of all I would like to throw a very big 'thanks' for your work(s) as this card is almost the only card type in my HA config and I really love it. So really lot of thanks for your efforts so far!

But from another aspect I got a soft problem at my use cases.

Environment:

- Home Assistant 2022.4.7 _('Core' through Docker)_
- Latest 0.11.0 'Mini Graph Card' _(through HACS)_

If we use `state_map`s we can not use `color_tresholds` with them _(and I do not really see the reason of that)_, as the result is always the usage of the defined color in the thresholds object. Check the following sample.

The config:

```
type: custom:mini-graph-card
entities:
  - entity: sensor.u_s_air_pollution_level
    name: Air quality
font_size_header: 10
font_size: 66
hour24: true
height: 50
line_width: 1
hours_to_show: 168
align_state: center
show:
  labels: false
color_thresholds:
  - value: hazardous
    color: '#ff3d00'
  - value: very unhealthy
    color: '#ffff00'
  - value: unhealthy
    color: '#ffff00'
  - value: unhealthy for sensitive groups
    color: '#ffff00'
  - value: moderate
    color: '#ffff00'
  - value: good
    color: '#64dd17'
state_map:
  - value: hazardous
    label: Hazardous
  - value: very unhealthy
    label: Very unhealthy
  - value: unhealthy
    label: Unhealthy
  - value: unhealthy for sensitive groups
    label: Unhealthy for sensitive groups
  - value: moderate
    label: Moderate
  - value: good
    label: Good
```

And the result:
![image](https://user-images.githubusercontent.com/25765137/165704378-702c05a5-34f6-4e5d-9265-48375e65081a.png)

Could anybody please help on it? Thanks for it in advance!
