### ISSUE TITLE
feat(state_map): support for ranges

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [kalkih/mini-graph-card#781]
Hi!

I would like to drop a 'small' **feature request** if possible.

Could you please allow intervals in `state_map` value definitions? In this case we could transform our numeric values to some talkative alternates like:

```
type: custom:mini-graph-card
entities:
  - entity: sensor.u_s_air_quality_index
    name: Air quality
font_size_header: 10
font_size: 66
hour24: true
height: 50
line_width: 1
hours_to_show: 168
align_state: center
show:
  labels: false
color_thresholds:
  - value: 0
    color: '#64dd17'
  - value: 51
    color: '#ffff00'
  - value: 101
    color: '#ffff00'
  - value: 151
    color: '#ffff00'
  - value: 201
    color: '#ffff00'
  - value: 301
    color: '#ff3d00'
state_map:
  - value: 301-
    label: Hazardous
  - value: 201-300
    label: Very unhealthy
  - value: 151-200
    label: Unhealthy
  - value: 101-150
    label: Unhealthy for sensitive groups
  - value: 51-100
    label: Moderate
  - value: 0-50
    label: Good
``` 

This would give us lot more of flexibility.

_(The example above is just an example for illustration the request. Of course we already have such 'text like' results from air quality sensors...)_

Thanks for your time!
