### ISSUE TITLE
Feature Request: Allow using the card as footer in entities card

### ISSUE THREAD

**Issue by microraptor** [kalkih/mini-graph-card#783]
Is it possible to use mini-graph-card as a graph in the footer of an entities card somehow, instead of the normal graph element?

It is possible to use the mini-graph-card as last entity in the entities card, but then there are these paddings at the sides and bottom :
![image](https://user-images.githubusercontent.com/15663536/166000037-c8529759-cfef-40a0-bb97-d113b47e23c2.png)

```yaml
type: entities
entities:
- type: custom:mini-graph-card
  entities:
  - sensor.example1
  - sensor.example2
  show:
    name: false
    icon: false
    state: false
    legend: false
```

Instead it would be nice to have it look like the standard footer graph element (but with the mini-graph-card options like two lines):
![image](https://user-images.githubusercontent.com/15663536/166000260-f8f7c8bc-360c-47e9-9260-8d642c2a89d9.png)

```yaml
type: entities
footer:
  type: graph
  entity: sensor.example1
```

**Comment by ildar170975** [comment]
> ```yaml
> type: entities
> entities:
> - type: custom:mini-graph-card
> ```

Do not think this is a proper use.
Try using a custom:stack-in-card with required settings:
- entities card
- mini-graph-card

**Comment by microraptor** [comment]
Thanks, that works perfectly.

The code (vertical-stack-in-card has to be installed through HACS):

```yaml
type: custom:vertical-stack-in-card
cards:
  - type: custom:mini-graph-card
    entities:
    - sensor.example1
    - sensor.example2
    show:
      name: false
      icon: false
      state: false
      legend: false
```
