### ISSUE TITLE
mini-graph-card showing wrong data after upgrade to HA 2022.6.1

### ISSUE THREAD

**Issue by stalakerob** [kalkih/mini-graph-card#797]
This is showing the same data in the stock graph and mini-graph-card. Obviously the mini-graph-card is wrong. The mini-graph-card shows a steep increase. I believe this happened when I upgraded to 2022.6.1

See also [https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/2076](url)

![grafik](https://user-images.githubusercontent.com/44496615/172113480-444119a4-6211-43d9-978d-b221a7f65704.png)
![grafik](https://user-images.githubusercontent.com/44496615/172113553-dad117c4-52d6-4154-b19b-54aa8d41f642.png)

`cards:
  - entities:
      - entity: sensor.lumi_6d760604_temperature
    extrema: true
    font_size: 58
    height: 350
    hour24: true
    hours_to_show: 24
    index: 0
    line_color: blue
    line_width: 4
    name: Eingang
    points_per_hour: 60
    type: custom:mini-graph-card`

**Comment by The-Deep-Sea** [comment]
I can confirm that. After the HA update, the mini-graph-card shows seemingly random data.

**Comment by ildar170975** [comment]
Checked some graphs, cannot confirm (2022.6.1).
```
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.xiaomi_cg_1_pm25
        color: green
        show_state: true
        show_points: true
    hours_to_show: 1
    points_per_hour: 120
    aggregate_func: last
    update_interval: 0
    height: 80
    show:
      state: true
      points: true
      extrema: true
      name: false
      icon: false
    line_width: 1
    hour24: true
    lower_bound: ~0
    smoothing: false
  - type: history-graph
    entities:
      - entity: sensor.xiaomi_cg_1_pm25
    hours_to_show: 1
    refresh_interval: 0
```
![image](https://user-images.githubusercontent.com/71872483/172146314-06238c14-465c-407a-b5ed-c8fdea8bf170.png)

Now place one graph to another (using Photoshop):
![image](https://user-images.githubusercontent.com/71872483/172146484-e7458e9c-4dad-4d5d-8b1e-6da6fbb7cdb8.png)

**Comment by jkrasinger** [comment]
Since upgrading HA to 2022.6.x mini graph card does not show any longer updated data, only horizontal line.

entities:
  - entity: sensor.nr_mq_wz_temperatur
    name: Temperatur
extrema: false
font_size: 75
hours_to_show: 24
line_color: red
line_width: 4
points_per_hour: 6
show:
  graph: line
type: custom:mini-graph-card



This is the data shown on min-graph-card:
![image](https://user-images.githubusercontent.com/8291803/172147617-20aed29e-4460-41ec-8546-b881bb2d1fd9.png)

This is the same data shown on Statistics (look norma)l:
![image](https://user-images.githubusercontent.com/8291803/172147434-2cd04363-5eb8-4e86-8d2a-70f87d7b7347.png)

**Comment by ildar170975** [comment]
I believe people have a good habit to clear cache after every HA update.

**Comment by ildar170975** [comment]
@jkrasinger Next time please always use a formatting for code.
Place a code into triple "`".

**Comment by jkrasinger** [comment]
@ildar170975 Excuse me, my fault.

**Comment by Mace404** [comment]
> I believe people have a good habit to clear cache after every HA update.

Clearing cache does not solve the problem.
Also having a flatline since last HA update while the HA own graph shows the correct historical data in recorder db.

**Comment by ildar170975** [comment]
Then I do not know...
```
type: vertical-stack
cards:
  - type: history-graph
    hours_to_show: 1
    refresh_interval: 0
    entities:
      - entity: sensor.processor_use
  - type: custom:mini-graph-card
    hours_to_show: 1
    update_interval: 0
    aggregate_func: last
    smoothing: false
    lower_bound: ~0
    line_width: 1
    entities:
      - entity: sensor.processor_use
    points_per_hour: 240
```
![image](https://user-images.githubusercontent.com/71872483/172151786-711202fb-f973-4049-bf1e-037216266f7d.png)

**Comment by ildar170975** [comment]
https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/2086?u=ildar_gabdullin

**Comment by Mace404** [comment]
After rebooting the host (and not just Core) the graphs went back to normal.

**Comment by ildar170975** [comment]
> After rebooting the host (and not just Core)

What kinf of installation do you use? What DB?

**Comment by Mace404** [comment]
> > After rebooting the host (and not just Core)
> 
> What kind of installation do you use? What DB?

Supervised on an Intel NUC with Maria database

**Comment by ildar170975** [comment]
I guess that Maria (in Docker?) should be rebooted too.. (but I dont think that this is normal)

**Comment by Mace404** [comment]
> 

That happened when I reboosted the host. So to think of it maybe only rebooting the Maria addon should be enough indeed.

**Comment by ildar170975** [comment]
Well, great that at least one person sorted out the problem ))) My best wishes.

**Comment by jkrasinger** [comment]
I now have restarted HA (not the host) ... the graphs are normal again. Seems to me that immediately after upgrading it was not working, Reason: DB Upgrade?

**Comment by ildar170975** [comment]
This HA release has some issues... See github. Hope guys will fix it one day.

**Comment by bdraco** [comment]
Issue is being tracked here https://github.com/sqlalchemy/sqlalchemy/issues/8098

2022.6.4 was just released with an alternate solution until the above can be sorted out

**Comment by Rustymage** [comment]
Here's my graphs now :/ 

<img width="441" alt="Screenshot 2022-07-26 at 20 50 52" src="https://user-images.githubusercontent.com/19926955/181099657-d36ab9d8-0fa9-4700-b263-ffcb095630b0.png">

```
type: custom:stack-in-card
cards:
  - type: glance
    entities:
      - sensor.shellyem_meter_power_0
    show_icon: false
    show_state: true
    show_name: false
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.shellyem_meter_power_0
    color_thresholds:
      - value: 0
        color: '#F44336'
      - value: 500
        color: '#00ff00'
      - value: 750
        color: '#FCB900'
      - value: 3000
        color: '#F44336'
    show:
      graph: line
      state: false
      name: false
      icon: false
    hours_to_show: 2
    update_interval: 15
    points_per_hour: 150
    hour24: true
    height: 150
```


```
type: custom:stack-in-card
cards:
  - type: custom:mini-graph-card
    name: Technology
    entities:
      - entity: sensor.home_lab_current_energy
        name: Office
      - entity: sensor.network_plug_current_energy
        name: Network
      - entity: sensor.worklaptop_current_energy
        name: Laptop
    show:
      graph: line
      state: false
      name: true
      icon: false
      labels: true
    hours_to_show: 1
    update_interval: 15
    points_per_hour: 60
    hour24: true
    height: 150
```
```
Home Assistant 2022.7.7 
Supervisor 2022.07.0 
Operating System 8.4 
Frontend 20220707.1 - latest
```
