### ISSUE TITLE
bug(graph): last known value is used after interruption in data

### ISSUE THREAD

**Issue by jlsjonas** [kalkih/mini-graph-card#799]
_Originally posted by @hcrohland in https://github.com/kalkih/mini-graph-card/issues/778#issuecomment-1146776434_

I have a similar problem: 
My temperature sensor lost connectivity for some hours:
![Bildschirmfoto 2022-06-05 um 11 56 58](https://user-images.githubusercontent.com/18126119/172045098-22f0b95d-9892-43cf-957d-d0f695abb55e.png)

And now the card shows a constant temperature since then:

![grafik](https://user-images.githubusercontent.com/18126119/172045254-70d78f60-b8f5-4930-9ac5-dabe173c4ae0.png)

Config is:

```
type: custom:mini-graph-card
entities:
  - entity: sensor.ausentemperatur_temperature
    show_fill: false
  - entity: sensor.ausentemperatur_humidity
    show_fill: false
    show_state: true
    y_axis: secondary
upper_bound_secondary: 100
name: Wetter
icon: mdi:home-thermometer-outline
```
