### ISSUE TITLE
state_map - only works for first entity when multiple entities exists

### ISSUE THREAD

**Issue by Sam01101101** [kalkih/mini-graph-card#802]
This example from the usage page no longer works on HA 2022.6. 

when the first entity changes, the state_map updates correctly, However, when the any of the other entity changes state the state_map doesn’t update or work. 

```
type: custom:mini-graph-card
entities:
  - entity: binary_sensor.living_room_motion
    name: Living room
  - entity: binary_sensor.corridor_motion
    name: Corridor
  - entity: binary_sensor.master_bed_motion
    name: Master bed.
    color: green
  - entity: binary_sensor.bedroom_motion
    name: Bedroom
name: Motion last hour
hours_to_show: 1
points_per_hour: 60
update_interval: 30
aggregate_func: max
line_width: 2
smoothing: false
state_map:
  - value: "off"
    label: Clear
  - value: "on"
    label: Detected
```

![image](https://user-images.githubusercontent.com/65209484/174790597-130d715a-c0cc-42d8-9ad2-b96208123fd7.png)
