### ISSUE TITLE
If a point with a zero value is selected - then a wrong state is displayed

### ISSUE THREAD

**Issue by DamianosS** [kalkih/mini-graph-card#805]
My weather station measures the amount of rain with a rain counter, which sums up the continuous amount of rain. 
For showing the daily rain, I've configured the following card:
```
type: custom:mini-graph-card
name: Daily Rain
entities:
  - entity: sensor.weather_station_rain_counter
show:
  graph: bar
hours_to_show: 168
aggregate_func: delta
group_by: date
hour24: true
line_color: '#15317E'
labels: true 
```
The result seems correct:
![mgc 01](https://user-images.githubusercontent.com/13657180/176176525-7039c08c-59b7-4789-9f85-79697bde8722.png)
27.4 mm is the total amount so far.

When hovering over the particular days, the card shows the correct value unless on that day there was no rain. Than it shows the total amount. However, IMHO it should show "0":
![mcg06](https://user-images.githubusercontent.com/13657180/176177894-ce4c8d54-8e14-4257-8436-174ec2367230.png)

Is my configuration wrong, or is it a card issue?

Thanks!

**Comment by pleasereset** [comment]
Chiming in to say that I can reproduce the issue with a simple graph, no aggregation

```
type: custom:mini-graph-card
entities:
  - entity: sensor.master_bathroom_illuminance
    name: Lux
line_color: '#e3d5ca'
line_width: 8
font_size: 75
points_per_hour: 2
```

**Comment by bartoszkaminski** [comment]
I confirm that I also have this problem:
https://user-images.githubusercontent.com/11258617/186196038-4b052285-4aea-4845-a611-dcd39f189960.mov

**Comment by tomkessler** [comment]
I have a similar issue where it's not just 0 values that don't update the number displayed, it's also "small values".  I used 0.55 hours of A/C on Saturday 3 Sept, but the number won't indicate that.

Here's the config of the card:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.hvac_cooling_today
    name: A/C
    color: '#595BBD'
    show_state: true
show:
  graph: bar
  labels: true
  legend: false
hours_to_show: 196
lower_bound: 0
group_by: date
aggregate_func: max
name: Daily A/C Usage
icon: mdi:air-conditioner
```

The current value is 1.96 hr, yet mousing over the bar which should show 0.55 hr doesn't cause an update.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/20233788/188702364-a48ec9ec-587b-4820-b1f4-03f7dfadb614.png">

**Comment by Ascathon** [comment]
It just shouldn't show any bar at all when 0. First I thought chart was wrong with the shorter bar showing a higher value than the larger bar next to it. But it was the total 24 hour value.
0, no data, no bar. In my utility meter it looks like the was power consumed during the night.

**Comment by scharmach** [comment]
Not a solution, only a workaround:

```
color_thresholds:
  - value: 0
    color: '#1c1c1c'
  - value: 1
    color: '#a4958b'
```

- 0 =  colour of the background
- ≥ 1 = colour of the bars

![grafik](https://user-images.githubusercontent.com/9080980/198088722-1458d1aa-8803-4f34-806a-9b311a5ee143.png)

**Comment by wizake** [comment]
I'm also having this issue with a bar chart :(

**Comment by darynwilkinson** [comment]
I'm having the same issue with a line chart.

![image](https://user-images.githubusercontent.com/22393914/204264321-2a8309b4-b852-4eae-84f0-b9f94fd266e2.png)

```
type: custom:mini-graph-card
name: Bedroom
entities:
  - entity: sensor.bedroom_temperature
    name: Current
    show_fill: false
  - entity: sensor.target_temperature_bedroom
    name: Target
    color: '#bc79f2'
    show_state: true
    show_fill: false
  - entity: sensor.heating_demand_bedroom
    show_line: false
    show_state: true
    name: Demand
    color: '#ccffcc'
    y_axis: secondary
show:
  icon: false
  labels: true
  labels_secondary: true
  average: true
  extrema: true
points_per_hour: 2
lower_bound_secondary: 0
upper_bound_secondary: 100
```

**Comment by ildar170975** [comment]
There is a bug here.
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_co2
    show_state: true
  - entity: sensor.xiaomi_cg_1_pm25
    show_state: true
    y_axis: secondary
show:
  icon: false
  labels: true
  points: true
  name: false
  labels_secondary: true
line_width: 1
smoothing: false
aggregate_func: last
points_per_hour: 120
hours_to_show: 1
lower_bound: ~400
lower_bound_secondary: ~0
```
When none graph is selected:
![image](https://user-images.githubusercontent.com/71872483/204545430-d2e9d5ad-4afb-4aed-8a27-7032d2e722f1.png)

When a primary graph is selected (values vary from 400 ppm):
![image](https://user-images.githubusercontent.com/71872483/204545647-e92e4a1f-111d-42f7-b614-d4bb2759ec9e.png)

When a secondary graph is selected (values vary 0 .. 1 μg/m³):
for a non-zero point:
![image](https://user-images.githubusercontent.com/71872483/204545884-4c16edd0-f1eb-41ee-a11e-7821901594fb.png)

for a zero-point - the LAST primary sensor's value is displayed and the secondary sensor's UoM:
![image](https://user-images.githubusercontent.com/71872483/204545955-50e08a72-55ee-46e8-befe-6a536f9925e6.png)

Note that the current value for the primary sensor is 689.
