### ISSUE TITLE
color_thresholds: a glitch may appear if "lower_bound" is specified and "named-"color format is used

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#807]
Check this example:
- two same cards (same settings except `lower_bound`);
- 1st card: `lower_bound: 0`
- 2nd card: `lower_bound: 1`

```
  - type: vertical-stack
    title: same color fmt, diff lower_bound
    cards:
      - type: custom:mini-graph-card
        lower_bound: 0
        <<: &ref_card_settings
          hours_to_show: 1
          points_per_hour: 240
          hour24: true
          line_width: 1
          color_thresholds_transition: hard
          aggregate_func: last
          smoothing: false
          height: 200
          entities:
            - sensor.processor_use
          show:
            points: true
            labels: true
        color_thresholds: &ref_colors_numbers
          - value: 0
            color: '#008000'
          - value: 40
            color: '#ffff00'
          - value: 60
            color: '#ff0000'
          - value: 80
            color: '#00ffff'
      - type: custom:mini-graph-card
        lower_bound: 1
        <<: *ref_card_settings
        color_thresholds: *ref_colors_numbers
```
These cards give same output - this is OK:
![image](https://user-images.githubusercontent.com/71872483/177551960-a21fe2dd-d212-47f8-96eb-1728a692be1f.png)

Now let's specify colors differently:
- 1st card - use kind of `#ff0000` format;
- 2nd card - use kind of `red` format.

```
  - type: vertical-stack
    title: diff color fmt, diff lower_bound
    cards:
      - type: custom:mini-graph-card
        lower_bound: 0
        <<: *ref_card_settings
        color_thresholds: *ref_colors_numbers
      - type: custom:mini-graph-card
        lower_bound: 1
        <<: *ref_card_settings
        color_thresholds: &ref_colors_names
          - value: 0
            color: green
          - value: 40
            color: yellow
          - value: 60
            color: red
          - value: 80
            color: cyan
```
Now the 2nd card has a strange fill - this is a BUG:
![image](https://user-images.githubusercontent.com/71872483/177552010-13f3a12a-1fbf-4b29-97e3-8d971a8d10ea.png)

Now specify same `lower_bound: 0` for both cards:
```
  - type: vertical-stack
    title: diff color fmt, same 0-lower_bound
    cards:
      - type: custom:mini-graph-card
        lower_bound: 0
        <<: *ref_card_settings
        color_thresholds: *ref_colors_numbers
      - type: custom:mini-graph-card
        lower_bound: 0
        <<: *ref_card_settings
        color_thresholds: *ref_colors_names
```

Graphs again look OK:
![image](https://user-images.githubusercontent.com/71872483/177552086-98df4e47-33f8-4356-8412-62321583068c.png)

Now specify same `lower_bound: 1` for both cards:
```
  - type: vertical-stack
    title: diff color fmt, same 1-lower_bound
    cards:
      - type: custom:mini-graph-card
        lower_bound: 1
        <<: *ref_card_settings
        color_thresholds: *ref_colors_numbers
      - type: custom:mini-graph-card
        lower_bound: 1
        <<: *ref_card_settings
        color_thresholds: *ref_colors_names
```

Same glitch:
![image](https://user-images.githubusercontent.com/71872483/177552125-649d1517-572a-4079-9adb-e00d2a22846e.png)

Now just remove the `lower_bound` for both cards:
```
  - type: vertical-stack
    title: diff color fmt, no lower_bound
    cards:
      - type: custom:mini-graph-card
        <<: *ref_card_settings
        color_thresholds: *ref_colors_numbers
      - type: custom:mini-graph-card
        <<: *ref_card_settings
        color_thresholds: *ref_colors_names
```

Same glitch:
![image](https://user-images.githubusercontent.com/71872483/177552257-38363e3b-1a9f-42c6-bb06-2a000b873bc6.png)

**Conclusion**: in case of both conditions:
- `lower_bound` is NOT specified or is not zero;
- color is specified by a name,
the glitch appears.

--------------

This is a problem with a "fill" - check these scaled cards:
Good:
![image](https://user-images.githubusercontent.com/71872483/177554108-5d172252-daf5-48c8-a9ec-227eb020c776.png)

Wrong:
![image](https://user-images.githubusercontent.com/71872483/177553999-a04dc722-8153-4554-8439-f06d6084f6e6.png)

**Comment by ildar170975** [comment]
The glitch does not appear if the first `value` in `color_thresholds` is more than defined `lower_bound`:
glitch arrears:
```
        lower_bound: 1
        ...
        color_thresholds:
          - value: 0
            color: green
```
no glitch:
```
        lower_bound: 1
        ...
        color_thresholds:
          - value: 2
            color: green
```
