### ISSUE TITLE
No color_thresholds unless hovering

### ISSUE THREAD

**Issue by sciurius** [kalkih/mini-graph-card#809]
I have this graph:
````
      - type: custom:mini-graph-card
        hours_to_show: 4
        graph: line
        points_per_hour: 60
        hour24: true
        font_size: 75
        line_width: 2
        show:
          legend: false
          labels: true
        color_thresholds:
          - value: 0
            color: "#00ff00"
          - value: 60
            color: "#ff0000"
        entities:
          - entity: sensor.ithocve_fan_speed_status
            name: Afzuiging
            y_axis: secondary
            color: blue
            show_points: false
            show_line: false
          - entity: sensor.ithocve_humidity
            name: Vochtigheid
        name: Afzuiging (4 uur)
````
Problem is that the threshold colors do not show (upper picture) unless I hover over it (lower picture).
What am I doing wrong?

![x](https://user-images.githubusercontent.com/1118804/177746152-7813835f-bd56-4249-a838-ec13016b75a8.png)
