### ISSUE TITLE
extrema and average does not show correctly for multi entity graph (probably)

### ISSUE THREAD

**Issue by evlo** [kalkih/mini-graph-card#812]
```
type: custom:mini-graph-card
entities:
  - entity: sensor.ac_dilna_power
    name: dílna
    show_points: true
  - entity: sensor.ac_loznice_power
    name: ložníce
    show_points: true
  - entity: sensor.ac_obyvak_power
    name: obývák
    show_points: true
  - entity: sensor.zasuvka_koupelna_topeni_power
    name: topení
    show_points: true
name: HAC
hours_to_show: 24
points_per_hour: 1
extrema: true
hour24: true
smoothing: true
aggregate_func: avg
show:
  labels: true
  extrema: true
  average: true
```

![image](https://user-images.githubusercontent.com/8813196/178156751-86f8f73e-b13f-4f71-9168-66aa8315e04a.png)

always show value for the first entity, I think it should change by the entity that have hover and i none, show value from all entities?
