### ISSUE TITLE
binary_sensor wont show correctly

### ISSUE THREAD

**Issue by magiva** [kalkih/mini-graph-card#814]
I created a simple binary_sensor to ping the google dns server.  The purpose is so that i can cycle the power of the wifi if the sensor shows 'off' for too long.  This is an observed problem and fix in the apartment im in with no access to the "main house router".

I thought it would be nice to plot this up/down into a chart
in config i created:
binary_sensor:
      - platform: ping
        name: Internet
        host: 8.8.8.8
        scan_interval: 15

in the card i created:
    type: custom:mini-graph-card
    name: Internet Status
    icon: mdi:check-network
    entities:
      - entity: binary_sensor.internet
        name: Internet
    hours_to_show: 12
    points_per_hour: 60
    aggregate_func: max
    line_width: 2
    smoothing: false
    state_map:
      - value: 'off'
        label: Down
      - value: 'on'
        label: Up

The chart show up and... up
![image](https://user-images.githubusercontent.com/7522405/178949037-01573378-184c-4b16-a3c7-f410c8118c12.png)

The sensor has off and on during the hours_to_:show
![image](https://user-images.githubusercontent.com/7522405/178949157-3b80000d-58e2-4bad-b2d0-1b5686cb8d73.png)

**Comment by magiva** [comment]
i see that the off spike was not long enough to reflect in the points_per_hour but still weird that i have up and up 
even if i put upper and lower bounds.

**Comment by ildar170975** [comment]
The issue will be faster analysed if it is created properly.
Here the code in unformatted and cannot be checked.
Use triple "`" to format the code.

**Comment by HeedfulCrayon** [comment]
You need to set `upper_bound: 1`
```
type: custom:mini-graph-card
name: Internet Status
icon: mdi:check-network
entities:
  - entity: binary_sensor.internet
    name: Internet
**upper_bound: 1**
hours_to_show: 12
points_per_hour: 60
aggregate_func: max
line_width: 2
smoothing: false
state_map:
  - value: 'off'
    label: Down
 - value: 'on'
    label: Up
```
