### ISSUE TITLE
Should show option be part of entities?

### ISSUE THREAD

**Issue by rdehuyss** [kalkih/mini-graph-card#82]
Hi,

first of all: love your card!

I have a question/feature request though: in a card which shows my power consumption, I would like to show the total price in EUR also (which is calculated by a template sensor). I can do this using two entities but I'm not interested in the graph of the price. So, the total price in EUR would be like metadata.

Configuration wise, I think this is solved by moving the show option to entities.

Just an idea...

**Comment by kalkih** [comment]
Hey,
Simply moving the show option object to the entity option object wouldn't really be a suitable solution since most of the show options are "card wide" options.

Adding a `show_graph` or similar option to the entity object would be a better solution maybe? Similar to the existing `show_state` option.

**Comment by rdehuyss** [comment]
Excellent idea. If we could even add more than one, that would be great.

**Comment by rdehuyss** [comment]
Hi @kalkih , I still look forward to this change. Is it a difficult one? Thanks again for your excellent work.

**Comment by kalkih** [comment]
Hey,
Should be easy, just haven't got around to it yet, I'll see if I can get it done tonight, thanks for the reminder :+1:

**Comment by rdehuyss** [comment]
You are a Hero!

**Comment by rdehuyss** [comment]
Hi @kalkih ,

I just tried the show_graph but it is not working as I would expect:

**Screenshot:**
![Screenshot from 2019-09-04 14-53-40](https://user-images.githubusercontent.com/567842/64256462-d2443080-cf23-11e9-8839-9ed24d0dbe83.png)


**What I would like:**
As in the screenshot, but without the blue bars, and the yellow bars thus wider.


**Lovelace configuration:**
```
              - entities:
                  - entity: sensor.house_daily
                    name: Verbruik 7 dagen
                    unit: kWh
                  - entity: sensor.house_kwh_today_in_eur
                    show_graph: false
                    show_state: true
                    unit: €
                font_size: 75
                hours_to_show: 168
                icon: 'mdi:flash'
                points_per_hour: 0.04166666666
                show:
                  graph: bar
                  legend: false
                type: 'custom:mini-graph-card'
```

Am I doing something wrong?
