### ISSUE TITLE
[FR] Display graphs in opposite Z-order: the last entity = bottommost, the 1st entity = topmost

### ISSUE THREAD

**Issue by jchhenderson** [kalkih/mini-graph-card#825]
Hi,

It appears to me that the lines are drawn in the order of the entities listed.  This means the last entity is drawn over the others.  I would request that there is the capability to make the last entity listed (the top drawn one) to be the main entity shown (for state etc at the top of the card).

Hope this makes sense!

**Comment by ildar170975** [comment]
Sorry, let me clarify.
Consider this example:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.mijia_300_1_temperature
    color: blue
    show_state: true
    name: Temp
  - entity: sensor.mijia_300_1_co2
    color: red
    show_state: true
    y_axis: secondary
    name: Humidity
```
![image](https://user-images.githubusercontent.com/71872483/184338723-e1e2b7fc-252c-479f-a3c2-89533954c65f.png)

Here "entity_1" state is on the left side.
If you add more entities - then 2nd, 3rd ... will be on the right side.
So, here entities are placed accordingly to their order (1st - left, others - in the right).

As for order of filling - unclear what color is on the top since colors are semi-transparent.
To know it - let's use [some card-mod](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2281) to remove transparency:
```
card_mod:
  style: |
    .fill {
      fill: white;
      opacity: 1 !important;
    }
```
which gives this:
![image](https://user-images.githubusercontent.com/71872483/184339312-ce472d1a-0458-47cb-a75f-ace061b95df9.png)
So, the order is same as above - but gives an opposite result.

Here we probably should display graphs in opposite order.
Agree?

**Comment by jchhenderson** [comment]
Hi,

I am not sure what point you are trying to make.  Are you agreeing with my request or telling me it is not necessary or something else?

>If you add more entities - then 2nd, 3rd ... entities will be on the right side.

yes, if you specify `y_axis: secondary`
I am not using `y_axis: secondary` in my scenario

This is my min-graph
![Screenshot 2022-08-12 at 12 23 48](https://user-images.githubusercontent.com/34644672/184344497-567c191a-94ba-4871-bc73-71fb91a3a7f1.png)

I would like the coloured line (outside temp) to be drawn over the two black lines (highest inside, coolest inside).  I seem to be able to only do this by making it the 3rd entity, but then the 1st entity is the one shown in the top-left corner.

here is my yaml:
```
  - type: custom:mini-graph-card
    name: 'Outside'
    show:
      state: true
      name: true
      icon: false
      extrema: true
    height: 300
    entities:
      - entity: sensor.outside_temp
        state_adaptive_color: true
        show_fill: false
        name: Outside
        show_state: true
        show_points: true
        show_legend: false
      - entity: sensor.hottest_temp
        name: Hottest inside
        show_state: false
        show_fill: false
        color: var(--paper-card-background-color)
        show_points: false
        show_legend: false
      - entity: sensor.coolest_temp
        color: var(--paper-card-background-color)
        name: Coolest inside
        show_state: false
        show_fill: false
        show_points: false
        show_legend: false
    hour24: true
    hours_to_show: 48
    lower_bound: 12 #"{{ states('sensor.coolest_inside_temp_48_hrs') }}" # templates not supported
    upper_bound: 35 #"{{ states('sensor.hottest_inside_temp_48_hrs') }}" # templates not supported
    points_per_hour: 4
    color_thresholds:
      - value: -10
        color: '#000fff' # Blue
      - from: 3
        color: '#002aff' # Blue (RYB)
      - color: '#055fff' # Blye (RYB)

      [...]
```

..._what I really want to do_ is show the difference between the two lines as a fill.

From what I read of your reply, if I put the lines on `y_axis: secondary`, fill them, make one the colour of the card background and set transparency to ), I could do this??  ...I'm going to try that now....
