### ISSUE TITLE
Best way to show long term data?

### ISSUE THREAD

**Issue by rdehuyss** [kalkih/mini-graph-card#83]
I've noticed that HomeAssistant gets unresponsive if showing history data for about two weeks using the default sqlite database.

Is it possible to do some throttling when asking for the history data?

I have 4 mini-graph-cards showing history like this:

```
          - entities:
              - entity: sensor.floor_2_kwh_verlichting_total
                name: VERLICHTING
            font_size: 75
            hours_to_show: 336
            icon: 'mdi:flash'
            line_width: 8
            points_per_hour: 0.041667
            type: 'custom:mini-graph-card'
```

But the result is that my homeassistant gets unresponsive and goes to 100% CPU due to the history api calls.
