### ISSUE TITLE
Request: Allow dynamic values in color thresholds

### ISSUE THREAD

**Issue by c11umw** [kalkih/mini-graph-card#834]
Hi.
Rather than having static numbers, it would be good to have the values be dynamically allocated so that the charted colors change automatically through the seasons.

Example 1: Using weather data, for thermostatic charts what's displayed as relative cold in winter will also display as relative cold in summer.

Example 2: In the below code, monitoring the temperature of a hot room relative to an adjacent room.

Current:
```
type: custom:mini-graph-card
entities:
  - sensor.boiler_room_temperature
name: Boiler Room
hours_to_show: 12
color_thresholds:
  - value: 22
    color: '#0066ff'
  - value: 25
    color: '#d35400'
  - value: 28
    color: '#c0392b'
```

Requested:
```
type: custom:mini-graph-card
entities:
  - sensor.boiler_room_temperature
name: Boiler Room
hours_to_show: 12
color_thresholds:
  - value: "{{ ((states.sensor.hallway_temperature.state) | float +0) }}"
    color: '#0066ff'
  - value: "{{ ((states.sensor.hallway_temperature.state) | float +3) }}"
    color: '#d35400'
  - value: "{{ ((states.sensor.hallway_temperature.state) | float +6) }}"
    color: '#c0392b'
```
