### ISSUE TITLE
Safari, iOS Companion App: glitches when "fill: fade" & using "decluttering-card" 

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#839]
Found a rather serious bug.
It occurs when:
-- `fill: fade`;
-- the `mini-graph-card` is placed inside a `custom:decluttering-card`;
-- there are at least 2 cards on the view with different `height`.
-- using Safari (observed in MacOS 10.x & iOS 15.x) or iOS Companion App.

Here is a code for a decluttering template (put your own sensor):
```
decl_test_graph:
  card:
    type: custom:mini-graph-card
    entities:
      - entity: sensor.speedtest_isp_1_download
    hours_to_show: 24
    height: '[[VALUE_HEIGHT]]'
    show:
      fill: fade
```
and for the test view:
```
  - type: vertical-stack
    title: inside decluttering
    cards:
      - type: custom:decluttering-card
        template: decl_test_graph
        variables:
          - VALUE_HEIGHT: 200

      - type: custom:decluttering-card
        template: decl_test_graph
        variables:
          - VALUE_HEIGHT: 100

  - type: vertical-stack
    title: w/o decluttering
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.speedtest_isp_1_download
        hours_to_show: 24
        height: 200
        show:
          fill: fade
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.speedtest_isp_1_download
        hours_to_show: 24
        height: 100
        show:
          fill: fade
```
The view contains 2 stacks:
-- two `mini-graph-card` inside `declutering-card` - with different heights;
-- two `mini-graph-card` - with different heights.

How it looks in Chrome+Win:
![image](https://user-images.githubusercontent.com/71872483/191873829-83030c94-4d1c-43f7-8be7-ae23e2e86049.png)

And how it looks in Safari:
![image](https://user-images.githubusercontent.com/71872483/191873877-ccbbeaef-bf64-49ef-ad1e-2bfa5902e3b1.png)

**There is a glitch on the top-left card - the "fill" seems to occupy just a half of the area.**

As a workaround - use "fill: true".
Or do not use Safari & iOS Companion App.

-------------------------

A possible reason is described below.

The graph contains of three objects:
-- the graph's line;
-- the graph's points;
-- the graph's fill.

If the card contains several entities - then it contains several sets of those objects (line, points, fill).
To differ objects belonging to different entities, the code uses a unique ID:
![image](https://user-images.githubusercontent.com/71872483/191873521-6a184b85-8102-4f5b-b426-820368781e4b.png)
containing a unique string and some index (0 - 1st entity, 1 - 2nd entity, ...).
The unique string seems to be some kind of "this card unique ID".

But when placed inside a `decluttering-card`, these IDs are same:
![image](https://user-images.githubusercontent.com/71872483/191874209-7014b682-1151-424b-b8e9-4407a95647a4.png)

The `declutter-child-` part is always same.
**Means - if several cards are present on the view, a wrong fill mask may be selected.**

**A possible fix should be generating a unique ID.**

**Comment by jlsjonas** [comment]
Issue is caused by `decluttering-card` hardcoding the `element.id` to `declutter-child`, breaking the HTML compliance of the page (ids must be unique)
I recommend raising an issue there pointing to the line/including this comment; it can set it's own id (would actually be beneficial in several cases); however there should still be a unique part of the id (f.e. `declutter-child-<instance#>`)

**Comment by ildar170975** [comment]
Absolutely agree - this is a `decluttering-card` issue.
Unfortunately, the repo seems to be abandoned.
And the author does not respond...
OK, we'll keep using `fill: true` as a workaround.

**Comment by ildar170975** [comment]
Issued a fix in `decluttering-card`: https://github.com/custom-cards/decluttering-card/pull/90.
(can be "fixed" locally - open the corresponding "decluttering-card.js" in a text editor & remove this line; then save the js-file, delete gz-file, purge a browser's cache)

Earlier only experienced the issue in Safari (observed in MacOS 10.x & iOS 15.x) or iOS Companion App.
Starting from 2025.2.5 + Chrome 133.0.6943.127 - see this issue in Chrome too.
Test code:
decluttering templates:
```
test_decl_graph_fill_true:
  card:
    <<: &ref_settings
      type: custom:mini-graph-card
      entities:
        - entity: sensor.xiaomi_cg_1_co2
      hours_to_show: 6
      points_per_hour: 60
    name: "decluttering, fill: true"
    show:
      fill: true

test_decl_graph_fill_fade:
  card:
    <<: *ref_settings
    name: "decluttering, fill: fade"
    show:
      fill: fade
```
test view:
```
  - type: custom:decluttering-card
    template: test_decl_graph_fill_true

  - type: custom:decluttering-card
    template: test_decl_graph_fill_fade

  - <<: &ref_settings
      type: custom:mini-graph-card
      entities:
        - entity: sensor.xiaomi_cg_1_co2
      hours_to_show: 6
      points_per_hour: 60
    name: "fill: true"
    show:
      fill: true

  - <<: *ref_settings
    name: "fill: fade"
    show:
      fill: fade
```
Result in Chrome:
After "refresh" from a sandwich menu:
![Image](https://github.com/user-attachments/assets/9c15fccb-103a-4c68-89a7-a54d3fb3e6eb)
Note that the card with `fill: fade` inside a `decluttering-card` may not have a fill.

After F5 - again good:
![Image](https://github.com/user-attachments/assets/41b61dc7-3b75-4486-bd39-f595edc4f018)

See no issue in iOS Companion App (iOS 15.7.x).
Note that the glitch occurs even with only card (i.e. not with cards with different `height` as it was reported in the 1st post).
