### ISSUE TITLE
Feature Request: Option so that additional entities do not influence the line display

### ISSUE THREAD

**Issue by c11umw** [kalkih/mini-graph-card#840]
Hi
I was hoping to change some of my sensors so that it would chart the value of the sensor (temperatures in this case) as well as the battery of the sensor on the same chart, but only the entity state.

When I add the additional entity it influences the information that I do want to see which means I can no longer see the historical charting.

Example. Outside weather sensor showing about 11C and the battery 56%
Left is normal charting and right is with the additional battery (status only)
As you can see, the right graph really only shows the current temperature where the left shows the temperature rise and fall.

![image](https://user-images.githubusercontent.com/48920056/192465203-07e41d4a-cd2e-497c-b6a7-b64b883e85f4.png)

If there was a way to have the second battery entity not influence the chart display, that would be perfect

Before:
```
type: custom:mini-graph-card
hour24: true
entities:
  - sensor.lumi_lumi_weather_abc123456_temperature
name: Outside
align_state: center
font_size: 80
hours_to_show: 24
points_per_hour: 2
color_thresholds:
  - value: 0
    color: '#0000ff'
  - value: 2
    color: '#0000ff'
  - value: 8
    color: '#0066ff'
  - value: 16
    color: '#ad6b0a'
  - value: 28
    color: '#c0392b'
  - value: 29
    color: '#c0392b'
```
After:
```
type: custom:mini-graph-card
hour24: true
entities:
  - entity: sensor.lumi_lumi_weather_abc123456_power
    color: '#050'
    show_state: true
    show_points: false
    fixed_value: true
  - entity: sensor.lumi_lumi_weather_abc123456_temperature
    show_state: true
name: Outside
decimals: 1
font_size: 60
hours_to_show: 8
points_per_hour: 6
color_thresholds:
  - value: 28
    color: '#0066ff'
  - value: 30
    color: '#d35400'
  - value: 32
    color: '#c0392b'
show:
  name: true
  legend: false
  icon: true
  labels: false
  line: true
  fill: true
```

Another more complex example where it's charting our (dumb) boiler room temperature to tell when the heat is on.
Using a temperature delta compared to the hallway so that it's always relative to the time of year.
Trying to show only the baseline (0), the line of the delta and then the real temperatures as states only
![image](https://user-images.githubusercontent.com/48920056/192468390-bd4043ca-7e19-4d54-a6bb-e4ac183ddd0c.png)

Before:
```
type: custom:mini-graph-card
hour24: true
entities:
  - entity: sensor.home_temperature
    color: '#050'
    show_state: true
    show_points: false
    fixed_value: true
  - entity: sensor.boiler_room_temperature
    show_state: true
name: Boiler Sensor 8h
decimals: 1
font_size: 60
hours_to_show: 8
points_per_hour: 6
color_thresholds:
  - value: 28
    color: '#0066ff'
  - value: 30
    color: '#d35400'
  - value: 32
    color: '#c0392b'
show:
  name: true
  legend: false
  icon: true
  labels: false
  line: true
  fill: true
```
After:
```
type: custom:mini-graph-card
hour24: true
entities:
  - entity: sensor.home_temperature
    show_state: true
    show_points: false
    show_line: false
    show_fill: false
  - entity: sensor.boiler_room_temperature
    show_state: true
    show_points: false
    show_line: false
    show_fill: false
  - entity: input_number.number_zero
    color: '#050'
    show_state: false
  - entity: sensor.boiler_room_temperature_delta
    show_state: false
name: Boiler Sensor 8h
decimals: 1
font_size: 60
hours_to_show: 8
points_per_hour: 6
color_thresholds:
  - value: 28
    color: '#0066ff'
  - value: 30
    color: '#d35400'
  - value: 32
    color: '#c0392b'
show:
  name: true
  legend: false
  icon: true
  labels: false
  line: true
  fill: true
```
