### ISSUE TITLE
Secondary sensors in a row

### ISSUE THREAD

**Issue by SAOPP** [kalkih/mini-graph-card#843]
Hi!

It's possible to implement something like this:

![image](https://user-images.githubusercontent.com/5647009/192561640-b80a7f68-ad5d-4b81-892f-15ac23fdc2b6.png)

I mean displays secondary sensors in a row, when we've setting in card like this:

```
        - type: custom:mini-graph-card
          icon: mdi:transmission-tower-export
          entities:
            - entity: sensor.corridor_input_electricity_meter_voltage_l2
              show_state: true
              show_points: hover
              name: Входное напряжение
            - entity: sensor.corridor_input_electricity_meter_power_l2
              show_state: true
              show_graph: false
            - entity: sensor.corridor_input_electricity_meter_current_l2
              show_state: true
              show_graph: false
            - entity: sensor.corridor_input_electricity_meter_frequency_l2
              show_state: true
              show_graph: false
            - entity: sensor.corridor_input_electricity_meter_power_factor_l2
              show_state: true
              show_graph: false
            - entity: sensor.electricity_input_wh_to_kwh_monthly
              show_state: true
              show_graph: false
            - entity: sensor.money_total_monthly
              show_state: true
              show_graph: false
            - color: gray
              entity: binary_sensor.tod_all_day
              name: Day
              show_line: false
              show_points: false
              show_legend: false
              ...
```

Cheers!
