### ISSUE TITLE
The Graph is drawn where it shouldn't be

### ISSUE THREAD

**Issue by Naxey** [kalkih/mini-graph-card#847]
What it looks like:
![image](https://user-images.githubusercontent.com/40920984/194119707-8c493f5d-a2b3-4dba-a8fc-48f0033d7bb6.png)
![image](https://user-images.githubusercontent.com/40920984/194119715-df33d3e2-fc93-468d-9de8-3aab5664d8cd.png)

What I think this should look like (red line):
![image](https://user-images.githubusercontent.com/40920984/194120440-1b1fc5c0-3269-4e68-a566-6edcc15fef1e.png)

**Comment by ildar170975** [comment]
And no code is applied.

**Comment by Naxey** [comment]
The sensor used in this example is the `lumi.sensor_magnet.aq2`

```yaml
type: custom:mini-graph-card
entities:
  - sensor.lumi_lumi_sensor_magnet_aq2_a11b4808_device_temperature
hours_to_show: 168
show:
  labels: true
  name: false
  icon: false
  state: true
color_thresholds:
  - value: 23
    color: '#f39c12'
  - value: 25
    color: '#d35400'
  - value: 28
    color: '#c0392b'
```
