### ISSUE TITLE
delta and diff bars showing not correct values for group_by date

### ISSUE THREAD

**Issue by pachi81** [kalkih/mini-graph-card#848]
Hi,

I think, the aggregate_func delta and diff in a bar chart are not correct calculated for group_by date (not sure, if it also is related to other group_by variants).
The reason/problem is, that they calculate the diff/delta of first and last or min and max for the current day, but if you have a total_increasing sensor like rainmeter, the first value of a day is set, if there was a change of the sensor value. And a change is a higher value then the one before (of the last day).
For example:
1. day:
    - first: 0
    - last: 2
    - delta: 2
2. day:
    - first: 3
    - last: 5
    - delta: **2 ! => delta should be 3! because it should be delta/diff with last value of the day before!**

Another example from my system for my rainmeter:
  
![Capture](https://user-images.githubusercontent.com/56817032/194305036-81ad45f2-a17d-4182-aefb-3f442b7727e3.JPG)

As you can see in the second chart, on day 2 the correct value is 5.2 (instead of 4.9), on day 3 the correct value is 25.8 (instead of 25.6) and on day 4 the correct value is 0.2 (instead of 0).

Config for the picture:
```
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.regen_total
    name: Regen 7 Tage
    hours_to_show: 168
    aggregate_func: max
    group_by: date
    hour24: true
    lower_bound: 0
    min_bound_range: 0
    show:
      graph: bar
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.regen_total
    name: Regen 7 Tage
    hours_to_show: 168
    aggregate_func: delta
    group_by: date
    hour24: true
    lower_bound: 0
    min_bound_range: 0
    show:
      graph: bar
  - type: history-graph
    entities:
      - entity: sensor.regen_total
    hours_to_show: 168
```
