### ISSUE TITLE
FR: Allow templates and/or input_numbers in color_threshold values

### ISSUE THREAD

**Issue by sciurius** [kalkih/mini-graph-card#852]
I would like to be able to write
````
color_thresholds:
  - value: 0
    color: "#00ff00"
  - value: input_number.some_threshold
    color: "#ff0000"
````
Alternatively, support for templates would be nice, e.g.
````
  - value: "{{ states('input_number.ithocve_humidity_threshold') }}"
````

Thanks,
