### ISSUE TITLE
Bug: group_by date is applying aggregated values to the wrong date

### ISSUE THREAD

**Issue by tomkessler** [kalkih/mini-graph-card#857]
I have a mini-graph-card which should show the amount of heat used by day.  My config is exactly like the example given for energy used daily in all foundational respects.  However, this week I used heat only on Wednesday, yet the graph attributes the heat usage to Tuesday.

Card config:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.hvac_heating_today
    name: Heat
    color: '#DB5F59'
    show_state: true
hours_to_show: 196
lower_bound: 0
upper_bound: ~4
min_bound_range: 4
group_by: date
aggregate_func: max
show:
  graph: bar
  labels: true
  legend: false
name: Daily Heat Usage
icon: mdi:heating-coil

```

If you look at the underlying sensor history values, it shows how the hvac_heating_today had a max of .59 on Wednesday, 19 October, not on Tuesday, 19 Oct.

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/20233788/197420322-54028130-dbd2-4ece-bd5b-aa50f0d44883.png">

Yet, this is how the card renders:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/20233788/197420338-58ed83b3-6095-4373-a43a-f50c3d402f2b.png">
