### ISSUE TITLE
[FEATURE REQUEST] Add separate "decimals" parameter for graph entities

### ISSUE THREAD

**Issue by szymucha94** [kalkih/mini-graph-card#863]
Please separate "decimals" parameter for main entity value that is shown on the card and additional entities that are shown only as graphs.
Currently I'm forced to use "decimals: 2" for both graph and main entity which results in unnecessary zeros after decimal point for power usage while two decimal points are necessary for energy consumption readings:
![1](https://user-images.githubusercontent.com/95378717/199849614-f4a5d59b-0069-4653-a751-f26958827b8a.JPG)
![2](https://user-images.githubusercontent.com/95378717/199849617-4de4e493-b6df-4d29-bae7-20550fe5b1dc.JPG)

Please, pretty please :)
Cheers

**Comment by ildar170975** [comment]
> main entity value that is shown on the card and additional entities that are shown only as graphs.

Not clear what you mean by "main value shown on the card" & "additional entities shown only as graphs".
Every entity may be shown as a graph and/or as a state.
Do you mean that your card (which you decided not to explain by a code) contains 2 entities - with a state, w/o a graph + w/o a state, with a graph ?

**Comment by szymucha94** [comment]
This is my card:

type: custom:mini-graph-card
view_layout:
  column: 2
entities:
  - entity: sensor.mainenergymetercurrent_power
    show_graph: false
    show_state: true
  - entity: sensor.mainenergymetertotal_energy
    show_graph: true
    show_state: false
    name: Energy consumption
name: Current Power Consumption
hour24: true
aggregate_func: delta
hours_to_show: 18
height: 88
decimals: 2
points_per_hour: 1
update_interval: 600
labels_secondary: false
group_by: hour
show:
  graph: bar
  labels: false
  fill: true

What I need is to represent sensor.mainenergymetercurrent_power as integer and sensor.mainenergymetertotal_energy as float.
Currently if I set "decimals: 0" sensor.mainenergymetercurrent_power is represented as expected, but sensor.mainenergymetertotal_energy (per hour) is shown as zero.

**Comment by ildar170975** [comment]
Next time use TRIPLE "`" for code.
Formatted the code by myself.

**Comment by szymucha94** [comment]
Yes, precisely.

**Comment by jlsjonas** [comment]
This will be fixed as part of the configuration update, allowing you to set most options on entity-level with global defaults/overrides!

**Comment by SeBsZ** [comment]
Hey was this ever added? I'm trying to show two entities, one without decimals and the other has 1 decimal. I can't set this to show correctly without per-entity decimal settings. Is this still planned or does someone know of a workaround?

**Comment by cataseven** [comment]
+1

**Comment by cataseven** [comment]
> This will be fixed as part of the configuration update, allowing you to set most options on entity-level with global defaults/overrides!

Is there any progress sir?

**Comment by cataseven** [comment]
> Hey was this ever added? I'm trying to show two entities, one without decimals and the other has 1 decimal. I can't set this to show correctly without per-entity decimal settings. Is this still planned or does someone know of a workaround?

I finally did it. You can use attached js file for entity based decimals. Link is [here](https://drive.google.com/file/d/1GtbGMdw8PbcLiB6Fz6i-4H7mAqRgfOBf/view?usp=drive_link)  :) 

Please note that;
- Firstly you should delete "mini-graph-card-bundle.js.gz" and "mini-graph-card-bundle.js" files under "mini-graph-card" folder 
- Then upload attached js file to mini-graph-card" folder 
- Then delete your browser cache, restart ha, restart your browser
- I use Turkish number format (1.234.567,89) if you want to change it to English format I can assist you
- I am not a developer so I do not know how to create pull request. I am just learning coding as hobby. If someone can create pull request, it is ok.

Example card yaml and screenshoots.

```
type: custom:mini-graph-card
entities:
  - entity: sensor.XXX
    name: XXX
    smoothing: false
    decimals: 0
  - entity: sensor.YYY
    name: YYYY
    attribute: ZZZ
    smoothing: false
    show_graph: false
    show_state: true
    unit: "%"
    decimals: 2
icon: mdi:car
hour24: true
hours_to_show: 24
points_per_hour: 12
line_color: green
line_width: 1
font_size: 100
font_size_header: 12
height: 217
animate: true
show:
  points: hover
  fill: fade
  extrema: true
  aggregate_func: max

```
you are welcome :)
@SeBsZ @szymucha94 @ildar170975
