### ISSUE TITLE
Double border when inside entities card (since HA 2022.11 release)

### ISSUE THREAD

**Issue by ReX1983** [kalkih/mini-graph-card#867]
HA 2022.11 release has introduced rounded edges (not a fan) and card outlines and some other changes.

As a result, when mini-graph-card is inside an entities card, there is an inner border (for mini-graph-card)  and an external border (for the entities card).

Can we do something to avoid the inner border?

<img width="358" alt="Capture" src="https://user-images.githubusercontent.com/37460549/201495252-686d8d9f-0e6e-4724-9c1d-715e31650fc1.PNG">

**Comment by jlsjonas** [comment]
Hey, could you share the yaml code used to generate the card with issues? I just upgraded to 2022.11.2 and can't see the issue you're describing on any of my cards.

Make sure to include any custom theming you might have

Thanks for the report!

**Comment by ReX1983** [comment]
I have added the card inside an entities card, as I wanted the title "Temperature" to be consistent (same color, position, size) with other entities card I have in the same tab. I didn't manage to achieve the same using the mini-graph-card name (that hence I have hidden). 

As side note, it seems that 2022.11 introduced a new behavior where card borders properties (e.g. outline, shadow, etc.) are inherited by internal cards. This has been reported by few people and it is discussed [here](https://community.home-assistant.io/t/2022-11-card-borders/485102/32). 

Thanks for your help and amazing card - it is definitely the most used in my UI :-). 

```
  - entities:
      - aggregate_func: avg
        align_state: null
        bar_spacing: 4
        decimals: 1
        entities:
          - entity: sensor.home_avg_temperature
            name: Home
            show_fill: false
            unit: °C, home
          - entity: sensor.outdoor_avg_temperature
            name: Outside
            show_fill: false
            show_indicator: true
            show_state: true
            unit: °C, outside
          - aggregate_func: avg
            entity: sensor.home_avg_heating
            name: Heating
            show_indicator: false
            show_line: false
            show_points: false
            show_state: false
            unit: '%, heating'
            y_axis: secondary
        entity: null
        font_size: 75
        height: 120
        line_width: 3
        name: Temperature (this is hidden...) 
        points_per_hour: 4
        show:
          icon: false
          labels: true
          legend: false
          name: false
          points: hover
        smoothing: true
        type: custom:mini-graph-card
    show_header_toggle: false
    title: Temperature
    type: entities
```

**Comment by jlsjonas** [comment]
Thanks for the link & template (I didn't realise you could add cards inside entities :joy:)!

It seems that https://community.home-assistant.io/t/2022-11-card-borders/485102/16 could serve as a workaround, especially as you mentioned you disliked them regardless.

I'll add an extra property to support clean embedding into other cards in the upcoming release (which should get some progress again with codespaces being released, as my main dev laptop sadly died recently)

**Comment by ReX1983** [comment]
I've tried restoring the original look, but if I remove the outline and add a shadow, the same shadow is applied to the inner card and it looks very bad. My temporary fix is to remove outline and shadow altogether but this doesn't look very nice as the cards blend too much into the background.

> I'll add an extra property to support clean embedding into other cards in the upcoming release

That's great - thanks!

Something else that could help me is the ability to customize the look of the card name/title: it is smaller and grey, different from the larger and white title of the entities card. I saw you I can change the size (but I didn't understand where to put the option) but I can't change the color. Is that something you could help me with?

Thanks!

**Comment by jlsjonas** [comment]
It seems like the required style change would be:
```css
.header {
    font-size: 24px;
    font-family: inherit;
}
```

I'll consider adding theming options for these, @ildar170975 might be able to help you with a card-mod template that would solve the issue more properly in the meantime

**Comment by jlsjonas** [comment]
> And this cannot be fixed just by editing a theme

Note that the css snippet above is the result of me trying to get it right (applied onto the mini-graph-card shadow root), it's quite a clean fix imho :)

**Comment by ReX1983** [comment]
> @ReX1983 Please describe your issue with borders / shadows in the `mini-graph-card` Community thread, we'll see what we can do. Add screenshots.
> 
> This 2022.11 release added borders & removed shadows. And this cannot be fixed just by editing a theme (as advised by many users).

The first problem is the one in my original post: the default theme outline is visible also in the inner card.

I've created a new theme, hiding the outline and introducing a shadow that replicates the shadow we had before this HA release.

As you can see the shadow out of the outer card is also shown inside:

![image](https://user-images.githubusercontent.com/37460549/202894798-89ddb58e-fd98-4fc4-bbfe-07c09a441491.png)

There is a distinct shadow below the orange line and a fainted shadow above the percentages.

```
entities:
  - aggregate_func: avg
    align_state: null
    bar_spacing: 4
    decimals: 1
    entities:
      - entity: sensor.home_avg_humidity
        name: Home
        show_fill: false
        unit: '%, home'
      - entity: sensor.outdoor_avg_humidity
        name: Outside
        show_fill: false
        show_indicator: true
        show_state: true
        unit: '%, outside'
    font_size: 75
    height: 120
    line_width: 3
    name: Humidity
    points_per_hour: 4
    show:
      icon: false
      labels: true
      legend: false
      name: false
      points: hover
    smoothing: true
    type: custom:mini-graph-card
title: Humidity
type: entities
```
