### ISSUE TITLE
[bug] min/max/avg values are wrong for the graph start (before first point)

### ISSUE THREAD

**Issue by wonderiuy** [kalkih/mini-graph-card#869]
Hello, is possible to achve a result like the Lovelace Statistic graph where the fill below the Min-line is white?
The graph would be more correct and readable.
Any way to achieve this with CSS card-mod?
Edit: why the min/max/avg line starts from the same value? They should start from the previous value if available
![max min avg](https://user-images.githubusercontent.com/53263262/201728304-eda4e38a-af55-401b-82ac-ebf7032e151c.jpg)

This is the Lovelace Statistic graph:
![immagine](https://user-images.githubusercontent.com/53263262/201728801-bc50b523-7e3f-4d96-a450-03802ed4e3b1.png)

**Comment by ildar170975** [comment]
> why the min/max/avg line starts from the same value? They should start from the previous value if available

Probably you should start with posting a minimal short code demonstrating your issue.

**Comment by wonderiuy** [comment]
> Probably you should start with posting a minimal short code demonstrating your issue.

Sorry, i thougth that previuos images speaks themselves

> Could be. But similar questions better to ask in the Community in the `mini-graph-card` thread.

OK, will do

**Comment by jlsjonas** [comment]
Note that @ildar170975 was referring to the question regarding css mod; more clearly displaying min/max would definitely be a contribution I'd accept (if interested, please discuss your approach first to avoid wasted effort)

**Comment by wonderiuy** [comment]
For the min/max values starting from the same point, a possible approach could be to add one period interval hiding outside the graph, ie: 7 days -> take 8 days and display the latter 7


> > more clearly displaying min/max would definitely be a contribution I'd accept
> 
> The question is that it is unclear for me from where these "min, max, media" value are taken. Without a code people may only guess.

It's a humidity sensor coming from Legrand/bticino thermostat, the code is:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.smarther_thermostat_humidity
    aggregate_func: max
    name: Max
  - entity: sensor.smarther_thermostat_humidity
    aggregate_func: min
    name: Min
  - entity: sensor.smarther_thermostat_humidity
    aggregate_func: avg
    name: Media
    color: green
line_width: 3
align_state: center
show:
  labels: false
  average: false
  extrema: true
  state: true
  fill: fade
name: Umidità ultima settimana
hours_to_show: 168
group_by: date
```
Sorry for non posting it
