### ISSUE TITLE
[bug] Aggregation using wrong data when data is missing

### ISSUE THREAD

**Issue by wonderiuy** [kalkih/mini-graph-card#870]
I'm trying to display device usage with a statistic graph, aggregating it by date (day) but when teh data is missing the previuos data are shown. This is a parallel with the Lovelace statistic graph (which correctly avoids displaying the bar when data is missing):

![wrong-display](https://user-images.githubusercontent.com/53263262/201895506-f5b3663e-ec71-479c-8771-4e1338a52e99.jpg)

Any solution?
My code:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.pro_6000_9e5e_time
    color: '#7396b7'
  - entity: sensor.smart_series_7000_be71_time
    color: '#b27bba'
hour24: true
name: Spazzolino ultima Settimana
icon: mdi:toothbrush
align_state: center
unit: s
hours_to_show: 168
aggregate_func: max
group_by: date
show:
  graph: bar
  labels: true
  legend: false
```
