### ISSUE TITLE
Data point not written in state field, when zero

### ISSUE THREAD

**Issue by akloeckner** [kalkih/mini-graph-card#876]
I just discovered that datapoints with `0` value are not written into the state field, when hovering over the data point.

Example:
![image](https://user-images.githubusercontent.com/7125061/205079733-0b677098-9e24-4631-958e-aa6b8c3d1af3.png)

The state field reads `18,9%`. It should read `0%`. The value `18.9` is the curent state of the primary entity (the actual temperature). And `%` is the unit of the data point currently hovered above (the opening of the thermostate valve).

Configuration for reference:
```yaml
type: custom:mini-graph-card
entities:
  - entity: climate.eingang_thermostat
    attribute: current_temperature
    unit: °C
  - entity: climate.eingang_thermostat
    attribute: temperature
    unit: °C
  - entity: sensor.eingang_thermostat_level
    y_axis: secondary
    unit: '%'
hours_to_show: 24
points_per_hour: 2
aggregate_func: avg
hour24: true
decimals: 1
smoothing: true
show:
  graph: line
  labels: true
  labels_secondary: true
  legend: false
```
