### ISSUE TITLE
Strange binning when using group_by in line graph

### ISSUE THREAD

**Issue by akloeckner** [kalkih/mini-graph-card#878]
I experience some strange behavior when binning data through `group_by` in a `line` graph.

Here's a working-as-expected card. Note how the rightmost point (currently hovered above) is today (2nd Dec):
![grafik](https://user-images.githubusercontent.com/7125061/205181500-882b6b11-86f5-4357-b1f8-380b7ca820da.png)

```yaml
type: custom:mini-graph-card
name: Außentemperatur
entities:
  - entity: weather.forecast_home
    attribute: temperature
    name: mean
    unit: °C
    aggregate_func: avg
hours_to_show: 72
group_by: date
hour24: true
decimals: 1
smoothing: false
show:
  graph: line
  labels: true
```

If I set the `hour_to_show` to something not-a-multiple-of-24, say `73` I get the following card. Note how the rightmost point is yesterday (1st Dec). It also seems shifted to the left a bit.
![grafik](https://user-images.githubusercontent.com/7125061/205181686-3d267ad3-794d-42dd-a83c-ca6876a186b5.png)

This issue does not happen with a `bar` graph.
