### ISSUE TITLE
First point not rendered as mouse-over-able

### ISSUE THREAD

**Issue by akloeckner** [kalkih/mini-graph-card#879]
When we render a graph, the `line` is drawn for all coordinates (or, data points). But the first coordinate is not drawn as a `point`, i.e. the user cannot hover over the point and read its value.

Example following. Notice the missing small circle for the left-most data point. There should be 3 points. But only 2 are rendered.
![image](https://user-images.githubusercontent.com/7125061/205264407-cb0090d6-58a0-431d-b205-2cbdd34cbcef.png)

Corresponding configuration:
```yaml
type: custom:mini-graph-card
entities:
  - entity: sensor.haushalt_gasverbrauch
hours_to_show: 3
points_per_hour: 1
aggregate_func: mean
hour24: true
decimals: 2
smoothing: false
show:
  graph: line
  labels: false
  state: false
```

Judging from the following code line, it seems this first point is removed on purpose. Is that correct? If so: Why is that? If not: Should it be fixed?
https://github.com/kalkih/mini-graph-card/blob/8e70381e3d887e5803bc8fc4bc115ecc4dc587e0/src/graph.js#L123

**Comment by ildar170975** [comment]
@akloeckner 
The issue is associated with a PR which was merged.
Shall we close the issue?
Or this merged code is still in dev?

**Comment by akloeckner** [comment]
The merged code is still in dev. We have never merged dev into master. I think we should do that at the next occasion. The code is stable for multiple months now...

**Comment by ildar170975** [comment]
Then let's keep the issue open...

**Comment by ildar170975** [comment]
@akloeckner 
Seems to be fixed: the 1st point is shown as a "point":

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/42e63974-7e28-4c78-864e-00922c8bd953)
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_co2
hours_to_show: 3
points_per_hour: 1
aggregate_func: mean
hour24: true
decimals: 2
smoothing: false
show:
  graph: line
  points: true
  labels: false
  state: true
```
Shall we close?
