### ISSUE TITLE
Border when embedded since 2022.11.0 (borders are not handled by "group: true")

### ISSUE THREAD

**Issue by julienlarivee** [kalkih/mini-graph-card#883]
When the card is embedded in an entities card, there is a border around the mini graph card.
Before HA 2022.11.0, there was no border.
![image](https://user-images.githubusercontent.com/55027006/205513726-92a6e141-bda3-442e-b8b8-30b2fa05bc75.png)
```
type: entities
entities:
  - entity: climate.thermostat_cuisine
    icon: mdi:thermostat
    name: Cuisine
    group: true
    type: custom:mini-climate
  - type: custom:mini-graph-card
    group: true
    entities:
      - entity: sensor.temperature_cuisine
        name: Température
```

If we look at the same entities, but with native HA cards, there is still no border in 2022.11.0
![image](https://user-images.githubusercontent.com/55027006/205513738-d5842100-3a76-4cd0-8fa7-712a18593ba8.png)
```
type: entities
entities:
  - entity: climate.thermostat_cuisine
  - entity: sensor.temperature_cuisine
```

Also, the time picker card had the same issue, but they fixed it. Here is the link to it if it can help:
https://github.com/GeorgeSG/lovelace-time-picker-card/issues/43
