### ISSUE TITLE
12:05 pm being displayed as 00:05 pm

### ISSUE THREAD

**Issue by dunxd** [kalkih/mini-graph-card#887]
When I mouse over my graph, the time shown is 00:nn pm instead of 12:nn pm

![image](https://user-images.githubusercontent.com/16608541/206922732-6480e7e7-ac89-44d2-a65d-2eed4e63b5f5.png)

If I set `hour24: true` then it shows 12:nn correctly.

**Comment by craigusus** [comment]
Hi,
I am getting the same. I have the following:

```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-title-card
        title: Values
        title_tap_action:
          action: none
        subtitle_tap_action:
          action: none
        alignment: center
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        hours_to_show: 24
        points_per_hour: 1
        entities:
          - sensor.212_value_almost_daily_dividend
        name: Daily Dividend
        icon: a
      - type: custom:mini-graph-card
        hours_to_show: 24
        points_per_hour: 1
        entities:
          - sensor.212_value_own_the_world_in_50
        name: Own The World in 50
        icon: a
```
With no `hour24` stated it defaults to `false` as per the [readme](https://github.com/kalkih/mini-graph-card#:~:text=show%20for%20states.-,hour24,-boolean). But as you can see below, when hovering over the data point it is showing as 0:43 pm. It should be 12:43 pm.

![image](https://github.com/kalkih/mini-graph-card/assets/6324863/e9abc621-ecca-4570-a82a-2577fa878820)

When adding `hour24: true` I get the correct time format shown.
![image](https://github.com/kalkih/mini-graph-card/assets/6324863/c2566c18-dad7-421a-aac3-c5148d7e1e3d)
