### ISSUE TITLE
show_state: false does not hide the state

### ISSUE THREAD

**Issue by MayeulC** [kalkih/mini-graph-card#889]
I was thinking the readme lacked an example for `state_map`, so I was building one by replicating the "thermostat" card from lovelace, which seemed to be a common request:

![image](https://user-images.githubusercontent.com/3952726/207022523-25773981-2171-4b26-91a0-7bebeb66cd38.png)

This is the yaml code:

```yaml
type: custom:mini-graph-card
name: Bedroom thermostat
hours_to_show: 24
points_per_hour: 60
decimals: 1
entities:
  - entity: climate.bedroom
    attribute: temperature
    name: target
    line_width: 1
    color: purple
    show_points: false
    show_legend: false
    show_fill: false
    show_state: false
    smoothing: false
  - entity: climate.bedroom
    attribute: current_temperature
    name: temperature
    show_state: true
  - entity: climate.bedroom
    attribute: hvac_action
    y_axis: secondary
    color: orange
    smoothing: false
    show_legend: false
    show_line: false
    show_points: false
state_map:
  - value: idle
    label: off
  - value: heating
```

And the result:
![image](https://user-images.githubusercontent.com/3952726/207022763-34abb56f-14e4-46ce-91b7-30e0408b3d33.png)

As you can see, this is almost ready to be used as an example (it may be a bit too long and may be more fitting in a wiki page).

The one issue I encounter is the following: since I wanted the target temperature to be in the background, I specified it first. However, I would prefer to have the `current_temperature` displayed as the state.
Unfortunately, hiding the state does not seem to be working for the first entity, as shown in the screenshot.

Displaying it works for the second entity, however.

**Comment by rogersmj** [comment]
Ha, I was trying to do the exact same thing, and ran into the same problem. The `show_state` option on entities doesn't seem to be fully working. I want the current temperature to be shown as the state, but I want it to be the third graph, so it's on "top" -- but this doesn't seem to be possible because of the bug with show_state.

```
- type: custom:mini-graph-card
        entities:
          - entity: sensor.target_temp_high_main_floor
            color: "var(--google-blue)"
            show_fill: false
            show_legend: false
            show_state: false
          - entity: sensor.target_temp_low_main_floor
            color: red
            show_fill: false
            show_legend: false
            show_state: false
          - entity: sensor.main_floor_thermostat_current_temperature
            name: Main floor
            color: "var(--google-green)"
            show_fill: false
            show_state: true
          - color: gray
            entity: binary_sensor.heating_on_main
            name: Heat (main)
            show_line: false
            show_fill: true
            show_points: false
            show_legend: false
            y_axis: secondary
        show:
          labels: true
          labels_secondary: false
        state_map:
          - value: "off"
            label: Off
          - value: "on"
            label: On
        points_per_hour: 60
        smoothing: false
```

![image](https://user-images.githubusercontent.com/20134/209704720-4a73b301-bcb1-4aeb-a32f-6738ef14af7f.png)

That "76 F" shouldn't be there, and the "70 F" should be on the left.

**Comment by rogersmj** [comment]
@kalkih Have you had a chance to look at this? I thought I might try to help but I'm a bit out of my depth when it comes to getting this running in such a way that I can develop against it, still working on that.

**Comment by ildar170975** [comment]
There is no need to post a complex code with lots of unrelated things, it distracts people from the main issue.
Consider this short:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_co2
    show_state: false
  - entity: sensor.xiaomi_cg_2_co2
    show_state: true
```
![image](https://github.com/kalkih/mini-graph-card/assets/71872483/c1f9f2e4-70c6-40c9-b7c9-7f98c742c35e)

What it was suggested is to allow hiding a state for the 1st entity.
In this particular simple case it may only be done by hiding both states:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_co2
  - entity: sensor.xiaomi_cg_2_co2
show:
  state: false
```
![image](https://github.com/kalkih/mini-graph-card/assets/71872483/96d66513-6c50-4b76-abd7-a080518b47a5)

This is by a design. 
Not a bug.
The 1st placeholder - for the 1st entity.

You still may customize it by card-mod: hide the 1st state + show the 2nd state, or move the 2nd state to the place of the 1st state (easy!).
Ask in HA community mini-graph-card thread.

FR https://github.com/kalkih/mini-graph-card/issues/972 - is about defining the "primary entity", which COULD BE an alternative to ["indexes"](https://github.com/kalkih/mini-graph-card/pull/658).

Closing this issue.
