### ISSUE TITLE
Empty graph with entities without history states

### ISSUE THREAD

**Issue by mihalken** [kalkih/mini-graph-card#89]
**Describe the bug**
Empty graph with entities without state history. A similar problem [#41](https://github.com/kalkih/mini-graph-card/issues/41).

**To Reproduce**
1. Stop update entity state, exp., `sensor.voltage1` by mqtt publish
2. Exclude entity in component `recorder`
3. **Only in test hass!** Clear entity history states. Call service `recorder.purge` with data `{"keep_days": 0, "repack": true}`.
4. Restart hass
5. Set state for entity, exp. for voltage = `12.3`
6. Add `mini-graph-card` on view
```
type: custom:mini-graph-card
show:
  graph: bar
  labels: true
entities:
  - entity: sensor.volatge1
  - entity: sensor.volatge2
  - entity: sensor.volatge3
```
7. See empty graph

**Expected behavior**
Graph card show bars current entities state.

**Screenshots**
![1](https://user-images.githubusercontent.com/9671385/57831359-bb43cc00-77d6-11e9-8083-06563c96060f.png)
![2](https://user-images.githubusercontent.com/9671385/57837584-e7664980-77e4-11e9-9637-5245b1b2d595.png)

**Home Assistant**
Version: 0.93
Tested: 0.92.2

**mini-graph-card**
Version: v0.3.3

**Additional context**
I exclude domain `sensor` and include entities those that are needed off history. Because i have a lot sensors and i want to see only current value.
