### ISSUE TITLE
Bug - graph size is drastically shrunk when used in grid view

### ISSUE THREAD

**Issue by timdonovanuk** [kalkih/mini-graph-card#890]
Why are the graphs so tiny?

![image](https://user-images.githubusercontent.com/8156439/207566760-84664aae-b044-4a86-b320-f7b5ea7d915c.png)

There is way too much padding around values, that could be put to better use by displaying the graph:

![image](https://user-images.githubusercontent.com/8156439/207566977-9e7d80ad-c1f8-4584-9381-2e9f5f34b41c.png)

I have played with various bound settings and height settings (this just increase the card height downwards which looks awkward in grids). 

Sometimes I see the graph div is much bigger but the graph doesn't seem to fill it?

![image](https://user-images.githubusercontent.com/8156439/207568086-7411625b-66d5-4c57-9e1f-73ead75f3f25.png)

How do you get it to display something more like this:

![image](https://user-images.githubusercontent.com/8156439/207568574-42f77b23-c0a3-4dfe-bd46-4be7560a8c7c.png)

**Comment by timdonovanuk** [comment]
Changed to bug, as realised this extra padding is only an issue when the card is used in grid view.

**Comment by timdonovanuk** [comment]
Even using horizontal-stack this card does not function as shown in the example docs:

```
type: horizontal-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - sensor.lounge_climate_sensor_temperature
    line_color: blue
    line_width: 8
    font_size: 75
```
Looks like (note tiny graph height):

![image](https://user-images.githubusercontent.com/8156439/207571812-c420e476-b224-43e4-90f8-4c79b8005d8e.png)

but should apparently look similar to:

![image](https://user-images.githubusercontent.com/8156439/207571847-64b66243-5773-4e02-b06c-c2077906641c.png)

**Comment by ildar170975** [comment]
Why this issue is considered as a BUG?
It's just a matter of combination of card's size & fonts' size.
Try fixing a view by customizing font size first.

**Comment by timdonovanuk** [comment]
@ildar170975 

I'm not sure what you mean, because here it is with font_size: 5 and font_size: 200

![image](https://user-images.githubusercontent.com/8156439/207718919-8dba131d-6335-4a41-8823-b64f1f03c391.png)

The font size has no impact on the positioning of the graph.

**Comment by ildar170975** [comment]
Please give me a code example - I will play and try to give you smth.
Also, give me a desired view - made in MS Paint or whatever.

**Comment by vincentscode** [comment]
I am facing the same issue in a stack configuration.
![image](https://user-images.githubusercontent.com/26576880/210158400-cea7a20f-0f37-4d92-bd15-4dce09dad6cf.png)
As you can see the graph fills up only a tiny portion of the tile regardless of font-size.
The yaml is as follows:
```yaml
type: horizontal-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.ens160_eco2
        name: eCO2
    lower_bound: 400
    upper_bound: 2000
    color_thresholds:
      - value: 600
        color: '#3D003D'
      - value: 1000
        color: '#800080'
      - value: 1500
        color: '#C700C7'
    line_width: 8
    hours_to_show: 12
    points_per_hour: 8
    font_size: 75
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.ens160_tvoc
        name: TVOC
    lower_bound: 0
    upper_bound: 2000
    color_thresholds:
      - value: 50
        color: '#266E26'
      - value: 750
        color: '#3BAB3B'
      - value: 1500
        color: '#38E038'
    line_color: lightgreen
    line_width: 8
    hours_to_show: 12
    points_per_hour: 8
    font_size: 75
```
