### ISSUE TITLE
color thresholds: wrong line color

### ISSUE THREAD

**Issue by nschloe** [kalkih/mini-graph-card#893]
I have a mini-graph-card with some color thresholds:

```yaml
type: custom:mini-graph-card
entities:
  - sensor.bogenhanf_conductivity
align_icon: left
align_state: left
show:
  fill: true
hours_to_show: 336
lower_bound: 0
upper_bound: 2500
color_thresholds:
  - value: 300
    color: '#D0342C'
  - value: 301
    color: '#008000'
  - value: 1000
    color: '#D0342C'
color_thresholds_transition: hard
```

The dots (shown when hovering over the graph) have the correct color, but the line doesnt:

![s2](https://user-images.githubusercontent.com/181628/209114189-9f39d494-58d5-48c4-a931-6f5b602ab46a.png)

![s1](https://user-images.githubusercontent.com/181628/209114207-b4bcd8b8-ef26-4d10-b730-680c47e1fc2d.png)

It doesn't matter if the transition is hard or smooth

**Comment by jlsjonas** [comment]
Hi,

There seems to be a drift on the linear gradient when setting a higher `upper_bound`.

If you need the color at a glance I'd recommend to either remove the `upper_bound` or set show option's `points: true`

**Comment by nschloe** [comment]
Observe the red and green area below the graph: They're also incorrectly computed. Perhaps the bug has something to do with that.

**Comment by ildar170975** [comment]
@nschloe 
1. Cannot reproduce your issue.

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/7c912329-a1f8-4957-a49a-bb43fe451ab0)
Code for the 1st card:
```
type: custom:mini-graph-card
name: 'lower_bound: ~400'
entities:
  - sensor.xiaomi_cg_1_co2
show:
  fill: true
  labels: true
hours_to_show: 48
height: 500
line_width: 2
lower_bound: ~400
upper_bound: 1000
color_thresholds:
  - value: 400
    color: green
  - value: 500
    color: red
  - value: 600
    color: blue
color_thresholds_transition: hard
```

2. Please post screenshots in a way to make them more visible.
> red and green area below the graph

On your screenshots this is rather subtle. Use a default light theme next time.

**Comment by nschloe** [comment]
All your transitions are quite sharp. Try it with flatter data near a color threshold.

**Comment by ildar170975** [comment]
> All your transitions are quite sharp.

This is good.

> Try it with flatter data near a color threshold.

What can it change?

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/358e7c57-ed1b-4dee-95e0-25486ec71760)
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_number.number
  - type: custom:mini-graph-card
    entities:
      - input_number.number
    show:
      fill: true
      labels: true
    hours_to_show: 0.083333
    height: 500
    cache: false
    line_width: 2
    lower_bound: 0
    points_per_hour: 600
    smoothing: false
    color_thresholds:
      - value: 0
        color: green
      - value: 10
        color: red
      - value: 20
        color: blue
    color_thresholds_transition: hard
```
