### ISSUE TITLE
documention: thresholds

### ISSUE THREAD

**Issue by nschloe** [kalkih/mini-graph-card#894]
The main documentation gives

```yaml
color_thresholds:
  - value: 0
    color: "#ff0000"
  - value: 1.333333
    color: "#ffff00"
  - value: 2.666667
    color: "#00ff00"
  - value: 4
    color: "#0000ff"
```

as an example for color thresholding. What exactly does this mean? 

- Between `0` and `1.3333` we have `#ff0000`? 
- What happens below `0`?
- What happens above `4`?

**Comment by jlsjonas** [comment]
Hi, this should indeed be cleared up a little!

Essentially, the color_treshold value works like a minimum: if the graph value is higher than a threshold, its color will apply (highest gets precedence and the first color is used as the lowest color, regardless of its value)

> Between 0 and 1.3333 we have #ff0000?

Correct! 

> What happens below 0?

Currently, the first threshold color is used; although we might want to expose the default color if no threshold was reached in the future (to improve multi-graph & allow for "red alert only" thresholds)

> What happens above 4?

`#0000ff` is applied.


i.e.:
```yaml
color_thresholds:
  - value: 0 # currently ignored
    color: "#ff0000"
  - value: 1.333333 # anything above 1.33333 
    color: "#ffff00"
  - value: 2.666667
    color: "#00ff00"
  - value: 4
    color: "#0000ff"
```

**Comment by nschloe** [comment]
If the the first "threshold" is ignored, then perhaps it should be there at all. That'd make it clearer that the thresholds are thresholds _from below_.

**Comment by Lemonadel** [comment]
Hi, it looks like it’s broken or something for past few months? Or user is broken? :D 

My config (tried using code but indentation on mobile is garbage :/ )

no matter if I skip first value 0 thd it’s shown as orange all the time even when value < orange thd.

Code:
color_thresholds:
 - value: 0
    color: blue
 - value: 100
    color: blue
 - value: 200
    color: orange
 - value: 300
    color: red
hours_to_show: 1
hour24: True
points_per_hour: 60
show:
   legend: True
   icon: False

Result:

![IMG_2171](https://github.com/kalkih/mini-graph-card/assets/43881989/f08f98e2-6b79-4924-8e22-25ffea7569bc)

**Comment by ildar170975** [comment]
First fix your posted code. Use triple "`".

**Comment by Lemonadel** [comment]
Done, thank you.

**Comment by ildar170975** [comment]
> color_thresholds

This is a global property, not per entity.
![image](https://github.com/kalkih/mini-graph-card/assets/71872483/9b0e2ead-be0a-4ef5-ac66-ac1f7568bce7)
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_number.number
  - type: custom:mini-graph-card
    entities:
      - entity: input_number.number
    color_thresholds_transition: hard
    color_thresholds:
      - value: 0
        color: blue
      - value: 30
        color: green
      - value: 50
        color: magenta
      - value: 80
        color: red
    hours_to_show: 0.08333
    points_per_hour: 600
    height: 200
    lower_bound: ~0
    show:
      points: false
      labels: true
```
