### ISSUE TITLE
Graph is jumping up and down on every graph update. 

### ISSUE THREAD

**Issue by Tontze** [kalkih/mini-graph-card#924]
Every second when graph is updated, whole graph line moves a lot up/down ? They also look completely different ? See pictures : 

![image](https://user-images.githubusercontent.com/28216916/219934267-f633c525-9134-4eb9-ada3-63e2e4a573e2.png)
![image](https://user-images.githubusercontent.com/28216916/219934292-a67d1332-3c2b-43c8-9b0b-96e9cfae442f.png)

**Comment by ildar170975** [comment]
What else do you you expect with “points_per_hour: 1” ????
A real frequency is high, no wonder curves are different.

**Comment by Tontze** [comment]
I wouldnt expect it to move whole graph up and down every second and modify it all the way every second... I thought points per hour is for user, how often he wants have check point on the graph, but i assume it is much more.

**Comment by Tontze** [comment]
I hanged it to 60, jump is much smaller now, but it still happends. Added video, right after value change, whole line moves downwards... 

https://user-images.githubusercontent.com/28216916/219937356-30d03e21-9573-4b45-8efd-493d4e9e0511.mp4

**Comment by ildar170975** [comment]
Check this:
```
type: vertical-stack
title: sysmon::scan_interval
cards:
  - type: entities
    entities:
      - entity: sensor.processor_use
        secondary_info: last-changed
  - type: history-graph
    hours_to_show: 1
    refresh_interval: 0
    entities:
      - entity: sensor.processor_use
  - type: custom:mini-graph-card
    name: 30 sec
    hours_to_show: 1
    update_interval: 0
    aggregate_func: last
    smoothing: false
    lower_bound: ~0
    line_width: 1
    entities:
      - entity: sensor.processor_use
    points_per_hour: 120
  - type: custom:mini-graph-card
    name: 15 sec
    hours_to_show: 1
    update_interval: 0
    aggregate_func: last
    smoothing: false
    lower_bound: ~0
    line_width: 1
    entities:
      - entity: sensor.processor_use
    points_per_hour: 240
```
and then play with `points_per_hour` for the 1st "mini-graph-card".
The real update frequency seems to be 15 sec (i.e. points_per_hour=240).
