### ISSUE TITLE
color_thresholds don't work in multiple entities config (with a hack/fix)

### ISSUE THREAD

**Issue by Mariusthvdb** [kalkih/mini-graph-card#926]
While a mini-graph with a single entity and 
```

        - entity: sensor.schimmel_sensor
          name: Schimmel
          color_thresholds:
            - value: 40
              color: skyblue
            - value: 50
              color: green
            - value: 60
              color: lightsalmon
            - value: 65
              color: orange
            - value: 70
              color: maroon
```
works as expected, 

<img width="502" alt="Scherm­afbeelding 2023-02-19 om 17 45 35" src="https://user-images.githubusercontent.com/33354141/219962154-5c27538d-85e9-409a-90b4-412de0dd74e2.png">

using the exact same mapping in a multiple entities graph shows only a fixed (and un configured ) color:

```
      entities:
        - entity: sensor.luchtvochtigheid_living
          name: Vocht
          color: skyblue
        - entity: sensor.schimmel_sensor
          name: Schimmel
          color_thresholds:
            - value: 40
              color: skyblue
            - value: 50
              color: green
            - value: 60
              color: lightsalmon
            - value: 65
              color: orange
            - value: 70
              color: maroon
#           y_axis: secondary
        - entity: sensor.temperatuur_living
          name: Temperatuur
          color: gold
          y_axis: secondary
```

<img width="501" alt="Scherm­afbeelding 2023-02-19 om 17 44 34" src="https://user-images.githubusercontent.com/33354141/219962089-b69a8a50-4dd5-4eb1-bd8f-b7f580b467f0.png">

not really sure this is a documented feature, and hence a bug. sorry if it isnt.

I did find a way to 'fix' this btw, by setting the color_thresholds on the main config, and overriding this in the entity object:
```
      type: custom:mini-graph-card
      height: 100
      line_width: 3
      font_size: 75
      color_thresholds:
        - value: 40
          color: skyblue
        - value: 50
          color: green
        - value: 60
          color: lightsalmon
        - value: 65
          color: orange
        - value: 70
          color: maroon

      show:
        fill: fade
        extrema: true
        icon: false
#         name: false
      entities:
        - entity: sensor.luchtvochtigheid_living
          name: Vocht
          color: skyblue
        - entity: sensor.schimmel_sensor
          name: Schimmel
#           y_axis: secondary
        - entity: sensor.temperatuur_living
          name: Temperatuur
          color: gold
          y_axis: secondary
```

<img width="501" alt="Scherm­afbeelding 2023-02-19 om 17 49 45" src="https://user-images.githubusercontent.com/33354141/219962356-638df142-c82c-4a07-a66d-d211ba7ece8b.png">

**Comment by akloeckner** [comment]
I just checked the docs and that seems to be expected behaviour. The colour thresholds can only be set for the entire card and not for single entities. It's also quite involved to make options work for single entities, so, I think this will not be added as a feature any time soon.

**Comment by martindybal** [comment]
+1 for this. For my case I need only one `color_thresholds`. And other lines can have a single color. Something like this. It's not working.
```
            color_thresholds:
              - value: 18
                color: "#03a9f4"
              - value: 20
                color: "#f39c12"
              - value: 24
                color: "#d35400"
              - value: 26
                color: "#c0392b"
            entities:
              - entity: sensor.realtemperature_pichler_supply_air_temperature
              - entity: sensor.realtemperature_pichler_extract_air_temperature
                line_color: yellow
              - entity: sensor.realtemperature_pichler_outdoor_air_temperature
                line_color: green
              - entity: sensor.realtemperature_pichler_exhaust_air_temperature
                line_color: blue
```                
<img width="384" alt="image" src="https://github.com/kalkih/mini-graph-card/assets/7644099/6ecbf248-35ce-4a2f-858e-c93f1efd0e53">
