### ISSUE TITLE
Problem with color_thresholds

### ISSUE THREAD

**Issue by vitinhosessa** [kalkih/mini-graph-card#93]
**Hassio version**
0.93.0

**mini-graph-card-bundle version**
0.4.1

**Lovelace Card**
````yaml
align_header: left
align_icon: left
align_state: left
color_thresholds:
  - color: '#ff0000'
    value: 0
  - color: '#ffa100'
    value: 100
  - color: '#ede500'
    value: 140
  - color: '#1dff00'
    value: 180
  - color: '#d800ff'
    value: 200
entities:
  - entity: sensor.speedtest_download
height: 88
hour24: true
hours_to_show: 12
icon: 'mdi:download'
lower_bound: 0
name: Download
points_per_hour: 4.5
show:
  extrema: true
  fill: fade
type: 'custom:mini-graph-card'
unit: MB/s
````

![mini graph](https://user-images.githubusercontent.com/41197767/57961509-ccc7c980-78e5-11e9-9b15-eaaf830664c8.png)
