### ISSUE TITLE
Issue with pulling attribute for Mini Graph

### ISSUE THREAD

**Issue by chicknlil** [kalkih/mini-graph-card#938]
I've got the following sensor:

![image](https://user-images.githubusercontent.com/100124187/223620573-db063f0d-2955-4596-8ca4-d075d9e0a889.png)

In trying to setup a card for this, it doesn't seem to know how to respond to the attribute provided (but perhaps I'm supplying it wrong?):

```
type: custom:mini-graph-card
entities: 
  -  entity: sensor.waqi_east_hartford_connecticut_usa
     attribute: Pm 10
     name: pm 10
     show_state: true
color_thresholds:
  - value: 0
    color: "#2ead8c"
  - value: 51
    color: "#ede066"
  - value: 101
    color: "#edad66"
  - value: 151
    color: "#c73a66"
  - value: 201
    color: "#7a3ab3"
  - value: 301
    color: "#8b395a"
hours_to_show: 168
show:
  icon: false
```
That makes this:
![image](https://user-images.githubusercontent.com/100124187/223620880-a6611b0a-797e-4d8e-b708-e7504aead1d8.png)

Ideally, what I'm looking to do is have one (or several if necessary) cards that tells me what the "Dominentpol" is and displays it (at the moment, it's PM 25), as well as the Pm 10 and Pm 2 5, all of which are attributes.

Am I doing this wrong?
