### ISSUE TITLE
Graph may not be updated

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#944]
HA 2023.3.5
latest `mini-graph-card`
Win10+Chrome

Consider this code:
```
input_number:
  testing_number_01:
    min: 0
    max: 1
    step: 1
    mode: slider
```
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: input_number.testing_number_01
        name: number
        secondary_info: last-changed

  - type: history-graph
    entities:
      - input_number.testing_number_01
    hours_to_show: 1

  - type: custom:mini-graph-card
    entities:
      - input_number.testing_number_01
    hours_to_show: 1
    points_per_hour: 3600
    aggregate_func: last
    smoothing: false
    line_width: 1
    cache: false
    show:
      labels: true

```
where `cache: false` seems to be not affecting at all, `points_per_hour: 240` is defined to ensure that changes made frequently by a user (here interval is 15 sec) are displayed properly.

Clear browser cache.

The initial state:
![image](https://user-images.githubusercontent.com/71872483/227688764-f1b03363-30b1-4ee4-80da-d702058e2e57.png)

Now change value and see how the `mini-graph-card` is updated.
**After 1 minute the graph is not updated:**
![image](https://user-images.githubusercontent.com/71872483/227688950-33b5f63b-e925-4b0d-a57f-af0f32bc3ac2.png)

Change again:
![image](https://user-images.githubusercontent.com/71872483/227688980-1c631bb2-91fd-44f6-bc67-f41db9ae4392.png)
Immediately after changing the graph is redrawn - **but we see only "0 -> 1" change instead of "0 -> 1 -> 0".**

Go to Editor - the graph is displayed properly:
![image](https://user-images.githubusercontent.com/71872483/227689050-1907629f-424f-4863-b7dc-e8b959fcd34b.png)

Go back, refresh (F5) - the graph is displayed properly:
![image](https://user-images.githubusercontent.com/71872483/227689116-cceb0488-b1c1-47b5-b6be-01cdc34889fc.png)

Setting `points_per_hour: 3600`, playing with `cache: false` do not help.

And now the weirdest part:
1. Copy the whole card onto another view.
2. Change value - the graph is updated properly - but after several minutes I observe the same behaviour.

**Comment by jlsjonas** [comment]
I'll try to look into it this weekend, thnx for the report!

**Comment by akloeckner** [comment]
When searching the repo for `update`, I found #250 . Maybe related.

**Comment by ildar170975** [comment]
I noticed the problem recently - may be same time when history-graph became "streaming"; not sure if it could be related...

**Comment by echo-lalia** [comment]
I just want to add that I believe I am observing the same issue. Graphs only seem to be accurate on refresh, and have really unexpected behavior when displaying them for a long time. (in addition to not updating regularly, I am having issues where two entities on the same graph/axis will not line up properly, or will disappear)

Before refreshing:
![image](https://github.com/kalkih/mini-graph-card/assets/108598670/b4d7b1ae-86dc-4531-be70-3f073d770158)

After refreshing:
![image](https://github.com/kalkih/mini-graph-card/assets/108598670/f3a3a914-1ce2-4e47-a5d3-d923f517ff48)


```
- type: custom:mini-graph-card
  entities:
    - entity: sensor.octoprint_actual_tool0_temp
      show_fill: false
    - entity: sensor.octoprint_target_tool0_temp
      smoothing: false
      show_fill: true
      show_line: false
      show_state: false
      show_points: false
  hours_to_show: 1
  points_per_hour: 10
  min_bound_range: 5
  show:
    icon: true
    extrema: false
    fill: fade
    legend: false
    name: false
  icon: mdi:printer-3d-nozzle-heat
  align_icon: state
  update_interval: 5
```
