### ISSUE TITLE
Changing a unit of measure of an entity is not reflected in the graphs

### ISSUE THREAD

**Issue by mfarad** [kalkih/mini-graph-card#945]
If we have an entity providing value in watts and we change his unit of measurement (by ex: in kW), the value displayed in the card is correct (kW) but the graph (+color_thresholds) is still based on the original value (watts).

**Card:**
 ```
  type: custom:mini-graph-card
  entities:
    - sensor.powerglobal_watts
  font_size: 100
  name: Power Global
  state_adaptive_color: true
  color: '#e6005c'
  icon: mdi:flash
  color_thresholds:
    - value: 1000
      color: '#1cf100'
    - value: 2000
      color: '#b5f100'
    - value: 5000
      color: '#f1b500'
    - value: 7000
      color: '#ff0000'
  points_per_hour: 30
  hours_to_show: 24
  hour24: true
  update_interval: 1
  align_state: center
  show:
    labels: false
    fill: true
```
![card](https://user-images.githubusercontent.com/7850425/227876729-4091b03a-7851-4a3d-b3a3-1b30eadcf74b.png)

**Entity:**

![entity](https://user-images.githubusercontent.com/7850425/227876604-20568730-bf40-4fb7-815a-214cf9692890.png)
