### ISSUE TITLE
Line color doesn't change according to the thresholds.

### ISSUE THREAD

**Issue by CosminFRC** [kalkih/mini-graph-card#950]
Hi,

I have a graph card for a humidity sensor but I can't make it work as it should.
The line gets the last treshold color and it doesn't change color when the state changes, although the state color changes according to the tresholds. So, the state color is working great but the line color doesn't.
Maybe I messed up something in the yaml config. but I really don't know.
```
type: custom:mini-graph-card
line_width: 8
font_size: 200
height: 55
hour24: true
entities:
  - entity: sensor.termostat_camera_ami_humidity
    state_adaptive_color: true
    unit: '%'
show:
  labels: false
  extrema: false
  state: true
  name: true
  icon: true
  name_adaptive_color: false
  icon_adaptive_color: false
color_thresholds:
  - value: 0
    color: '#b9fdff'
  - value: 30
    color: '#9da6e5'
  - value: 60
    color: '#f288ff'
name: Umiditate
hours_to_show: '24'
group_by: hourly
```

**Comment by ildar170975** [comment]
Probably there are issues with `color_thresholds`.
But check this, seems to work fine:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_number.number
  - type: custom:mini-graph-card
    entities:
      - entity: input_number.number
        state_adaptive_color: true
    color_thresholds:
      - value: 0
        color: red
      - value: 100
        color: green
      - value: 200
        color: blue
    hours_to_show: 0.083333
    points_per_hour: 3600
    smoothing: false
    color_thresholds_transition: hard
    line_width: 1
    lower_bound: 0
```
![image](https://user-images.githubusercontent.com/71872483/231876913-ef0cc0b3-e2e6-4e6d-a43f-232e63376543.png)


Suggestions:
1.Next time when you post a code - do not post a code with options which are not relevant to a problem (like `group_by` etc).
Use options which HELP to localize an issue - like "normal" colors (hex values are not as clear as "red" or "green").
2.Check other open issues here, there are already present issues for the same (or similar) problem, no need to register one more.
