### ISSUE TITLE
Is using templates in the hours_to_show option possible?

### ISSUE THREAD

**Issue by Aaroneisele55** [kalkih/mini-graph-card#952]
I want to make a graph with adjustable historic time ( using an input_number helper), but that makes the graph disappear, even tough when I set the same value in the YAML code, it works. I'm using the following code:

```
type: custom:mini-graph-card
hour24: true
animate: true
hours_to_show: |
  {{states("input_number.graph_stunden")|int}}
entities:
  - entity: sensor.anteil_co2_neutraler_strom
  - entity: sensor.anteil_solarstrom
```
Where the template works when used in the dev tools template section, and the graph card works when I put in a 2 instead of the Template

How should I do it instead?

Thanks
Aaron
