### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#960]
0.12.0-dev.2

Observe this error in Browser console for ALL entities which were not changed within a selected period:

1) DB size did not change within 4 days (> 24 hrs which is a default value for `hours_to_show`)
```
type: custom:mini-graph-card
entities:
  - sensor.home_assistant_v2_db_size
```
![изображение](https://user-images.githubusercontent.com/71872483/234384858-b24f4399-47e2-4e83-8666-be42ca6557c7.png)

![изображение](https://user-images.githubusercontent.com/71872483/234384910-efc39b90-e822-493f-ada8-f9707cc36af8.png)

2) This `input_number` helper was not changed for a long time.
Consider this card:
```
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    entities:
      - input_number.testing_device_class_apparent_power
  - type: history-graph
    entities:
      - entity: input_number.testing_device_class_apparent_power
  - type: entities
    entities:
      - entity: input_number.testing_device_class_apparent_power
```
Now the graph is not displayed, same errors in the console:
![изображение](https://user-images.githubusercontent.com/71872483/234386722-c8e6db6e-a546-4310-8804-b4b8ccf073e6.png)
![изображение](https://user-images.githubusercontent.com/71872483/234386760-446b1d61-6fc5-49cf-b35c-5c48c8104110.png)

Change the helper's value - then the graph will be displayed w/o errors:

![изображение](https://user-images.githubusercontent.com/71872483/234386973-38d73a38-7ca1-4ac9-bf11-8963f484ba99.png)

3. Any sensor which value was changed more than 15 minutes ago:
![изображение](https://user-images.githubusercontent.com/71872483/234388122-5ce4bf35-62e0-4ad4-9bb8-5c47fb79bf9b.png)
