### ISSUE TITLE
Help with thresholds

### ISSUE THREAD

**Issue by fridrichovsky** [kalkih/mini-graph-card#964]
Hello,
first of all I would like to say that mini graph card  is really great card. I am new with HA so I would like ask you if I do something wrong.

What I want is that I will see graph blue for temperature bellow -10, light blue for bellow zero, orange over zero and red over 28. 

I set this:
```
        color_thresholds_transition: hard
        color_thresholds:
          - color: blue
            value: -50
          - color: '#039BE5'
            value: -10
          - color: var(--accent-color)
            value: 0
          - color: '#E74C3C'
            value: 28
```
Problem is that I do not see expected graph with correct color, but I se black graph.

![obrazek](https://github.com/kalkih/mini-graph-card/assets/56153909/c5b50627-0edc-4b8d-81aa-bdf618a395b0)

What I have is that my temperature sensor have samples from 1,5C to 18C. It means that my database do not have temperatures bellow zero and over 28C.
I did some test. 
TEST 1. When I set thresholds in "samples" range it works same way as I expected. But with wrong thresholds for me.
```
        color_thresholds_transition: hard
        color_thresholds:
          - color: blue
            value: 2
          - color: '#039BE5'
            value: 5
          - color: var(--accent-color)
            value: 7
          - color: '#E74C3C'
            value: 10
```
![obrazek](https://github.com/kalkih/mini-graph-card/assets/56153909/80ed9161-bfb4-46e6-8c38-909e27d92a3e)

TEST 2. Last threshold over then existing data set highest part to black color, same behavior is for lowest threshold:
```
        color_thresholds_transition: hard
        color_thresholds:
          - color: blue
            value: 2
          - color: '#039BE5'
            value: 5
          - color: var(--accent-color)
            value: 7
          - color: '#E74C3C'
            value: 28
```
![obrazek](https://github.com/kalkih/mini-graph-card/assets/56153909/a2e5b4fb-a1ff-44f1-9a00-6de544d6e833)

TEST 3. Required thresholds with lower and upper bound works, but it create small graph:
```
        upper_bound: ~50
        lower_bound: ~-50
        color_thresholds_transition: hard
        color_thresholds:
          - color: blue
            value: -50
          - color: '#039BE5'
            value: -10
          - color: var(--accent-color)
            value: 0
          - color: '#E74C3C'
            value: 28

```
![obrazek](https://github.com/kalkih/mini-graph-card/assets/56153909/88c73925-d9f1-4a8d-8ca0-0ab390b286e7)

TEST 4: If I change upper_bound lower then highest threshold graph is changed to black

TEST 5: If I set working thresholds and I wait few days. I get new values (for last monitored 48h) that are not in "correct" range. Minigraph is again black.

I would like to use threshold for see temperature ranges. It does not mean that I will see all colors it should be depended on values from last 48 hours (set in hours_to_show). 

Thank you for your advices and help

**Comment by ildar170975** [comment]
1. Please post screenshots made in a default light theme. Sorry, I see nothing.
2. I guess it is rather difficult to see something in a small narrow area. So, retest with a full width card with `height: 200` defined.
3. Also, not many people are able to say what "E74C3C" is. So, test either with human-friendly "green/red/..." or easily recognizable "#ff0000 / #00ff00 / #0000ff".

**Comment by fridrichovsky** [comment]
Add 1. and 2. I changed colors and heigh and mark problem parts. 

![obrazek](https://github.com/kalkih/mini-graph-card/assets/56153909/4c2a4fad-01f8-4403-adc2-1a7bd0701594)

Add 3. 
  It is standard for colors and how to set so customer color. But for you I changed setup

```
type: custom:mini-graph-card
height: 200
entities:
  - entity: sensor.pokoj_teplomer_humidity
    name: Aktuální vlhkost
    show_legend: false
    smoothing: false
    extrema: true
name: Vlhkost
points_per_hour: 2
color_thresholds_transition: hard
color_thresholds:
  - color: red
    value: 0
  - color: yellow
    value: 40
  - color: green
    value: 45
  - color: blue
    value: 55
  - color: red
    value: 60
```
