### ISSUE TITLE
bug: states and colors get confused with multiple sensors.

### ISSUE THREAD

**Issue by ex-nerd** [kalkih/mini-graph-card#971]
I'm trying to set up a card to graph the 3 particulate readings from my AirGradient sensor. Given a config like this:

```yaml
type: custom:mini-graph-card
title: Outdoor Particulate Matter
entities:
  - entity: >-
      sensor.airgradient_open_air_1_airgradient_open_air_particulate_matter_2_5um_concentration
    name: PM2.5
    show_state: true
    state_adaptive_color: true
  - entity: >-
      sensor.airgradient_open_air_1_airgradient_open_air_particulate_matter_10_0um_concentration
    name: PM10
    show_state: true
    state_adaptive_color: true
  - entity: >-
      sensor.airgradient_open_air_1_airgradient_open_air_particulate_matter_1_0um_concentration
    name: PM1
    show_state: true
    state_adaptive_color: true
line_width: 2
hours_to_show: 24
min_bound_range: 10
show:
  # labels: true
  fill: fade
  # name: false
  state: true
  # icon: false
  icon_adaptive_color: true
  name_adaptive_color: true
  state_adaptive_color: true
```

It renders this oddity that shows 3 measurements in different colors/sizes. I get states for entities 2 and 3, but for some reason the "overall average" (?) larger value is colored the same as the "primary" `PM2.5` (I really wish I could specify which one is primary rather than just the first), while the name shows `PM2.5` in the top left corner.

<img width="501" alt="Screenshot 2023-05-31 at 11 43 10 PM" src="https://github.com/kalkih/mini-graph-card/assets/154074/daceff6a-d1fe-41cb-8800-65f0c3c8a6b4">

However, if I move the cursor over the `PM1` legend to get its current state (sorry, screenshot hides the cursor), you notice that the name in the top left corner changes to `PM1` and the larger orange value now shows the value of the `PM1` sensor. But it's still orange.

<img width="499" alt="Screenshot 2023-05-31 at 11 44 05 PM" src="https://github.com/kalkih/mini-graph-card/assets/154074/caefca38-314d-40d7-afa5-36a4e6053060">

I was hoping with various config options to:

- Show the current value of the "primary" sensor by default (to match its name in the top left), or at least show it somewhere (as the other 2 are shown)
- When hovering over the graph, the color of the "current" value should match the color of the sensor it is displaying.
- Either one of the following:
   - Show only one sensor value at a time (e.g. hide the two side-by-side values on the right and show the current value of the primary sensor int he main position, updating to the value of whichever non-primary sensor I hover over)
   - Show all 3 sensor current values in a similar layout to their legend positions (e.g. all in a line horizontally), or at least all of the same size
