### ISSUE TITLE
Bar graph height not correct in relation to previous days.

### ISSUE THREAD

**Issue by GeraldPape** [kalkih/mini-graph-card#973]
Using a BAR graph, the current day bar height is way to less.

the far right bar shall present a value of 3.072 Wh, the bar to the left 4.974Wh
![grafik](https://github.com/kalkih/mini-graph-card/assets/72608781/cafbd363-6522-4be4-822e-5edb1a292a0c)

```
      - type: custom:mini-graph-card
        aggregate_func: max
        color_thresholds:
          - color: '#900D09'
            value: 1000
          - color: '#f1c232'
            value: 2000
          - color: '#b6d7a8'
            value: 3000
          - color: '#6aa84f'
            value: 4000
        color_thresholds_transition: hard
        entities:
          - sensor.balkon_yieldday
        group_by: date
        hour24: true
        hours_to_show: 168
        name: Tägliche Produktion
        show:
          fill: fade
          graph: bar
          labels: false
        smoothing: false

```
