### ISSUE TITLE
Mini graph cards loading empty

### ISSUE THREAD

**Issue by L0bit0** [kalkih/mini-graph-card#974]
Hi

since arround one week ago I use to get all my cards using mini graph empty:
![image](https://github.com/kalkih/mini-graph-card/assets/10359623/102b0e3d-344b-4a8a-94fb-431bbaf46040)
and should show something like this:
![image](https://github.com/kalkih/mini-graph-card/assets/10359623/e71d3e60-f88c-4dc6-88f3-21b000a26c86)

As soon I restart home assistant it works again for some hours.

More info:
- I do not see any error on the logs
- I tried to redownload
- I create a new view with only one card, just in case performance or other cards are being affecting, and it also did not work
- this is the only card failing
- It is happening with all mini graph cards, also with oter sensors.
- This is card YAML:
```
type: custom:mini-graph-card
name: Netatmo Temperatura (7d)
line_width: 0.5
hours_to_show: 168
tap_action:
  action: navigate
  url: /dashboard-salondashboard/netatmo
show:
  state: false
  fill: true
  name: false
  icon: false
entities:
  - entity: sensor.netatmo_ext_temperature
    name: EXT
    color: '#3FB056'
  - entity: sensor.netatmo_int_temperature
    name: INT
    color: '#11FECA'
 
```

Any idea?

thanks in advance
