### ISSUE TITLE
Odd color issue with thresholds

### ISSUE THREAD

**Issue by aram535** [kalkih/mini-graph-card#978]
Some odd results ... I wanted to have hard color change if the temperature or humidity of these sensors goes above 55F.
The humidity graphs look strange and somehow "red" is being interpreted as "blue?" 

![graph](https://github.com/kalkih/mini-graph-card/assets/3215912/4bc59658-a475-4eb8-ac74-ca09d88f744c)
```
square: true
columns: 3
type: grid
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.wca_temperature
        name: WCA Temp
    align_state: center
    font_size: 50
    line_width: 10
    color_thresholds_transition: hard
    color_thresholds:
      - value: 0
        color: '#f39c12'
      - value: 55
        color: '#c0392b'
    aggregate_fun: avg
    update_interval: 1800
    hours_to_show: 12
    points_per_hour: 6
    show_points: false
    show_line: false
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.wcc_temperature
        name: WCC Temp
    align_state: center
    font_size: 50
    line_width: 10
    color_thresholds_transition: hard
    color_thresholds:
      - value: 0
        color: '#f39c12'
      - value: 55
        color: '#c0392b'
    aggregate_fun: avg
    update_interval: 1800
    hours_to_show: 12
    points_per_hour: 6
    show_points: false
    show_line: false
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.wcd_temperature
        name: WCD Temp
    align_state: center
    font_size: 50
    line_width: 10
    color_thresholds_transition: hard
    color_thresholds:
      - value: 0
        color: '#f39c12'
      - value: 55
        color: '#c0392b'
    aggregate_fun: avg
    update_interval: 1800
    hours_to_show: 12
    points_per_hour: 6
    show_points: false
    show_line: false
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.wca_humidity
        name: WCA Humidity
    align_state: center
    font_size: 50
    line_width: 10
    color_thresholds_transition: hard
    color_thresholds:
      - value: 0
        color: '#fff'
      - value: 55
        color: '#EE4B2B'
    aggregate_fun: avg
    update_interval: 1800
    hours_to_show: 12
    points_per_hour: 6
    show_points: false
    show_line: false
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.wcc_humidity
        name: WCC Humidity
    align_state: center
    font_size: 50
    line_width: 10
    color_thresholds_transition: hard
    color_thresholds:
      - value: 0
        color: '#fff'
      - value: 55
        color: '#EE4B2B'
    aggregate_fun: avg
    update_interval: 1800
    hours_to_show: 12
    points_per_hour: 6
    show_points: false
    show_line: false
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.wcd_humidity
        name: WCD Humidity
    align_state: center
    font_size: 50
    line_width: 10
    color_thresholds_transition: hard
    color_thresholds:
      - value: 0
        color: '#fff'
      - value: 55
        color: '#EE4B2B'
    aggregate_fun: avg
    update_interval: 1800
    hours_to_show: 12
    points_per_hour: 6
    show_points: false
    show_line: false
```
