### ISSUE TITLE
card may not be displayed in a dashboard edit mode

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#984]
Simple - the card may not be displayed.
Create a new dashboard a add 2 cards:
```
  - theme: ''
    title: xxx
    path: xxx
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: xxx
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.xiaomi_cg_1_co2
```
Absolutely same as reported for some other custom cards like windrose-card, horizon-card.

Must be:

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/456bbec0-0b5c-4ea6-8bcf-2172a9fda255)

What I see after refreshing the page:

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/43035ccb-fb9f-4613-9d7e-72aa51b34e66)

Replace `markdown` with `history-graph` - same:

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/5f85ad6b-6733-4ad0-b04e-25c9081061a5)

Use the 1st card w/o `vertical-stack` - works again.
