### ISSUE TITLE
[Feature Request] colour thresholds for single/multiple entities instead of entire card

### ISSUE THREAD

**Issue by Psicrow925** [kalkih/mini-graph-card#987]
I would like to be able to use color thresholds for single/multiple entities and not just for entire cards

would it be possible for you to implement this with a future update?

```
- cards:
      - align_state: center
        name: Temperatur & Luftfeuchtigkeit
        align_header: center
        show:
          icon: false
        entities:
          - entity: sensor.fritz_dect_440_wohnzimmer_temperatur
            name: Temperatur
            show_state: true
            color_thresholds:
              - value: 0
                color: '#58D3F7'
              - value: 20
                color: '#F3F781'
              - value: 22
                color: '#F78181'
          - entity: sensor.fritz_dect_440_wohnzimmer_luftfeuchtigkeit
            name: Luftfeuchtigkeit
            show_state: true
            color_thresholds:
              - value: 0
                color: '#58D3F7'
              - value: 40
                color: '#A9F5A9'
              - value: 60
                color: '#58D3F7'
        type: custom:mini-graph-card
```

#color_thresholds don't work in multiple entities config (with a hack/fix) #926
