### ISSUE TITLE
Dynamic color change with color_threshold not working at all

### ISSUE THREAD

**Issue by MrFr33man123** [kalkih/mini-graph-card#989]
With the example code it isn't even working.

Version 0.11.0
HA: 2023.7.4

```type: custom:mini-graph-card
entities:
  - sensor.klima_wohnzimmer_temperature
show:
  labels: true
color_thresholds:
  - value: 20
    color: '#f39c12'
  - value: 21
    color: '#d35400'
  - value: 23.5
    color: '#c0392b'
```

![image](https://github.com/kalkih/mini-graph-card/assets/906150/8a4f87d4-be2f-4b4d-a84e-467b7aef72fc)

I tried also with the color transition smooth option. Nothing helps.

**Comment by ildar170975** [comment]
To simplify a task for people, suggest to use normal human-readable names for colors instead of cryptic hexes.

**Comment by ildar170975** [comment]
@MrFr33man123 
Although hex colors are less clear for people, here is my test with hex colors.
I chose colors which are easier to imagine - `ff0000` (red), `00ff00` (green), `0000ff` (blue):
![image](https://github.com/kalkih/mini-graph-card/assets/71872483/2406ae1d-7b87-4164-9c66-ee7ab475a94b)
```
type: custom:mini-graph-card
entities:
  - sensor.xiaomi_cg_1_co2
show:
  labels: true
color_thresholds:
  - value: 560
    color: '#0000ff'
  - value: 600
    color: '#00ff00'
  - value: 650
    color: '#ff0000'
```
Some colors are rather similar, so it is advised to use `color_thresholds_transition: hard` for testing:

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/9de5ed0c-df3b-4bca-8616-b8a7093325b0)

Note that in your example the lower bound (`22.05`) is greater than the 1st & 2nd thresholds (`20`, `21`).
Here is a simulation:

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/bcb1af22-40b6-4430-985f-366c3a397e21)

With hard transition:

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/312bf856-ab64-4b83-a2a7-7ca42801b59d)
