### ISSUE TITLE
secondary labels not showing

### ISSUE THREAD

**Issue by squirtbrnr** [kalkih/mini-graph-card#991]
My graph will only show the lower and upper bound labels.  It does not show the secondary bound labels.
![image](https://github.com/kalkih/mini-graph-card/assets/35356217/63a327e7-3315-4d25-951f-bd9a0d05e868)

```
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.dsgv
        hours_to_show: 6
        points_per_hour: 12
        show:
          fill: false
          points: true
          labels: true
          labels_secondary: true
        animate: true
        height: 300
        color_thresholds:
          - value: 40
            color: "#FF0000"
          - value: 65
            color: "#C0C0C0"
          - value: 250
            color: "FFFF00"
        color_thresholds_transition: hard
        lower_bound: 40
        upper_bound: 300
        lower_bound_secondary: 65
        upper_bound_secondary: 250
```
