### ISSUE TITLE
Two or more sensors causes flat lining

### ISSUE THREAD

**Issue by smartypantsuk** [kalkih/mini-graph-card#992]
Hi, 

I simplified my code to try and diagnose this but nothing works... it has been working for months. 
I'm on latest HASS.

```
type: custom:mini-graph-card
name: Cupboard
entities:
  - entity: sensor.cupboard_humidity_9
    - sensor.cupboard_temperature_8
hours_to_show: `24`
points_per_hour: 6
```

I've tried variations of the above code,  including update frequency,  cache disabled,  etc etc.  Nothing seems to change the graph... yet with one sensor I get a proper line of data,  whereas two sensors (any sensors) I get the last in order sensor graph flat lining and the top most one with a slight curve but completely inaccurate. 

This:
![Screenshot_20230802_002302_Home Assistant](https://github.com/kalkih/mini-graph-card/assets/58052383/431b413b-c126-470e-b000-ecee24aba9fd)

Should be:
![Screenshot_20230802_002628_Home Assistant](https://github.com/kalkih/mini-graph-card/assets/58052383/72967382-9690-4d81-b1ae-ac69fc582799)

And:
![Screenshot_20230802_002536_Home Assistant](https://github.com/kalkih/mini-graph-card/assets/58052383/fed15d7b-9f87-4ed5-962b-4cd0b7bdca6e)

Tried deleting and recreating,  tried restarting HA.
Tried loads of configuration options,  nothing fixed it. 

Ok so I tried the exact code taken from the example on the code page with the exception that I changed the sensors to my own. 

```
type: custom:mini-graph-card
entities:
  - entity: sensor.cupboard_humidity_9
    show_state: true
    show_graph: false
  - entity: sensor.cupboard_temperature_7
    color: green
    show_state: false
    name: CO2-1
  - entity: sensor.cupboard_temperature_8
    color: orange
    show_state: false
    name: CO2-2
name: Humidity
hours_to_show: 4
points_per_hour: 60
show:
  name: true
  legend: true
  icon: false
  labels: true
```
Which produces the same:

![Screenshot_20230802_082201_Home Assistant](https://github.com/kalkih/mini-graph-card/assets/58052383/2de2e9e3-b870-45f6-a6fd-caaab217f85a)

Still flat lines

**Comment by ildar170975** [comment]
Start with formatting the posted code, there is a special tag for it. Otherwise it is not clear.

**Comment by ildar170975** [comment]
Also, the 1st screenshot seems to be for three entities, and your code was for two.

**Comment by smartypantsuk** [comment]
> Start with formatting the posted code, there is a special tag for it. Otherwise it is not clear.

Done

**Comment by smartypantsuk** [comment]
> Also, the 1st screenshot seems to be for three entities, and your code was for two.

I've added three entities on the last example with the same outcome

**Comment by ildar170975** [comment]
1. Even the formatted code you posted has wrong indents. Do not edit code in the post. Always paste the exact code you tested with. 
2. What you do is still very confusing. Adding the example with 3 sensors is not the same as fixing your other “NaN” examples. 

Here described how to test a situation when the card gives a strange output: https://github.com/kalkih/mini-graph-card/issues/933#issuecomment-1464932117
Take any two sensors with same unit of measurement, test with each sensor as described above. Then test the card with two sensors. 
And do not forget to update HA, update the card, clear browser cache, test with standard browsers like Chrome (btw Safari cannot be called a “standard”).

**Comment by sharpsan** [comment]
Same thing for me:

```
type: custom:mini-graph-card
name: Living Room
icon: mdi:thermometer
entities:
  - entity: sensor.my_ecobee_current_temperature
    name: Temperature
  - entity: sensor.my_ecobee_current_humidity
    name: Humidity
hours_to_show: 24

```

They look normal (non-flattened) when only a single entity is listed.
