### ISSUE TITLE
Line plots in graphs intermittently not rendering

### ISSUE THREAD

**Issue by cmerkle** [kalkih/mini-graph-card#999]
I just created a new dashboard which includes 8  mini-graph-cards. Intermittently, although more often than not, the line plots in the graphs do not ever render. The rest of the cards (states, names, icons, legend, etc) render fine. Oddly enough it only occurs in desktop browsers (edge, chrome, firefox). On mobile they render without issue. As shown in the image my CPU load is very low so I don't think it's a system performance issue.

Here is the section of my YAML config containing the graphs:

```yaml
- square: false
  type: grid
  cards:
    - type: custom:mini-graph-card
      name: Living Room Temp
      animate: true
      height: 100
      hours_to_show: 24
      points_per_hour: 1
      update_interval: 60
      decimals: 1
      entities:
        - entity: sensor.living_room_thermostat_temperature
          color: '#4caf50'
    - type: custom:mini-graph-card
      name: Bedroom Temp
      animate: true
      height: 100
      hours_to_show: 24
      points_per_hour: 1
      update_interval: 60
      decimals: 1
      entities:
        - entity: sensor.master_bedroom_temperature
          color: '#4caf50'
    - type: custom:mini-graph-card
      name: Office Temp
      animate: true
      height: 100
      hours_to_show: 24
      points_per_hour: 1
      update_interval: 60
      decimals: 1
      entities:
        - entity: sensor.office_meter_plus_temperature
          color: '#4caf50'
    - type: custom:mini-graph-card
      name: Nursery Temp
      animate: true
      height: 100
      hours_to_show: 24
      points_per_hour: 1
      update_interval: 60
      decimals: 1
      entities:
        - entity: sensor.nursery_meter_plus_temperature
          color: '#4caf50'
    - type: custom:mini-graph-card
      name: Living Room Humidity
      animate: true
      height: 100
      hours_to_show: 24
      points_per_hour: 1
      update_interval: 60
      entities:
        - entity: sensor.living_room_thermostat_humidity
          color: '#2196f3'
    - type: custom:mini-graph-card
      name: Office Humidity
      animate: true
      height: 100
      hours_to_show: 24
      points_per_hour: 1
      update_interval: 60
      entities:
        - entity: sensor.office_meter_plus_humidity
          color: '#2196f3'
    - type: custom:mini-graph-card
      name: Nursery Humidity
      animate: true
      height: 100
      hours_to_show: 24
      points_per_hour: 1
      update_interval: 60
      entities:
        - entity: sensor.nursery_meter_plus_humidity
          color: '#2196f3'
    - type: custom:mini-graph-card
      name: Filament Box Hum.
      animate: true
      height: 100
      hours_to_show: 24
      points_per_hour: 1
      update_interval: 60
      entities:
        - entity: sensor.filament_storage_box_1_meter_plus_humidity
          color: '#4caf50'
          name: Box 1
          show_state: true
        - entity: sensor.filament_storage_box_2_meter_plus_humidity
          color: '#2196f3'
          name: Box 2
          show_state: true
  columns: 2
```
![Screenshot_2023-08-15_20-09-08](https://github.com/kalkih/mini-graph-card/assets/33108196/2ac6df59-3a76-41cf-b590-37dfac6975b5)

[home-assistant_2023-08-15T20-15-01.960Z.log](https://github.com/kalkih/mini-graph-card/files/12352714/home-assistant_2023-08-15T20-15-01.960Z.log)
